const fs = require('fs');
const lines = fs.readFileSync('assets/js/admin.js', 'utf8').split('\n');

// ১. পুরনো Flash Sale Manager ব্লক খুঁজে বের করা (Trending Manager এর আগ পর্যন্ত)
const startIdx = lines.findIndex(l => l.includes('/* ===================== FLASH SALE MANAGER ===================== */'));
const endMarkerIdx = lines.findIndex(l => l.includes('/* ===================== TRENDING PRODUCTS MANAGER ===================== */'));

if (startIdx === -1 || endMarkerIdx === -1) {
  console.log("❌ মার্কার পাওয়া যায়নি, startIdx:", startIdx, "endMarkerIdx:", endMarkerIdx);
  process.exit(1);
}

const newBlock = [
'/* ===================== FLASH SALE CATEGORY MANAGER (v2) ===================== */',
'let trendingCache = {};',
'const trendingSearchInput = document.getElementById("trending-search");',
'',
'let fscCategoriesCache = {};',
'let fscSelectedCatId = null;',
'let fscSelectedCatProducts = {}; // pid -> {discountPercent, addedAt}',
'',
'function loadFlashSaleCategories(){',
'  const listDiv = document.getElementById("fsc-list");',
'  if(!listDiv) return;',
'  onValue(ref(db, "settings/flashSaleCategories"), (snapshot) => {',
'    fscCategoriesCache = snapshot.val() || {};',
'    renderFscList();',
'    if(fscSelectedCatId && fscCategoriesCache[fscSelectedCatId]){',
'      document.getElementById("fsc-products-title").textContent = "🛍️ প্রোডাক্ট — " + (fscCategoriesCache[fscSelectedCatId].name||"").replace(/\\n/g," ");',
'    }',
'  });',
'',
'  const addBtn = document.getElementById("fsc-add-btn");',
'  if(addBtn){',
'    addBtn.onclick = async () => {',
'      const name = document.getElementById("fsc-name").value.trim();',
'      const order = parseInt(document.getElementById("fsc-order").value) || 0;',
'      const startDate = document.getElementById("fsc-startdate").value.trim();',
'      const endDate = document.getElementById("fsc-enddate").value.trim();',
'      if(!name){ alert("ক্যাটাগরির নাম দিন"); return; }',
'      try{',
'        const newRef = push(ref(db, "settings/flashSaleCategories"));',
'        await set(newRef, { name, order, startDate, endDate, createdAt: Date.now() });',
'        document.getElementById("fsc-name").value = "";',
'        document.getElementById("fsc-order").value = "0";',
'        document.getElementById("fsc-startdate").value = "";',
'        document.getElementById("fsc-enddate").value = "";',
'        alert("✅ ক্যাটাগরি যোগ হয়েছে");',
'      }catch(err){',
'        alert("❌ Error: " + err.message);',
'      }',
'    };',
'  }',
'}',
'',
'function renderFscList(){',
'  const listDiv = document.getElementById("fsc-list");',
'  if(!listDiv) return;',
'  const entries = Object.entries(fscCategoriesCache).sort((a,b)=>(a[1].order||0)-(b[1].order||0));',
'  if(entries.length === 0){',
'    listDiv.innerHTML = "<p style=\\"color:#888\\">কোনো Flash Sale ক্যাটাগরি নেই</p>";',
'    return;',
'  }',
'  listDiv.innerHTML = "";',
'  entries.forEach(([id, item]) => {',
'    const div = document.createElement("div");',
'    div.className = "card";',
'    div.innerHTML = `',
'      <label>নাম <input type="text" class="fsc-edit-name" value="${(item.name||"").replace(/"/g,"&quot;")}"></label>',
'      <label>Order <input type="number" class="fsc-edit-order" value="${item.order||0}" style="width:80px"></label>',
'      <label>শুরুর তারিখ <input type="text" class="fsc-edit-startdate" value="${(item.startDate||"").replace(/"/g,"&quot;")}" placeholder="dd-mm-yyyy"></label>',
'      <label>শেষের তারিখ <input type="text" class="fsc-edit-enddate" value="${(item.endDate||"").replace(/"/g,"&quot;")}" placeholder="dd-mm-yyyy"></label>',
'      <div style="margin-top:10px;display:flex;gap:8px;flex-wrap:wrap">',
'        <button class="save-btn fsc-view-btn">🛍️ প্রোডাক্ট দেখুন / যোগ করুন</button>',
'        <button class="save-btn fsc-save-btn">💾 Save</button>',
'        <button class="danger-btn fsc-delete-btn">🗑️ Delete</button>',
'      </div>',
'    `;',
'    div.querySelector(".fsc-view-btn").onclick = () => selectFscCategory(id);',
'    div.querySelector(".fsc-save-btn").onclick = async () => {',
'      const newName = div.querySelector(".fsc-edit-name").value.trim();',
'      const newOrder = parseInt(div.querySelector(".fsc-edit-order").value) || 0;',
'      const newStart = div.querySelector(".fsc-edit-startdate").value.trim();',
'      const newEnd = div.querySelector(".fsc-edit-enddate").value.trim();',
'      try{',
'        await update(ref(db, "settings/flashSaleCategories/"+id), { name: newName, order: newOrder, startDate: newStart, endDate: newEnd });',
'        alert("✅ Update হয়েছে");',
'      }catch(err){ alert("❌ Error: " + err.message); }',
'    };',
'    div.querySelector(".fsc-delete-btn").onclick = async () => {',
'      if(!confirm(`"${item.name}" ক্যাটাগরি এবং এর সব প্রোডাক্ট লিংক ডিলিট করবেন? (মূল প্রোডাক্ট ডিলিট হবে না)`)) return;',
'      try{',
'        await remove(ref(db, "settings/flashSaleCategories/"+id));',
'        await remove(ref(db, "settings/flashSaleCategoryProducts/"+id));',
'        if(fscSelectedCatId === id){',
'          fscSelectedCatId = null;',
'          document.getElementById("fsc-products-panel").style.display = "none";',
'        }',
'      }catch(err){ alert("❌ Error: " + err.message); }',
'    };',
'    listDiv.appendChild(div);',
'  });',
'}',
'',
'function selectFscCategory(catId){',
'  fscSelectedCatId = catId;',
'  const panel = document.getElementById("fsc-products-panel");',
'  panel.style.display = "block";',
'  const title = document.getElementById("fsc-products-title");',
'  title.textContent = "🛍️ প্রোডাক্ট — " + ((fscCategoriesCache[catId]||{}).name||"").replace(/\\n/g," ");',
'  panel.scrollIntoView({ behavior: "smooth", block: "start" });',
'',
'  onValue(ref(db, "settings/flashSaleCategoryProducts/"+catId), (snapshot) => {',
'    fscSelectedCatProducts = snapshot.val() || {};',
'    renderFscProductsList();',
'  });',
'}',
'',
'async function renderFscProductsList(){',
'  const listDiv = document.getElementById("fsc-products-list");',
'  if(!listDiv) return;',
'  const pids = Object.keys(fscSelectedCatProducts);',
'  if(pids.length === 0){',
'    listDiv.innerHTML = "<p style=\\"color:#888\\">এই ক্যাটাগরিতে কোনো প্রোডাক্ট নেই। উপরে সার্চ করে যোগ করুন।</p>";',
'    return;',
'  }',
'  listDiv.innerHTML = "<p style=\\"color:#888\\">লোড হচ্ছে...</p>";',
'',
'  const rows = await Promise.all(pids.map(async (pid) => {',
'    try{',
'      const snap = await get(ref(db, "products/"+pid));',
'      const data = snap.val();',
'      return { pid, data, mapInfo: fscSelectedCatProducts[pid] };',
'    }catch(e){',
'      return { pid, data: null, mapInfo: fscSelectedCatProducts[pid] };',
'    }',
'  }));',
'',
'  listDiv.innerHTML = "";',
'  rows.forEach(({pid, data, mapInfo}) => {',
'    const div = document.createElement("div");',
'    div.className = "card";',
'    const title = data ? (data.title || data.name || "Unnamed") : "⚠️ প্রোডাক্ট পাওয়া যায়নি (ডিলিট হয়ে থাকতে পারে)";',
'    const price = data ? data.price : "-";',
'    div.innerHTML = `',
'      <h3>${title}</h3>',
'      <p>মূল দাম: ৳${price}</p>',
'      <label>Discount %: <input type="number" class="fsc-item-discount" value="${mapInfo.discountPercent||0}" min="0" max="100" style="width:80px"></label>',
'      <div style="margin-top:8px;display:flex;gap:8px">',
'        <button class="save-btn fsc-item-save">💾 Save</button>',
'        <button class="danger-btn fsc-item-remove">🗑️ সরিয়ে ফেলুন</button>',
'      </div>',
'    `;',
'    div.querySelector(".fsc-item-save").onclick = async () => {',
'      const disc = parseInt(div.querySelector(".fsc-item-discount").value) || 0;',
'      try{',
'        await update(ref(db, `settings/flashSaleCategoryProducts/${fscSelectedCatId}/${pid}`), { discountPercent: disc });',
'        alert("✅ সেভ হয়েছে");',
'      }catch(err){ alert("❌ Error: " + err.message); }',
'    };',
'    div.querySelector(".fsc-item-remove").onclick = async () => {',
'      if(!confirm("এই প্রোডাক্টটি এই ক্যাটাগরি থেকে সরাবেন?")) return;',
'      try{',
'        await remove(ref(db, `settings/flashSaleCategoryProducts/${fscSelectedCatId}/${pid}`));',
'      }catch(err){ alert("❌ Error: " + err.message); }',
'    };',
'    listDiv.appendChild(div);',
'  });',
'',
'  const bulkBtn = document.getElementById("fsc-bulk-apply-btn");',
'  if(bulkBtn){',
'    bulkBtn.onclick = async () => {',
'      const bulkVal = parseInt(document.getElementById("fsc-bulk-discount").value);',
'      if(isNaN(bulkVal) || bulkVal < 0 || bulkVal > 100){',
'        alert("সঠিক % দিন (0-100)"); return;',
'      }',
'      const statusEl = document.getElementById("fsc-bulk-status");',
'      const updates = {};',
'      pids.forEach(pid => {',
'        updates[`settings/flashSaleCategoryProducts/${fscSelectedCatId}/${pid}/discountPercent`] = bulkVal;',
'      });',
'      try{',
'        await update(ref(db), updates);',
'        statusEl.textContent = "✅ সব প্রোডাক্টে " + bulkVal + "% প্রয়োগ হয়েছে";',
'        setTimeout(()=>{ statusEl.textContent=""; }, 3000);',
'      }catch(err){',
'        statusEl.style.color = "#f88";',
'        statusEl.textContent = "❌ Error: " + err.message;',
'      }',
'    };',
'  }',
'}',
'',
'function setupFscSearch(){',
'  const searchInput = document.getElementById("fsc-search-input");',
'  const resultsDiv = document.getElementById("fsc-search-results");',
'  if(!searchInput || !resultsDiv) return;',
'  searchInput.addEventListener("input", () => {',
'    const q = searchInput.value.trim().toLowerCase();',
'    resultsDiv.innerHTML = "";',
'    if(!q || !fscSelectedCatId){ return; }',
'    const matches = Object.entries(allProductsCache).filter(([pid, data]) => {',
'      const name = (data.title || data.name || "").toLowerCase();',
'      return name.includes(q) && !fscSelectedCatProducts[pid];',
'    }).slice(0, 20);',
'    if(matches.length === 0){',
'      resultsDiv.innerHTML = "<p style=\\"color:#888;font-size:13px\\">কোনো ফলাফল পাওয়া যায়নি</p>";',
'      return;',
'    }',
'    matches.forEach(([pid, data]) => {',
'      const row = document.createElement("div");',
'      row.style.cssText = "display:flex;justify-content:space-between;align-items:center;padding:6px 0;border-bottom:1px solid #333";',
'      row.innerHTML = `<span>${data.title||data.name} — ৳${data.price}</span>`;',
'      const addBtn = document.createElement("button");',
'      addBtn.className = "save-btn";',
'      addBtn.textContent = "+ যোগ করুন";',
'      addBtn.onclick = async () => {',
'        try{',
'          await set(ref(db, `settings/flashSaleCategoryProducts/${fscSelectedCatId}/${pid}`), { discountPercent: 0, addedAt: Date.now() });',
'          searchInput.value = "";',
'          resultsDiv.innerHTML = "";',
'        }catch(err){ alert("❌ Error: " + err.message); }',
'      };',
'      row.appendChild(addBtn);',
'      resultsDiv.appendChild(row);',
'    });',
'  });',
'}',
'',
'setupFscSearch();',
''
];

lines.splice(startIdx, endMarkerIdx - startIdx, ...newBlock);
fs.writeFileSync('assets/js/admin.js', lines.join('\n'), 'utf8');
console.log("✅ assets/js/admin.js এ নতুন Flash Sale Category Manager বসানো হয়েছে");

// ২. init কল আপডেট (loadFlashSale, loadFlashSaleLabel -> loadFlashSaleCategories)
let content = fs.readFileSync('assets/js/admin.js', 'utf8');
content = content.replace('loadFlashSale();\n  loadTrending();\n  loadFlashSaleLabel();', 'loadFlashSaleCategories();\n  loadTrending();');
fs.writeFileSync('assets/js/admin.js', content, 'utf8');
console.log("✅ init কল আপডেট হয়েছে");
