import json

price_desc = {
    "area_rug": (3500, "Area Rug — a decorative rug used to define and enhance a living space."),
    "armchair": (8500, "Armchair — a single-seat upholstered chair designed for comfort."),
    "aroma_diffuser": (1800, "Aroma Diffuser — a device that disperses fragrance into a room."),
    "artificial_flowers": (400, "Artificial Flowers — decorative faux flowers used for home decor."),
    "baby_crib": (9500, "Baby Crib — a bed with high sides designed for infant sleep safety."),
    "bar_cabinet": (12000, "Bar Cabinet — a furniture piece designed to store and display drinks."),
    "bar_stool": (3500, "Bar Stool — a tall seat designed for use at a bar or counter."),
    "bar_table": (8500, "Bar Table — a tall table designed for use with bar stools."),
    "bathroom_cabinet": (6500, "Bathroom Cabinet — a storage unit designed for bathroom essentials."),
    "bathroom_decor": (700, "Bathroom Decor — decorative accessories designed for bathroom spaces."),
    "bathroom_shelf": (1500, "Bathroom Shelf — a shelving unit designed for bathroom storage."),
    "bed_frame": (12000, "Bed Frame — a structural frame used to support a mattress."),
    "bed_runner": (900, "Bed Runner — a decorative fabric strip placed across a bed."),
    "bed_sheet": (900, "Bed Sheet — a fabric covering used on a mattress for comfort."),
    "bedding_linens": (1500, "Bedding & Linens — a general range of bedding textile products."),
    "bedroom_bench": (5500, "Bedroom Bench — a padded bench designed for use at the foot of a bed."),
    "bedroom_furniture": (8500, "Bedroom Furniture — a general range of furniture pieces for bedrooms."),
    "bedside_table": (4500, "Bedside Table — a small table placed beside a bed for convenience."),
    "blanket": (900, "Blanket — a soft covering used for warmth and comfort."),
    "bookcase": (8500, "Bookcase — a furniture piece with shelves designed for storing books."),
    "bookshelf": (7500, "Bookshelf — a shelving unit designed for storing and displaying books."),
    "buffet_cabinet": (15000, "Buffet Cabinet — a storage furniture piece used for dining room organization."),
    "bunk_bed": (18000, "Bunk Bed — a stacked bed frame designed to save floor space."),
    "cabinet_handles": (150, "Cabinet Handles — hardware used for opening cabinets and drawers."),
    "candle_holder": (450, "Candle Holder — a decorative stand used to hold candles."),
    "canvas_painting": (2500, "Canvas Painting — decorative artwork printed or painted on canvas."),
    "carpet": (4500, "Carpet — a soft floor covering used for home decor and comfort."),
    "cat_scratcher": (900, "Cat Scratcher — a scratching post designed for feline pets."),
    "cat_tree": (5500, "Cat Tree — a multi-level structure designed for cats to climb and rest."),
    "chair_cushions": (700, "Chair Cushions — padded cushions used to add comfort to seating."),
    "chair_lamp_indoor_plant": (900, "Chair, Lamp & Indoor Plant Set — a bundled set of home decor items."),
    "chandelier": (12000, "Chandelier — a decorative hanging light fixture."),
    "chest_of_drawers": (12000, "Chest of Drawers — a furniture piece with multiple drawers for storage."),
    "childrens_furniture": (5500, "Children's Furniture — furniture pieces designed and sized for children."),
    "china_cabinet": (18000, "China Cabinet — a display cabinet designed to store fine dishware."),
    "christmas_ornaments": (450, "Christmas Ornaments — decorative items used to adorn a Christmas tree."),
    "christmas_tree": (3500, "Christmas Tree — a decorative artificial tree used for holiday decor."),
    "clock": (900, "Clock — a decorative timepiece used for home decor."),
    "closet_organizer": (900, "Closet Organizer — a storage system used to organize clothing and items."),
    "coffee_table": (8500, "Coffee Table — a low table typically placed in front of a sofa."),
    "comforter": (2500, "Comforter — a thick padded bed covering used for warmth."),
    "computer_desk": (7500, "Computer Desk — a desk designed for computer and office work."),
    "console_table": (6500, "Console Table — a narrow table typically placed against a wall."),
    "corner_shelf": (1500, "Corner Shelf — a shelving unit designed to fit into room corners."),
    "curtain_rings": (150, "Curtain Rings — hardware used to hang curtains on a rod."),
    "curtain_rod": (900, "Curtain Rod — a rod used to hang curtains above windows."),
    "curtain_tieback": (250, "Curtain Tieback — a decorative accessory used to hold curtains open."),
    "curtains": (1800, "Curtains — fabric window coverings used for privacy and decor."),
    "curtains_window_decor": (1800, "Curtains & Window Decor — a general range of window covering products."),
    "cushion": (450, "Cushion — a soft pillow used for seating comfort and decor."),
    "cushion_cover": (350, "Cushion Cover — a removable fabric cover designed for cushions."),
    "daybed": (15000, "Daybed — a versatile furniture piece used as both a bed and sofa."),
    "decorative_accessories": (700, "Decorative Accessories — a general range of home decor accent items."),
    "decorative_bowl": (700, "Decorative Bowl — an ornamental bowl used for home display."),
    "decorative_candle": (450, "Decorative Candle — a candle designed for aesthetic home decor."),
    "decorative_garland": (450, "Decorative Garland — a decorative strand used for festive home decor."),
    "decorative_mirror": (2500, "Decorative Mirror — an ornamental mirror used to enhance home decor."),
    "decorative_panels": (1500, "Decorative Panels — ornamental wall panels used for interior decor."),
    "decorative_tray": (700, "Decorative Tray — an ornamental tray used for home display and organization."),
    "decorative_vase": (900, "Decorative Vase — an ornamental vase used for home decor."),
    "desk_lamp": (1500, "Desk Lamp — a lamp designed for focused lighting at a desk."),
    "dining_bench": (6500, "Dining Bench — a bench seat designed for use at a dining table."),
    "dining_chair": (3500, "Dining Chair — a chair designed for use at a dining table."),
    "dining_room_furniture": (15000, "Dining Room Furniture — a general range of furniture pieces for dining rooms."),
    "dining_table": (18000, "Dining Table — a table designed for meals and gatherings."),
    "dish_rack": (900, "Dish Rack — a rack used to dry and organize dishes."),
    "display_cabinet": (15000, "Display Cabinet — a furniture piece used to showcase decorative items."),
    "door_mat": (450, "Door Mat — a mat placed at an entrance to collect dirt from shoes."),
    "double_bed": (15000, "Double Bed — a bed frame sized for two people."),
    "drawer_organizer": (450, "Drawer Organizer — a tool used to organize items within a drawer."),
    "drawer_slides": (250, "Drawer Slides — hardware used for smooth drawer movement."),
    "dresser": (15000, "Dresser — a furniture piece with drawers used for clothing storage."),
    "dressing_table": (12000, "Dressing Table — a table with a mirror designed for grooming and makeup."),
    "duvet": (2500, "Duvet — a soft bed covering filled with insulating material."),
    "duvet_cover": (1500, "Duvet Cover — a removable fabric cover designed for a duvet."),
    "eid_decorations": (900, "Eid Decorations — decorative items used for Eid festive celebrations."),
    "entertainment_unit": (15000, "Entertainment Unit — a furniture piece designed to hold TV and media equipment."),
    "ergonomic_chair": (12000, "Ergonomic Chair — a chair designed for supportive, comfortable seating."),
    "executive_desk": (18000, "Executive Desk — a large desk designed for professional office use."),
    "feeding_station": (900, "Feeding Station — a stand designed to hold pet food and water bowls."),
    "felt_pads": (150, "Felt Pads — protective pads used under furniture legs to prevent floor scratches."),
    "festive_lights": (900, "Festive Lights — decorative string lights used for holiday and celebration decor."),
    "figurines": (700, "Figurines — small decorative statues used for home display."),
    "filing_cabinet": (8500, "Filing Cabinet — a storage furniture piece designed for organizing documents."),
    "floating_shelf": (1500, "Floating Shelf — a wall-mounted shelf with a concealed support system."),
    "floor_lamp": (3500, "Floor Lamp — a tall standing lamp used for room lighting."),
    "floor_mat": (450, "Floor Mat — a mat used to protect and decorate flooring."),
    "folding_screen": (5500, "Folding Screen — a decorative room divider that folds for storage."),
    "furniture_casters": (350, "Furniture Casters — wheels used to make furniture easily movable."),
    "furniture_covers": (900, "Furniture Covers — protective covers designed to shield furniture."),
    "furniture_hardware_accessories": (350, "Furniture Hardware & Accessories — a general range of furniture assembly hardware."),
    "furniture_home_decor-1": (700, "Furniture & Home Decor — a general range of furniture and decor products."),
    "furniture_home_decor": (700, "Furniture & Home Decor — a general range of furniture and decor products."),
    "furniture_legs": (450, "Furniture Legs — replacement legs used to support furniture pieces."),
    "gaming_chair": (12000, "Gaming Chair — an ergonomic chair designed for long gaming sessions."),
    "garden_chair": (3500, "Garden Chair — an outdoor chair designed for garden and patio use."),
    "garden_table": (6500, "Garden Table — an outdoor table designed for garden and patio use."),
    "hammock": (3500, "Hammock — a suspended fabric bed used for relaxing outdoors."),
    "hanger": (100, "Hanger — a tool used to hang and store clothing."),
    "headboard": (8500, "Headboard — a decorative panel attached to the head of a bed frame."),
    "hinges": (100, "Hinges — hardware used to allow doors and cabinets to pivot open and closed."),
    "home_decor": (700, "Home Decor — a general range of decorative items for the home."),
    "home_organization": (900, "Home Organization — a general range of products used to organize household items."),
    "incense_holder": (350, "Incense Holder — a decorative stand used to hold burning incense."),
    "indoor_plants": (700, "Indoor Plants — potted plants used to decorate indoor spaces."),
    "kids_bed": (12000, "Kids Bed — a bed frame sized and designed for children."),
    "kids_chair": (1200, "Kids Chair — a small chair sized for young children."),
    "kids_table": (2500, "Kids Table — a small table sized for young children's activities."),
    "king_bed": (18000, "King Bed — a large bed frame sized for maximum sleeping space."),
    "kitchen_cabinet": (15000, "Kitchen Cabinet — a storage unit designed for kitchen organization."),
    "kitchen_cart": (6500, "Kitchen Cart — a mobile storage and prep unit designed for kitchens."),
    "kitchen_furniture_storage": (5500, "Kitchen Furniture & Storage — a general range of kitchen storage furniture."),
    "kitchen_island": (25000, "Kitchen Island — a freestanding counter unit designed for kitchen prep and storage."),
    "kitchen_rack": (2500, "Kitchen Rack — a rack used to organize kitchen items."),
    "laundry_basket": (900, "Laundry Basket — a container used to collect and carry laundry."),
    "laundry_hamper": (1200, "Laundry Hamper — a container used to store dirty laundry."),
    "led_decorative_light": (900, "LED Decorative Light — energy-efficient LED lighting used for home decor."),
    "lighting_decor": (900, "Lighting & Decor — a general range of decorative lighting products."),
    "living_room_furniture": (15000, "Living Room Furniture — a general range of furniture pieces for living rooms."),
    "mattress": (12000, "Mattress — a cushioned pad used as a sleeping surface on a bed."),
    "mattress_protector": (1500, "Mattress Protector — a protective cover used to shield a mattress."),
    "microwave_stand": (5500, "Microwave Stand — a furniture piece designed to hold a microwave oven."),
    "night_light": (450, "Night Light — a small light used for gentle illumination at night."),
    "nursery_shelf": (1800, "Nursery Shelf — a shelving unit designed for baby nursery organization."),
    "office_chair": (8500, "Office Chair — a chair designed for comfortable seating during office work."),
    "office_desk": (12000, "Office Desk — a desk designed for professional office use."),
    "office_furniture": (12000, "Office Furniture — a general range of furniture pieces for office use."),
    "office_shelf": (2500, "Office Shelf — a shelving unit designed for office storage."),
    "ottoman": (5500, "Ottoman — a padded footstool used for seating or resting feet."),
    "outdoor_bench": (5500, "Outdoor Bench — a durable bench designed for outdoor use."),
    "outdoor_furniture": (12000, "Outdoor Furniture — a general range of furniture designed for outdoor spaces."),
    "outdoor_sofa": (25000, "Outdoor Sofa — a durable sofa designed for outdoor patio use."),
    "pantry_shelf": (2500, "Pantry Shelf — a shelving unit designed for kitchen pantry storage."),
    "patio_set": (25000, "Patio Set — a coordinated furniture set designed for outdoor patio use."),
    "pendant_light": (3500, "Pendant Light — a decorative hanging light fixture."),
    "pet_bed": (1800, "Pet Bed — a cushioned bed designed for pets to sleep on."),
    "pet_furniture": (5500, "Pet Furniture — a general range of furniture designed for pets."),
    "pet_house": (3500, "Pet House — a small enclosed shelter designed for pets."),
    "photo_frame": (500, "Photo Frame — a decorative frame designed for displaying photographs."),
    "picnic_table": (8500, "Picnic Table — an outdoor table designed for picnics and gatherings."),
    "pillow": (450, "Pillow — a soft cushion used for sleeping or seating comfort."),
    "pillow_cover": (350, "Pillow Cover — a removable fabric cover designed for pillows."),
    "planters": (700, "Planters — decorative containers used for growing plants."),
    "plastic_drawer": (1500, "Plastic Drawer — a lightweight storage drawer unit."),
    "prayer_mat": (900, "Prayer Mat — a mat used for religious prayer."),
    "queen_bed": (16000, "Queen Bed — a bed frame sized for two people with generous space."),
    "quilt": (2500, "Quilt — a padded bed covering used for warmth and decor."),
    "ramadan_lantern": (900, "Ramadan Lantern — a decorative lantern used for Ramadan celebrations."),
    "recliner_chair": (15000, "Recliner Chair — an adjustable chair designed for reclining comfort."),
    "roller_blinds": (1800, "Roller Blinds — window coverings that roll up and down for light control."),
    "roman_blinds": (2500, "Roman Blinds — fabric window coverings that fold in sections."),
    "room_divider": (5500, "Room Divider — a portable screen used to separate living spaces."),
    "rugs_carpets": (3500, "Rugs & Carpets — a general range of floor covering products."),
    "runner_rug": (1800, "Runner Rug — a long, narrow rug used for hallways and corridors."),
    "sculpture": (2500, "Sculpture — a decorative three-dimensional art piece for home display."),
    "seasonal_decor": (900, "Seasonal Decor — decorative items used for seasonal home decoration."),
    "sectional_sofa": (45000, "Sectional Sofa — a modular sofa designed for flexible seating arrangements."),
    "shelf_brackets": (250, "Shelf Brackets — hardware used to support wall-mounted shelves."),
    "shelving_unit": (5500, "Shelving Unit — a freestanding structure used for storage and display."),
    "shoe_rack": (2500, "Shoe Rack — a rack designed to organize and store shoes."),
    "shower_curtain": (900, "Shower Curtain — a fabric curtain used to enclose a shower area."),
    "side_table": (4500, "Side Table — a small table placed beside seating for convenience."),
    "sideboard": (15000, "Sideboard — a storage furniture piece used in dining rooms."),
    "single_bed": (9500, "Single Bed — a bed frame sized for one person."),
    "smart_lamp": (2500, "Smart Lamp — a connected lamp controllable via app or voice assistant."),
    "soap_dispenser": (450, "Soap Dispenser — a container used to dispense liquid soap."),
    "sofa": (25000, "Sofa — an upholstered seating furniture piece designed for multiple people."),
    "sofa_bed": (25000, "Sofa Bed — a versatile furniture piece that converts from sofa to bed."),
    "spice_rack": (900, "Spice Rack — a rack used to organize and store cooking spices."),
    "storage_basket": (700, "Storage Basket — a basket used to organize household items."),
    "storage_bin": (700, "Storage Bin — a container used to organize and store household items."),
    "storage_box": (700, "Storage Box — a box designed for organizing household items."),
    "storage_cabinet": (8500, "Storage Cabinet — a furniture piece designed for general household storage."),
    "storage_furniture": (8500, "Storage Furniture — a general range of furniture pieces designed for storage."),
    "string_lights": (700, "String Lights — decorative lights used for ambient home decor."),
    "study_desk": (6500, "Study Desk — a desk designed for reading and studying."),
    "study_table": (6500, "Study Table — a table designed for reading and studying."),
    "sun_lounger": (8500, "Sun Lounger — a reclining outdoor chair designed for sunbathing."),
    "swing_chair": (12000, "Swing Chair — a suspended chair designed for relaxed outdoor seating."),
    "table_decor": (700, "Table Decor — decorative items used to accent tabletop surfaces."),
    "table_lamp": (1800, "Table Lamp — a lamp designed for placement on tables and desks."),
    "table_runner": (700, "Table Runner — a decorative fabric strip placed across a table."),
    "toddler_bed": (8500, "Toddler Bed — a small bed frame designed for young children."),
    "toothbrush_holder": (350, "Toothbrush Holder — a stand used to organize toothbrushes."),
    "towel_rack": (1500, "Towel Rack — a rack used to hang and organize towels."),
    "toy_storage_cabinet": (5500, "Toy Storage Cabinet — a furniture piece designed for organizing children's toys."),
    "tv_stand": (8500, "TV Stand — a furniture piece designed to hold and display a television."),
    "umbrella_stand": (1500, "Umbrella Stand — a stand used to hold and store umbrellas."),
    "vacuum_storage_bag": (450, "Vacuum Storage Bag — a bag used to compress and store bedding and clothing."),
    "vanity_mirror": (2500, "Vanity Mirror — a mirror designed for grooming and makeup use."),
    "wall_art": (2500, "Wall Art — decorative artwork designed for wall display."),
    "wall_clock": (900, "Wall Clock — a decorative clock designed for wall mounting."),
    "wall_light": (1800, "Wall Light — a light fixture designed for wall mounting."),
    "wall_shelf": (1500, "Wall Shelf — a shelving unit designed for wall mounting."),
    "wall_stickers": (450, "Wall Stickers — decorative adhesive designs used for wall decor."),
    "wallpaper": (450, "Wallpaper — decorative paper used to cover and finish interior walls."),
    "wardrobe": (18000, "Wardrobe — a furniture piece designed for clothing storage."),
    "window_blinds": (1800, "Window Blinds — adjustable window coverings used for light control."),
    "window_valance": (900, "Window Valance — a decorative fabric topper used above window curtains."),
    "wreath": (900, "Wreath — a decorative circular arrangement used for home and festive decor."),
}

path = "data/products-placeholder.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
skipped = []
for sku, prod in data.items():
    if prod.get("categoryId") == "furniture_home_decor":
        img = prod["images"]["main"].split("/")[-1].replace(".png", "")
        if img in price_desc:
            price, desc = price_desc[img]
            title = " ".join(w.capitalize() for w in img.split("_"))
            prod["title"] = title
            prod["price"] = price
            prod["description"] = desc
            prod["status"] = "active"
            updated += 1
        else:
            skipped.append((sku, img))

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
