import json

price_desc = {
    "sports_outdoors_fitness": (100, "Sports & Outdoors, Fitness — a general range of sports, outdoor and fitness equipment."),
    "football_dumbbell_water_bottle": (600, "Football Dumbbell Water Bottle — a novelty sports-themed water bottle for gym or outdoor use."),
    "fitness_equipment": (2500, "Fitness Equipment — general exercise equipment used for home or gym workouts."),
    "treadmill": (35000, "Treadmill — a motorized machine used for running or walking indoors."),
    "exercise_bike": (18000, "Exercise Bike — a stationary bike used for indoor cardio workouts."),
    "spin_bike": (22000, "Spin Bike — a stationary bike designed for high-intensity indoor cycling classes."),
    "elliptical_trainer": (28000, "Elliptical Trainer — a low-impact cardio machine that simulates running motion."),
    "rowing_machine": (25000, "Rowing Machine — a cardio machine that simulates the rowing motion for full-body workouts."),
    "stair_climber": (30000, "Stair Climber — a cardio machine that simulates climbing stairs."),
    "home_gym_machine": (45000, "Home Gym Machine — a multi-station machine offering various strength exercises at home."),
    "smith_machine": (55000, "Smith Machine — a guided barbell machine used for safe weightlifting."),
    "power_rack": (35000, "Power Rack — a heavy-duty frame used for squats, bench press, and safety bar work."),
    "squat_rack": (25000, "Squat Rack — a frame designed to safely support a barbell during squats."),
    "bench_press": (12000, "Bench Press — a weight bench used for barbell chest press exercises."),
    "adjustable_weight_bench": (8500, "Adjustable Weight Bench — a bench with multiple incline settings for varied exercises."),
    "dumbbells": (1500, "Dumbbells — handheld weights used for strength training exercises."),
    "adjustable_dumbbells": (8500, "Adjustable Dumbbells — dumbbells with selectable weight plates for varied resistance."),
    "kettlebells": (1800, "Kettlebells — cast-iron weights with a handle used for dynamic strength training."),
    "barbell": (3500, "Barbell — a long weighted bar used for compound strength exercises."),
    "weight_plates": (1200, "Weight Plates — plates used to add resistance to a barbell."),
    "resistance_bands": (500, "Resistance Bands — elastic bands used for strength and flexibility training."),
    "pull_up_bar": (1500, "Pull Up Bar — a bar mounted for doing pull-up and chin-up exercises."),
    "dip_station": (4500, "Dip Station — a stand used for performing tricep dips and leg raises."),
    "jump_rope": (350, "Jump Rope — a rope used for cardio and coordination training."),
    "ab_roller": (700, "Ab Roller — a wheel device used for core strengthening exercises."),
    "push_up_board": (900, "Push Up Board — a board with handles for varying push-up positions."),
    "medicine_ball": (1500, "Medicine Ball — a weighted ball used for strength and core exercises."),
    "slam_ball": (1800, "Slam Ball — a durable weighted ball designed for slamming exercises."),
    "balance_board": (1500, "Balance Board — a board used for balance and stability training."),
    "foam_roller": (900, "Foam Roller — a cylindrical tool used for muscle recovery and self-massage."),
    "yoga_ball": (900, "Yoga Ball — an inflatable ball used for core and balance exercises."),
    "hand_grip_strengthener": (350, "Hand Grip Strengthener — a spring tool used to build hand and forearm strength."),
    "yoga_pilates": (2200, "Yoga Pilates Set — a bundled set of accessories for yoga and pilates practice."),
    "yoga_mat": (700, "Yoga Mat — a cushioned mat used for yoga and floor exercises."),
    "yoga_block": (350, "Yoga Block — a foam block used to support proper alignment during yoga poses."),
    "yoga_strap": (250, "Yoga Strap — a strap used to assist stretching and pose alignment in yoga."),
    "yoga_wheel": (900, "Yoga Wheel — a circular prop used to deepen backbends and improve flexibility."),
    "meditation_cushion": (900, "Meditation Cushion — a supportive cushion used for seated meditation practice."),
    "pilates_ring": (700, "Pilates Ring — a flexible ring used to add resistance to pilates exercises."),
    "pilates_ball": (500, "Pilates Ball — a small ball used for pilates stability exercises."),
    "resistance_loop_band": (300, "Resistance Loop Band — a small looped band used for lower-body resistance exercises."),
    "running_walking": (1200, "Running & Walking Set — a bundled set of accessories for running or walking."),
    "running_shoes": (3500, "Running Shoes — footwear designed for running and jogging."),
    "running_belt": (700, "Running Belt — a waist belt used to carry essentials while running."),
    "hydration_belt": (900, "Hydration Belt — a waist belt with bottle holders for runners."),
    "running_vest": (1500, "Running Vest — a lightweight vest with storage designed for runners."),
    "reflective_vest": (500, "Reflective Vest — a high-visibility vest worn for safety during low-light activity."),
    "sports_cap": (400, "Sports Cap — a cap designed for sun protection during outdoor activity."),
    "running_socks": (350, "Running Socks — moisture-wicking socks designed for running comfort."),
    "fitness_tracker": (2500, "Fitness Tracker — a wearable device that tracks activity, steps, and heart rate."),
    "camping_hiking": (2500, "Camping & Hiking Set — a bundled set of gear for camping and hiking trips."),
    "camping_tent": (6500, "Camping Tent — a portable shelter designed for outdoor camping."),
    "sleeping_bag": (2500, "Sleeping Bag — a padded bag designed to keep campers warm while sleeping outdoors."),
    "camping_mattress": (2200, "Camping Mattress — a portable mattress designed for sleeping comfort while camping."),
    "camping_pillow": (700, "Camping Pillow — a compact, inflatable pillow designed for camping trips."),
    "camping_chair": (1800, "Camping Chair — a lightweight, foldable chair designed for outdoor use."),
    "camping_table": (2200, "Camping Table — a foldable table designed for outdoor camping use."),
    "camping_stove": (2500, "Camping Stove — a portable stove used for cooking while camping."),
    "portable_grill": (3500, "Portable Grill — a compact grill designed for outdoor cooking."),
    "cooler_box": (2800, "Cooler Box — an insulated box used to keep food and drinks cold outdoors."),
    "water_container": (700, "Water Container — a portable container used to store and carry water outdoors."),
    "camping_lantern": (900, "Camping Lantern — a portable light source designed for outdoor camping use."),
    "headlamp": (700, "Headlamp — a hands-free light worn on the head for outdoor activities."),
    "multi_tool": (900, "Multi Tool — a compact tool combining several functions for outdoor use."),
    "hiking_backpack": (3500, "Hiking Backpack — a durable backpack designed for carrying gear on hikes."),
    "trekking_poles": (1800, "Trekking Poles — adjustable poles used for support and stability while hiking."),
    "compass": (500, "Compass — a navigational tool used to determine direction outdoors."),
    "binoculars": (2500, "Binoculars — an optical device used for viewing distant objects outdoors."),
    "cycling": (2500, "Cycling Gear Set — a bundled set of accessories for cycling."),
    "bicycle": (15000, "Bicycle — a pedal-powered two-wheeled vehicle used for transport or exercise."),
    "mountain_bike": (25000, "Mountain Bike — a rugged bicycle designed for off-road terrain."),
    "road_bike": (28000, "Road Bike — a lightweight bicycle designed for paved-road cycling."),
    "bmx_bike": (12000, "BMX Bike — a small, sturdy bicycle designed for tricks and stunts."),
    "electric_bike": (55000, "Electric Bike — a bicycle equipped with a motor for assisted pedaling."),
    "cycling_helmet": (1800, "Cycling Helmet — protective headgear designed for cyclists."),
    "bike_lock": (900, "Bike Lock — a locking device used to secure a bicycle."),
    "bike_pump": (700, "Bike Pump — a pump used to inflate bicycle tires."),
    "bike_lights": (700, "Bike Lights — front and rear lights used for cyclist visibility."),
    "cycling_gloves": (700, "Cycling Gloves — padded gloves designed for cycling grip and comfort."),
    "bike_repair_kit": (900, "Bike Repair Kit — a compact kit used for roadside bicycle repairs."),
    "bicycle_saddle": (1500, "Bicycle Saddle — a replacement seat designed for cycling comfort."),
    "water_bottle_cage": (350, "Water Bottle Cage — a bicycle-mounted holder for a water bottle."),
    "team_sports": (1500, "Team Sports Set — a bundled set of equipment for team sports."),
    "football_soccer": (1200, "Football/Soccer Set — a bundled set of soccer equipment."),
    "football": (900, "Football — a ball designed for playing football/soccer."),
    "football_boots": (2500, "Football Boots — cleated footwear designed for football/soccer."),
    "shin_guards": (500, "Shin Guards — protective gear worn to shield the shins during football."),
    "goal_net": (2200, "Goal Net — a net used with a football or hockey goal frame."),
    "goalkeeper_gloves": (900, "Goalkeeper Gloves — padded gloves designed for football goalkeepers."),
    "basketball": (1200, "Basketball — a ball designed for playing basketball."),
    "basketball_hoop": (5500, "Basketball Hoop — a rim and backboard setup used for basketball."),
    "basketball_net": (400, "Basketball Net — a replacement net for a basketball hoop."),
    "basketball_shoes": (3500, "Basketball Shoes — footwear designed for basketball performance."),
    "volleyball": (1200, "Volleyball — a ball designed for playing volleyball."),
    "volleyball_net": (2500, "Volleyball Net — a net setup used for volleyball games."),
    "knee_pads": (700, "Knee Pads — protective padding worn to cushion the knees during sport."),
    "cricket": (1500, "Cricket Set — a bundled set of cricket equipment."),
    "cricket_bat": (2500, "Cricket Bat — a bat used for playing cricket."),
    "cricket_ball": (400, "Cricket Ball — a ball designed for playing cricket."),
    "batting_gloves": (900, "Batting Gloves — protective gloves worn by cricket batters."),
    "batting_pads": (1800, "Batting Pads — protective leg pads worn by cricket batters."),
    "cricket_helmet": (2500, "Cricket Helmet — protective headgear worn by cricket batters."),
    "wicket_set": (1200, "Wicket Set — stumps and bails used to set up a cricket wicket."),
    "tennis_badminton": (1500, "Tennis & Badminton Set — a bundled set of racket sport equipment."),
    "tennis_racket": (3500, "Tennis Racket — a racket used for playing tennis."),
    "tennis_balls": (500, "Tennis Balls — balls designed for playing tennis."),
    "badminton_racket": (1500, "Badminton Racket — a racket used for playing badminton."),
    "shuttlecock": (300, "Shuttlecock — a projectile used for playing badminton."),
    "racket_bag": (1200, "Racket Bag — a bag designed to carry and protect rackets."),
    "grip_tape": (150, "Grip Tape — tape used to improve grip on a racket handle."),
    "water_sports": (2200, "Water Sports Set — a bundled set of equipment for water sports."),
    "swimming_goggles": (500, "Swimming Goggles — eyewear designed to protect eyes while swimming."),
    "swim_cap": (250, "Swim Cap — a cap worn to reduce drag while swimming."),
    "swim_fins": (900, "Swim Fins — foot fins used to increase propulsion while swimming."),
    "kickboard": (500, "Kickboard — a flotation board used for swim training."),
    "snorkel_set": (1500, "Snorkel Set — a mask and snorkel combo used for underwater viewing."),
    "life_jacket": (1800, "Life Jacket — a flotation vest worn for water safety."),
    "paddle_board": (18000, "Paddle Board — a board used for stand-up paddleboarding."),
    "kayak": (25000, "Kayak — a small watercraft propelled by a double-bladed paddle."),
    "inflatable_boat": (12000, "Inflatable Boat — a portable inflatable watercraft."),
    "outdoor_recreation": (1500, "Outdoor Recreation Set — a bundled set of general outdoor leisure gear."),
    "picnic_blanket": (900, "Picnic Blanket — a portable blanket designed for outdoor picnics."),
    "hammock": (1800, "Hammock — a suspended fabric bed used for outdoor relaxation."),
    "portable_chair": (1500, "Portable Chair — a lightweight, foldable chair for outdoor use."),
    "beach_umbrella": (2200, "Beach Umbrella — a large umbrella designed for shade at the beach."),
    "fishing_rod": (1800, "Fishing Rod — a rod used for casting and reeling in fishing."),
    "fishing_reel": (1500, "Fishing Reel — a reel used to wind and release fishing line."),
    "fishing_tackle_box": (900, "Fishing Tackle Box — a box used to organize fishing gear."),
    "fishing_line": (350, "Fishing Line — line used for casting and catching fish."),
    "fishing_lures": (400, "Fishing Lures — bait-like items used to attract fish."),
    "boxing_martial_arts": (1500, "Boxing & Martial Arts Set — a bundled set of combat sport equipment."),
    "boxing_gloves": (1500, "Boxing Gloves — padded gloves used for boxing training and sparring."),
    "punching_bag": (5500, "Punching Bag — a heavy bag used for boxing and striking practice."),
    "hand_wraps": (350, "Hand Wraps — wraps used to protect hands during boxing training."),
    "mma_gloves": (1500, "MMA Gloves — fingerless gloves designed for mixed martial arts training."),
    "karate_uniform": (1500, "Karate Uniform — a traditional uniform worn for karate practice."),
    "taekwondo_uniform": (1500, "Taekwondo Uniform — a traditional uniform worn for taekwondo practice."),
    "martial_arts_belt": (350, "Martial Arts Belt — a rank belt worn with a martial arts uniform."),
    "head_guard": (1200, "Head Guard — protective headgear worn during combat sports sparring."),
    "winter_sports": (2500, "Winter Sports Set — a bundled set of equipment for winter sports."),
    "ski_helmet": (3500, "Ski Helmet — protective headgear designed for skiing and snowboarding."),
    "ski_goggles": (2200, "Ski Goggles — eyewear designed to protect eyes during winter sports."),
    "ski_poles": (1800, "Ski Poles — poles used for balance and propulsion while skiing."),
    "snow_boots": (2500, "Snow Boots — insulated boots designed for cold, snowy conditions."),
    "ice_skates": (3500, "Ice Skates — boots fitted with blades for ice skating."),
    "sled": (1800, "Sled — a device used for sliding on snow."),
    "golf": (2500, "Golf Set — a bundled set of golf equipment."),
    "golf_clubs": (12000, "Golf Clubs — clubs used for playing golf."),
    "golf_balls": (700, "Golf Balls — balls designed for playing golf."),
    "golf_bag": (3500, "Golf Bag — a bag designed to carry golf clubs and accessories."),
    "golf_gloves": (500, "Golf Gloves — gloves designed to improve grip while playing golf."),
    "golf_tees": (150, "Golf Tees — small pegs used to elevate a golf ball for the first shot."),
    "golf_rangefinder": (4500, "Golf Rangefinder — a device used to measure distance to the golf hole."),
    "sportswear": (900, "Sportswear Set — a bundled set of athletic apparel."),
    "sports_t_shirt": (500, "Sports T-Shirt — a breathable t-shirt designed for athletic activity."),
    "compression_shirt": (700, "Compression Shirt — a tight-fitting shirt designed to support muscles during exercise."),
    "sports_shorts": (500, "Sports Shorts — lightweight shorts designed for athletic activity."),
    "leggings": (700, "Leggings — form-fitting pants designed for exercise and athletic wear."),
    "track_pants": (700, "Track Pants — loose-fitting pants designed for athletic and casual wear."),
    "sports_jacket": (1500, "Sports Jacket — a lightweight jacket designed for athletic activity."),
    "sports_bra": (500, "Sports Bra — supportive activewear designed for exercise."),
    "compression_socks": (400, "Compression Socks — socks designed to improve circulation during exercise or recovery."),
    "wearables": (2500, "Wearables Set — a bundled set of wearable fitness devices."),
    "smartwatch": (5500, "Smartwatch — a wearable device offering fitness tracking and notifications."),
    "heart_rate_monitor": (2200, "Heart Rate Monitor — a wearable device that tracks heart rate during exercise."),
    "gps_sports_watch": (6500, "GPS Sports Watch — a wearable watch that tracks location and performance metrics."),
    "sports_nutrition": (900, "Sports Nutrition Set — a bundled set of hydration and nutrition accessories."),
    "protein_shaker_bottle": (400, "Protein Shaker Bottle — a bottle designed for mixing protein shakes."),
    "water_bottle": (350, "Water Bottle — a reusable bottle designed for staying hydrated."),
    "hydration_pack": (2200, "Hydration Pack — a backpack with a built-in water reservoir for hydration on the go."),
    "electrolyte_bottle": (500, "Electrolyte Bottle — a bottle designed for mixing electrolyte drinks."),
    "recovery_rehabilitation": (1800, "Recovery & Rehabilitation Set — a bundled set of muscle recovery accessories."),
    "massage_gun": (4500, "Massage Gun — a handheld device used for percussive muscle recovery."),
    "massage_ball": (500, "Massage Ball — a small ball used for targeted muscle release."),
    "ice_pack": (400, "Ice Pack — a reusable cold pack used to reduce swelling and pain."),
    "heating_pad": (900, "Heating Pad — a pad used to apply heat therapy to sore muscles."),
    "knee_brace": (900, "Knee Brace — a supportive brace worn to stabilize the knee."),
    "ankle_support": (600, "Ankle Support — a supportive wrap worn to stabilize the ankle."),
    "wrist_support": (500, "Wrist Support — a supportive wrap worn to stabilize the wrist."),
    "compression_sleeve": (500, "Compression Sleeve — a sleeve worn to support muscles and circulation."),
    "outdoor_safety": (1200, "Outdoor Safety Set — a bundled set of safety gear for outdoor activities."),
    "first_aid_kit": (900, "First Aid Kit — a compact kit of essential supplies for treating minor injuries."),
    "emergency_whistle": (200, "Emergency Whistle — a whistle used to signal for help in emergencies."),
    "survival_kit": (2200, "Survival Kit — a kit of essential tools for outdoor emergency situations."),
    "fire_starter": (400, "Fire Starter — a tool used to ignite a fire in outdoor conditions."),
    "emergency_blanket": (350, "Emergency Blanket — a lightweight thermal blanket used for emergency warmth."),
    "bear_bell": (250, "Bear Bell — a small bell worn to alert wildlife of a hiker's presence."),
    "gym_accessories": (900, "Gym Accessories Set — a bundled set of general gym accessories."),
    "gym_bag": (1500, "Gym Bag — a bag designed to carry workout gear and clothing."),
    "sweat_towel": (350, "Sweat Towel — a small towel used to wipe sweat during workouts."),
    "lifting_belt": (1500, "Lifting Belt — a supportive belt worn during heavy weightlifting."),
    "wrist_wraps": (400, "Wrist Wraps — wraps used to support the wrists during weightlifting."),
    "lifting_straps": (500, "Lifting Straps — straps used to improve grip during heavy lifts."),
    "chalk_ball": (300, "Chalk Ball — a ball of chalk used to improve grip during lifting."),
    "gym_gloves": (500, "Gym Gloves — gloves worn to protect hands during weightlifting."),
    "kids_sports": (1200, "Kids Sports Set — a bundled set of sports equipment designed for children."),
    "kids_bicycle": (8500, "Kids Bicycle — a bicycle sized for children."),
    "kids_helmet": (900, "Kids Helmet — protective headgear sized for children."),
    "skateboard": (2500, "Skateboard — a board with wheels used for skateboarding."),
    "scooter": (3500, "Scooter — a foot-powered or kick scooter used for recreation and transport."),
    "roller_skates": (2500, "Roller Skates — footwear fitted with wheels for skating."),
    "balance_bike": (3500, "Balance Bike — a pedal-less bike designed to teach young children balance."),
    "referee_coaching": (900, "Referee & Coaching Set — a bundled set of officiating and coaching accessories."),
    "stopwatch": (500, "Stopwatch — a timing device used for sports and training."),
    "whistle": (150, "Whistle — a device used by referees and coaches to signal during play."),
    "scoreboard": (3500, "Scoreboard — a display board used to track scores during a game."),
    "coaching_board": (700, "Coaching Board — a tactics board used by coaches to plan plays."),
    "training_cones": (500, "Training Cones — marker cones used for agility and drill training."),
    "agility_ladder": (900, "Agility Ladder — a flat ladder used for footwork and speed training."),
    "speed_parachute": (900, "Speed Parachute — a resistance parachute used for sprint training."),
}

paths = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch3.json",
]

total_updated = 0
total_skipped = []

for path in paths:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    updated = 0
    skipped = []
    for sku, prod in data.items():
        if prod.get("categoryId") == "sports_outdoors_fitness":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
            else:
                skipped.append((sku, img))

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"--- {path}: Updated {updated}, Skipped {skipped} ---")
    total_updated += updated
    total_skipped.extend(skipped)

print(f"TOTAL Updated: {total_updated}")
print(f"TOTAL Skipped: {total_skipped}")
