import json

price_desc = {
    "office_school_supplies": (300, "Office & School Supplies — a general range of stationery and office essentials."),
    "notebook_pens_pencil_holder": (500, "Notebook, Pens & Pencil Holder Set — a bundled set of essential stationery items."),
    "writing_instruments": (100, "Writing Instruments — a general range of pens and pencils for everyday writing."),
    "ballpoint_pen": (30, "Ballpoint Pen — a standard pen used for everyday writing."),
    "gel_pen": (50, "Gel Pen — a smooth-writing pen using gel-based ink."),
    "fountain_pen": (500, "Fountain Pen — a classic pen using liquid ink for smooth, elegant writing."),
    "rollerball_pen": (80, "Rollerball Pen — a pen using liquid ink for a smooth writing experience."),
    "marker_pen": (60, "Marker Pen — a pen used for bold writing and coloring."),
    "permanent_marker": (60, "Permanent Marker — a marker using long-lasting, waterproof ink."),
    "whiteboard_marker": (60, "Whiteboard Marker — a marker designed for writing on whiteboards."),
    "highlighter": (50, "Highlighter — a marker used to emphasize text on paper."),
    "pencil": (15, "Pencil — a standard graphite pencil used for writing and drawing."),
    "mechanical_pencil": (100, "Mechanical Pencil — a pencil using replaceable lead for consistent writing."),
    "colored_pencils": (350, "Colored Pencils — a set of pencils used for coloring and illustration."),
    "charcoal_pencil": (60, "Charcoal Pencil — a drawing pencil used for sketching and shading."),
    "eraser": (15, "Eraser — a tool used for removing pencil marks."),
    "pencil_sharpener": (30, "Pencil Sharpener — a tool used for sharpening pencils."),
    "pencil_case": (250, "Pencil Case — a case designed for storing pens, pencils, and small stationery."),
    "paper_products": (200, "Paper Products — a general range of paper items for writing and printing."),
    "a4_copy_paper": (350, "A4 Copy Paper — standard paper used for printing and copying documents."),
    "a3_paper": (500, "A3 Paper — larger format paper used for printing and drawing."),
    "printer_paper": (350, "Printer Paper — standard paper designed for use in printers."),
    "photo_paper": (500, "Photo Paper — glossy paper designed for printing photographs."),
    "graph_paper": (150, "Graph Paper — paper printed with a grid, used for technical drawing and math."),
    "construction_paper": (200, "Construction Paper — thick colored paper commonly used for crafts."),
    "cardstock": (300, "Cardstock — thick, sturdy paper suited for crafting and card making."),
    "colored_paper": (200, "Colored Paper — assorted colored paper sheets used for crafts and printing."),
    "sticky_notes": (100, "Sticky Notes — small adhesive notes used for reminders and annotations."),
    "memo_pad": (100, "Memo Pad — a small notepad used for quick notes and reminders."),
    "notepad": (100, "Notepad — a pad of lined or blank paper for writing notes."),
    "notebook": (150, "Notebook — a bound book of pages used for writing and note-taking."),
    "spiral_notebook": (150, "Spiral Notebook — a notebook bound with a spiral coil for easy page-turning."),
    "composition_book": (150, "Composition Book — a stitched notebook commonly used for schoolwork."),
    "sketchbook": (350, "Sketchbook — a bound book of blank paper used for drawing and sketching."),
    "drawing_book": (250, "Drawing Book — a book of blank pages designed for drawing and illustration."),
    "scrapbook": (500, "Scrapbook — a book designed for arranging photos, mementos, and decorations."),
    "filing_organization": (250, "Filing & Organization — a general range of products for organizing documents."),
    "file_folder": (30, "File Folder — a basic folder used for organizing loose documents."),
    "lever_arch_file": (300, "Lever Arch File — a large capacity file with a lever mechanism for holding documents."),
    "ring_binder": (250, "Ring Binder — a binder with rings used for organizing loose-leaf paper."),
    "expanding_file": (350, "Expanding File — a multi-pocket file used for organizing documents by category."),
    "document_wallet": (100, "Document Wallet — a flat folder used for holding loose documents."),
    "clipboard": (200, "Clipboard — a flat board with a clip used to hold papers for writing."),
    "document_tray": (350, "Document Tray — a tray designed for organizing incoming and outgoing documents."),
    "magazine_holder": (400, "Magazine Holder — a stand designed for organizing magazines and folders."),
    "file_box": (500, "File Box — a storage box designed for organizing files and documents."),
    "folder_labels": (100, "Folder Labels — adhesive labels used for identifying files and folders."),
    "index_dividers": (150, "Index Dividers — tabbed dividers used to organize sections within a binder."),
    "desk_accessories": (300, "Desk Accessories — a general range of items used to organize a desk."),
    "pen_holder": (200, "Pen Holder — a stand designed for organizing pens and pencils on a desk."),
    "desk_organizer": (500, "Desk Organizer — a multi-compartment tray used for organizing desk items."),
    "paper_tray": (350, "Paper Tray — a tray designed for holding loose sheets of paper."),
    "letter_tray": (350, "Letter Tray — a tray designed for organizing incoming and outgoing letters."),
    "book_stand": (400, "Book Stand — a stand designed for holding books upright while reading."),
    "monitor_stand": (700, "Monitor Stand — a stand designed to raise a monitor to eye level."),
    "desk_pad": (500, "Desk Pad — a large writing pad used to protect and decorate a desk surface."),
    "mouse_pad": (200, "Mouse Pad — a flat pad designed for smooth mouse movement on a desk."),
    "name_plate": (300, "Name Plate — a desk plate used to display a name or title."),
    "business_card_holder": (250, "Business Card Holder — a case designed for storing and organizing business cards."),
    "calendar": (200, "Calendar — a printed calendar used for tracking dates and schedules."),
    "desk_clock": (500, "Desk Clock — a small clock designed for placement on a desk."),
    "adhesives_tapes": (100, "Adhesives & Tapes — a general range of adhesive products for office use."),
    "glue_stick": (60, "Glue Stick — a solid adhesive stick used for paper crafts."),
    "liquid_glue": (60, "Liquid Glue — a liquid adhesive used for paper and craft projects."),
    "super_glue": (80, "Super Glue — a fast-bonding adhesive used for various materials."),
    "double_sided_tape": (80, "Double-Sided Tape — a tape with adhesive on both sides for mounting and crafts."),
    "masking_tape": (60, "Masking Tape — a low-tack tape used for temporary marking and masking."),
    "transparent_tape": (50, "Transparent Tape — a clear adhesive tape used for general purposes."),
    "packing_tape": (100, "Packing Tape — a strong adhesive tape used for sealing packages."),
    "tape_dispenser": (200, "Tape Dispenser — a tool designed for holding and cutting adhesive tape."),
    "glue_gun": (500, "Glue Gun — a tool that melts glue sticks for craft bonding."),
    "glue_sticks": (150, "Glue Sticks — solid adhesive sticks used with a glue gun."),
    "cutting_measuring": (150, "Cutting & Measuring Tools — a general range of tools for cutting and measuring."),
    "scissors": (150, "Scissors — a cutting tool used for paper and craft projects."),
    "utility_knife": (150, "Utility Knife — a precision knife used for cutting paper and materials."),
    "paper_cutter": (700, "Paper Cutter — a tool designed for cutting stacks of paper evenly."),
    "rotary_cutter": (500, "Rotary Cutter — a wheeled cutting tool used for precise straight cuts."),
    "metal_ruler": (100, "Metal Ruler — a durable ruler used for precise measuring and cutting."),
    "plastic_ruler": (30, "Plastic Ruler — a basic ruler used for measuring and drawing straight lines."),
    "measuring_tape": (150, "Measuring Tape — a flexible tape used for measuring length."),
    "protractor": (50, "Protractor — a tool used for measuring and drawing angles."),
    "compass": (100, "Compass — a tool used for drawing circles and measuring arcs."),
    "geometry_set": (200, "Geometry Set — a set of tools used for geometric drawing, including ruler and compass."),
    "stapling_binding": (150, "Stapling & Binding — a general range of tools for stapling and binding documents."),
    "stapler": (200, "Stapler — a tool used for fastening sheets of paper together."),
    "staples": (60, "Staples — small metal fasteners used with a stapler."),
    "staple_remover": (60, "Staple Remover — a tool used for removing staples from paper."),
    "hole_punch": (250, "Hole Punch — a tool used for punching holes in paper for binders."),
    "binder_clips": (60, "Binder Clips — clips used for holding stacks of paper together."),
    "paper_clips": (40, "Paper Clips — small clips used for holding loose sheets of paper together."),
    "rubber_bands": (40, "Rubber Bands — elastic bands used for bundling items together."),
    "push_pins": (50, "Push Pins — small pins used for mounting paper on boards."),
    "thumb_tacks": (50, "Thumb Tacks — small tacks used for pinning paper to surfaces."),
    "spiral_binding_machine": (3500, "Spiral Binding Machine — a machine used for binding documents with a spiral coil."),
    "binding_covers": (300, "Binding Covers — cover sheets used for finishing bound documents."),
    "whiteboards_presentation": (500, "Whiteboards & Presentation — a general range of tools for presentations and displays."),
    "whiteboard": (1500, "Whiteboard — a reusable board used for writing with dry-erase markers."),
    "magnetic_whiteboard": (2200, "Magnetic Whiteboard — a whiteboard with a magnetic surface for holding notes."),
    "cork_board": (900, "Cork Board — a pinboard used for displaying notes and reminders."),
    "bulletin_board": (1200, "Bulletin Board — a board used for displaying announcements and notices."),
    "flip_chart": (2500, "Flip Chart — a large pad of paper on an easel used for presentations."),
    "easel_stand": (1500, "Easel Stand — a stand designed for holding a flip chart or whiteboard."),
    "whiteboard_eraser": (100, "Whiteboard Eraser — a tool used for erasing dry-erase marker ink."),
    "whiteboard_cleaner": (150, "Whiteboard Cleaner — a solution used for cleaning whiteboard surfaces."),
    "presentation_pointer": (500, "Presentation Pointer — a laser pointer used for highlighting during presentations."),
    "art_craft_supplies": (300, "Art & Craft Supplies — a general range of materials for art and craft projects."),
    "acrylic_paint": (400, "Acrylic Paint — a fast-drying water-based paint for various art projects."),
    "watercolor_paint": (450, "Watercolor Paint — a water-based paint used for fine art painting."),
    "oil_paint": (600, "Oil Paint — a slow-drying paint used for fine art painting."),
    "paint_brushes": (400, "Paint Brushes — a set of brushes used for painting and craft projects."),
    "canvas": (500, "Canvas — a blank stretched surface used for painting."),
    "palette": (350, "Palette — a flat surface used for mixing paint colors."),
    "craft_paper": (200, "Craft Paper — plain or colored paper used for a variety of craft projects."),
    "glitter": (100, "Glitter — small sparkling particles used to decorate craft projects."),
    "foam_sheets": (150, "Foam Sheets — soft craft sheets used for cutting and shaping decorations."),
    "clay": (350, "Clay — moldable material used for sculpting and craft projects."),
    "modeling_clay": (350, "Modeling Clay — pliable clay used for sculpting and craft projects."),
    "origami_paper": (200, "Origami Paper — thin, colored paper designed for paper-folding crafts."),
    "stickers": (100, "Stickers — adhesive decorative labels used for crafts and decoration."),
    "school_essentials": (350, "School Essentials — a general range of items needed for school."),
    "school_bag": (1200, "School Bag — a durable backpack designed for carrying school supplies."),
    "backpack": (1200, "Backpack — a general-purpose bag for carrying books and belongings."),
    "lunch_box": (450, "Lunch Box — a container designed for carrying meals to school or work."),
    "water_bottle": (350, "Water Bottle — a reusable bottle designed for carrying drinking water."),
    "school_uniform": (900, "School Uniform — standard clothing worn by students as part of a school dress code."),
    "name_labels": (100, "Name Labels — adhesive labels used to mark personal belongings with a name."),
    "id_card_holder": (150, "ID Card Holder — a case designed for holding and displaying identification cards."),
    "exam_pad": (150, "Exam Pad — a rigid writing pad used for taking exams."),
    "flash_cards": (200, "Flash Cards — cards used for memorization and quick learning."),
    "office_electronics": (900, "Office Electronics — a general range of electronic devices for office use."),
    "calculator": (250, "Calculator — a device used for performing mathematical calculations."),
    "scientific_calculator": (700, "Scientific Calculator — a calculator designed for advanced mathematical functions."),
    "label_printer": (3500, "Label Printer — a printer designed for creating adhesive labels."),
    "barcode_scanner": (2500, "Barcode Scanner — a device used for scanning and reading barcodes."),
    "laminating_machine": (2500, "Laminating Machine — a device used for sealing documents in protective plastic film."),
    "laminating_pouches": (300, "Laminating Pouches — plastic pouches used for laminating documents."),
    "paper_shredder": (3500, "Paper Shredder — a machine used for destroying sensitive documents."),
    "document_scanner": (5500, "Document Scanner — a device used for digitizing paper documents."),
    "printer": (9500, "Printer — a device used for printing documents and images."),
    "printer_ink": (900, "Printer Ink — ink cartridges used for inkjet printers."),
    "toner_cartridge": (1800, "Toner Cartridge — a cartridge used for laser printers."),
    "teacher_classroom_supplies": (350, "Teacher & Classroom Supplies — a general range of materials for classroom use."),
    "attendance_register": (200, "Attendance Register — a book used for recording student attendance."),
    "lesson_planner": (300, "Lesson Planner — a planner used for organizing lesson schedules and content."),
    "grade_book": (250, "Grade Book — a book used for recording student grades and assessments."),
    "classroom_timer": (700, "Classroom Timer — a timer used for managing classroom activities and tests."),
    "educational_charts": (300, "Educational Charts — printed charts used for teaching various subjects."),
    "alphabet_chart": (200, "Alphabet Chart — a chart used for teaching letter recognition."),
    "world_map": (500, "World Map — a printed map used for teaching geography."),
    "globe": (1500, "Globe — a spherical model of the Earth used for teaching geography."),
    "storage_organization": (350, "Storage & Organization — a general range of products for organizing supplies."),
    "storage_box": (500, "Storage Box — a box designed for general storage of supplies and items."),
    "plastic_drawer": (900, "Plastic Drawer — a stackable drawer unit used for organizing items."),
    "shelf_organizer": (700, "Shelf Organizer — a unit designed for organizing items on a shelf."),
    "storage_basket": (500, "Storage Basket — a basket used for organizing loose items."),
    "bookends": (350, "Bookends — supports used to keep books upright on a shelf."),
    "drawer_organizer": (500, "Drawer Organizer — a tray used for organizing small items within a drawer."),
    "mailing_shipping": (150, "Mailing & Shipping — a general range of supplies for sending mail and packages."),
    "envelopes": (100, "Envelopes — paper covers used for mailing letters and documents."),
    "bubble_mailers": (150, "Bubble Mailers — padded envelopes used for shipping fragile items."),
    "shipping_labels": (100, "Shipping Labels — adhesive labels used for addressing packages."),
    "packing_list_envelope": (100, "Packing List Envelope — a clear envelope used for attaching packing lists to shipments."),
    "postal_scale": (900, "Postal Scale — a scale used for weighing letters and packages."),
    "packaging_tape": (100, "Packaging Tape — a strong adhesive tape used for sealing packages."),
    "office_furniture_accessories": (500, "Office Furniture Accessories — a general range of accessories for office furniture."),
    "office_chair_mat": (1500, "Office Chair Mat — a protective mat placed under an office chair."),
    "foot_rest": (900, "Foot Rest — an ergonomic support designed to rest the feet while seated."),
    "laptop_stand": (900, "Laptop Stand — a stand designed to raise a laptop to a comfortable viewing height."),
    "keyboard_tray": (1500, "Keyboard Tray — a sliding tray designed to hold a keyboard under a desk."),
    "cable_organizer": (300, "Cable Organizer — a tool used for organizing and managing cables."),
    "computer_accessories": (500, "Computer Accessories — a general range of accessories used with computers."),
    "usb_flash_drive": (700, "USB Flash Drive — a portable storage device with a standard USB connector."),
    "external_hard_drive": (4500, "External Hard Drive — a portable storage device used for backing up data."),
    "usb_hub": (700, "USB Hub — a device that expands a single USB port into multiple ports."),
    "memory_card": (700, "Memory Card — a small storage card used for expanding device storage."),
    "card_reader": (400, "Card Reader — a device used to read data from memory cards."),
    "webcam": (2200, "Webcam — a camera device used for video calls and streaming."),
    "headset": (900, "Headset — a combined headphone and microphone device used for calls."),
    "cleaning_supplies": (200, "Cleaning Supplies — a general range of products for office cleaning."),
    "screen_cleaning_kit": (300, "Screen Cleaning Kit — a set of tools designed for cleaning device screens."),
    "keyboard_cleaning_brush": (150, "Keyboard Cleaning Brush — a small brush used for cleaning keyboard crevices."),
    "cleaning_wipes": (150, "Cleaning Wipes — pre-moistened wipes used for general office cleaning."),
    "hand_sanitizer": (150, "Hand Sanitizer — a liquid gel used for disinfecting hands."),
    "trash_bin": (500, "Trash Bin — a container used for disposing of waste in an office or classroom."),
    "awards_recognition": (500, "Awards & Recognition — a general range of items used for honoring achievement."),
    "trophy": (900, "Trophy — an award given to recognize achievement or victory."),
    "medal": (600, "Medal — a collectible or award medal valued for recognition."),
    "certificate_holder": (200, "Certificate Holder — a folder designed for protecting and presenting certificates."),
    "plaque": (900, "Plaque — a decorative award piece used for recognition."),
    "ribbon_award": (150, "Ribbon Award — a fabric ribbon given to recognize achievement."),
    "educational_supplies": (500, "Educational Supplies — a general range of materials used for learning."),
    "educational_toys": (700, "Educational Toys — toys designed to support learning and development."),
    "science_lab_kit": (1800, "Science Lab Kit — a kit designed for conducting basic science experiments."),
    "math_learning_kit": (900, "Math Learning Kit — a kit designed to support math skill development."),
    "stem_kit": (2500, "STEM Kit — a kit designed to teach science, technology, engineering, and math concepts."),
    "puzzle_set": (700, "Puzzle Set — a set of puzzles designed for learning and entertainment."),
}

files_map = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch3.json",
]

updated = 0
skipped = []

for path in files_map:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    changed = False
    for sku, prod in data.items():
        if prod.get("categoryId") == "office_school_supplies":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
                changed = True
            else:
                skipped.append((path, sku, img))
    if changed:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
