import json

price_desc = {
    "video_games_consoles": (500, "Video Games & Consoles — a general range of gaming consoles, games and accessories."),
    "gaming_console_and_controller": (35000, "Gaming Console and Controller — a bundled set including a console and matching controller."),
    "gaming_consoles": (30000, "Gaming Consoles — a general listing category for home and portable game consoles."),
    "home_gaming_console": (35000, "Home Gaming Console — a stationary console designed for TV-connected gaming."),
    "handheld_gaming_console": (25000, "Handheld Gaming Console — a portable console designed for on-the-go gaming."),
    "portable_gaming_console": (22000, "Portable Gaming Console — a compact console designed for travel-friendly gaming."),
    "retro_gaming_console": (8000, "Retro Gaming Console — a console designed to play classic and older-generation games."),
    "mini_gaming_console": (5500, "Mini Gaming Console — a compact console preloaded with classic games."),
    "digital_edition_console": (32000, "Digital Edition Console — a disc-less console version designed for digital game downloads."),
    "console_bundle": (40000, "Console Bundle — a package deal combining a console with games or accessories."),
    "gaming_controllers": (2500, "Gaming Controllers — a general listing category for console and PC game controllers."),
    "wireless_controller": (3500, "Wireless Controller — a cordless controller designed for console and PC gaming."),
    "wired_controller": (1800, "Wired Controller — a cable-connected controller designed for console and PC gaming."),
    "pro_controller": (5500, "Pro Controller — a premium controller with enhanced features for competitive gaming."),
    "arcade_stick": (6500, "Arcade Stick — a joystick-style controller designed for arcade-style gaming."),
    "fight_stick": (7500, "Fight Stick — an arcade-style controller designed for fighting games."),
    "racing_wheel": (8500, "Racing Wheel — a steering wheel controller designed for racing games."),
    "flight_stick": (6500, "Flight Stick — a joystick controller designed for flight simulation games."),
    "joystick": (3500, "Joystick — a control stick used for precise directional input in games."),
    "gamepad": (2200, "Gamepad — a handheld controller designed for console and PC gaming."),
    "mobile_game_controller": (2500, "Mobile Game Controller — a controller designed to clip onto a smartphone for gaming."),
    "console_accessories": (1000, "Console Accessories — a general range of accessories for gaming consoles."),
    "charging_dock": (2200, "Charging Dock — a docking station designed to charge gaming controllers."),
    "charging_cable": (500, "Charging Cable — a cable designed to charge gaming controllers and devices."),
    "rechargeable_battery_pack": (1500, "Rechargeable Battery Pack — a battery pack designed to power wireless controllers."),
    "controller_grip": (700, "Controller Grip — an add-on grip designed to improve controller handling."),
    "controller_case": (900, "Controller Case — a protective case designed to store a game controller."),
    "thumb_grips": (400, "Thumb Grips — small silicone caps designed to improve thumbstick control."),
    "trigger_extenders": (600, "Trigger Extenders — attachments designed to extend controller trigger reach."),
    "cooling_stand": (1800, "Cooling Stand — a stand fitted with fans to cool a gaming console."),
    "vertical_stand": (900, "Vertical Stand — a stand designed to hold a console upright to save space."),
    "console_carrying_case": (2500, "Console Carrying Case — a protective case designed for transporting a console."),
    "gaming_headsets_audio": (2000, "Gaming Headsets & Audio — a general range of audio products for gaming."),
    "gaming_headset": (3500, "Gaming Headset — a headset designed for immersive in-game audio and voice chat."),
    "wireless_gaming_headset": (5500, "Wireless Gaming Headset — a cordless headset designed for gaming audio and voice chat."),
    "wired_gaming_headset": (2500, "Wired Gaming Headset — a cable-connected headset designed for gaming audio."),
    "gaming_earbuds": (2200, "Gaming Earbuds — compact wireless earbuds designed for low-latency gaming audio."),
    "usb_microphone": (4500, "USB Microphone — a plug-and-play microphone designed for streaming and voice chat."),
    "gaming_speakers": (3500, "Gaming Speakers — speakers designed to enhance in-game audio immersion."),
    "soundbar": (5500, "Soundbar — a compact speaker bar designed to enhance TV and gaming audio."),
    "gaming_monitors_displays": (2500, "Gaming Monitors & Displays — a general range of display products for gaming."),
    "gaming_monitor": (25000, "Gaming Monitor — a high-refresh-rate monitor designed for competitive gaming."),
    "curved_gaming_monitor": (35000, "Curved Gaming Monitor — a curved-screen monitor designed for immersive gaming."),
    "portable_gaming_monitor": (18000, "Portable Gaming Monitor — a compact, lightweight monitor designed for gaming on the go."),
    "monitor_arm": (3500, "Monitor Arm — an adjustable mount designed to position a monitor ergonomically."),
    "hdmi_switch": (1800, "HDMI Switch — a device that allows multiple HDMI sources to share one display."),
    "displayport_cable": (900, "DisplayPort Cable — a cable designed for high-resolution video and audio transfer."),
    "virtual_reality_vr": (2500, "Virtual Reality (VR) — a general range of VR gaming products."),
    "vr_headset": (35000, "VR Headset — a head-mounted display designed for immersive virtual reality gaming."),
    "vr_controllers": (8500, "VR Controllers — motion controllers designed for interacting in virtual reality."),
    "vr_face_cover": (900, "VR Face Cover — a replaceable, washable cover designed for VR headset comfort and hygiene."),
    "vr_carrying_case": (2500, "VR Carrying Case — a protective case designed for transporting a VR headset and accessories."),
    "vr_charging_dock": (2200, "VR Charging Dock — a docking station designed to charge VR controllers."),
    "vr_link_cable": (3500, "VR Link Cable — a cable designed to connect a VR headset to a PC for high-speed data transfer."),
    "video_games": (2500, "Video Games — a general listing category for physical and digital games."),
    "physical_games": (2500, "Physical Games — disc or cartridge-based games designed for consoles."),
    "action_games": (2800, "Action Games — fast-paced games focused on combat and physical challenges."),
    "adventure_games": (2800, "Adventure Games — story-driven games focused on exploration and puzzle solving."),
    "rpg_games": (3000, "RPG Games — role-playing games focused on character progression and storytelling."),
    "racing_games": (2800, "Racing Games — games focused on competitive vehicle racing."),
    "sports_games": (2800, "Sports Games — games simulating real-world sports and competitions."),
    "strategy_games": (2800, "Strategy Games — games focused on tactical planning and resource management."),
    "simulation_games": (2800, "Simulation Games — games designed to realistically simulate real-world activities."),
    "puzzle_games": (2000, "Puzzle Games — games focused on logic, problem-solving and brain teasers."),
    "horror_games": (2800, "Horror Games — games designed to deliver suspense and scares through gameplay and story."),
    "fighting_games": (2800, "Fighting Games — games focused on one-on-one or team combat mechanics."),
    "family_games": (2500, "Family Games — games designed to be enjoyed by players of all ages."),
    "digital_games": (2500, "Digital Games — downloadable games purchased and played without a physical disc."),
    "digital_game_download": (2500, "Digital Game Download — a code or direct download granting access to a digital game."),
    "game_expansion_pack": (1500, "Game Expansion Pack — additional content that expands an existing game's story or features."),
    "season_pass": (2500, "Season Pass — a bundled pass granting access to a game's upcoming downloadable content."),
    "downloadable_content_dlc": (1200, "Downloadable Content (DLC) — additional purchasable content added to a base game."),
    "pc_gaming_accessories": (1500, "PC Gaming Accessories — a general range of accessories designed for PC gaming setups."),
    "gaming_keyboard": (3500, "Gaming Keyboard — a keyboard designed with responsive keys for competitive gaming."),
    "mechanical_keyboard": (5500, "Mechanical Keyboard — a keyboard using mechanical switches for tactile, durable typing."),
    "gaming_mouse": (2500, "Gaming Mouse — a precision mouse designed for fast, accurate in-game movement."),
    "mouse_pad": (700, "Mouse Pad — a smooth surface designed to improve mouse tracking and comfort."),
    "rgb_mouse_pad": (1500, "RGB Mouse Pad — a mouse pad fitted with customizable RGB lighting."),
    "gaming_chair": (12000, "Gaming Chair — an ergonomic chair designed for long gaming sessions."),
    "gaming_desk": (15000, "Gaming Desk — a desk designed with features suited for a gaming setup."),
    "gaming_webcam": (3500, "Gaming Webcam — a webcam designed for streaming and video calls while gaming."),
    "stream_deck": (8500, "Stream Deck — a customizable control panel designed for streamers and content creators."),
    "pc_gaming_components": (2500, "PC Gaming Components — a general range of internal parts used to build gaming PCs."),
    "graphics_card_gpu": (65000, "Graphics Card (GPU) — a component that renders visuals for high-performance gaming."),
    "gaming_processor_cpu": (35000, "Gaming Processor (CPU) — a processor designed for high-performance gaming workloads."),
    "gaming_motherboard": (18000, "Gaming Motherboard — a motherboard designed to support high-performance gaming components."),
    "gaming_ram": (6500, "Gaming RAM — high-speed memory modules designed for gaming performance."),
    "nvme_ssd": (8500, "NVMe SSD — a high-speed solid-state drive designed for fast game loading."),
    "liquid_cpu_cooler": (7500, "Liquid CPU Cooler — a liquid cooling system designed to keep a gaming CPU cool."),
    "power_supply_psu": (6500, "Power Supply (PSU) — a unit that supplies stable power to a gaming PC's components."),
    "gaming_pc_case": (8500, "Gaming PC Case — a case designed to house and showcase gaming PC components."),
    "rgb_fans": (1800, "RGB Fans — case fans fitted with customizable RGB lighting."),
    "streaming_equipment": (2500, "Streaming Equipment — a general range of equipment designed for content creation and streaming."),
    "capture_card": (8500, "Capture Card — a device used to record and stream gameplay footage."),
    "streaming_microphone": (5500, "Streaming Microphone — a high-quality microphone designed for live streaming."),
    "webcam": (2500, "Webcam — a camera designed for video calls and streaming."),
    "ring_light": (1800, "Ring Light — a circular light designed to evenly illuminate a streamer on camera."),
    "green_screen": (3500, "Green Screen — a backdrop used to digitally replace a streamer's background."),
    "boom_arm": (2200, "Boom Arm — an adjustable arm designed to position a microphone for streaming."),
    "audio_mixer": (7500, "Audio Mixer — a device used to control and balance multiple audio sources while streaming."),
    "storage": (1500, "Storage — a general range of storage devices for games and media."),
    "external_ssd": (7500, "External SSD — a portable solid-state drive designed for fast external game storage."),
    "external_hard_drive": (5500, "External Hard Drive — a portable drive designed for extra game and media storage."),
    "usb_flash_drive": (700, "USB Flash Drive — a small portable drive used for storing and transferring files."),
    "microsd_card": (1200, "MicroSD Card — a compact memory card designed for expanding handheld console storage."),
    "memory_card_case": (500, "Memory Card Case — a protective case designed to store and organize memory cards."),
    "cooling_protection": (900, "Cooling & Protection — a general range of products for cooling and protecting gaming gear."),
    "cooling_fan": (1200, "Cooling Fan — a fan designed to help dissipate heat from gaming devices."),
    "cooling_pad": (1500, "Cooling Pad — a padded stand fitted with fans to help cool a device during use."),
    "dust_cover": (500, "Dust Cover — a protective cover designed to keep dust off gaming equipment."),
    "screen_protector": (400, "Screen Protector — a thin film designed to protect a device's screen from scratches."),
    "protective_skin": (700, "Protective Skin — a decorative, protective wrap designed for a console or controller."),
    "carrying_sleeve": (900, "Carrying Sleeve — a slim, padded sleeve designed for protecting portable gaming devices."),
    "cables_connectivity": (500, "Cables & Connectivity — a general range of cables and connectivity accessories."),
    "hdmi_cable": (500, "HDMI Cable — a cable designed to transmit high-definition video and audio."),
    "usb_c_cable": (400, "USB-C Cable — a cable designed for fast charging and data transfer."),
    "ethernet_cable": (400, "Ethernet Cable — a cable designed for stable, wired internet connectivity."),
    "usb_hub": (900, "USB Hub — a device that expands a single USB port into multiple ports."),
    "bluetooth_adapter": (1200, "Bluetooth Adapter — a device that adds wireless Bluetooth connectivity to a system."),
    "racing_flight_simulation": (5500, "Racing & Flight Simulation — a general range of simulation gaming accessories."),
    "gear_shifter": (6500, "Gear Shifter — a simulation accessory that mimics a manual car gear shifter."),
    "handbrake": (5500, "Handbrake — a simulation accessory that mimics a car's handbrake for racing games."),
    "racing_seat": (18000, "Racing Seat — a seat designed to simulate the driving position for racing games."),
    "flight_yoke": (12000, "Flight Yoke — a control yoke designed to simulate aircraft piloting."),
    "flight_rudder_pedals": (9500, "Flight Rudder Pedals — foot pedals designed to simulate aircraft rudder control."),
    "hotas_flight_stick": (15000, "HOTAS Flight Stick — a combined throttle and stick control system for flight simulation."),
    "gaming_furniture": (5500, "Gaming Furniture — a general range of furniture designed for gaming setups."),
    "monitor_stand": (2200, "Monitor Stand — a stand designed to elevate and position a gaming monitor."),
    "headphone_stand": (900, "Headphone Stand — a stand designed to hold and display a gaming headset."),
    "controller_stand": (700, "Controller Stand — a stand designed to hold and display a game controller."),
    "gaming_merchandise": (700, "Gaming Merchandise — a general range of gaming-themed collectibles and apparel."),
    "gaming_t_shirt": (700, "Gaming T-Shirt — a t-shirt featuring gaming-themed designs."),
    "gaming_hoodie": (1800, "Gaming Hoodie — a hoodie featuring gaming-themed designs."),
    "posters": (400, "Posters — printed wall art featuring gaming-themed artwork."),
    "action_figures": (1500, "Action Figures — collectible figures modeled after gaming characters."),
    "collectible_statues": (5500, "Collectible Statues — premium display statues modeled after gaming characters."),
    "gaming_stickers": (200, "Gaming Stickers — decorative stickers featuring gaming-themed designs."),
    "keychains": (300, "Keychains — small collectible keychains featuring gaming-themed designs."),
    "plush_toys": (900, "Plush Toys — soft collectible toys modeled after gaming characters."),
    "retro_gaming": (2500, "Retro Gaming — a general listing category for classic gaming consoles and accessories."),
    "retro_console": (8000, "Retro Console — a console designed to replicate classic gaming systems."),
    "classic_controller": (1800, "Classic Controller — a controller styled after retro gaming console designs."),
    "cartridge_storage_case": (900, "Cartridge Storage Case — a case designed to organize and protect game cartridges."),
    "retro_game_cartridge": (1500, "Retro Game Cartridge — a physical cartridge containing a classic video game."),
    "repair_maintenance": (700, "Repair & Maintenance — a general range of tools for gaming device upkeep."),
    "precision_screwdriver_set": (700, "Precision Screwdriver Set — a set of small screwdrivers designed for electronics repair."),
    "cleaning_kit": (500, "Cleaning Kit — a kit of tools designed for cleaning gaming devices and discs."),
    "thermal_paste": (400, "Thermal Paste — a compound applied to improve heat transfer in gaming hardware."),
    "replacement_thumbsticks": (500, "Replacement Thumbsticks — spare thumbstick caps designed for controller repair."),
    "replacement_buttons": (400, "Replacement Buttons — spare buttons designed for controller repair."),
    "console_repair_kit": (1500, "Console Repair Kit — a complete kit of tools designed for console repair and maintenance."),
    "gift_cards_subscriptions": (1000, "Gift Cards & Subscriptions — a general range of digital gaming gift cards and subscriptions."),
    "digital_gift_card": (1000, "Digital Gift Card — a code redeemable for digital store credit."),
    "game_store_gift_card": (1000, "Game Store Gift Card — a card redeemable for credit at a gaming store."),
    "online_membership_card": (1500, "Online Membership Card — a card granting access to online gaming services."),
    "subscription_voucher": (1200, "Subscription Voucher — a voucher redeemable for a gaming subscription service."),
    "portable_gaming_accessories": (900, "Portable Gaming Accessories — a general range of accessories for handheld gaming devices."),
    "travel_carrying_case": (1500, "Travel Carrying Case — a case designed for safely transporting portable gaming devices."),
    "power_bank": (2200, "Power Bank — a portable battery pack used to charge gaming devices on the go."),
    "protective_case": (700, "Protective Case — a case designed to shield a portable gaming device from damage."),
    "foldable_stand": (500, "Foldable Stand — a compact, collapsible stand designed for handheld gaming devices."),
    "screen_cleaning_kit": (350, "Screen Cleaning Kit — a kit designed for safely cleaning gaming device screens."),
}

paths = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch3.json",
]

target_id = "video_games_consoles"
total_updated = 0

for path in paths:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    updated = 0
    skipped = []
    for sku, prod in data.items():
        if prod.get("categoryId") == target_id:
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
            else:
                skipped.append((sku, img))
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"--- {path}: Updated {updated}, Skipped {skipped} ---")
    total_updated += updated

print(f"TOTAL Updated: {total_updated}")
