import json

price_desc = {
    "toys_games_hobbies": (500, "Toys, Games & Hobbies — a general range of toys, games and hobby items."),
    "teddy_bear_puzzle_pieces_game_controller": (500, "Toys & Games Assortment — a mixed set representing plush toys, puzzles and game accessories."),
    "baby_toddler_toys": (400, "Baby & Toddler Toys — safe, age-appropriate toys designed for very young children."),
    "soft_toys": (400, "Soft Toys — plush, cuddly toys designed for children."),
    "plush_toys": (450, "Plush Toys — soft stuffed toys designed for comfort and play."),
    "rattles": (200, "Rattles — small toys that produce sound to entertain infants."),
    "teething_toys": (250, "Teething Toys — chewable toys designed to soothe a teething baby's gums."),
    "activity_gym": (2200, "Activity Gym — a padded play mat with hanging toys to stimulate a baby's development."),
    "stacking_rings": (350, "Stacking Rings — a classic toy that helps toddlers develop hand-eye coordination."),
    "shape_sorter": (500, "Shape Sorter — an educational toy that helps toddlers learn shapes."),
    "musical_toys": (700, "Musical Toys — toys that play sounds or melodies to entertain children."),
    "bath_toys": (300, "Bath Toys — floating toys designed to entertain children during bath time."),
    "push_pull_toys": (600, "Push Pull Toys — toys designed to encourage a toddler's first steps."),
    "learning_walker": (2500, "Learning Walker — a supportive frame that helps toddlers learn to walk while playing."),
    "building_blocks": (600, "Building Blocks — stackable toy blocks that support early childhood development."),
    "educational_toys": (800, "Educational Toys — toys designed to support learning and cognitive development."),
    "alphabet_learning_toys": (450, "Alphabet Learning Toys — toys designed to teach children letters and early literacy."),
    "number_learning_toys": (450, "Number Learning Toys — toys designed to teach children counting and numbers."),
    "stem_learning_kit": (1500, "STEM Learning Kit — a hands-on kit designed to teach science, technology, engineering and math."),
    "science_kit": (1500, "Science Kit — an experiment kit designed to introduce children to basic science."),
    "math_learning_kit": (900, "Math Learning Kit — a set of tools designed to make learning math engaging."),
    "flash_cards": (250, "Flash Cards — a set of learning cards used to teach vocabulary, numbers or facts."),
    "puzzle_blocks": (500, "Puzzle Blocks — interlocking blocks that double as an early puzzle toy."),
    "montessori_toys": (900, "Montessori Toys — toys designed around Montessori principles for independent learning."),
    "coding_robot": (3500, "Coding Robot — a programmable robot toy that teaches basic coding concepts."),
    "globe": (900, "Globe — a spherical model of the Earth used for learning geography."),
    "microscope_kit": (1800, "Microscope Kit — a beginner microscope set designed to explore the natural world."),
    "telescope_kit": (2500, "Telescope Kit — a beginner telescope designed to explore the night sky."),
    "building_toys": (700, "Building Toys — construction-style toys that encourage creative building."),
    "magnetic_building_tiles": (1800, "Magnetic Building Tiles — magnetic tiles that snap together to build 3D structures."),
    "construction_blocks": (700, "Construction Blocks — interlocking blocks designed for creative construction play."),
    "brick_sets": (900, "Brick Sets — interlocking brick sets designed for imaginative building."),
    "wooden_blocks": (600, "Wooden Blocks — classic wooden building blocks for open-ended play."),
    "marble_run": (1200, "Marble Run — a track set where marbles roll and drop through a chain of paths."),
    "engineering_kit": (1800, "Engineering Kit — a construction kit designed to teach basic engineering concepts."),
    "action_figures_dolls": (400, "Action Figures & Dolls — a general range of action figures and dolls."),
    "action_figures": (450, "Action Figures — poseable character figures designed for imaginative play."),
    "superhero_figures": (450, "Superhero Figures — action figures modeled after popular superhero characters."),
    "anime_figures": (900, "Anime Figures — collectible figures modeled after anime characters."),
    "fashion_dolls": (600, "Fashion Dolls — dolls designed with changeable outfits and accessories."),
    "baby_dolls": (500, "Baby Dolls — dolls designed to resemble infants for nurturing play."),
    "doll_house": (3500, "Doll House — a miniature house set designed for imaginative doll play."),
    "doll_furniture": (700, "Doll Furniture — miniature furniture pieces designed for doll houses."),
    "doll_accessories": (350, "Doll Accessories — small accessories designed to complement dolls."),
    "collectible_figures": (700, "Collectible Figures — figures designed for collecting and display."),
    "remote_control_rc_toys": (1500, "Remote Control (RC) Toys — a general range of radio-controlled toys."),
    "rc_car": (1800, "RC Car — a remote-controlled toy car designed for racing and play."),
    "rc_truck": (2200, "RC Truck — a remote-controlled toy truck built for off-road play."),
    "rc_motorcycle": (2000, "RC Motorcycle — a remote-controlled toy motorcycle designed for play."),
    "rc_boat": (2500, "RC Boat — a remote-controlled toy boat designed for water play."),
    "rc_helicopter": (2200, "RC Helicopter — a remote-controlled toy helicopter designed for indoor or outdoor flight."),
    "rc_airplane": (2800, "RC Airplane — a remote-controlled toy airplane designed for outdoor flight."),
    "rc_tank": (2000, "RC Tank — a remote-controlled toy tank designed for play."),
    "rc_robot": (2500, "RC Robot — a remote-controlled robot toy designed for interactive play."),
    "rc_controller": (600, "RC Controller — a remote control unit designed for RC toys."),
    "spare_rc_battery": (500, "Spare RC Battery — a replacement rechargeable battery designed for RC toys."),
    "outdoor_toys": (700, "Outdoor Toys — toys designed for active outdoor play."),
    "trampoline": (7500, "Trampoline — a bouncing surface set on a frame designed for active outdoor play."),
    "swing_set": (8500, "Swing Set — an outdoor play structure with swings designed for children."),
    "slide": (5500, "Slide — a play structure designed for children to slide down."),
    "water_gun": (350, "Water Gun — a toy gun designed for outdoor water play."),
    "bubble_machine": (900, "Bubble Machine — a device that automatically blows a stream of bubbles."),
    "bubble_solution": (150, "Bubble Solution — a liquid solution used to blow soap bubbles."),
    "flying_disc": (300, "Flying Disc — a disc-shaped toy designed for outdoor throwing games."),
    "kite": (400, "Kite — a lightweight toy designed to fly in the wind."),
    "beach_toys": (400, "Beach Toys — a set of toys designed for beach and sand play."),
    "sand_toys": (350, "Sand Toys — tools and molds designed for playing in sand."),
    "play_tent": (1800, "Play Tent — a small tent designed for imaginative indoor or outdoor play."),
    "ride_on_toys": (3500, "Ride-On Toys — a general range of toys designed for children to ride."),
    "ride_on_car": (5500, "Ride-On Car — a toy car designed for a child to sit in and ride."),
    "electric_ride_on_car": (9500, "Electric Ride-On Car — a battery-powered toy car designed for a child to ride."),
    "ride_on_motorcycle": (6500, "Ride-On Motorcycle — a toy motorcycle designed for a child to ride."),
    "balance_bike": (3500, "Balance Bike — a pedal-less bike designed to help children learn balance."),
    "kids_scooter": (2500, "Kids Scooter — a scooter sized and designed for children."),
    "tricycle": (4500, "Tricycle — a three-wheeled bike designed for young children."),
    "wagon": (3500, "Wagon — a pull-along cart designed for carrying children or toys."),
    "board_games": (600, "Board Games — tabletop games designed for family or group play."),
    "chess_set": (700, "Chess Set — a classic strategy board game set."),
    "checkers": (400, "Checkers — a classic two-player strategy board game."),
    "ludo": (300, "Ludo — a classic board game of strategy and luck for the family."),
    "monopoly": (1500, "Monopoly — a classic property-trading board game."),
    "scrabble": (1200, "Scrabble — a classic word-building board game."),
    "playing_cards": (150, "Playing Cards — a standard deck of cards used for various card games."),
    "dominoes": (350, "Dominoes — a classic tile-based game of matching numbers."),
    "jigsaw_puzzle": (450, "Jigsaw Puzzle — an interlocking picture puzzle designed for all ages."),
    "sudoku_book": (200, "Sudoku Book — a book of number-placement logic puzzles."),
    "video_game_accessories": (600, "Video Game Accessories — a general range of accessories for video game play."),
    "game_controller": (900, "Game Controller — a handheld controller designed for playing video games."),
    "gaming_headset": (1500, "Gaming Headset — a headset designed for immersive audio during gaming."),
    "racing_wheel": (4500, "Racing Wheel — a steering wheel controller designed for racing games."),
    "vr_headset": (7500, "VR Headset — a wearable device that immerses the user in virtual reality."),
    "controller_charging_dock": (900, "Controller Charging Dock — a dock designed to charge game controllers."),
    "gaming_chair": (9500, "Gaming Chair — an ergonomic chair designed for long gaming sessions."),
    "arts_crafts": (400, "Arts & Crafts — a general range of art and craft supplies."),
    "coloring_book": (150, "Coloring Book — a book of illustrations designed for coloring."),
    "crayons": (150, "Crayons — a set of wax sticks used for coloring and drawing."),
    "colored_pencils": (250, "Colored Pencils — a set of pencils designed for coloring and sketching."),
    "markers": (300, "Markers — a set of felt-tip pens designed for coloring and drawing."),
    "paint_set": (500, "Paint Set — a set of paints designed for creative art projects."),
    "watercolor_set": (450, "Watercolor Set — a set of water-based paints designed for painting."),
    "acrylic_paint": (400, "Acrylic Paint — a fast-drying, water-based paint designed for craft projects."),
    "paint_brushes": (250, "Paint Brushes — a set of brushes designed for painting projects."),
    "canvas": (350, "Canvas — a blank painting surface designed for art projects."),
    "clay": (250, "Clay — a moldable material used for sculpting and craft projects."),
    "modeling_clay": (300, "Modeling Clay — a soft, moldable clay designed for creative sculpting."),
    "slime_kit": (400, "Slime Kit — a kit for making stretchy, squishy slime at home."),
    "bead_craft_kit": (450, "Bead Craft Kit — a kit of beads and tools designed for making jewelry and crafts."),
    "origami_paper": (150, "Origami Paper — colorful paper designed for the art of paper folding."),
    "diy_craft_kit": (700, "DIY Craft Kit — a complete kit designed for a do-it-yourself craft project."),
    "toy_piano": (1500, "Toy Piano — a small piano designed to introduce children to music."),
    "toy_guitar": (900, "Toy Guitar — a small guitar designed for children to play and learn music."),
    "toy_drum_set": (1800, "Toy Drum Set — a small drum kit designed for children."),
    "toy_keyboard": (1500, "Toy Keyboard — a small electronic keyboard designed for children."),
    "xylophone": (700, "Xylophone — a musical instrument with tuned bars designed for children."),
    "microphone_toy": (600, "Microphone Toy — a toy microphone designed for singing and pretend play."),
    "science_robotics": (900, "Science & Robotics Toys — a general range of science and robotics kits."),
    "robot_kit": (2500, "Robot Kit — a build-it-yourself kit designed to construct a working robot."),
    "electronics_kit": (1800, "Electronics Kit — a kit designed to teach basic electronics through hands-on projects."),
    "solar_robot_kit": (1500, "Solar Robot Kit — a build kit for a robot powered by solar energy."),
    "coding_kit": (2500, "Coding Kit — a kit designed to teach children the basics of programming."),
    "circuit_learning_kit": (1500, "Circuit Learning Kit — a kit designed to teach basic electrical circuits."),
    "diy_robot": (2200, "DIY Robot — a build-your-own robot kit designed for hands-on learning."),
    "model_kits": (900, "Model Kits — a general range of scale model building kits."),
    "car_model_kit": (900, "Car Model Kit — a scale model kit designed to build a car replica."),
    "airplane_model_kit": (900, "Airplane Model Kit — a scale model kit designed to build an airplane replica."),
    "ship_model_kit": (1200, "Ship Model Kit — a scale model kit designed to build a ship replica."),
    "train_model_kit": (1500, "Train Model Kit — a scale model kit designed to build a train replica."),
    "gundam_model_kit": (1800, "Gundam Model Kit — a scale model kit designed to build a Gundam robot figure."),
    "miniature_house_kit": (1800, "Miniature House Kit — a scale model kit designed to build a miniature house."),
    "collectibles": (700, "Collectibles — a general range of items designed for collecting and display."),
    "trading_cards": (250, "Trading Cards — collectible cards designed for trading and gameplay."),
    "sports_cards": (300, "Sports Cards — collectible cards featuring athletes and sports teams."),
    "coin_collection_album": (500, "Coin Collection Album — an album designed to store and display collectible coins."),
    "stamp_collection_album": (500, "Stamp Collection Album — an album designed to store and display collectible stamps."),
    "action_figure_display_case": (900, "Action Figure Display Case — a case designed to display collectible action figures."),
    "collectible_coins": (700, "Collectible Coins — coins designed and minted for collecting."),
    "hobby_supplies": (400, "Hobby Supplies — a general range of tools and materials for hobby projects."),
    "airbrush_kit": (2500, "Airbrush Kit — a spray-painting kit designed for detailed hobby and model work."),
    "hobby_knife": (200, "Hobby Knife — a precision knife designed for detailed craft and model work."),
    "cutting_mat": (400, "Cutting Mat — a self-healing mat designed to protect surfaces during craft cutting."),
    "glue": (100, "Glue — an adhesive designed for craft and hobby projects."),
    "mini_drill": (1500, "Mini Drill — a small rotary tool designed for detailed hobby work."),
    "craft_storage_box": (600, "Craft Storage Box — a box designed to organize craft supplies."),
    "magic_novelty": (400, "Magic & Novelty Toys — a general range of magic tricks and novelty items."),
    "magic_kit": (900, "Magic Kit — a set of props and instructions designed to perform magic tricks."),
    "prank_toys": (300, "Prank Toys — novelty items designed for playful pranks."),
    "fidget_spinner": (150, "Fidget Spinner — a small spinning toy designed to relieve stress or fidgeting."),
    "fidget_cube": (200, "Fidget Cube — a small cube toy with buttons designed to relieve fidgeting."),
    "stress_ball": (150, "Stress Ball — a squeezable ball designed to relieve stress."),
    "yo_yo": (200, "Yo-Yo — a classic string toy designed for tricks and play."),
    "rubiks_cube": (350, "Rubik's Cube — a classic twisting puzzle cube."),
    "party_costume": (700, "Party Costume — a costume designed for dress-up and party occasions."),
    "costume_set": (700, "Costume Set — a complete costume outfit designed for role-play."),
    "superhero_costume": (800, "Superhero Costume — a costume designed to resemble a popular superhero."),
    "princess_costume": (800, "Princess Costume — a costume designed to resemble a fairy-tale princess."),
    "masks": (200, "Masks — decorative masks designed for costumes and parties."),
    "face_paint_kit": (350, "Face Paint Kit — a set of paints designed for decorating the face for parties."),
    "party_props": (400, "Party Props — decorative items designed for parties and celebrations."),
    "toy_storage": (700, "Toy Storage — a general range of storage solutions for children's toys."),
    "toy_box": (2500, "Toy Box — a large box designed for storing children's toys."),
    "toy_organizer": (900, "Toy Organizer — a storage unit designed to keep children's toys organized."),
    "storage_bins": (500, "Storage Bins — bins designed to organize and store toys."),
    "wall_organizer": (700, "Wall Organizer — a wall-mounted storage solution for toys and books."),
    "puzzle_storage": (450, "Puzzle Storage — a storage solution designed to organize jigsaw puzzles."),
    "pet_toys": (300, "Pet Toys — a general range of toys designed for pets."),
    "dog_toy": (350, "Dog Toy — a toy designed for dogs to play and chew."),
    "cat_toy": (250, "Cat Toy — a toy designed to engage a cat's play instincts."),
    "interactive_pet_toy": (700, "Interactive Pet Toy — a toy designed to actively engage a pet during play."),
    "seasonal_toys": (600, "Seasonal Toys — toys designed for seasonal or holiday play."),
    "inflatable_pool": (1800, "Inflatable Pool — an inflatable pool designed for outdoor water play."),
    "snow_sled": (1500, "Snow Sled — a sled designed for sliding on snow."),
    "water_balloons": (150, "Water Balloons — small balloons designed for water balloon fights."),
    "christmas_toy_set": (900, "Christmas Toy Set — a themed toy set designed for the Christmas holiday."),
    "ramadan_eid_gift_toys": (900, "Ramadan & Eid Gift Toys — a themed toy set designed for Ramadan and Eid gifting."),
}

paths = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch3.json",
]

target_id = "toys_games_hobbies"
total_updated = 0

for path in paths:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    updated = 0
    skipped = []
    for sku, prod in data.items():
        if prod.get("categoryId") == target_id:
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
            else:
                skipped.append((sku, img))

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"--- {path}: Updated {updated}, Skipped {skipped} ---")
    total_updated += updated

print(f"TOTAL Updated: {total_updated}")
