import json

price_desc = {
    "2_in_1_laptop": (55000, "2-in-1 Laptop — a convertible laptop that transforms into a tablet."),
    "4k_monitor": (35000, "4K Monitor — an ultra-high-definition display designed for sharp visuals."),
    "access_point": (5500, "Access Point — a networking device used to extend Wi-Fi coverage."),
    "all_in_one_pc": (65000, "All-in-One PC — a desktop computer integrated into a single display unit."),
    "all_in_one_printer": (12000, "All-in-One Printer — a printer combining print, scan, and copy functions."),
    "amd_graphics_card": (35000, "AMD Graphics Card — a discrete GPU designed for gaming and rendering performance."),
    "amd_processor": (18000, "AMD Processor — a computer CPU designed for desktop and laptop performance."),
    "android_tablet": (18000, "Android Tablet — a touchscreen tablet running the Android operating system."),
    "antivirus_software": (1500, "Antivirus Software — a program used to protect computers from malware and threats."),
    "atx_motherboard": (12000, "ATX Motherboard — a standard-size motherboard used in desktop PC builds."),
    "atx_power_supply": (6500, "ATX Power Supply — a standard power supply unit used in desktop computers."),
    "audio_video": (2500, "Audio Video — a general range of audio and video equipment for computers."),
    "backup_software": (1500, "Backup Software — a program used to create and manage data backups."),
    "barcode_printer": (8500, "Barcode Printer — a device used to print barcodes for retail and inventory."),
    "barebone_pc": (25000, "Barebone PC — a partially assembled computer kit for custom builds."),
    "business_laptop": (65000, "Business Laptop — a laptop designed for professional productivity and reliability."),
    "cable_management_box": (900, "Cable Management Box — a container used to organize and hide cables."),
    "cable_organizer": (350, "Cable Organizer — a tool used to bundle and organize loose cables."),
    "cable_tester": (1500, "Cable Tester — a device used to check network cable connectivity and faults."),
    "cables_adapters": (450, "Cables & Adapters — a general range of connectivity cables and adapters."),
    "card_reader": (700, "Card Reader — a device used to transfer files from memory cards to a computer."),
    "case_fan": (900, "Case Fan — a cooling fan installed inside a computer case for airflow."),
    "chromebook": (35000, "Chromebook — a lightweight laptop running Chrome OS for web-based computing."),
    "computer_case": (5500, "Computer Case — a chassis used to house desktop computer components."),
    "computer_components": (2500, "Computer Components — a general range of internal PC hardware parts."),
    "computers_tablets_networking": (3000, "Computers, Tablets & Networking — a general range of computing and networking products."),
    "conference_camera": (12000, "Conference Camera — a camera designed for professional video conferencing."),
    "cooling": (1800, "Cooling — a general range of computer cooling solutions."),
    "cooling_pad": (900, "Cooling Pad — a laptop accessory used to improve airflow and reduce heat."),
    "cpu_air_cooler": (3500, "CPU Air Cooler — a heatsink and fan assembly used to cool a processor."),
    "crimping_tool": (900, "Crimping Tool — a tool used to attach connectors to network cables."),
    "curved_monitor": (25000, "Curved Monitor — a display with a curved screen for an immersive viewing experience."),
    "ddr4_ram": (3500, "DDR4 RAM — computer memory modules used for system performance."),
    "ddr5_ram": (6500, "DDR5 RAM — next-generation computer memory modules offering higher speeds."),
    "desktop_computers": (45000, "Desktop Computers — a general range of full-size desktop PCs."),
    "desktop_pc": (45000, "Desktop PC — a stationary computer designed for home or office use."),
    "digital_whiteboard": (85000, "Digital Whiteboard — an interactive display used for collaborative presentations."),
    "displayport_cable": (450, "DisplayPort Cable — a cable used to connect monitors for high-resolution display."),
    "docking_station": (5500, "Docking Station — a hub that expands a laptop's connectivity options."),
    "document_scanner": (8500, "Document Scanner — a device used to digitize physical documents."),
    "drawing_tablet": (8500, "Drawing Tablet — a pen-based input device used for digital illustration."),
    "dvi_cable": (350, "DVI Cable — a cable used to connect displays with DVI ports."),
    "e_reader": (12000, "E-Reader — a portable device designed for reading digital books."),
    "ethernet_adapter": (900, "Ethernet Adapter — a device used to add wired network connectivity."),
    "ethernet_cable_cat5e": (350, "Ethernet Cable (Cat5e) — a network cable used for standard wired connections."),
    "ethernet_cable_cat6": (450, "Ethernet Cable (Cat6) — a network cable offering improved speed and performance."),
    "ethernet_cable_cat6a": (600, "Ethernet Cable (Cat6a) — a network cable designed for higher bandwidth applications."),
    "ethernet_cable_cat7": (900, "Ethernet Cable (Cat7) — a high-performance network cable for demanding applications."),
    "ethernet_cable_cat8": (1500, "Ethernet Cable (Cat8) — a premium network cable designed for maximum data speeds."),
    "external_hdd": (5500, "External HDD — a portable hard drive used for additional data storage."),
    "external_ssd": (8500, "External SSD — a fast, portable solid-state drive for data storage."),
    "firewall_appliance": (25000, "Firewall Appliance — a hardware device used to protect networks from threats."),
    "flatbed_scanner": (6500, "Flatbed Scanner — a scanner used to digitize documents and photos."),
    "full_tower_case": (12000, "Full Tower Case — a large computer case designed for extensive hardware setups."),
    "gaming_accessories": (1500, "Gaming Accessories — a general range of accessories designed for gaming setups."),
    "gaming_chair": (12000, "Gaming Chair — an ergonomic chair designed for long gaming sessions."),
    "gaming_controller": (3500, "Gaming Controller — a handheld device used to control video games."),
    "gaming_desk": (15000, "Gaming Desk — a desk designed with features suited for gaming setups."),
    "gaming_headset": (3500, "Gaming Headset — a headset designed for immersive gaming audio and communication."),
    "gaming_keyboard": (3500, "Gaming Keyboard — a keyboard designed for responsive gaming performance."),
    "gaming_laptop": (95000, "Gaming Laptop — a high-performance laptop designed for gaming."),
    "gaming_monitor": (25000, "Gaming Monitor — a high-refresh-rate display designed for gaming."),
    "gaming_mouse": (2500, "Gaming Mouse — a precision mouse designed for gaming performance."),
    "gaming_pc": (120000, "Gaming PC — a high-performance desktop computer built for gaming."),
    "graphic_tablet": (8500, "Graphic Tablet — a pen-based input device used for digital drawing."),
    "graphics_card": (45000, "Graphics Card — a discrete GPU used to render visuals and improve performance."),
    "hdmi_adapter": (450, "HDMI Adapter — a device used to connect HDMI cables to different port types."),
    "hdmi_cable": (350, "HDMI Cable — a cable used to transmit high-definition audio and video."),
    "headphones": (900, "Headphones — audio devices used for personal listening with a computer."),
    "inkjet_printer": (8500, "Inkjet Printer — a printer that uses liquid ink for document and photo printing."),
    "input_devices": (1200, "Input Devices — a general range of computer input peripherals."),
    "intel_processor": (18000, "Intel Processor — a computer CPU designed for desktop and laptop performance."),
    "internal_hdd": (4500, "Internal HDD — a hard drive installed inside a desktop or laptop for storage."),
    "ips_monitor": (18000, "IPS Monitor — a display known for accurate color and wide viewing angles."),
    "keystone_jack": (150, "Keystone Jack — a networking connector used in structured cabling systems."),
    "kids_tablet": (8500, "Kids Tablet — a tablet designed with parental controls for children's use."),
    "laptop_backpack": (1800, "Laptop Backpack — a padded backpack designed to carry and protect a laptop."),
    "laptop_charger": (1500, "Laptop Charger — a power adapter used to charge a laptop."),
    "laptop_ram": (3500, "Laptop RAM — memory modules designed for upgrading laptop performance."),
    "laptop_sleeve": (700, "Laptop Sleeve — a padded case used to protect a laptop during transport."),
    "laptop_stand": (900, "Laptop Stand — a stand used to elevate a laptop for ergonomic positioning."),
    "laptop_tablet_wifi_router": (1500, "Laptop, Tablet & Wi-Fi Router Set — a bundled set of computing accessories."),
    "laptops": (55000, "Laptops — a general range of portable computers."),
    "laser_printer": (12000, "Laser Printer — a printer that uses toner for fast, high-quality printing."),
    "led_monitor": (12000, "LED Monitor — a display using LED backlighting for everyday computer use."),
    "lightning_cable": (450, "Lightning Cable — a charging and data cable designed for Apple devices."),
    "liquid_cooler": (6500, "Liquid Cooler — a cooling system that uses liquid to dissipate CPU heat."),
    "managed_switch": (12000, "Managed Switch — a network switch offering configurable traffic control."),
    "mechanical_keyboard": (3500, "Mechanical Keyboard — a keyboard using individual mechanical switches for tactile typing."),
    "memory_card": (900, "Memory Card — a portable storage card used in various devices."),
    "memory_ram": (3500, "Memory (RAM) — computer memory modules used for system performance."),
    "mesh_wi_fi_system": (12000, "Mesh Wi-Fi System — a networking system used to extend Wi-Fi coverage seamlessly."),
    "micro_atx_motherboard": (9500, "Micro ATX Motherboard — a compact motherboard used in smaller PC builds."),
    "microsd_card": (900, "MicroSD Card — a compact memory card used in mobile and computing devices."),
    "mid_tower_case": (7500, "Mid Tower Case — a standard-size computer case used for typical PC builds."),
    "mini_itx_case": (8500, "Mini ITX Case — a compact case designed for small form factor PC builds."),
    "mini_itx_motherboard": (10500, "Mini ITX Motherboard — a compact motherboard used in small form factor builds."),
    "mini_pc": (35000, "Mini PC — a compact desktop computer designed for space-saving setups."),
    "mini_projector": (8500, "Mini Projector — a compact projector designed for portable display needs."),
    "modem": (3500, "Modem — a networking device used to connect to an internet service provider."),
    "modular_psu": (8500, "Modular PSU — a power supply unit with detachable cables for clean builds."),
    "monitor_arm": (2500, "Monitor Arm — an adjustable mount used to position a display ergonomically."),
    "monitor_stand": (1200, "Monitor Stand — a stand used to elevate and organize a display setup."),
    "monitors": (15000, "Monitors — a general range of computer display screens."),
    "motherboard": (12000, "Motherboard — the main circuit board that connects a computer's components."),
    "nas_network_attached_storage": (35000, "NAS (Network Attached Storage) — a networked device used for centralized data storage."),
    "network_accessories": (900, "Network Accessories — a general range of networking equipment and cables."),
    "network_hub": (1800, "Network Hub — a basic device used to connect multiple network devices."),
    "network_interface_card_nic": (1500, "Network Interface Card (NIC) — a hardware component used to connect a computer to a network."),
    "network_switch": (5500, "Network Switch — a networking device used to connect multiple devices on a LAN."),
    "networking_equipment": (5500, "Networking Equipment — a general range of devices used to build computer networks."),
    "numeric_keypad": (700, "Numeric Keypad — a compact keyboard accessory used for entering numbers."),
    "nvidia_graphics_card": (45000, "NVIDIA Graphics Card — a discrete GPU designed for gaming and rendering performance."),
    "nvme_ssd": (8500, "NVMe SSD — a high-speed solid-state drive used for fast data storage."),
    "office_accessories": (700, "Office Accessories — a general range of computer and office desk accessories."),
    "office_software": (2500, "Office Software — a program suite used for documents, spreadsheets, and presentations."),
    "operating_system": (5500, "Operating System — software used to manage computer hardware and applications."),
    "otg_adapter": (250, "OTG Adapter — a device used to connect USB peripherals to mobile devices."),
    "patch_panel": (3500, "Patch Panel — a networking panel used to organize and manage cable connections."),
    "pc_speakers": (1800, "PC Speakers — external speakers designed for computer audio output."),
    "pcie_wi_fi_card": (1800, "PCIe Wi-Fi Card — an internal card used to add wireless connectivity to a desktop."),
    "pdf_software": (1500, "PDF Software — a program used to create, edit, and manage PDF documents."),
    "photo_printer": (12000, "Photo Printer — a printer designed specifically for producing photographic prints."),
    "portable_monitor": (12000, "Portable Monitor — a lightweight external display designed for on-the-go use."),
    "portable_printer": (8500, "Portable Printer — a compact printer designed for mobile printing needs."),
    "power_backup": (8500, "Power Backup — a device used to provide backup power during outages."),
    "power_strip": (700, "Power Strip — a device with multiple outlets used to power several devices."),
    "power_supply": (6500, "Power Supply — a component that provides electrical power to a computer's parts."),
    "presenter_remote": (1500, "Presenter Remote — a wireless device used to control slides during presentations."),
    "printers_scanners": (8500, "Printers & Scanners — a general range of printing and scanning devices."),
    "privacy_screen_filter": (1500, "Privacy Screen Filter — a filter used to limit screen visibility from side angles."),
    "processor_cpu": (18000, "Processor (CPU) — the central processing unit that powers a computer."),
    "projector_screen": (5500, "Projector Screen — a surface used to display projected images and video."),
    "racing_wheel": (12000, "Racing Wheel — a gaming peripheral designed for racing game simulation."),
    "range_extender": (2500, "Range Extender — a device used to boost Wi-Fi signal coverage."),
    "receipt_printer": (5500, "Receipt Printer — a device used to print sales receipts at point-of-sale terminals."),
    "refurbished_laptop": (35000, "Refurbished Laptop — a professionally restored laptop offered at a lower price."),
    "rgb_mouse_pad": (900, "RGB Mouse Pad — a mouse pad with customizable LED lighting effects."),
    "rj45_connector": (100, "RJ45 Connector — a connector used to terminate Ethernet network cables."),
    "sata_ssd": (5500, "SATA SSD — a solid-state drive used for fast and reliable data storage."),
    "screen_cleaning_kit": (450, "Screen Cleaning Kit — a set of tools used to clean computer and device screens."),
    "sd_card": (900, "SD Card — a memory card used to store data in cameras and computers."),
    "sfx_power_supply": (7500, "SFX Power Supply — a compact power supply unit used in small form factor PCs."),
    "smart_office_devices": (5500, "Smart Office Devices — a general range of connected devices for office productivity."),
    "software_licenses": (3500, "Software Licenses — activation keys used to license computer software."),
    "soundbar": (5500, "Soundbar — a compact speaker system used to enhance computer audio."),
    "storage": (5500, "Storage — a general range of computer data storage devices."),
    "storage_devices": (5500, "Storage Devices — a general range of internal and external data storage devices."),
    "student_laptop": (35000, "Student Laptop — an affordable laptop designed for everyday academic use."),
    "surge_protector": (1500, "Surge Protector — a device used to protect electronics from power surges."),
    "tablet_cover": (900, "Tablet Cover — a protective cover designed for tablets."),
    "tablet_keyboard_case": (2500, "Tablet Keyboard Case — a case with an integrated keyboard for tablet productivity."),
    "tablet_screen_protector": (350, "Tablet Screen Protector — a protective film applied to a tablet's screen."),
    "tablet_stylus": (900, "Tablet Stylus — a pen-like device used for precise tablet input."),
    "tablets": (18000, "Tablets — a general range of touchscreen tablet devices."),
    "thermal_paste": (450, "Thermal Paste — a compound applied between a CPU and cooler for heat transfer."),
    "thin_client": (12000, "Thin Client — a lightweight computer designed for centralized network computing."),
    "touchpad": (1500, "Touchpad — an input device used to control a cursor via touch gestures."),
    "touchscreen_monitor": (25000, "Touchscreen Monitor — a display that supports direct touch interaction."),
    "trackball_mouse": (2500, "Trackball Mouse — a pointing device controlled by rotating an embedded ball."),
    "ultrabook": (75000, "Ultrabook — a slim, lightweight laptop designed for portability and performance."),
    "universal_laptop_adapter": (1800, "Universal Laptop Adapter — a charger compatible with multiple laptop brands."),
    "unmanaged_switch": (2500, "Unmanaged Switch — a basic plug-and-play network switch."),
    "ups": (8500, "UPS — an uninterruptible power supply used to provide backup power for electronics."),
    "usb_a_cable": (250, "USB-A Cable — a standard cable used for data transfer and charging."),
    "usb_c_cable": (350, "USB-C Cable — a reversible cable used for data transfer and charging."),
    "usb_c_charger": (900, "USB-C Charger — a charging adapter designed for USB-C compatible devices."),
    "usb_flash_drive": (700, "USB Flash Drive — a portable storage device used for transferring digital files."),
    "usb_hub": (900, "USB Hub — a device used to expand the number of available USB ports."),
    "usb_microphone": (2500, "USB Microphone — a plug-and-play microphone used for computer audio recording."),
    "usb_sound_card": (1200, "USB Sound Card — an external device used to add or improve audio output."),
    "usb_to_ethernet_adapter": (900, "USB to Ethernet Adapter — a device used to add wired network connectivity via USB."),
    "usb_wi_fi_adapter": (900, "USB Wi-Fi Adapter — a device used to add wireless connectivity via USB."),
    "vga_cable": (350, "VGA Cable — a legacy cable used to connect displays with VGA ports."),
    "video_conference_system": (25000, "Video Conference System — equipment designed for professional video conferencing."),
    "vpn_software_license": (2500, "VPN Software License — an activation key used to access VPN protection services."),
    "vr_headset": (35000, "VR Headset — a wearable device used for immersive virtual reality experiences."),
    "webcam": (2500, "Webcam — a camera designed for video calls and live streaming."),
    "wi_fi_repeater": (1800, "Wi-Fi Repeater — a device used to extend wireless network coverage."),
    "wi_fi_router": (3500, "Wi-Fi Router — a networking device used to provide wireless internet access."),
    "windows_tablet": (25000, "Windows Tablet — a tablet running the full Windows operating system."),
    "wired_keyboard": (700, "Wired Keyboard — a keyboard that connects to a computer via cable."),
    "wired_mouse": (450, "Wired Mouse — a mouse that connects to a computer via cable."),
    "wireless_keyboard": (1500, "Wireless Keyboard — a keyboard that connects to a computer without cables."),
    "wireless_mouse": (900, "Wireless Mouse — a mouse that connects to a computer without cables."),
    "workstation": (150000, "Workstation — a high-performance computer designed for professional computing tasks."),
}

path = "data/products-placeholder.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
skipped = []
for sku, prod in data.items():
    if prod.get("categoryId") == "computers_tablets_networking":
        img = prod["images"]["main"].split("/")[-1].replace(".png", "")
        if img in price_desc:
            price, desc = price_desc[img]
            title = " ".join(w.capitalize() for w in img.split("_"))
            prod["title"] = title
            prod["price"] = price
            prod["description"] = desc
            prod["status"] = "active"
            updated += 1
        else:
            skipped.append((sku, img))

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
