import json

price_desc = {
    "home_improvement_tools_hardware": (500, "Home Improvement, Tools & Hardware — a general range of tools and supplies designed for home projects."),
    "acrylic_sealant": (350, "Acrylic Sealant — a flexible sealant used to fill gaps and joints."),
    "adhesives_sealants": (400, "Adhesives & Sealants — a general range of products designed to bond and seal materials."),
    "adjustable_wrench": (450, "Adjustable Wrench — a wrench with a movable jaw designed to fit various bolt sizes."),
    "air_compressor": (12500, "Air Compressor — a machine that pressurizes air for powering pneumatic tools."),
    "air_hose_reel": (2500, "Air Hose Reel — a reel designed for storing and dispensing an air hose."),
    "alarm_system": (5500, "Alarm System — a security system designed to detect and alert intrusions."),
    "allen_key_set": (300, "Allen Key Set — a set of hexagonal wrenches designed for fastening hex bolts."),
    "anchors": (150, "Anchors — fasteners designed to secure screws into walls."),
    "angle_grinder": (3500, "Angle Grinder — a power tool used for cutting, grinding, and polishing."),
    "ball_valve": (350, "Ball Valve — a valve used to control the flow of liquid or gas."),
    "belt_sander": (4500, "Belt Sander — a power tool used to sand and smooth surfaces."),
    "bench_vise": (2500, "Bench Vise — a clamping tool designed to hold workpieces securely."),
    "bolts": (150, "Bolts — threaded fasteners used to join materials."),
    "cabinet_handle": (200, "Cabinet Handle — a hardware fitting designed for cabinet doors and drawers."),
    "cabinet_hardware": (300, "Cabinet Hardware — a general range of fittings designed for cabinets."),
    "cabinet_hinge": (150, "Cabinet Hinge — a hinge designed for cabinet doors."),
    "cabinet_knob": (150, "Cabinet Knob — a hardware fitting designed for cabinet doors and drawers."),
    "cable_clips": (100, "Cable Clips — small clips designed to organize and secure cables."),
    "cable_ties": (100, "Cable Ties — plastic ties used to bundle and organize cables."),
    "carbon_monoxide_detector": (1800, "Carbon Monoxide Detector — a device designed to detect dangerous carbon monoxide levels."),
    "caulk": (300, "Caulk — a sealant used to fill gaps and cracks."),
    "caulking_gun": (350, "Caulking Gun — a tool used to apply caulk or sealant."),
    "ceiling_fan": (3500, "Ceiling Fan — a fan mounted on the ceiling designed for air circulation."),
    "ceiling_light": (1800, "Ceiling Light — a light fixture designed for ceiling installation."),
    "chalk_line": (350, "Chalk Line — a tool used to mark straight lines for construction work."),
    "chisel_set": (900, "Chisel Set — a set of tools used for carving and cutting wood or stone."),
    "circuit_breaker_mcb": (700, "Circuit Breaker (MCB) — an electrical device designed to protect circuits from overload."),
    "circular_saw": (5500, "Circular Saw — a power tool used for cutting wood and other materials."),
    "clamp_meter": (2500, "Clamp Meter — an electrical testing tool used to measure current without disconnecting wires."),
    "claw_hammer": (450, "Claw Hammer — a hammer with a curved claw used for driving and removing nails."),
    "combination_wrench": (350, "Combination Wrench — a wrench with an open end and a box end for versatile use."),
    "construction_adhesive": (450, "Construction Adhesive — a strong adhesive used for bonding building materials."),
    "cordless_drill": (5500, "Cordless Drill — a battery-powered drill used for drilling and driving screws."),
    "cpvc_pipe": (350, "CPVC Pipe — a plastic pipe designed for hot and cold water plumbing."),
    "crack_repair_kit": (700, "Crack Repair Kit — a kit designed for repairing cracks in walls or surfaces."),
    "cutting_disc": (250, "Cutting Disc — an abrasive disc used with power tools for cutting materials."),
    "cutting_pliers": (350, "Cutting Pliers — pliers designed for cutting wire and small materials."),
    "deadbolt": (900, "Deadbolt — a locking bolt designed for door security."),
    "desoldering_pump": (350, "Desoldering Pump — a tool used to remove excess solder."),
    "digital_multimeter": (1800, "Digital Multimeter — an electrical testing tool used to measure voltage, current, and resistance."),
    "distribution_board": (2500, "Distribution Board — an electrical panel designed to distribute power to circuits."),
    "door_closer": (1500, "Door Closer — a device designed to automatically close a door."),
    "door_handle": (450, "Door Handle — a hardware fitting designed for opening and closing doors."),
    "door_knob": (400, "Door Knob — a rounded hardware fitting designed for opening and closing doors."),
    "door_lock": (900, "Door Lock — a locking mechanism designed for door security."),
    "door_seal": (250, "Door Seal — a weatherproofing strip designed to seal door gaps."),
    "door_stopper": (200, "Door Stopper — a device designed to prevent doors from slamming shut."),
    "door_window_hardware": (450, "Door & Window Hardware — a general range of fittings designed for doors and windows."),
    "doorbell": (900, "Doorbell — a device designed to signal visitors at the door."),
    "drain_cleaner": (350, "Drain Cleaner — a product used to clear clogged drains."),
    "drawer_slide": (450, "Drawer Slide — a mechanism designed for smooth drawer movement."),
    "drill_bits": (450, "Drill Bits — cutting tools designed for use with a drill."),
    "drop_cloth": (350, "Drop Cloth — a protective sheet used to cover surfaces during painting or construction."),
    "dust_mask": (150, "Dust Mask — a protective mask designed to filter airborne dust particles."),
    "ear_protection": (350, "Ear Protection — protective gear designed to reduce noise exposure."),
    "electric_drill": (4500, "Electric Drill — a power tool used for drilling and driving screws."),
    "electrical_supplies": (500, "Electrical Supplies — a general range of products designed for electrical work."),
    "electrical_wire": (300, "Electrical Wire — a conductive wire designed for electrical wiring."),
    "epoxy_adhesive": (450, "Epoxy Adhesive — a strong two-part adhesive used for bonding materials."),
    "exhaust_fan": (2500, "Exhaust Fan — a fan designed to ventilate and remove indoor air."),
    "extension_cord": (450, "Extension Cord — a cable designed to extend the reach of an electrical outlet."),
    "extension_ladder": (5500, "Extension Ladder — an adjustable ladder designed for reaching greater heights."),
    "exterior_paint": (1500, "Exterior Paint — paint formulated for outdoor surfaces."),
    "face_shield": (250, "Face Shield — a protective clear shield worn over the face."),
    "fasteners": (300, "Fasteners — a general range of hardware used to join materials."),
    "faucet": (1500, "Faucet — a fixture designed to control water flow from a pipe."),
    "file_set": (450, "File Set — a set of tools used for smoothing and shaping materials."),
    "flexible_hose": (450, "Flexible Hose — a bendable hose designed for plumbing connections."),
    "flood_light": (1800, "Flood Light — a bright, wide-beam light designed for outdoor illumination."),
    "folding_ladder": (2500, "Folding Ladder — a compact, collapsible ladder designed for easy storage."),
    "furniture_repair_kit": (700, "Furniture Repair Kit — a kit designed for repairing scratches and damage on furniture."),
    "garage_shelf": (2500, "Garage Shelf — a shelving unit designed for garage storage."),
    "garage_workshop_equipment": (3500, "Garage & Workshop Equipment — a general range of tools designed for garage and workshop use."),
    "gate_valve": (450, "Gate Valve — a valve used to control the flow of liquid in a pipeline."),
    "grease_gun": (900, "Grease Gun — a tool used to apply lubricating grease to machinery."),
    "grinding_disc": (250, "Grinding Disc — an abrasive disc used with power tools for grinding."),
    "hacksaw": (350, "Hacksaw — a hand saw designed for cutting metal."),
    "hammer": (450, "Hammer — a hand tool used for driving nails and general construction tasks."),
    "hammer_drill": (6500, "Hammer Drill — a power tool designed for drilling into masonry and concrete."),
    "hand_saw": (450, "Hand Saw — a manual saw designed for cutting wood."),
    "hand_tools": (500, "Hand Tools — a general range of manually operated tools."),
    "heat_gun": (1800, "Heat Gun — a tool that emits hot air used for stripping paint and shrinking materials."),
    "hinges": (150, "Hinges — hardware fittings designed for door and cabinet movement."),
    "hole_saw_kit": (900, "Hole Saw Kit — a set of cutting tools designed for drilling large holes."),
    "home_repair_accessories": (500, "Home Repair Accessories — a general range of items designed for household repairs."),
    "home_security": (2500, "Home Security Products — a general range of devices designed to protect the home."),
    "hydraulic_jack": (3500, "Hydraulic Jack — a tool used to lift heavy loads."),
    "impact_driver": (5500, "Impact Driver — a power tool designed for driving screws with high torque."),
    "infrared_thermometer": (900, "Infrared Thermometer — a non-contact thermometer used to measure surface temperature."),
    "interior_paint": (1500, "Interior Paint — paint formulated for indoor surfaces."),
    "jack_stand": (1800, "Jack Stand — a support stand used to hold a vehicle after lifting."),
    "jigsaw": (4500, "Jigsaw — a power tool used for cutting curved shapes in wood and other materials."),
    "junction_box": (250, "Junction Box — an enclosure designed to house electrical wire connections."),
    "knee_pads": (350, "Knee Pads — protective padding designed for kneeling during work."),
    "ladders_access_equipment": (3500, "Ladders & Access Equipment — a general range of tools designed for reaching heights."),
    "lamp_holder": (150, "Lamp Holder — a fitting designed to hold a light bulb."),
    "laser_distance_meter": (2500, "Laser Distance Meter — a device used to measure distance using a laser."),
    "led_bulb": (250, "LED Bulb — an energy-efficient light bulb using LED technology."),
    "lighting_electrical_fixtures": (900, "Lighting & Electrical Fixtures — a general range of items designed for home electrical systems."),
    "locking_pliers": (450, "Locking Pliers — pliers designed to lock onto a workpiece for a firm grip."),
    "magnetic_catch": (150, "Magnetic Catch — a hardware fitting designed to hold cabinet doors closed."),
    "measuring_tape": (200, "Measuring Tape — a flexible tape used for measuring length."),
    "measuring_testing_tools": (700, "Measuring & Testing Tools — a general range of tools designed for precision measurement."),
    "miter_saw": (7500, "Miter Saw — a power tool used for making precise angled cuts."),
    "moisture_meter": (1200, "Moisture Meter — a device used to measure moisture content in materials."),
    "motion_sensor": (900, "Motion Sensor — a device designed to detect movement for security or lighting."),
    "multi_purpose_ladder": (4500, "Multi-Purpose Ladder — a versatile ladder designed for multiple configurations."),
    "nail_gun": (5500, "Nail Gun — a power tool used to drive nails quickly."),
    "nails": (150, "Nails — metal fasteners used to join materials."),
    "needle_nose_pliers": (350, "Needle Nose Pliers — pliers with a narrow tip designed for precision work."),
    "nuts": (100, "Nuts — threaded fasteners used with bolts to join materials."),
    "orbital_sander": (4500, "Orbital Sander — a power tool used to sand and smooth surfaces."),
    "paint_brush": (200, "Paint Brush — a brush designed for applying paint."),
    "paint_painting_supplies": (500, "Paint & Painting Supplies — a general range of products designed for painting projects."),
    "paint_roller": (250, "Paint Roller — a roller tool designed for applying paint to large surfaces."),
    "paint_scraper": (200, "Paint Scraper — a tool used to remove old paint from surfaces."),
    "paint_sprayer": (4500, "Paint Sprayer — a device used to apply paint using a spray mechanism."),
    "paint_tray": (250, "Paint Tray — a tray designed to hold paint for roller application."),
    "painters_tape": (200, "Painters Tape — an adhesive tape used to mask areas during painting."),
    "parts_organizer": (700, "Parts Organizer — a storage case designed for organizing small hardware parts."),
    "pegboard": (900, "Pegboard — a perforated board designed for tool storage and organization."),
    "pipe_clamp": (350, "Pipe Clamp — a clamp designed to hold pipes in place."),
    "pipe_fittings": (250, "Pipe Fittings — connectors designed for joining pipes."),
    "pipe_wrench": (700, "Pipe Wrench — a wrench designed for gripping and turning pipes."),
    "pliers": (350, "Pliers — a hand tool designed for gripping and bending materials."),
    "plug": (150, "Plug — an electrical fitting designed to connect a device to a power source."),
    "plumbers_tape": (100, "Plumbers Tape — a sealing tape used for pipe thread connections."),
    "plumbing_supplies": (500, "Plumbing Supplies — a general range of products designed for plumbing work."),
    "polishing_pad": (250, "Polishing Pad — a pad designed for use with power tools for polishing surfaces."),
    "power_cable": (350, "Power Cable — a cable designed to supply electrical power to a device."),
    "power_planer": (5500, "Power Planer — a power tool used to smooth and shape wood surfaces."),
    "power_strip": (500, "Power Strip — a multi-outlet device designed to expand electrical connections."),
    "power_tool_accessories": (450, "Power Tool Accessories — a general range of add-on items designed for power tools."),
    "power_tools": (4500, "Power Tools — a general range of motorized tools designed for construction and repair."),
    "ppr_pipe": (350, "PPR Pipe — a plastic pipe designed for hot and cold water plumbing."),
    "precision_screwdriver_set": (450, "Precision Screwdriver Set — a set of small screwdrivers designed for fine detail work."),
    "pressure_washer": (9500, "Pressure Washer — a machine that uses pressurized water for cleaning."),
    "primer": (900, "Primer — a preparatory coating applied before painting."),
    "pu_foam": (450, "PU Foam — an expanding foam sealant used to fill gaps."),
    "pvc_pipe": (300, "PVC Pipe — a plastic pipe designed for plumbing and drainage."),
    "reciprocating_saw": (5500, "Reciprocating Saw — a power tool used for cutting through various materials."),
    "reflective_vest": (350, "Reflective Vest — a high-visibility vest designed for safety."),
    "respirator": (700, "Respirator — a protective mask designed to filter harmful airborne particles."),
    "rivet_gun": (900, "Rivet Gun — a tool used to install rivets."),
    "rivets": (150, "Rivets — metal fasteners used to join materials permanently."),
    "rotary_hammer": (9500, "Rotary Hammer — a power tool designed for heavy-duty drilling into concrete."),
    "rotary_tool": (3500, "Rotary Tool — a versatile power tool used for cutting, grinding, and polishing."),
    "router_bits": (450, "Router Bits — cutting tools designed for use with a wood router."),
    "safety_boots": (1800, "Safety Boots — protective footwear designed for work environments."),
    "safety_equipment": (700, "Safety Equipment — a general range of protective gear designed for work safety."),
    "safety_glasses": (250, "Safety Glasses — protective eyewear designed to shield the eyes from hazards."),
    "safety_helmet": (700, "Safety Helmet — protective headgear designed for work environments."),
    "sanding_paper": (150, "Sanding Paper — an abrasive paper designed for smoothing surfaces."),
    "saw_blades": (450, "Saw Blades — cutting blades designed for use with saws."),
    "scaffolding": (12500, "Scaffolding — a temporary structure designed to support workers at height."),
    "screwdriver_bits": (250, "Screwdriver Bits — interchangeable tips designed for use with a screwdriver or drill."),
    "screwdriver_set": (450, "Screwdriver Set — a set of screwdrivers designed for various fastening tasks."),
    "screws": (150, "Screws — threaded fasteners used to join materials."),
    "security_camera": (3500, "Security Camera — a camera designed for home or property monitoring."),
    "shelf_bracket": (250, "Shelf Bracket — a support fitting designed to hold a shelf."),
    "shower_head": (900, "Shower Head — a fixture designed to disperse water in a shower."),
    "silicone_sealant": (350, "Silicone Sealant — a flexible sealant used to fill gaps and joints."),
    "sledge_hammer": (900, "Sledge Hammer — a heavy hammer used for demolition and driving stakes."),
    "sliding_door_roller": (350, "Sliding Door Roller — a hardware fitting designed for smooth sliding door movement."),
    "smart_door_lock": (5500, "Smart Door Lock — a connected lock controllable via app or keypad."),
    "smart_doorbell": (5500, "Smart Doorbell — a connected doorbell with camera and app notifications."),
    "smoke_detector": (900, "Smoke Detector — a device designed to detect smoke and alert of fire."),
    "socket": (150, "Socket — an electrical fitting designed to receive a plug."),
    "socket_wrench_set": (1800, "Socket Wrench Set — a set of sockets and a ratchet designed for fastening tasks."),
    "solder_wire": (350, "Solder Wire — a metal wire used for soldering electrical connections."),
    "soldering_iron": (900, "Soldering Iron — a tool used to melt solder for electrical connections."),
    "spirit_level": (450, "Spirit Level — a tool used to check whether a surface is level."),
    "spot_light": (900, "Spot Light — a focused light fixture designed for accent lighting."),
    "spray_paint": (450, "Spray Paint — paint applied via aerosol spray."),
    "staple_gun": (900, "Staple Gun — a tool used to drive staples into materials."),
    "step_ladder": (2500, "Step Ladder — a self-supporting ladder designed for indoor use."),
    "storage_bin": (450, "Storage Bin — a container designed for general storage."),
    "storage_organization": (500, "Storage & Organization Products — a general range of items designed for household storage."),
    "stud_finder": (900, "Stud Finder — a device used to locate wall studs behind drywall."),
    "super_glue": (150, "Super Glue — a fast-bonding adhesive used for quick repairs."),
    "switch": (150, "Switch — an electrical fitting designed to control power flow."),
    "table_saw": (15000, "Table Saw — a power tool used for making precise straight cuts in wood."),
    "thread_locker": (350, "Thread Locker — an adhesive used to secure threaded fasteners."),
    "threaded_rods": (250, "Threaded Rods — metal rods with external threading used as fasteners."),
    "tool_bag": (900, "Tool Bag — a bag designed to carry and organize tools."),
    "tool_box": (1500, "Tool Box — a container designed to store and organize tools."),
    "tool_cabinet": (5500, "Tool Cabinet — a cabinet designed for organizing and storing tools."),
    "tool_chest": (5500, "Tool Chest — a multi-drawer chest designed for organizing tools."),
    "tool_set": (2500, "Tool Set — a coordinated collection of hand tools."),
    "tool_trolley": (5500, "Tool Trolley — a wheeled cart designed for organizing and transporting tools."),
    "toolbox_hammer_screwdriver": (900, "Toolbox with Hammer & Screwdriver — a basic starter toolbox with essential hand tools."),
    "try_square": (350, "Try Square — a tool used to check and mark right angles."),
    "tube_light": (350, "Tube Light — a linear fluorescent or LED light fixture."),
    "u_bolts": (200, "U-Bolts — U-shaped threaded fasteners used to secure pipes or rods."),
    "utility_knife": (250, "Utility Knife — a retractable-blade knife designed for cutting tasks."),
    "voltage_tester": (350, "Voltage Tester — a tool used to check for the presence of electrical voltage."),
    "wall_light": (1500, "Wall Light — a light fixture designed for wall mounting."),
    "wall_plugs": (150, "Wall Plugs — fasteners designed to anchor screws into walls."),
    "wall_putty": (700, "Wall Putty — a filler compound used to smooth wall surfaces before painting."),
    "wall_tool_rack": (900, "Wall Tool Rack — a rack designed for wall-mounted tool storage."),
    "washers": (100, "Washers — flat discs used to distribute load under a fastener."),
    "weather_stripping": (350, "Weather Stripping — a sealing strip designed to block drafts around doors and windows."),
    "welding_gloves": (450, "Welding Gloves — protective gloves designed for welding work."),
    "welding_helmet": (2500, "Welding Helmet — protective headgear designed to shield the face during welding."),
    "welding_machine": (12500, "Welding Machine — a machine used to fuse metal parts together."),
    "welding_soldering": (700, "Welding & Soldering Products — a general range of items designed for metal joining work."),
    "window_handle": (350, "Window Handle — a hardware fitting designed for opening and closing windows."),
    "window_lock": (350, "Window Lock — a locking mechanism designed for window security."),
    "window_seal": (250, "Window Seal — a weatherproofing strip designed to seal window gaps."),
    "wire_brush_wheel": (250, "Wire Brush Wheel — an abrasive wheel designed for cleaning and deburring metal."),
    "wood_filler": (350, "Wood Filler — a compound used to fill gaps and cracks in wood."),
    "wood_glue": (250, "Wood Glue — an adhesive designed for bonding wood materials."),
    "work_gloves": (250, "Work Gloves — protective gloves designed for manual work."),
    "work_platform": (3500, "Work Platform — a raised platform designed to support workers during tasks."),
    "workbench": (5500, "Workbench — a sturdy table designed for workshop tasks."),
}

paths = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch2.json",
]

total_updated = 0
total_skipped = []
for path in paths:
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        continue

    updated = 0
    for sku, prod in data.items():
        if prod.get("categoryId") == "home_improvement_tools_hardware":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
            else:
                total_skipped.append((path, sku, img))

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"{path}: Updated {updated}")
    total_updated += updated

print(f"Total Updated: {total_updated}")
print(f"Skipped: {total_skipped}")
