import json

price_desc = {
    "health_medical_supplies": (500, "Health & Medical Supplies — a general range of medical care and wellness products."),
    "acupressure_mat": (900, "Acupressure Mat — a spiked mat designed to relax muscles through pressure point stimulation."),
    "adhesive_bandages": (150, "Adhesive Bandages — small sterile dressings used to cover minor cuts and wounds."),
    "adult_diapers": (700, "Adult Diapers — absorbent protective wear designed for incontinence care."),
    "aed_automated_external_defibrillator": (45000, "AED (Automated External Defibrillator) — a portable device used to deliver an electric shock during cardiac emergencies."),
    "alcohol_swabs": (150, "Alcohol Swabs — pre-moistened pads used for skin disinfection."),
    "ankle_brace": (500, "Ankle Brace — a supportive wrap designed to stabilize the ankle joint."),
    "antiseptic_wipes": (150, "Antiseptic Wipes — wipes used to clean and disinfect skin and surfaces."),
    "arm_sling": (450, "Arm Sling — a supportive fabric wrap used to immobilize an injured arm."),
    "baby_medicine_dispenser": (200, "Baby Medicine Dispenser — a tool used to accurately measure and give liquid medicine to infants."),
    "baby_thermometer": (700, "Baby Thermometer — a thermometer designed for accurate infant temperature readings."),
    "back_support_belt": (900, "Back Support Belt — a wearable belt designed to support and stabilize the lower back."),
    "balance_board": (1500, "Balance Board — a training board used for balance and core exercises."),
    "bed_assist_handle": (900, "Bed Assist Handle — a handle that attaches to a bed to assist with sitting up or standing."),
    "bed_pads": (400, "Bed Pads — absorbent pads used to protect bedding."),
    "bed_rail": (2200, "Bed Rail — a safety barrier that helps prevent falls from bed."),
    "bedside_cabinet": (3500, "Bedside Cabinet — a small storage cabinet designed for bedside use in care settings."),
    "bedside_commode": (3500, "Bedside Commode — a portable toilet chair designed for bedside use."),
    "biohazard_bags": (250, "Biohazard Bags — bags designed for the safe disposal of medical waste."),
    "bipap_machine": (45000, "BiPAP Machine — a respiratory device that delivers pressurized air to assist breathing."),
    "blood_glucose_meter": (1500, "Blood Glucose Meter — a device used to measure blood sugar levels."),
    "blood_pressure_monitor": (1800, "Blood Pressure Monitor — a device used to measure blood pressure."),
    "body_fat_analyzer": (1500, "Body Fat Analyzer — a device used to estimate body fat percentage."),
    "body_weight_scale": (900, "Body Weight Scale — a scale used to measure body weight."),
    "breast_pump": (4500, "Breast Pump — a device used to express and collect breast milk."),
    "burn_dressing": (350, "Burn Dressing — a sterile dressing designed for covering burn wounds."),
    "cold_therapy_wrap": (700, "Cold Therapy Wrap — a wrap used to apply cold therapy to injuries."),
    "compression_bandage": (250, "Compression Bandage — an elastic bandage used to apply pressure to an injury."),
    "compression_sleeves": (400, "Compression Sleeves — sleeves designed to improve circulation in limbs."),
    "compression_socks": (400, "Compression Socks — socks designed to improve blood circulation in the legs."),
    "contact_lens_case": (150, "Contact Lens Case — a small case used to store and clean contact lenses."),
    "cooler_bag_for_medicines": (900, "Cooler Bag for Medicines — an insulated bag used to keep medicines at a safe temperature."),
    "cotton_balls": (100, "Cotton Balls — soft cotton used for general hygiene and first aid care."),
    "cotton_swabs": (100, "Cotton Swabs — small swabs used for hygiene and first aid care."),
    "cpap_machine": (35000, "CPAP Machine — a respiratory device that delivers continuous air pressure to assist breathing during sleep."),
    "cpr_face_shield": (150, "CPR Face Shield — a protective barrier used during CPR to prevent direct contact."),
    "cpr_mask": (250, "CPR Mask — a protective mask used during CPR to assist with rescue breaths."),
    "crutches": (1200, "Crutches — mobility aids used to support walking while recovering from injury."),
    "daily_living_aids": (900, "Daily Living Aids — assistive tools designed to support everyday tasks."),
    "dental_care": (300, "Dental Care Products — a general range of items designed for oral hygiene."),
    "dental_floss": (100, "Dental Floss — a thin thread used to clean between teeth."),
    "denture_cleaning_kit": (350, "Denture Cleaning Kit — a set of tools designed for cleaning dentures."),
    "diagnostic_equipment": (3500, "Diagnostic Equipment — a general range of tools used for basic health assessment."),
    "digital_thermometer": (350, "Digital Thermometer — an electronic thermometer used to measure body temperature."),
    "disinfectant_spray": (300, "Disinfectant Spray — a spray used to sanitize surfaces."),
    "disinfectant_wipes": (250, "Disinfectant Wipes — pre-moistened wipes used to sanitize surfaces."),
    "disposable_apron": (150, "Disposable Apron — a single-use protective apron for hygiene tasks."),
    "disposable_caps": (150, "Disposable Caps — single-use head coverings used for hygiene."),
    "disposable_gloves": (250, "Disposable Gloves — single-use gloves designed for hygiene and protection."),
    "disposable_underpads": (400, "Disposable Underpads — absorbent single-use pads used to protect bedding."),
    "ear_plugs": (150, "Ear Plugs — small inserts used to reduce noise exposure."),
    "ecg_monitor": (8500, "ECG Monitor — a device used to monitor heart electrical activity."),
    "elastic_bandage": (200, "Elastic Bandage — a stretchable bandage used to wrap and support injuries."),
    "elbow_support": (450, "Elbow Support — a supportive wrap designed to stabilize the elbow joint."),
    "elderly_care": (900, "Elderly Care Products — a general range of items designed to support elderly care."),
    "electric_toothbrush": (1500, "Electric Toothbrush — a powered toothbrush designed for oral hygiene."),
    "electric_wheelchair": (45000, "Electric Wheelchair — a motorized chair designed for mobility assistance."),
    "emergency_blanket": (250, "Emergency Blanket — a lightweight thermal blanket used in emergency situations."),
    "emergency_equipment": (3500, "Emergency Equipment — a general range of tools designed for emergency preparedness."),
    "emergency_whistle": (150, "Emergency Whistle — a small whistle used to signal for help in emergencies."),
    "ems_muscle_stimulator": (1800, "EMS Muscle Stimulator — a device that uses electrical pulses to stimulate muscles."),
    "examination_couch": (12500, "Examination Couch — a padded table designed for clinical examinations."),
    "exercise_ball": (700, "Exercise Ball — an inflatable ball used for fitness and rehabilitation exercises."),
    "exercise_resistance_bands": (400, "Exercise Resistance Bands — elastic bands used for strength and rehabilitation exercises."),
    "eye_patch": (150, "Eye Patch — a protective cover worn over the eye."),
    "eyeglass_repair_kit": (200, "Eyeglass Repair Kit — a small kit used for minor eyeglass repairs."),
    "face_mask": (150, "Face Mask — a protective covering worn over the nose and mouth."),
    "face_shield": (250, "Face Shield — a protective clear shield worn over the face."),
    "finger_pulse_exerciser": (500, "Finger Pulse Exerciser — a small device used to exercise finger and hand strength."),
    "first_aid_kit": (900, "First Aid Kit — a compact kit of essential care items for minor injuries."),
    "first_aid_kit_medicine_bottle": (700, "First Aid Kit with Medicine Bottle — a kit combining basic supplies with a medicine storage bottle."),
    "first_aid_supplies": (700, "First Aid Supplies — a general range of items used for treating minor injuries."),
    "foam_roller": (900, "Foam Roller — a cylindrical tool used for muscle recovery and stretching."),
    "foot_massager": (2500, "Foot Massager — a device designed to relax and massage the feet."),
    "hand_grip_strengthener": (300, "Hand Grip Strengthener — a small tool used to exercise hand and grip strength."),
    "hand_sanitizer": (150, "Hand Sanitizer — a quick-drying gel used to clean hands without water."),
    "health_monitoring_devices": (2500, "Health Monitoring Devices — a general range of tools used to track health metrics."),
    "health_wellness": (500, "Health & Wellness Products — a general range of items designed to support wellbeing."),
    "heart_rate_monitor": (1800, "Heart Rate Monitor — a device used to track heart rate."),
    "heating_pad": (900, "Heating Pad — a pad used to apply warmth to sore muscles."),
    "height_measuring_scale": (900, "Height Measuring Scale — a device used to measure standing height."),
    "hospital_bed": (35000, "Hospital Bed — an adjustable bed designed for patient care settings."),
    "hospital_clinic_supplies": (900, "Hospital & Clinic Supplies — a general range of items used in clinical settings."),
    "hot_cold_pack": (350, "Hot & Cold Pack — a reusable pack used for both heat and cold therapy."),
    "hot_water_bag": (300, "Hot Water Bag — a rubber bag used to apply warmth to the body."),
    "hygiene_sanitation": (300, "Hygiene & Sanitation Products — a general range of items used for personal hygiene."),
    "ice_pack": (250, "Ice Pack — a reusable pack used for cold therapy."),
    "infrared_thermometer": (900, "Infrared Thermometer — a non-contact thermometer used to measure body temperature."),
    "instant_cold_pack": (200, "Instant Cold Pack — a single-use pack that activates for immediate cold therapy."),
    "insulated_medicine_bag": (700, "Insulated Medicine Bag — a bag designed to keep medicines at a safe temperature while traveling."),
    "isolation_gown": (350, "Isolation Gown — a protective gown used in hygiene-sensitive settings."),
    "iv_stand": (2500, "IV Stand — a pole used to hold intravenous fluid bags."),
    "knee_brace": (700, "Knee Brace — a supportive wrap designed to stabilize the knee joint."),
    "knee_scooter": (5500, "Knee Scooter — a wheeled mobility aid used for lower leg injuries."),
    "magnifying_glass": (350, "Magnifying Glass — a handheld lens used to enlarge small text or objects."),
    "manual_toothbrush": (100, "Manual Toothbrush — a standard toothbrush used for oral hygiene."),
    "massage_cushion": (2500, "Massage Cushion — a cushion designed to provide massage for the back and neck."),
    "massage_gun": (3500, "Massage Gun — a handheld device used for percussive muscle therapy."),
    "maternity_baby_care": (700, "Maternity & Baby Care Products — a general range of items designed for maternity and infant care."),
    "measuring_tape": (150, "Measuring Tape — a flexible tape used for body measurements."),
    "medical_consumables": (500, "Medical Consumables — a general range of single-use medical supplies."),
    "medical_gown": (350, "Medical Gown — a protective gown used in clinical settings."),
    "medical_refrigerator": (25000, "Medical Refrigerator — a refrigerator designed for safely storing temperature-sensitive medicines."),
    "medical_scissors": (250, "Medical Scissors — scissors designed for clinical and first aid use."),
    "medical_stool": (1800, "Medical Stool — an adjustable stool designed for clinical settings."),
    "medical_storage": (1500, "Medical Storage — a general range of storage solutions for medical supplies."),
    "medical_tape": (150, "Medical Tape — adhesive tape used to secure dressings and bandages."),
    "medical_trolley": (5500, "Medical Trolley — a wheeled cart designed for organizing medical supplies."),
    "medical_waste_bags": (250, "Medical Waste Bags — bags designed for the disposal of medical waste."),
    "medicine_cabinet": (1800, "Medicine Cabinet — a cabinet designed for storing medicines and health supplies."),
    "medicine_storage_box": (700, "Medicine Storage Box — a box designed for organizing medicines."),
    "mobility_aids": (2500, "Mobility Aids — a general range of tools designed to assist with movement."),
    "n95_mask": (200, "N95 Mask — a protective respirator mask designed for filtering airborne particles."),
    "nasal_aspirator": (450, "Nasal Aspirator — a device used to gently clear nasal congestion."),
    "nasal_cannula": (250, "Nasal Cannula — a tube device used to deliver supplemental oxygen."),
    "nebulizer": (2500, "Nebulizer — a device that converts liquid medication into an inhalable mist."),
    "neck_collar": (500, "Neck Collar — a supportive brace designed to stabilize the neck."),
    "neck_massager": (2500, "Neck Massager — a device designed to relax and massage the neck."),
    "nursing_pillow": (1500, "Nursing Pillow — a supportive pillow designed to assist with breastfeeding."),
    "ophthalmoscope": (3500, "Ophthalmoscope — a handheld instrument used to examine the eye."),
    "orthopedic_supports": (700, "Orthopedic Supports — a general range of braces designed to support joints and muscles."),
    "otoscope": (2500, "Otoscope — a handheld instrument used to examine the ear."),
    "overbed_table": (2500, "Overbed Table — an adjustable table designed to fit over a bed for patient use."),
    "oxygen_concentrator": (35000, "Oxygen Concentrator — a device that filters and delivers concentrated oxygen."),
    "oxygen_cylinder": (5500, "Oxygen Cylinder — a portable cylinder used to store and deliver medical oxygen."),
    "oxygen_mask": (350, "Oxygen Mask — a mask used to deliver supplemental oxygen."),
    "patient_lift_sling": (2500, "Patient Lift Sling — a sling used to assist in safely lifting or transferring patients."),
    "peak_flow_meter": (900, "Peak Flow Meter — a device used to measure breathing airflow."),
    "pedal_exerciser": (1800, "Pedal Exerciser — a compact pedal device used for seated leg exercises."),
    "penlight": (150, "Penlight — a small pocket light used for basic clinical examinations."),
    "personal_protective_equipment_ppe": (700, "Personal Protective Equipment (PPE) — a general range of gear designed to protect against health hazards."),
    "physiotherapy_equipment": (2500, "Physiotherapy Equipment — a general range of tools used for physical rehabilitation."),
    "pill_crusher": (250, "Pill Crusher — a tool used to crush tablets into a fine powder."),
    "pill_cutter": (150, "Pill Cutter — a tool used to accurately split tablets."),
    "pill_organizer": (300, "Pill Organizer — a container with compartments used to sort medication by day."),
    "posture_corrector": (900, "Posture Corrector — a wearable brace designed to support upright posture."),
    "privacy_screen": (3500, "Privacy Screen — a portable divider used to create privacy in care settings."),
    "protective_coveralls": (450, "Protective Coveralls — full-body protective wear used in hygiene-sensitive settings."),
    "pulse_oximeter": (900, "Pulse Oximeter — a device used to measure blood oxygen saturation."),
    "quad_cane": (900, "Quad Cane — a four-legged cane designed for extra walking stability."),
    "reacher_grabber": (500, "Reacher Grabber — a tool used to reach and grab items without bending."),
    "reading_glasses": (350, "Reading Glasses — glasses designed to assist with close-up reading."),
    "reflex_hammer": (350, "Reflex Hammer — a handheld tool used to test neurological reflexes."),
    "rehabilitation_equipment": (3500, "Rehabilitation Equipment — a general range of tools used for physical recovery."),
    "respiratory_care": (2500, "Respiratory Care Products — a general range of items designed to support breathing health."),
    "rollator": (5500, "Rollator — a wheeled walking frame with a seat for mobility support."),
    "safety_goggles": (350, "Safety Goggles — protective eyewear used to shield the eyes from hazards."),
    "shoe_covers": (150, "Shoe Covers — disposable covers used to protect footwear in hygiene-sensitive settings."),
    "shoulder_support": (700, "Shoulder Support — a supportive brace designed to stabilize the shoulder."),
    "shower_chair": (2500, "Shower Chair — a seat designed for safe bathing assistance."),
    "sleep_mask": (250, "Sleep Mask — a soft mask worn over the eyes to block light during sleep."),
    "smart_scale": (2500, "Smart Scale — a connected scale that tracks weight and body metrics."),
    "spirometer": (1800, "Spirometer — a device used to measure lung breathing capacity."),
    "steam_inhaler": (1500, "Steam Inhaler — a device used to deliver steam therapy for nasal congestion."),
    "sterile_gauze": (150, "Sterile Gauze — sterile fabric used to dress and cover wounds."),
    "stethoscope": (1500, "Stethoscope — an instrument used to listen to internal body sounds."),
    "surface_cleaner": (300, "Surface Cleaner — a cleaning product used to sanitize surfaces."),
    "surgical_gloves": (250, "Surgical Gloves — sterile single-use gloves designed for clinical use."),
    "surgical_mask": (150, "Surgical Mask — a protective mask worn to reduce exposure to particles."),
    "syringe": (100, "Syringe — a tool used to measure and administer liquid medication."),
    "tens_unit": (2500, "TENS Unit — a device that uses electrical pulses for muscle and pain therapy."),
    "therapy_putty": (300, "Therapy Putty — a moldable putty used for hand rehabilitation exercises."),
    "toilet_safety_rail": (1500, "Toilet Safety Rail — a rail designed to assist with toilet safety and support."),
    "tongue_cleaner": (150, "Tongue Cleaner — a small tool used for oral hygiene."),
    "transfer_board": (2500, "Transfer Board — a board used to assist with safely transferring patients between surfaces."),
    "trauma_kit": (2500, "Trauma Kit — a comprehensive kit designed for emergency injury response."),
    "tweezers": (150, "Tweezers — a small precision tool used for first aid and grooming tasks."),
    "vision_care": (700, "Vision Care Products — a general range of items designed to support eye health."),
    "walker": (2500, "Walker — a mobility frame used to assist with walking support."),
    "walking_stick": (700, "Walking Stick — a cane used to assist with walking stability."),
    "water_flosser": (1800, "Water Flosser — a device that uses a water stream for oral hygiene."),
    "wheelchair": (12500, "Wheelchair — a mobility chair designed to assist with transportation."),
    "wound_dressing": (250, "Wound Dressing — a sterile covering used to protect and heal wounds."),
    "wrist_brace": (450, "Wrist Brace — a supportive wrap designed to stabilize the wrist."),
    "yoga_mat": (700, "Yoga Mat — a padded mat used for yoga and floor exercises."),
}

paths = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch2.json",
]

total_updated = 0
total_skipped = []
for path in paths:
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        continue

    updated = 0
    for sku, prod in data.items():
        if prod.get("categoryId") == "health_medical_supplies":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
            else:
                total_skipped.append((path, sku, img))

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"{path}: Updated {updated}")
    total_updated += updated

print(f"Total Updated: {total_updated}")
print(f"Skipped: {total_skipped}")
