import json

price_desc = {
    "shoes_accessories": (900, "Shoes & Accessories — a general range of footwear and related accessories."),
    "sneakers_handbag": (1500, "Sneakers & Handbag Set — a bundled set of footwear and accessory essentials."),
    "mens_shoes": (1800, "Men's Shoes — a general range of footwear designed for men."),
    "casual_shoes": (1500, "Casual Shoes — everyday footwear designed for comfort and versatility."),
    "formal_shoes": (2500, "Formal Shoes — dress footwear designed for professional and formal occasions."),
    "oxford_shoes": (3000, "Oxford Shoes — classic lace-up formal shoes with a closed-lacing design."),
    "derby_shoes": (2800, "Derby Shoes — formal shoes featuring an open-lacing design."),
    "loafers": (2200, "Loafers — slip-on shoes offering a casual yet polished look."),
    "moccasins": (1800, "Moccasins — soft, flexible shoes with a traditional heelless design."),
    "sneakers": (2500, "Sneakers — casual athletic-style shoes suited for everyday wear."),
    "running_shoes": (3000, "Running Shoes — footwear designed with cushioning for running activities."),
    "walking_shoes": (2200, "Walking Shoes — comfortable footwear designed for everyday walking."),
    "training_shoes": (2800, "Training Shoes — footwear designed for gym and cross-training workouts."),
    "basketball_shoes": (3500, "Basketball Shoes — footwear designed with ankle support for basketball."),
    "football_boots": (2500, "Football Boots — cleated footwear designed for football play."),
    "hiking_boots": (3500, "Hiking Boots — durable boots designed for outdoor trail hiking."),
    "work_boots": (2800, "Work Boots — durable boots designed for workplace protection and comfort."),
    "safety_shoes": (2200, "Safety Shoes — protective footwear designed for workplace hazards."),
    "sandals": (900, "Sandals — open footwear designed for casual, warm-weather wear."),
    "slippers": (500, "Slippers — soft, casual footwear designed for indoor wear."),
    "flip_flops": (350, "Flip Flops — casual open-toe sandals with a simple thong strap."),
    "womens_shoes": (1800, "Women's Shoes — a general range of footwear designed for women."),
    "heels": (2200, "Heels — elevated footwear designed for formal and dressy occasions."),
    "pumps": (2200, "Pumps — classic closed-toe heeled shoes for formal wear."),
    "stilettos": (2500, "Stilettos — heeled shoes featuring a thin, tall heel."),
    "wedges": (2000, "Wedges — heeled shoes featuring a solid wedge-shaped sole."),
    "flats": (1500, "Flats — comfortable, low-profile shoes for everyday wear."),
    "ballet_flats": (1500, "Ballet Flats — soft, rounded-toe flat shoes inspired by ballet slippers."),
    "boots": (2800, "Boots — footwear covering the ankle or leg, suited for various occasions."),
    "ankle_boots": (2800, "Ankle Boots — boots that end just above the ankle."),
    "knee_high_boots": (3500, "Knee-High Boots — tall boots extending up to the knee."),
    "rain_boots": (1800, "Rain Boots — waterproof boots designed to keep feet dry in wet weather."),
    "espadrilles": (1500, "Espadrilles — casual shoes featuring a woven rope sole."),
    "kids_shoes": (900, "Kids' Shoes — footwear designed for children."),
    "school_shoes": (900, "School Shoes — durable footwear designed for daily school wear."),
    "sports_shoes": (1500, "Sports Shoes — athletic footwear designed for various sports activities."),
    "baby_shoes": (600, "Baby Shoes — soft, lightweight footwear designed for infants."),
    "tennis_shoes": (2500, "Tennis Shoes — footwear designed for court support during tennis play."),
    "badminton_shoes": (2500, "Badminton Shoes — footwear designed for quick lateral movement in badminton."),
    "golf_shoes": (3000, "Golf Shoes — footwear designed with traction for the golf course."),
    "cricket_shoes": (2500, "Cricket Shoes — footwear designed with spikes for cricket play."),
    "volleyball_shoes": (2800, "Volleyball Shoes — footwear designed for grip and support during volleyball."),
    "cycling_shoes": (3500, "Cycling Shoes — footwear designed to clip into bicycle pedals."),
    "hiking_shoes": (3000, "Hiking Shoes — lightweight footwear designed for trail walking."),
    "trail_running_shoes": (3200, "Trail Running Shoes — footwear designed with traction for off-road running."),
    "outdoor_footwear": (1800, "Outdoor Footwear — a general range of shoes designed for outdoor activities."),
    "trekking_boots": (3800, "Trekking Boots — rugged boots designed for long-distance trekking."),
    "mountaineering_boots": (5500, "Mountaineering Boots — heavy-duty boots designed for high-altitude climbing."),
    "snow_boots": (3000, "Snow Boots — insulated boots designed for cold, snowy conditions."),
    "water_shoes": (900, "Water Shoes — quick-drying footwear designed for wet environments."),
    "aqua_shoes": (900, "Aqua Shoes — lightweight footwear designed for water-based activities."),
    "hunting_boots": (3500, "Hunting Boots — durable boots designed for outdoor hunting conditions."),
    "work_safety_footwear": (2200, "Work & Safety Footwear — a general range of protective footwear for the workplace."),
    "steel_toe_boots": (2800, "Steel Toe Boots — protective boots featuring a reinforced steel toe cap."),
    "composite_toe_shoes": (2800, "Composite Toe Shoes — protective shoes featuring a lightweight composite toe cap."),
    "slip_resistant_shoes": (2000, "Slip-Resistant Shoes — footwear designed with enhanced grip to prevent slipping."),
    "waterproof_work_boots": (3200, "Waterproof Work Boots — durable boots designed to keep feet dry on the job."),
    "electrical_safety_shoes": (2500, "Electrical Safety Shoes — footwear designed to protect against electrical hazards."),
    "industrial_boots": (2800, "Industrial Boots — heavy-duty boots designed for industrial work environments."),
    "fashion_footwear": (2200, "Fashion Footwear — a general range of stylish, trend-forward shoes."),
    "designer_shoes": (5500, "Designer Shoes — premium footwear crafted with high-end design and materials."),
    "platform_shoes": (2500, "Platform Shoes — shoes featuring a thick, elevated sole."),
    "mule_shoes": (2000, "Mule Shoes — backless slip-on shoes offering a casual, chic look."),
    "clogs": (1800, "Clogs — sturdy shoes featuring a thick sole and closed front."),
    "gladiator_sandals": (1500, "Gladiator Sandals — sandals featuring multiple straps extending up the leg."),
    "shoe_care": (300, "Shoe Care — a general range of products for maintaining footwear."),
    "shoe_polish": (250, "Shoe Polish — a product used to shine and protect leather shoes."),
    "shoe_brush": (200, "Shoe Brush — a brush used for cleaning and polishing shoes."),
    "shoe_cleaner": (300, "Shoe Cleaner — a solution used for cleaning footwear."),
    "leather_conditioner": (350, "Leather Conditioner — a product used to soften and protect leather footwear."),
    "waterproof_spray": (350, "Waterproof Spray — a spray used to protect shoes from water damage."),
    "shoe_deodorizer": (250, "Shoe Deodorizer — a product used to eliminate odor from footwear."),
    "shoe_shine_kit": (700, "Shoe Shine Kit — a complete set of tools for cleaning and polishing shoes."),
    "shoe_accessories": (250, "Shoe Accessories — a general range of add-on products for footwear."),
    "shoelaces": (100, "Shoelaces — cords used for fastening shoes."),
    "elastic_shoelaces": (150, "Elastic Shoelaces — stretchable laces that eliminate the need for tying."),
    "shoe_insoles": (300, "Shoe Insoles — cushioned inserts used to improve shoe comfort."),
    "gel_insoles": (350, "Gel Insoles — cushioned inserts using gel padding for extra comfort."),
    "orthopedic_insoles": (500, "Orthopedic Insoles — supportive inserts designed for foot alignment and comfort."),
    "heel_cushions": (200, "Heel Cushions — padded inserts designed to cushion the heel."),
    "heel_grips": (150, "Heel Grips — small pads used to prevent heel slipping in shoes."),
    "arch_support": (350, "Arch Support — inserts designed to support the foot's natural arch."),
    "toe_protectors": (150, "Toe Protectors — cushioned covers designed to protect the toes from friction."),
    "shoe_trees": (400, "Shoe Trees — inserts used to maintain a shoe's shape when not worn."),
    "shoe_horn": (150, "Shoe Horn — a tool used to assist in putting on shoes."),
    "shoe_stretcher": (500, "Shoe Stretcher — a tool used to expand and loosen tight shoes."),
    "boot_shaper": (500, "Boot Shaper — an insert used to maintain a boot's shape during storage."),
    "socks": (150, "Socks — a general range of footwear coverings for the feet."),
    "ankle_socks": (150, "Ankle Socks — short socks that end at the ankle."),
    "crew_socks": (150, "Crew Socks — mid-length socks that reach above the ankle."),
    "knee_high_socks": (200, "Knee-High Socks — socks that extend up to the knee."),
    "compression_socks": (350, "Compression Socks — socks designed to improve circulation."),
    "sports_socks": (200, "Sports Socks — socks designed for cushioning and support during physical activity."),
    "wool_socks": (250, "Wool Socks — warm socks made from wool material."),
    "thermal_socks": (250, "Thermal Socks — insulated socks designed for cold-weather warmth."),
    "no_show_socks": (150, "No-Show Socks — low-cut socks designed to remain hidden inside shoes."),
    "dress_socks": (150, "Dress Socks — thin, formal socks designed for dress shoes."),
    "kids_socks": (100, "Kids' Socks — socks designed for children."),
    "shoe_storage": (500, "Shoe Storage — a general range of products for organizing footwear."),
    "shoe_rack": (900, "Shoe Rack — a stand designed for organizing multiple pairs of shoes."),
    "shoe_cabinet": (2500, "Shoe Cabinet — an enclosed cabinet designed for storing shoes."),
    "shoe_organizer": (700, "Shoe Organizer — a storage unit designed for arranging footwear."),
    "shoe_storage_box": (250, "Shoe Storage Box — an individual box used for storing a pair of shoes."),
    "hanging_shoe_organizer": (500, "Hanging Shoe Organizer — a fabric organizer with pockets for storing shoes."),
    "shoe_bag": (250, "Shoe Bag — a protective bag for packing shoes separately while traveling."),
    "travel_shoe_bag": (300, "Travel Shoe Bag — a bag designed to keep shoes separate while traveling."),
    "shoe_repair": (300, "Shoe Repair — a general range of products for fixing and restoring footwear."),
    "shoe_glue": (150, "Shoe Glue — an adhesive used for repairing shoes."),
    "heel_replacement": (350, "Heel Replacement — replacement heel pieces for repairing shoes."),
    "sole_repair_kit": (500, "Sole Repair Kit — a kit used for repairing worn or damaged shoe soles."),
    "shoe_repair_patch": (200, "Shoe Repair Patch — a patch used to mend torn or damaged shoe material."),
    "leather_repair_kit": (500, "Leather Repair Kit — a kit used for repairing scuffs and tears in leather footwear."),
    "rain_winter_accessories": (500, "Rain & Winter Accessories — a general range of weather-protective footwear accessories."),
    "boot_covers": (350, "Boot Covers — protective covers used to shield boots from rain and mud."),
    "waterproof_shoe_covers": (350, "Waterproof Shoe Covers — covers designed to keep shoes dry in wet conditions."),
    "ice_grips": (500, "Ice Grips — traction devices attached to shoes for walking on ice."),
    "snow_cleats": (500, "Snow Cleats — spiked attachments designed for grip on snow and ice."),
    "thermal_insoles": (350, "Thermal Insoles — insulated inserts designed to keep feet warm."),
    "orthopedic_footwear": (2500, "Orthopedic Footwear — a general range of shoes designed for foot health support."),
    "orthopedic_shoes": (3500, "Orthopedic Shoes — shoes designed to provide therapeutic support for foot conditions."),
    "diabetic_shoes": (3500, "Diabetic Shoes — shoes designed with extra depth and cushioning for diabetic foot care."),
    "medical_sandals": (1800, "Medical Sandals — supportive sandals designed for recovery and comfort."),
    "walking_sandals": (1500, "Walking Sandals — supportive sandals designed for extended walking."),
    "recovery_sandals": (1500, "Recovery Sandals — cushioned sandals designed for post-activity foot recovery."),
    "dance_shoes": (1800, "Dance Shoes — a general range of footwear designed for dance performance."),
    "ballet_shoes": (900, "Ballet Shoes — soft, flexible shoes designed for ballet dancing."),
    "jazz_shoes": (1200, "Jazz Shoes — lightweight shoes designed for jazz dance."),
    "tap_shoes": (1800, "Tap Shoes — shoes fitted with metal taps for tap dancing."),
    "ballroom_shoes": (2200, "Ballroom Shoes — shoes designed with suede soles for ballroom dancing."),
    "latin_dance_shoes": (2200, "Latin Dance Shoes — shoes designed with heel support for Latin dance styles."),
    "shoe_bags_travel": (300, "Shoe Bags for Travel — a general range of bags designed for transporting shoes."),
    "shoe_travel_bag": (300, "Shoe Travel Bag — a bag designed to keep shoes separate while traveling."),
    "dust_bag": (150, "Dust Bag — a soft bag used to protect shoes from dust during storage."),
    "boot_bag": (350, "Boot Bag — a bag designed for carrying and storing boots."),
    "sports_shoe_bag": (300, "Sports Shoe Bag — a bag designed for carrying sports footwear."),
    "foot_care_products": (350, "Foot Care Products — a general range of products for foot health and comfort."),
    "foot_cream": (400, "Foot Cream — a moisturizing cream formulated for dry, cracked feet."),
    "foot_scrub": (400, "Foot Scrub — an exfoliating product used to smooth rough skin on the feet."),
    "foot_massager": (2500, "Foot Massager — a device designed to relax and massage tired feet."),
    "corn_remover": (250, "Corn Remover — a product used to treat and remove foot corns."),
    "heel_repair_cream": (400, "Heel Repair Cream — a cream formulated to heal cracked heels."),
    "toe_separators": (200, "Toe Separators — cushioned inserts used to align and separate the toes."),
    "foot_roller": (500, "Foot Roller — a massage tool used to relieve foot tension."),
    "luxury_footwear": (5500, "Luxury Footwear — a premium range of high-end shoes."),
    "premium_leather_shoes": (6500, "Premium Leather Shoes — high-end shoes crafted from genuine leather."),
    "luxury_sneakers": (7500, "Luxury Sneakers — premium sneakers crafted with high-end materials and design."),
    "designer_boots": (8500, "Designer Boots — premium boots crafted with high-end design and materials."),
    "handmade_shoes": (6500, "Handmade Shoes — footwear crafted individually with artisan techniques."),
    "shoe_display": (900, "Shoe Display — a general range of products for showcasing footwear."),
    "shoe_display_stand": (900, "Shoe Display Stand — a stand designed for displaying shoes."),
    "rotating_shoe_rack": (3500, "Rotating Shoe Rack — a rotating unit designed for displaying and storing shoes."),
    "shoe_display_shelf": (1200, "Shoe Display Shelf — a shelf designed for showcasing footwear."),
}

files_map = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch3.json",
]

updated = 0
skipped = []

for path in files_map:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    changed = False
    for sku, prod in data.items():
        if prod.get("categoryId") == "shoes_accessories":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
                changed = True
            else:
                skipped.append((path, sku, img))
    if changed:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
