import json

price_desc = {
    "adult_scooter": (8500, "Adult Scooter — a kick scooter designed for adult riders and commuting."),
    "arm_sleeves": (450, "Arm Sleeves — fabric sleeves used to protect and warm the arms while cycling."),
    "balance_bike": (4500, "Balance Bike — a pedal-less bike designed to teach young children balance."),
    "basket": (900, "Basket — a bicycle-mounted basket used for carrying items."),
    "battery_case": (1500, "Battery Case — a protective housing used for an electric vehicle's battery."),
    "battery_charger": (1800, "Battery Charger — a device used to recharge electric bike or scooter batteries."),
    "battery_management_system": (3500, "Battery Management System — an electronic system that monitors and protects battery performance."),
    "battery_pack": (12000, "Battery Pack — a rechargeable battery unit used to power electric bikes and scooters."),
    "bicycle_electric_scooter": (35000, "Bicycle Electric Scooter — a hybrid electric scooter designed for efficient urban commuting."),
    "bicycle_fork": (3500, "Bicycle Fork — the front component that holds the front wheel and supports steering."),
    "bicycle_frame": (8500, "Bicycle Frame — the main structural framework of a bicycle."),
    "bicycle_helmet": (1800, "Bicycle Helmet — protective headgear worn while cycling."),
    "bicycle_lock": (900, "Bicycle Lock — a security device used to prevent bicycle theft."),
    "bicycles": (15000, "Bicycles — a general range of pedal-powered bicycles."),
    "bicycles_scooters_electric_vehicles": (500, "Bicycles, Scooters & Electric Vehicles — a general range of personal transportation products."),
    "bike_bell": (250, "Bike Bell — a bell mounted on the handlebar to alert pedestrians."),
    "bike_cleaning_kit": (1200, "Bike Cleaning Kit — a complete set of tools and products for bicycle maintenance."),
    "bike_computer": (2500, "Bike Computer — a device that tracks speed, distance, and other cycling metrics."),
    "bike_horn": (350, "Bike Horn — a horn mounted on a bicycle to alert others of its presence."),
    "bike_pump": (900, "Bike Pump — a hand or foot pump used to inflate bicycle tires."),
    "bike_repair_stand": (3500, "Bike Repair Stand — a stand used to hold a bicycle in place for maintenance."),
    "bmx_bike": (12000, "BMX Bike — a compact, durable bicycle designed for stunts and off-road riding."),
    "bottle_cage": (450, "Bottle Cage — a holder mounted on the bike frame to carry a water bottle."),
    "bottom_bracket": (1500, "Bottom Bracket — a bicycle component that houses the spindle connecting the crankset."),
    "brake_lever": (600, "Brake Lever — a handlebar-mounted lever used to actuate bicycle brakes."),
    "brake_pad": (450, "Brake Pad — a friction component used in bicycle braking systems."),
    "cargo_bike": (35000, "Cargo Bike — a heavy-duty bicycle designed for carrying large loads."),
    "cassette": (1800, "Cassette — a cluster of gears mounted on the rear wheel of a bicycle."),
    "chain": (700, "Chain — a metal link chain that transmits power from the pedals to the rear wheel."),
    "chain_cleaner": (600, "Chain Cleaner — a tool used to clean grime and dirt from a bicycle chain."),
    "chain_guard": (500, "Chain Guard — a protective cover that shields the bicycle chain."),
    "chain_lubricant": (350, "Chain Lubricant — a lubricant used to reduce friction on a bicycle chain."),
    "charging_adapter": (700, "Charging Adapter — an adapter used to connect an electric vehicle to a power source."),
    "charging_cable": (900, "Charging Cable — a cable used to charge electric bikes, scooters, and vehicles."),
    "child_bike_seat": (2500, "Child Bike Seat — a seat mounted on a bicycle for carrying a young child."),
    "city_bike": (16000, "City Bike — a comfortable bicycle designed for urban commuting."),
    "cleaning_brush": (250, "Cleaning Brush — a brush used for cleaning bicycle and scooter components."),
    "controller": (3500, "Controller — an electronic unit that regulates power delivery in electric vehicles."),
    "crankset": (2500, "Crankset — the component that connects the pedals to the chain and drives the bicycle."),
    "cruiser_bike": (18000, "Cruiser Bike — a relaxed-style bicycle designed for comfortable leisure riding."),
    "cycling_glasses": (900, "Cycling Glasses — protective eyewear designed for cyclists."),
    "cycling_gloves": (600, "Cycling Gloves — padded gloves designed for grip and comfort while cycling."),
    "cycling_jacket": (2200, "Cycling Jacket — a lightweight, weather-resistant jacket designed for cyclists."),
    "cycling_jersey": (1500, "Cycling Jersey — a fitted shirt designed for cycling performance and comfort."),
    "cycling_shoes": (2500, "Cycling Shoes — specialized shoes designed for efficient pedaling."),
    "cycling_shorts": (1200, "Cycling Shorts — padded shorts designed for comfort during long rides."),
    "cycling_socks": (350, "Cycling Socks — moisture-wicking socks designed for cycling comfort."),
    "derailleur": (2500, "Derailleur — a mechanism used to shift gears on a bicycle."),
    "disc_brake": (2200, "Disc Brake — a braking system that uses a rotor and caliper for stopping power."),
    "display_panel": (2500, "Display Panel — an electronic panel that shows speed, battery, and ride data."),
    "elbow_pads": (500, "Elbow Pads — protective padding worn to guard the elbows while riding."),
    "electric_atv": (95000, "Electric ATV — an electric all-terrain vehicle designed for off-road use."),
    "electric_bicycle": (55000, "Electric Bicycle — a pedal bicycle equipped with an electric motor for assisted riding."),
    "electric_bus": (2500000, "Electric Bus — a large passenger vehicle powered entirely by electric batteries."),
    "electric_cargo_vehicle": (180000, "Electric Cargo Vehicle — an electric vehicle designed for transporting goods."),
    "electric_golf_cart": (150000, "Electric Golf Cart — a small electric vehicle designed for golf courses and short trips."),
    "electric_mini_car": (350000, "Electric Mini Car — a compact electric vehicle designed for city driving."),
    "electric_moped": (85000, "Electric Moped — a small electric two-wheeler designed for urban commuting."),
    "electric_motor": (12000, "Electric Motor — the drive unit that powers electric bikes, scooters, and vehicles."),
    "electric_motorcycle": (250000, "Electric Motorcycle — a motorcycle powered entirely by an electric motor."),
    "electric_passenger_car": (2200000, "Electric Passenger Car — a fully electric car designed for personal transportation."),
    "electric_pickup_truck": (2800000, "Electric Pickup Truck — a fully electric truck designed for hauling and utility use."),
    "electric_scooter": (35000, "Electric Scooter — a motorized scooter designed for efficient urban commuting."),
    "electric_tricycle": (65000, "Electric Tricycle — a three-wheeled electric vehicle offering added stability."),
    "electric_utility_vehicle": (280000, "Electric Utility Vehicle — an electric vehicle designed for utility and light transport tasks."),
    "electric_van": (1800000, "Electric Van — a fully electric van designed for passenger or cargo transport."),
    "electric_wheelchair": (65000, "Electric Wheelchair — a motorized wheelchair designed for mobility assistance."),
    "fast_charger": (3500, "Fast Charger — a charging device designed to quickly recharge electric vehicle batteries."),
    "fat_tire_bike": (22000, "Fat Tire Bike — a bicycle with oversized tires designed for rough terrain."),
    "folding_bike": (18000, "Folding Bike — a compact bicycle designed to fold for easy storage and transport."),
    "folding_mechanism": (1500, "Folding Mechanism — a hinge component used in folding bikes and scooters."),
    "folding_scooter": (18000, "Folding Scooter — a compact scooter designed to fold for easy storage."),
    "freewheel": (900, "Freewheel — a bicycle component that allows the rear wheel to coast without pedaling."),
    "front_light": (700, "Front Light — a light mounted on the front of a bike or scooter for visibility."),
    "fuse_kit": (450, "Fuse Kit — a set of replacement fuses used in electric vehicle electrical systems."),
    "gear_shifter": (900, "Gear Shifter — a control used to change gears on a bicycle."),
    "gps_tracker": (2800, "GPS Tracker — a device used to monitor the real-time location of a bike or vehicle."),
    "handlebar": (1200, "Handlebar — the steering component gripped by the rider of a bike or scooter."),
    "handlebar_bag": (900, "Handlebar Bag — a storage bag mounted on the handlebar for carrying essentials."),
    "helmet_cover": (350, "Helmet Cover — a protective cover fitted over a cycling helmet."),
    "home_charging_station": (25000, "Home Charging Station — a fixed charging unit installed for electric vehicles at home."),
    "hub_motor": (15000, "Hub Motor — an electric motor integrated into the wheel hub of an e-bike or scooter."),
    "hybrid_bike": (20000, "Hybrid Bike — a versatile bicycle combining road and mountain bike features."),
    "inner_tube": (350, "Inner Tube — a rubber tube fitted inside a tire to hold air."),
    "kick_scooter": (3500, "Kick Scooter — a manually propelled scooter used for casual riding."),
    "kickstand": (450, "Kickstand — a folding support used to keep a bicycle upright when parked."),
    "kids_bicycle": (8500, "Kids Bicycle — a bicycle sized and designed for children."),
    "kids_scooter": (2500, "Kids Scooter — a scooter designed for children's casual use."),
    "knee_pads": (500, "Knee Pads — protective padding worn to guard the knees while riding."),
    "lead_acid_battery": (8500, "Lead Acid Battery — a rechargeable battery type used in some electric vehicles."),
    "leg_warmers": (600, "Leg Warmers — fabric coverings used to keep legs warm while cycling."),
    "lithium_ion_battery": (18000, "Lithium Ion Battery — a lightweight, high-capacity battery used in electric bikes and scooters."),
    "mobility_scooter": (55000, "Mobility Scooter — an electric scooter designed to assist those with limited mobility."),
    "motor_controller": (3500, "Motor Controller — an electronic device that regulates power to an electric motor."),
    "mountain_bike": (25000, "Mountain Bike — a rugged bicycle designed for off-road terrain."),
    "mudguard": (600, "Mudguard — a fender that protects the rider from mud and water splashes."),
    "multi_tool": (700, "Multi Tool — a compact tool combining several functions for bike repairs."),
    "off_road_electric_scooter": (65000, "Off-Road Electric Scooter — a rugged electric scooter designed for rough terrain."),
    "pannier_bag": (1500, "Pannier Bag — a bag mounted on the side of a bike rack for carrying cargo."),
    "patch_kit": (250, "Patch Kit — a set of tools and patches used to repair a punctured inner tube."),
    "pedal_assist_sensor": (1500, "Pedal Assist Sensor — a sensor that detects pedaling to activate electric motor assistance."),
    "pedals": (900, "Pedals — the components pressed by the rider's feet to power the bicycle."),
    "phone_holder": (450, "Phone Holder — a mount used to secure a phone on a bike or scooter handlebar."),
    "portable_ev_charger": (8500, "Portable EV Charger — a compact, mobile charger for electric vehicles."),
    "racing_bike": (35000, "Racing Bike — a lightweight bicycle designed for high-speed road cycling."),
    "rain_coat": (900, "Rain Coat — a waterproof coat designed for cyclists in wet weather."),
    "rear_light": (600, "Rear Light — a light mounted on the back of a bike or scooter for visibility."),
    "rear_rack": (1500, "Rear Rack — a mounted platform used to carry cargo on the back of a bicycle."),
    "reflective_vest": (450, "Reflective Vest — a high-visibility vest worn by cyclists for safety."),
    "reflectors": (250, "Reflectors — small reflective devices mounted on a bike for visibility."),
    "rim": (1500, "Rim — the outer circular part of a wheel that holds the tire."),
    "road_bike": (30000, "Road Bike — a lightweight bicycle designed for speed on paved roads."),
    "saddle": (1200, "Saddle — the seat of a bicycle designed for rider comfort."),
    "saddle_bag": (700, "Saddle Bag — a small bag mounted under the bicycle seat for storage."),
    "safety_gloves": (450, "Safety Gloves — protective gloves worn while riding for grip and hand protection."),
    "safety_lights": (600, "Safety Lights — lights used to increase visibility while riding at night."),
    "scooter_brake": (900, "Scooter Brake — a braking component used to stop an electric or kick scooter."),
    "scooter_controller": (3500, "Scooter Controller — an electronic unit that regulates power delivery in electric scooters."),
    "scooter_deck": (2500, "Scooter Deck — the flat platform on which a rider stands on a scooter."),
    "scooter_grip": (350, "Scooter Grip — a handlebar grip designed for scooter control and comfort."),
    "scooter_handlebar": (1200, "Scooter Handlebar — the steering component of a scooter."),
    "scooter_helmet": (1800, "Scooter Helmet — protective headgear worn while riding a scooter."),
    "scooter_motor": (12000, "Scooter Motor — the electric motor that powers an electric scooter."),
    "scooter_suspension": (2200, "Scooter Suspension — a shock-absorbing system used to smooth out scooter rides."),
    "scooter_tire": (900, "Scooter Tire — a tire designed for electric or kick scooters."),
    "scooter_wheel": (1500, "Scooter Wheel — a wheel component designed for electric or kick scooters."),
    "seat_post": (900, "Seat Post — the tube that connects the saddle to the bicycle frame."),
    "shoe_covers": (450, "Shoe Covers — protective covers worn over cycling shoes for weather protection."),
    "smart_scooter": (55000, "Smart Scooter — an electric scooter equipped with connected smart features."),
    "spokes": (350, "Spokes — the thin rods that connect a wheel's rim to its hub."),
    "stem": (900, "Stem — the component that connects the handlebar to the bicycle fork."),
    "stunt_scooter": (5500, "Stunt Scooter — a durable scooter designed for tricks and stunt riding."),
    "tandem_bicycle": (35000, "Tandem Bicycle — a bicycle designed for two riders to pedal together."),
    "three_wheel_scooter": (12000, "Three-Wheel Scooter — a stable scooter design with three wheels."),
    "throttle": (900, "Throttle — a control used to regulate speed on an electric bike or scooter."),
    "tire": (1200, "Tire — a rubber tire designed for bicycles, scooters, or electric vehicles."),
    "tire_lever": (150, "Tire Lever — a tool used to remove a tire from the wheel rim."),
    "tire_repair_kit": (450, "Tire Repair Kit — a set of tools used to fix punctured bicycle or scooter tires."),
    "torque_wrench": (2200, "Torque Wrench — a precision tool used to tighten bicycle components to spec."),
    "touring_bike": (28000, "Touring Bike — a durable bicycle designed for long-distance travel."),
    "trailer": (8500, "Trailer — a towable cart attached to a bicycle for carrying cargo or children."),
    "water_bottle": (350, "Water Bottle — a lightweight bottle designed for use while cycling."),
    "wheel_truing_stand": (5500, "Wheel Truing Stand — a tool used to straighten and true bicycle wheels."),
    "wheelset": (8500, "Wheelset — a matched pair of wheels designed for a bicycle."),
    "wiring_harness": (2500, "Wiring Harness — a bundled set of wires that connects an electric vehicle's electrical system."),
    "wrist_guards": (450, "Wrist Guards — protective gear worn to guard the wrists while riding."),
}

path = "data/products-placeholder.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
skipped = []
for sku, prod in data.items():
    if prod.get("categoryId") == "bicycles_scooters_electric_vehicles":
        img = prod["images"]["main"].split("/")[-1].replace(".png", "")
        if img in price_desc:
            price, desc = price_desc[img]
            title = " ".join(w.capitalize() for w in img.split("_"))
            prod["title"] = title
            prod["price"] = price
            prod["description"] = desc
            prod["status"] = "active"
            updated += 1
        else:
            skipped.append((sku, img))

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
