import json

price_desc = {
    "power_tools_hand_tools": (500, "Power Tools & Hand Tools — a general range of power and hand tools for workshop and home use."),
    "power_drill_wrench_screwdriver": (2500, "Power Drill, Wrench & Screwdriver Combo — a versatile multi-tool kit for drilling and driving tasks."),
    "power_drills": (3500, "Power Drills — electric drills designed for drilling holes and driving screws."),
    "cordless_drill": (3800, "Cordless Drill — a battery-powered drill offering portable drilling and driving."),
    "electric_drill": (2800, "Electric Drill — a corded drill designed for consistent drilling power."),
    "hammer_drill": (4500, "Hammer Drill — a drill with a hammering action designed for masonry and concrete."),
    "rotary_hammer": (6500, "Rotary Hammer — a heavy-duty drill designed for demolition and concrete drilling."),
    "impact_drill": (3200, "Impact Drill — a drill with impact action for tougher drilling tasks."),
    "impact_driver": (3500, "Impact Driver — a compact tool designed for driving screws with high torque."),
    "right_angle_drill": (4200, "Right Angle Drill — a drill designed for drilling in tight, confined spaces."),
    "magnetic_drill_press": (12500, "Magnetic Drill Press — a drill that mounts magnetically to metal surfaces for precise drilling."),
    "saws": (2500, "Saws — a general range of power saws for cutting wood, metal, and other materials."),
    "circular_saw": (4500, "Circular Saw — a power saw with a rotating blade designed for straight cuts."),
    "jigsaw": (3200, "Jigsaw — a power saw designed for cutting curves and intricate shapes."),
    "reciprocating_saw": (4200, "Reciprocating Saw — a power saw with a push-pull blade motion for demolition work."),
    "miter_saw": (7500, "Miter Saw — a saw designed for making precise angled crosscuts."),
    "table_saw": (12500, "Table Saw — a stationary saw with a mounted blade for cutting large wood pieces."),
    "band_saw": (9500, "Band Saw — a saw with a continuous blade loop for cutting curves and resawing."),
    "chop_saw": (6500, "Chop Saw — a power saw designed for making straight cuts through metal or wood."),
    "tile_saw": (7500, "Tile Saw — a saw designed for cutting ceramic and stone tiles."),
    "scroll_saw": (5500, "Scroll Saw — a fine-bladed saw designed for intricate curved cuts."),
    "chainsaw": (6500, "Chainsaw — a power saw with a rotating chain designed for cutting wood and trees."),
    "grinders_sanders": (2800, "Grinders & Sanders — a general range of power tools for grinding and sanding surfaces."),
    "angle_grinder": (3500, "Angle Grinder — a handheld power tool for cutting, grinding, and polishing."),
    "bench_grinder": (4500, "Bench Grinder — a stationary grinder used for sharpening and shaping metal."),
    "die_grinder": (2800, "Die Grinder — a compact rotary tool for grinding and finishing detailed work."),
    "belt_sander": (4500, "Belt Sander — a power sander with a continuous abrasive belt for fast material removal."),
    "orbital_sander": (2800, "Orbital Sander — a power sander with a circular motion for smooth finishing."),
    "random_orbital_sander": (3200, "Random Orbital Sander — a sander combining rotary and orbital motion for a swirl-free finish."),
    "detail_sander": (2200, "Detail Sander — a compact sander designed for tight corners and detailed work."),
    "disc_sander": (5500, "Disc Sander — a stationary sander with a rotating abrasive disc."),
    "polisher": (3500, "Polisher — a power tool designed for polishing and buffing surfaces."),
    "buffer_machine": (4200, "Buffer Machine — a power tool used for buffing and finishing surfaces to a shine."),
    "cutting_finishing_tools": (2500, "Cutting & Finishing Tools — a general range of tools for cutting and surface finishing."),
    "rotary_tool": (2800, "Rotary Tool — a versatile handheld tool for cutting, grinding, and engraving."),
    "oscillating_multi_tool": (3500, "Oscillating Multi-Tool — a versatile tool for cutting, sanding, and scraping tasks."),
    "heat_gun": (1800, "Heat Gun — a tool that emits hot air for stripping paint and shrinking materials."),
    "electric_planer": (3800, "Electric Planer — a power tool used to smooth and shape wood surfaces."),
    "laminate_trimmer": (2800, "Laminate Trimmer — a compact router designed for trimming laminate edges."),
    "router": (4500, "Router — a power tool used for hollowing out or shaping wood."),
    "wood_router": (4800, "Wood Router — a power tool designed for routing grooves and edges in wood."),
    "wall_chaser": (7500, "Wall Chaser — a power tool used for cutting channels into walls for wiring or piping."),
    "fastening_tools": (2200, "Fastening Tools — a general range of tools designed for driving fasteners."),
    "nail_gun": (4500, "Nail Gun — a power tool that drives nails quickly into wood or other materials."),
    "brad_nailer": (3500, "Brad Nailer — a nail gun designed for driving thin brad nails."),
    "finish_nailer": (4200, "Finish Nailer — a nail gun designed for fine finish carpentry work."),
    "framing_nailer": (5500, "Framing Nailer — a heavy-duty nail gun designed for structural framing work."),
    "staple_gun": (1500, "Staple Gun — a tool designed to drive staples into wood or fabric."),
    "rivet_gun": (1200, "Rivet Gun — a hand tool used for installing pop rivets."),
    "electric_screwdriver": (1800, "Electric Screwdriver — a compact power tool designed for driving screws."),
    "air_spray_equipment": (3500, "Air & Spray Equipment — a general range of pneumatic and spraying tools."),
    "air_compressor": (8500, "Air Compressor — a machine that pressurizes air for powering pneumatic tools."),
    "spray_gun": (1800, "Spray Gun — a tool used to apply paint or coatings using compressed air."),
    "paint_sprayer": (4500, "Paint Sprayer — a power tool designed for applying paint evenly over large surfaces."),
    "pressure_washer": (7500, "Pressure Washer — a machine that uses high-pressure water for cleaning surfaces."),
    "air_blow_gun": (450, "Air Blow Gun — a pneumatic tool used to blow away dust and debris."),
    "grease_gun": (900, "Grease Gun — a tool used to apply lubricating grease to machinery."),
    "measuring_detection_tools": (1500, "Measuring & Detection Tools — a general range of tools for precise measurement and detection."),
    "laser_distance_meter": (2500, "Laser Distance Meter — a device that measures distance using a laser beam."),
    "laser_level": (3500, "Laser Level — a tool that projects a laser line for accurate leveling."),
    "digital_level": (2800, "Digital Level — an electronic level that displays precise angle readings."),
    "stud_finder": (1200, "Stud Finder — a device used to locate studs behind walls."),
    "moisture_meter": (1800, "Moisture Meter — a device used to measure moisture content in materials."),
    "digital_multimeter": (1500, "Digital Multimeter — a device used to measure voltage, current, and resistance."),
    "clamp_meter": (2200, "Clamp Meter — a device used to measure electrical current without breaking the circuit."),
    "voltage_tester": (450, "Voltage Tester — a tool used to check whether an electrical circuit is live."),
    "infrared_thermometer": (1200, "Infrared Thermometer — a device used to measure surface temperature remotely."),
    "hand_tools": (500, "Hand Tools — a general range of manually operated tools for various tasks."),
    "screwdrivers": (150, "Screwdrivers — hand tools used for driving and removing screws."),
    "screwdriver_set": (700, "Screwdriver Set — a set of screwdrivers with various tips and sizes."),
    "phillips_screwdriver": (150, "Phillips Screwdriver — a screwdriver with a cross-shaped tip."),
    "flat_head_screwdriver": (150, "Flat Head Screwdriver — a screwdriver with a flat, single-slot tip."),
    "precision_screwdriver": (500, "Precision Screwdriver — a small screwdriver designed for delicate electronic work."),
    "ratcheting_screwdriver": (600, "Ratcheting Screwdriver — a screwdriver with a ratchet mechanism for faster driving."),
    "insulated_screwdriver": (400, "Insulated Screwdriver — a screwdriver with insulated handle for electrical safety."),
    "wrenches": (300, "Wrenches — hand tools used for gripping and turning nuts and bolts."),
    "adjustable_wrench": (450, "Adjustable Wrench — a wrench with a movable jaw for various fastener sizes."),
    "combination_wrench": (350, "Combination Wrench — a wrench with an open end and a box end."),
    "socket_wrench": (700, "Socket Wrench — a wrench used with interchangeable sockets."),
    "torque_wrench": (1800, "Torque Wrench — a wrench designed to apply a specific amount of torque."),
    "pipe_wrench": (600, "Pipe Wrench — a wrench designed for gripping and turning pipes."),
    "hex_key_set": (350, "Hex Key Set — a set of L-shaped keys designed for hexagonal fasteners."),
    "allen_key_set": (350, "Allen Key Set — a set of hex keys used for driving Allen-head screws."),
    "pliers": (250, "Pliers — hand tools used for gripping, bending, and cutting materials."),
    "combination_pliers": (300, "Combination Pliers — versatile pliers designed for gripping and cutting."),
    "long_nose_pliers": (300, "Long Nose Pliers — pliers with a narrow tip for reaching tight spaces."),
    "diagonal_cutting_pliers": (300, "Diagonal Cutting Pliers — pliers designed for cutting wire and cable."),
    "locking_pliers": (450, "Locking Pliers — pliers with a locking jaw mechanism for a firm grip."),
    "slip_joint_pliers": (300, "Slip Joint Pliers — pliers with an adjustable pivot for varying jaw widths."),
    "water_pump_pliers": (400, "Water Pump Pliers — pliers with an adjustable jaw for gripping pipes and fittings."),
    "circlip_pliers": (400, "Circlip Pliers — pliers designed for installing and removing circlips."),
    "hammers": (300, "Hammers — hand tools used for driving nails and general striking tasks."),
    "claw_hammer": (450, "Claw Hammer — a hammer with a claw end for removing nails."),
    "ball_peen_hammer": (450, "Ball Peen Hammer — a hammer with a rounded end used for metalworking."),
    "rubber_mallet": (350, "Rubber Mallet — a soft-headed hammer used for non-marring strikes."),
    "sledge_hammer": (900, "Sledge Hammer — a heavy hammer used for demolition and driving stakes."),
    "dead_blow_hammer": (600, "Dead Blow Hammer — a hammer designed to minimize rebound on impact."),
    "cutting_tools": (350, "Cutting Tools — a general range of hand tools designed for cutting materials."),
    "utility_knife": (200, "Utility Knife — a retractable-blade knife used for general cutting tasks."),
    "snap_off_knife": (150, "Snap-Off Knife — a utility knife with a snap-off segmented blade."),
    "hacksaw": (350, "Hacksaw — a hand saw designed for cutting metal."),
    "hand_saw": (350, "Hand Saw — a manually operated saw designed for cutting wood."),
    "coping_saw": (400, "Coping Saw — a hand saw with a thin blade for cutting intricate curves."),
    "tin_snips": (400, "Tin Snips — hand shears designed for cutting sheet metal."),
    "bolt_cutter": (1200, "Bolt Cutter — a heavy-duty cutting tool designed for cutting bolts and chains."),
    "glass_cutter": (250, "Glass Cutter — a tool used to score and cut glass sheets."),
    "wire_cutter": (300, "Wire Cutter — a hand tool designed for cutting electrical and other wires."),
    "chisels_files": (350, "Chisels & Files — a general range of hand tools for shaping and smoothing materials."),
    "wood_chisel": (400, "Wood Chisel — a hand tool used for carving and shaping wood."),
    "cold_chisel": (350, "Cold Chisel — a hand tool used for cutting and shaping cold metal."),
    "masonry_chisel": (400, "Masonry Chisel — a chisel designed for cutting stone, brick, and concrete."),
    "metal_file": (250, "Metal File — a hand tool used for smoothing and shaping metal surfaces."),
    "wood_rasp": (300, "Wood Rasp — a coarse file used for shaping and smoothing wood."),
    "file_set": (700, "File Set — a set of files with various shapes for shaping and smoothing tasks."),
    "measuring_tools": (300, "Measuring Tools — a general range of tools used for precise measurement."),
    "measuring_tape": (250, "Measuring Tape — a flexible ruler used for measuring length."),
    "steel_ruler": (200, "Steel Ruler — a rigid metal ruler used for precise measurement and cutting guides."),
    "combination_square": (500, "Combination Square — a measuring tool used for checking angles and marking lines."),
    "try_square": (350, "Try Square — a tool used for checking and marking right angles."),
    "spirit_level": (600, "Spirit Level — a tool used to check whether a surface is horizontal or vertical."),
    "chalk_line": (350, "Chalk Line — a tool used to snap straight chalk lines on surfaces."),
    "feeler_gauge": (300, "Feeler Gauge — a tool used to measure small gaps and clearances."),
    "vernier_caliper": (700, "Vernier Caliper — a precision instrument used for accurate internal and external measurements."),
    "digital_caliper": (1200, "Digital Caliper — an electronic caliper providing precise digital measurement readings."),
    "micrometer": (1500, "Micrometer — a precision tool used for measuring very small dimensions."),
    "clamps_vises": (500, "Clamps & Vises — a general range of tools used to hold workpieces securely."),
    "c_clamp": (350, "C-Clamp — a C-shaped clamp used to hold materials firmly in place."),
    "bar_clamp": (700, "Bar Clamp — a long clamp used for securing larger workpieces."),
    "spring_clamp": (250, "Spring Clamp — a spring-loaded clamp used for quick, light-duty clamping."),
    "corner_clamp": (450, "Corner Clamp — a clamp designed to hold two pieces at a right angle."),
    "bench_vise": (2500, "Bench Vise — a mounted clamping tool used to hold work securely on a bench."),
    "pipe_clamp": (600, "Pipe Clamp — a clamp used with a pipe to secure large glue-ups."),
    "quick_grip_clamp": (500, "Quick Grip Clamp — a one-handed clamp designed for fast, easy clamping."),
    "tool_storage": (900, "Tool Storage — a general range of products designed for organizing and storing tools."),
    "tool_box": (1500, "Tool Box — a portable box designed for storing and carrying tools."),
    "tool_bag": (900, "Tool Bag — a soft-sided bag designed for carrying tools."),
    "tool_backpack": (1800, "Tool Backpack — a backpack-style bag designed for carrying tools hands-free."),
    "tool_chest": (5500, "Tool Chest — a large storage unit with multiple drawers for organizing tools."),
    "tool_cabinet": (7500, "Tool Cabinet — a stationary cabinet designed for storing tools and equipment."),
    "rolling_tool_cart": (6500, "Rolling Tool Cart — a mobile cart with drawers designed for organizing tools."),
    "parts_organizer": (700, "Parts Organizer — a compartmentalized case designed for sorting small parts."),
    "drill_saw_accessories": (350, "Drill & Saw Accessories — a general range of accessories for drills and saws."),
    "drill_bit_set": (700, "Drill Bit Set — a set of drill bits for various drilling tasks."),
    "masonry_drill_bits": (400, "Masonry Drill Bits — drill bits designed for drilling into concrete and stone."),
    "wood_drill_bits": (350, "Wood Drill Bits — drill bits designed specifically for drilling wood."),
    "metal_drill_bits": (450, "Metal Drill Bits — drill bits designed for drilling into metal."),
    "hole_saw_kit": (900, "Hole Saw Kit — a set of hole saws used for cutting large circular holes."),
    "screwdriver_bits": (300, "Screwdriver Bits — interchangeable bits used with drills and drivers."),
    "saw_blades": (500, "Saw Blades — replacement blades designed for various power saws."),
    "jigsaw_blades": (300, "Jigsaw Blades — replacement blades designed for jigsaws."),
    "circular_saw_blades": (600, "Circular Saw Blades — replacement blades designed for circular saws."),
    "grinding_disc": (250, "Grinding Disc — an abrasive disc used with angle grinders for grinding."),
    "cutting_disc": (200, "Cutting Disc — an abrasive disc used with angle grinders for cutting metal."),
    "flap_disc": (300, "Flap Disc — a layered abrasive disc used for grinding and finishing."),
    "sanding_disc": (200, "Sanding Disc — an abrasive disc used with sanders for surface finishing."),
    "sandpaper": (150, "Sandpaper — abrasive paper used for smoothing surfaces by hand or machine."),
    "wire_brush_wheel": (350, "Wire Brush Wheel — a rotary wire brush used for cleaning and rust removal."),
    "welding_soldering": (2500, "Welding & Soldering — a general range of tools used for welding and soldering."),
    "welding_machine": (12500, "Welding Machine — a machine used to fuse metal parts together."),
    "soldering_iron": (900, "Soldering Iron — a hand tool used to melt solder for joining metal or electronics."),
    "solder_wire": (350, "Solder Wire — a metal wire used to join components during soldering."),
    "desoldering_pump": (300, "Desoldering Pump — a tool used to remove excess solder from joints."),
    "welding_helmet": (2200, "Welding Helmet — protective headgear designed to shield the eyes and face during welding."),
    "welding_gloves": (700, "Welding Gloves — heat-resistant gloves designed to protect hands while welding."),
    "safety_equipment": (500, "Safety Equipment — a general range of personal protective equipment for workshop use."),
    "safety_glasses": (250, "Safety Glasses — protective eyewear designed to shield eyes from debris."),
    "face_shield": (450, "Face Shield — a protective shield designed to guard the face during hazardous work."),
    "work_gloves": (350, "Work Gloves — protective gloves designed for general workshop and manual tasks."),
    "ear_protection": (300, "Ear Protection — protective gear designed to reduce exposure to loud noise."),
    "dust_mask": (150, "Dust Mask — a protective mask designed to filter out dust particles."),
    "respirator": (900, "Respirator — a protective mask designed to filter harmful airborne particles and fumes."),
    "safety_helmet": (600, "Safety Helmet — protective headgear designed to shield the head from impact."),
    "knee_pads": (450, "Knee Pads — protective padding designed to cushion the knees during kneeling work."),
    "safety_boots": (1800, "Safety Boots — protective footwear designed with reinforced toes for workshop safety."),
    "reflective_vest": (350, "Reflective Vest — a high-visibility vest designed for safety in low-light conditions."),
    "workshop_accessories": (500, "Workshop Accessories — a general range of accessories used to support workshop tasks."),
    "extension_cord": (450, "Extension Cord — a power cord used to extend the reach of electrical tools."),
    "cable_reel": (1500, "Cable Reel — a retractable reel used to store and manage power cables."),
    "work_light": (900, "Work Light — a portable light designed to illuminate work areas."),
    "magnetic_pickup_tool": (350, "Magnetic Pickup Tool — a telescoping tool with a magnetic tip for retrieving small metal items."),
    "tool_magnet": (250, "Tool Magnet — a magnetic strip or holder used to keep tools organized."),
    "workbench": (6500, "Workbench — a sturdy table designed as a work surface for tools and projects."),
    "saw_horse": (900, "Saw Horse — a support stand used to hold material while cutting."),
    "parts_tray": (250, "Parts Tray — a tray used for sorting and holding small parts during work."),
    "hardware_consumables": (200, "Hardware Consumables — a general range of small hardware items used in workshop tasks."),
    "screws": (150, "Screws — threaded fasteners used for joining materials."),
    "nails": (150, "Nails — metal fasteners used for joining wood and other materials."),
    "bolts": (200, "Bolts — threaded fasteners used with nuts to join materials."),
    "nuts": (100, "Nuts — threaded fasteners used with bolts to secure materials."),
    "washers": (100, "Washers — flat discs used to distribute load under a fastener."),
    "anchors": (200, "Anchors — fasteners designed to secure screws into masonry or drywall."),
    "wall_plugs": (150, "Wall Plugs — plastic anchors used to secure screws into walls."),
    "rivets": (150, "Rivets — permanent fasteners used to join metal or other materials."),
    "cable_ties": (150, "Cable Ties — plastic straps used to bundle and organize cables."),
    "construction_adhesive": (350, "Construction Adhesive — a strong adhesive used for bonding building materials."),
    "super_glue": (150, "Super Glue — a fast-bonding adhesive used for quick repairs."),
    "epoxy_adhesive": (300, "Epoxy Adhesive — a two-part adhesive used for strong, durable bonds."),
    "silicone_sealant": (350, "Silicone Sealant — a flexible sealant used for waterproofing joints and gaps."),
    "ptfe_thread_seal_tape": (100, "PTFE Thread Seal Tape — a tape used to seal threaded pipe connections."),
    "replacement_parts": (350, "Replacement Parts — a general range of spare parts for power tools."),
    "carbon_brushes": (250, "Carbon Brushes — replacement brushes used in electric motor tools."),
    "power_tool_battery": (2500, "Power Tool Battery — a rechargeable battery designed for cordless power tools."),
    "battery_charger": (1500, "Battery Charger — a charger designed for recharging power tool batteries."),
    "replacement_chuck": (700, "Replacement Chuck — a spare chuck designed for holding drill bits."),
    "replacement_blade": (400, "Replacement Blade — a spare blade designed for power tools."),
    "replacement_grinding_wheel": (350, "Replacement Grinding Wheel — a spare abrasive wheel designed for bench grinders."),
    "tool_belts": (700, "Tool Belts — a wearable belt with pouches designed for carrying tools."),
    "carrying_case": (900, "Carrying Case — a protective case designed for transporting tools safely."),
}

paths = ["data/products-placeholder.json", "data/products-placeholder-batch3.json"]

total_updated = 0
total_skipped = []

for path in paths:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    updated = 0
    for sku, prod in data.items():
        if prod.get("categoryId") == "power_tools_hand_tools":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
            else:
                total_skipped.append((path, sku, img))

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"{path}: Updated {updated}")
    total_updated += updated

print(f"Total Updated: {total_updated}")
print(f"Skipped: {total_skipped}")
