import json

price_desc = {
    "vehicles_transportation": (500, "Vehicles & Transportation — a general range of vehicles, parts and transportation accessories."),
    "car_and_motorcycle": (500, "Car & Motorcycle — a general range of car and motorcycle listings."),
    "cars": (800000, "Cars — a general listing category for passenger cars."),
    "sedan": (900000, "Sedan — a traditional three-box passenger car with a separate trunk."),
    "hatchback": (700000, "Hatchback — a compact car with a rear door that opens upward."),
    "suv": (1500000, "SUV — a sport utility vehicle designed for both on-road comfort and off-road capability."),
    "crossover": (1300000, "Crossover — a vehicle blending SUV styling with car-like handling."),
    "coupe": (1200000, "Coupe — a two-door car with a sporty, sloped roofline."),
    "convertible": (2000000, "Convertible — a car with a retractable roof for open-air driving."),
    "wagon": (900000, "Wagon — a car with an extended rear cargo area for extra storage."),
    "pickup_truck": (1800000, "Pickup Truck — a vehicle with an open cargo bed for hauling."),
    "minivan": (1600000, "Minivan — a family vehicle designed for passenger and cargo versatility."),
    "electric_car_ev": (2500000, "Electric Car (EV) — a battery-powered car with zero tailpipe emissions."),
    "hybrid_car": (2000000, "Hybrid Car — a car combining a combustion engine with an electric motor."),
    "luxury_car": (3500000, "Luxury Car — a premium vehicle with high-end features and finishes."),
    "sports_car": (3000000, "Sports Car — a performance-focused car built for speed and handling."),
    "used_car": (600000, "Used Car — a pre-owned vehicle available for resale."),
    "motorcycles_scooters": (100000, "Motorcycles & Scooters — a general listing category for two-wheelers."),
    "motorcycle": (150000, "Motorcycle — a two-wheeled motor vehicle designed for road use."),
    "sport_bike": (250000, "Sport Bike — a high-performance motorcycle built for speed."),
    "cruiser_motorcycle": (300000, "Cruiser Motorcycle — a motorcycle designed for relaxed, long-distance riding."),
    "touring_motorcycle": (400000, "Touring Motorcycle — a motorcycle built for comfort on long journeys."),
    "dirt_bike": (180000, "Dirt Bike — a lightweight motorcycle designed for off-road riding."),
    "scooter": (120000, "Scooter — a small motorbike with step-through design for easy riding."),
    "electric_scooter": (90000, "Electric Scooter — a battery-powered scooter for eco-friendly commuting."),
    "moped": (100000, "Moped — a small, low-powered motorbike suited for city commuting."),
    "three_wheel_scooter": (150000, "Three-Wheel Scooter — a stable three-wheeled scooter for easy riding."),
    "bicycles": (8000, "Bicycles — a general listing category for pedal-powered bikes."),
    "mountain_bike": (18000, "Mountain Bike — a bike built with rugged tires and suspension for off-road trails."),
    "road_bike": (25000, "Road Bike — a lightweight bike designed for speed on paved roads."),
    "hybrid_bike": (15000, "Hybrid Bike — a bike combining road and mountain bike features for versatile riding."),
    "bmx_bike": (12000, "BMX Bike — a small, sturdy bike designed for tricks and stunts."),
    "folding_bike": (14000, "Folding Bike — a compact bike that folds for easy storage and transport."),
    "electric_bicycle": (45000, "Electric Bicycle — a pedal-assist bike powered by a rechargeable battery."),
    "kids_bicycle": (6000, "Kids Bicycle — a bike sized and designed for children."),
    "balance_bike": (3500, "Balance Bike — a pedal-less bike designed to help children learn balance."),
    "commercial_vehicles": (1200000, "Commercial Vehicles — a general listing category for business-use vehicles."),
    "cargo_van": (1800000, "Cargo Van — a van designed for transporting goods."),
    "delivery_van": (1600000, "Delivery Van — a van optimized for parcel and goods delivery."),
    "mini_truck": (900000, "Mini Truck — a small truck designed for light cargo hauling."),
    "box_truck": (2500000, "Box Truck — a truck with an enclosed cargo box for freight transport."),
    "flatbed_truck": (2200000, "Flatbed Truck — a truck with an open, flat cargo area."),
    "refrigerated_truck": (3500000, "Refrigerated Truck — a truck fitted with cooling equipment for perishable goods."),
    "bus": (3500000, "Bus — a large passenger vehicle for public or private transport."),
    "minibus": (2200000, "Minibus — a smaller bus designed for moderate passenger capacity."),
    "coach_bus": (5000000, "Coach Bus — a large bus designed for long-distance passenger travel."),
    "agricultural_vehicles": (800000, "Agricultural Vehicles — a general listing category for farm machinery vehicles."),
    "tractor": (1200000, "Tractor — a heavy vehicle designed for agricultural fieldwork."),
    "power_tiller": (150000, "Power Tiller — a walk-behind machine used to till farmland."),
    "farm_trailer": (200000, "Farm Trailer — a towable trailer designed for transporting farm produce."),
    "atv_all_terrain_vehicle": (500000, "ATV (All-Terrain Vehicle) — a small off-road vehicle designed for rugged terrain."),
    "utility_vehicle_utv": (700000, "Utility Vehicle (UTV) — a side-by-side vehicle designed for utility and off-road work."),
    "recreational_vehicles": (2500000, "Recreational Vehicles — a general listing category for leisure and travel vehicles."),
    "motorhome": (5000000, "Motorhome — a self-contained vehicle equipped for living while traveling."),
    "camper_van": (3000000, "Camper Van — a van converted for camping and travel accommodation."),
    "travel_trailer": (2000000, "Travel Trailer — a towable trailer equipped for travel and camping."),
    "caravan": (1800000, "Caravan — a towable living unit designed for travel and camping."),
    "golf_cart": (350000, "Golf Cart — a small electric or gas vehicle designed for golf courses and short trips."),
    "marine_vehicles": (300000, "Marine Vehicles — a general listing category for boats and watercraft."),
    "fishing_boat": (400000, "Fishing Boat — a boat designed for recreational or commercial fishing."),
    "speed_boat": (900000, "Speed Boat — a fast boat designed for recreational water sport."),
    "inflatable_boat": (150000, "Inflatable Boat — a lightweight, portable boat made of durable inflatable material."),
    "kayak": (25000, "Kayak — a narrow, paddle-powered boat designed for one or two people."),
    "canoe": (30000, "Canoe — an open, paddle-powered boat designed for calm water travel."),
    "jet_ski": (700000, "Jet Ski — a personal watercraft designed for recreational riding."),
    "yacht": (5000000, "Yacht — a luxury boat designed for cruising and recreation."),
    "boat_trailer": (150000, "Boat Trailer — a towable trailer designed for transporting boats."),
    "vehicle_parts": (500, "Vehicle Parts — a general range of replacement and upgrade parts for vehicles."),
    "engine_parts": (2000, "Engine Parts — a general range of components used in vehicle engines."),
    "engine": (150000, "Engine — a complete engine unit designed for vehicle installation."),
    "engine_oil": (700, "Engine Oil — a lubricant designed to protect and maintain engine performance."),
    "oil_filter": (350, "Oil Filter — a filter designed to remove contaminants from engine oil."),
    "air_filter": (400, "Air Filter — a filter designed to keep debris out of the engine's air intake."),
    "fuel_filter": (450, "Fuel Filter — a filter designed to remove impurities from fuel before combustion."),
    "spark_plug": (250, "Spark Plug — a component that ignites the fuel-air mixture in an engine."),
    "timing_belt": (1500, "Timing Belt — a belt that synchronizes engine valve and piston timing."),
    "drive_belt": (800, "Drive Belt — a belt that powers auxiliary engine components."),
    "radiator": (4500, "Radiator — a component that cools the engine by dissipating heat."),
    "water_pump": (2500, "Water Pump — a pump that circulates coolant through the engine."),
    "fuel_pump": (3500, "Fuel Pump — a pump that delivers fuel from the tank to the engine."),
    "turbocharger": (25000, "Turbocharger — a device that boosts engine power using exhaust gases."),
    "battery": (5500, "Battery — a rechargeable battery designed to start and power a vehicle."),
    "brake_parts": (1500, "Brake Parts — a general range of components used in vehicle braking systems."),
    "brake_pads": (1200, "Brake Pads — friction pads that press against the rotor to slow a vehicle."),
    "brake_disc": (2500, "Brake Disc — a rotor that the brake pads clamp against to slow a vehicle."),
    "brake_drum": (2200, "Brake Drum — a cylindrical component used in drum brake systems."),
    "brake_caliper": (3500, "Brake Caliper — a component that houses the brake pads and clamps the rotor."),
    "brake_fluid": (500, "Brake Fluid — a hydraulic fluid used to transfer force in the braking system."),
    "abs_sensor": (1800, "ABS Sensor — a sensor that monitors wheel speed for the anti-lock braking system."),
    "suspension_steering": (2500, "Suspension & Steering — a general range of parts for vehicle suspension and steering."),
    "shock_absorber": (3500, "Shock Absorber — a component that dampens suspension movement for a smoother ride."),
    "strut": (4500, "Strut — a structural suspension component combining a shock absorber and spring."),
    "coil_spring": (2500, "Coil Spring — a spring that supports the vehicle's weight and absorbs road shocks."),
    "control_arm": (3000, "Control Arm — a suspension component that connects the wheel hub to the frame."),
    "ball_joint": (1200, "Ball Joint — a pivoting joint that connects suspension components."),
    "tie_rod": (900, "Tie Rod — a steering component that connects the steering rack to the wheel."),
    "steering_rack": (12000, "Steering Rack — a component that translates steering wheel input into wheel movement."),
    "transmission": (80000, "Transmission — a component that transfers engine power to the wheels."),
    "clutch_kit": (8000, "Clutch Kit — a set of components used to engage and disengage engine power."),
    "flywheel": (5500, "Flywheel — a rotating component that stores and smooths engine rotational energy."),
    "gearbox": (60000, "Gearbox — a unit that manages gear ratios for power transfer."),
    "transmission_fluid": (700, "Transmission Fluid — a lubricant designed for smooth gear shifting."),
    "cv_joint": (2500, "CV Joint — a joint that allows power transfer at a variable angle."),
    "drive_shaft": (8000, "Drive Shaft — a shaft that transmits torque from the transmission to the wheels."),
    "wheels_tires": (2500, "Wheels & Tires — a general range of wheels and tires for vehicles."),
    "car_tire": (5500, "Car Tire — a rubber tire designed for passenger vehicles."),
    "alloy_wheel": (8000, "Alloy Wheel — a lightweight wheel made from an alloy of aluminum or magnesium."),
    "steel_wheel": (3500, "Steel Wheel — a durable, budget-friendly wheel made of steel."),
    "wheel_cover": (900, "Wheel Cover — a decorative cover designed to fit over a steel wheel."),
    "tire_valve": (100, "Tire Valve — a small valve used to inflate and seal a tire."),
    "tire_repair_kit": (700, "Tire Repair Kit — a kit designed to patch and repair a punctured tire."),
    "spare_tire": (4500, "Spare Tire — a backup tire kept for emergency use."),
    "vehicle_accessories": (500, "Vehicle Accessories — a general range of accessories for vehicles."),
    "seat_cover": (1500, "Seat Cover — a protective cover designed to fit over vehicle seats."),
    "floor_mat": (1200, "Floor Mat — a protective mat designed for a vehicle's floor."),
    "steering_wheel_cover": (500, "Steering Wheel Cover — a grip cover designed to fit over a steering wheel."),
    "sunshade": (400, "Sunshade — a reflective shade designed to block sunlight through a windshield."),
    "car_cover": (2500, "Car Cover — a protective cover designed to shield a parked car."),
    "roof_rack": (4500, "Roof Rack — a rack mounted on a vehicle roof for extra cargo capacity."),
    "roof_box": (8000, "Roof Box — an enclosed storage box mounted on a vehicle's roof."),
    "phone_holder": (400, "Phone Holder — a mount designed to hold a phone securely in a vehicle."),
    "car_organizer": (700, "Car Organizer — a storage accessory designed to keep a car's interior tidy."),
    "trunk_organizer": (900, "Trunk Organizer — a storage accessory designed to organize a car's trunk space."),
    "dash_camera": (3500, "Dash Camera — a camera mounted on a dashboard to record while driving."),
    "reverse_camera": (2500, "Reverse Camera — a camera that assists with visibility while reversing."),
    "parking_sensor": (2200, "Parking Sensor — a sensor system that alerts drivers to nearby obstacles while parking."),
    "gps_navigation": (4500, "GPS Navigation — a device that provides turn-by-turn driving directions."),
    "car_charger": (400, "Car Charger — a charging adapter designed for a vehicle's power outlet."),
    "usb_charger": (350, "USB Charger — a charging adapter with USB ports for in-car use."),
    "jump_starter": (3500, "Jump Starter — a portable device used to start a vehicle with a dead battery."),
    "lighting": (500, "Lighting — a general range of vehicle lighting products."),
    "led_headlight": (2500, "LED Headlight — a bright, energy-efficient headlight bulb."),
    "headlight_bulb": (700, "Headlight Bulb — a replacement bulb designed for vehicle headlights."),
    "fog_light": (1500, "Fog Light — a light designed to improve visibility in foggy conditions."),
    "tail_light": (1800, "Tail Light — a rear light designed for vehicle visibility and signaling."),
    "indicator_light": (500, "Indicator Light — a light used to signal a vehicle's turning direction."),
    "interior_led_light": (600, "Interior LED Light — an LED light strip designed for a vehicle's interior."),
    "light_bar": (3500, "Light Bar — a bar of powerful lights mounted for extra illumination."),
    "audio_electronics": (2000, "Audio & Electronics — a general range of vehicle audio and electronic accessories."),
    "car_stereo": (4500, "Car Stereo — an audio head unit designed for a vehicle's sound system."),
    "android_car_display": (8500, "Android Car Display — a touchscreen infotainment unit running Android."),
    "car_speaker": (2500, "Car Speaker — a speaker designed for a vehicle's audio system."),
    "amplifier": (4500, "Amplifier — a device that boosts audio signal power for a car sound system."),
    "subwoofer": (5500, "Subwoofer — a speaker designed to reproduce deep bass frequencies."),
    "fm_transmitter": (700, "FM Transmitter — a device that broadcasts audio to a car radio via FM signal."),
    "gps_tracker": (2500, "GPS Tracker — a device used to monitor a vehicle's real-time location."),
    "obd_ii_scanner": (2200, "OBD-II Scanner — a diagnostic tool used to read a vehicle's engine codes."),
    "motorcycle_accessories": (500, "Motorcycle Accessories — a general range of accessories for motorcycles."),
    "motorcycle_helmet": (2500, "Motorcycle Helmet — a protective helmet designed for motorcycle riders."),
    "riding_jacket": (3500, "Riding Jacket — a protective jacket designed for motorcycle riders."),
    "riding_gloves": (1200, "Riding Gloves — protective gloves designed for motorcycle riders."),
    "riding_boots": (2800, "Riding Boots — protective boots designed for motorcycle riders."),
    "motorcycle_cover": (1500, "Motorcycle Cover — a protective cover designed to shield a parked motorcycle."),
    "top_box": (3500, "Top Box — a storage case mounted on the rear of a motorcycle."),
    "side_box": (3200, "Side Box — a storage case mounted on the side of a motorcycle."),
    "tank_bag": (1800, "Tank Bag — a storage bag designed to mount on a motorcycle's fuel tank."),
    "motorcycle_lock": (900, "Motorcycle Lock — a security lock designed to prevent motorcycle theft."),
    "bicycle_accessories": (400, "Bicycle Accessories — a general range of accessories for bicycles."),
    "bicycle_helmet": (1200, "Bicycle Helmet — a protective helmet designed for cyclists."),
    "bike_pump": (600, "Bike Pump — a pump designed to inflate bicycle tires."),
    "bike_lock": (700, "Bike Lock — a security lock designed to prevent bicycle theft."),
    "water_bottle_cage": (300, "Water Bottle Cage — a mount designed to hold a water bottle on a bike frame."),
    "bicycle_lights": (500, "Bicycle Lights — lights designed to improve a cyclist's visibility."),
    "cycling_computer": (2500, "Cycling Computer — a device that tracks speed, distance and other ride metrics."),
    "bike_repair_kit": (900, "Bike Repair Kit — a kit of tools designed for basic bicycle repairs."),
    "mudguard": (500, "Mudguard — a fender designed to block mud and water splashes from wheels."),
    "bicycle_bell": (200, "Bicycle Bell — a small bell used to alert others while cycling."),
    "tools_maintenance": (500, "Tools & Maintenance — a general range of tools for vehicle maintenance."),
    "car_jack": (2500, "Car Jack — a tool used to lift a vehicle for maintenance or tire changes."),
    "jack_stand": (1800, "Jack Stand — a support stand used to hold a lifted vehicle securely."),
    "torque_wrench": (2500, "Torque Wrench — a wrench designed to apply a precise amount of tightening force."),
    "wheel_wrench": (700, "Wheel Wrench — a wrench designed to loosen and tighten wheel lug nuts."),
    "air_compressor": (5500, "Air Compressor — a device used to inflate tires and power pneumatic tools."),
    "tire_inflator": (1800, "Tire Inflator — a portable device used to inflate vehicle tires."),
    "pressure_washer": (6500, "Pressure Washer — a device that sprays high-pressure water for vehicle cleaning."),
    "car_wash_kit": (900, "Car Wash Kit — a set of supplies designed for washing a vehicle."),
    "car_vacuum_cleaner": (2200, "Car Vacuum Cleaner — a portable vacuum designed for cleaning a vehicle's interior."),
    "microfiber_cloth": (200, "Microfiber Cloth — a soft cloth designed for streak-free vehicle cleaning."),
    "polish_wax": (700, "Polish & Wax — a product used to protect and shine a vehicle's paint."),
    "safety_equipment": (700, "Safety Equipment — a general range of vehicle safety products."),
    "first_aid_kit": (900, "First Aid Kit — a compact kit of essential supplies for vehicle emergencies."),
    "fire_extinguisher": (1500, "Fire Extinguisher — a portable device used to put out small vehicle fires."),
    "reflective_triangle": (500, "Reflective Triangle — a warning sign used to alert other drivers of a stopped vehicle."),
    "tow_rope": (700, "Tow Rope — a strong rope used to tow a disabled vehicle."),
    "emergency_toolkit": (1500, "Emergency Toolkit — a compact kit of tools for roadside emergencies."),
    "safety_vest": (350, "Safety Vest — a high-visibility vest used for roadside safety."),
    "tire_pressure_gauge": (300, "Tire Pressure Gauge — a tool used to measure a tire's air pressure."),
    "ev_charging": (2000, "EV Charging — a general range of electric vehicle charging equipment."),
    "ev_charger": (35000, "EV Charger — a device used to recharge an electric vehicle's battery."),
    "home_charging_station": (55000, "Home Charging Station — a dedicated charging unit installed for home EV charging."),
    "portable_ev_charger": (25000, "Portable EV Charger — a compact, mobile charger for electric vehicles."),
    "ev_charging_cable": (5500, "EV Charging Cable — a cable designed to connect an EV to a charging point."),
    "ev_adapter": (3500, "EV Adapter — an adapter designed to connect different EV charging plug types."),
    "fuel_fluids": (500, "Fuel & Fluids — a general range of fluids and additives for vehicles."),
    "transmission_oil": (700, "Transmission Oil — a lubricant designed for a vehicle's transmission system."),
    "coolant": (500, "Coolant — a fluid used to regulate engine temperature."),
    "power_steering_fluid": (450, "Power Steering Fluid — a hydraulic fluid used in power steering systems."),
    "windshield_washer_fluid": (250, "Windshield Washer Fluid — a fluid used to clean a vehicle's windshield."),
    "fuel_additive": (350, "Fuel Additive — a product added to fuel to improve engine performance."),
    "travel_accessories": (700, "Travel Accessories — a general range of accessories for vehicle travel."),
    "luggage_carrier": (3500, "Luggage Carrier — a rack or box designed to carry extra luggage on a vehicle."),
    "bike_carrier": (4500, "Bike Carrier — a rack designed to transport bicycles on a vehicle."),
    "child_car_seat": (5500, "Child Car Seat — a safety seat designed to protect children while traveling by car."),
    "pet_car_seat": (2200, "Pet Car Seat — a safety seat designed to secure a pet while traveling by car."),
    "travel_cooler": (1800, "Travel Cooler — a portable cooler designed for keeping items cold during travel."),
    "portable_refrigerator": (12000, "Portable Refrigerator — a compact fridge designed for use in a vehicle."),
    "garage_equipment": (2500, "Garage Equipment — a general range of equipment used in a vehicle garage."),
    "tool_chest": (8500, "Tool Chest — a storage cabinet designed to organize garage tools."),
    "workbench": (9500, "Workbench — a sturdy table designed for vehicle repair and maintenance work."),
    "creeper": (2500, "Creeper — a low, wheeled platform used to slide under a vehicle for repairs."),
    "hydraulic_lift": (45000, "Hydraulic Lift — a lift used to raise a vehicle for undercarriage repairs."),
    "engine_hoist": (18000, "Engine Hoist — a hoist used to lift an engine out of a vehicle."),
    "battery_charger": (2500, "Battery Charger — a device used to recharge a vehicle's battery."),
}

paths = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch3.json",
]

target_id = "vehicles_transportation"
total_updated = 0

for path in paths:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    updated = 0
    skipped = []
    for sku, prod in data.items():
        if prod.get("categoryId") == target_id:
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
            else:
                skipped.append((sku, img))

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"--- {path}: Updated {updated}, Skipped {skipped} ---")
    total_updated += updated

print(f"TOTAL Updated: {total_updated}")
