import json

price_desc = {
    "2_axis_gimbal": (8500, "2-Axis Gimbal — a stabilization mount used to smooth footage across two rotational axes."),
    "360_action_camera": (25000, "360 Action Camera — an action camera capable of capturing full spherical footage."),
    "3_axis_gimbal": (12000, "3-Axis Gimbal — a stabilization mount used to smooth footage across three rotational axes."),
    "4k_action_camera": (18000, "4K Action Camera — a rugged camera capable of capturing ultra-high-definition footage."),
    "4k_drone_camera": (25000, "4K Drone Camera — a camera module designed to capture ultra-high-definition aerial footage."),
    "5k_action_camera": (25000, "5K Action Camera — a rugged camera capable of capturing extremely high-resolution footage."),
    "8k_drone_camera": (55000, "8K Drone Camera — a camera module designed for ultra-high-resolution aerial footage."),
    "action_camera_accessories": (700, "Action Camera Accessories — a general range of accessories for action cameras."),
    "action_camera_power_storage": (900, "Action Camera Power & Storage — a general range of batteries and storage products for action cameras."),
    "action_cameras": (18000, "Action Cameras — compact, durable cameras designed for capturing adventure footage."),
    "agricultural_drone": (350000, "Agricultural Drone — a drone designed for crop monitoring and precision farming."),
    "air_blower": (450, "Air Blower — a tool used to remove dust from camera sensors and lenses."),
    "anti_fog_inserts": (350, "Anti-Fog Inserts — inserts used to prevent lens fogging in action cameras."),
    "audio_lighting": (2500, "Audio & Lighting — a general range of audio and lighting accessories for content creation."),
    "backpack": (2500, "Backpack — a padded backpack designed to carry drones and camera equipment."),
    "battery_charging_hub": (2500, "Battery Charging Hub — a device used to charge multiple drone batteries simultaneously."),
    "beginner_drone": (8500, "Beginner Drone — an easy-to-fly drone designed for new pilots."),
    "bike_camera": (5500, "Bike Camera — a compact camera designed for mounting on a bicycle."),
    "bike_handlebar_mount": (700, "Bike Handlebar Mount — a mount used to attach a camera to a bike handlebar."),
    "body_camera": (5500, "Body Camera — a wearable camera used for personal recording."),
    "brushless_motor": (1800, "Brushless Motor — a motor used in drones for efficient, durable propulsion."),
    "camera_drone": (35000, "Camera Drone — an unmanned aerial vehicle equipped with a camera for aerial photography."),
    "camera_mount": (700, "Camera Mount — an accessory used to attach a camera to various surfaces."),
    "car_mount": (700, "Car Mount — a mount used to secure a camera inside a vehicle."),
    "card_reader": (700, "Card Reader — a device used to transfer files from memory cards to a computer."),
    "carrying_case": (1800, "Carrying Case — a protective case designed for transporting drones and cameras."),
    "charging_dock": (1800, "Charging Dock — a stand used to charge a drone or camera conveniently."),
    "chest_mount": (700, "Chest Mount — a harness used to mount an action camera on the chest."),
    "cleaning_protection": (700, "Cleaning & Protection — a general range of cleaning and protective products for cameras."),
    "clip_mount": (450, "Clip Mount — a clip-on accessory used to attach a camera to clothing or gear."),
    "commercial_drone": (450000, "Commercial Drone — a professional-grade drone designed for business applications."),
    "compass_module": (900, "Compass Module — a navigation component used to help a drone determine orientation."),
    "control_sticks": (450, "Control Sticks — replaceable joystick components used on drone remote controllers."),
    "controller_case": (900, "Controller Case — a protective case designed for a drone's remote controller."),
    "controller_lanyard": (350, "Controller Lanyard — a strap used to secure a drone controller around the neck."),
    "controller_screen_protector": (250, "Controller Screen Protector — a protective film for a drone controller's screen."),
    "cpl_filter": (1500, "CPL Filter — a polarizing filter used to reduce glare and enhance colors."),
    "delivery_drone": (550000, "Delivery Drone — a drone designed for transporting small packages."),
    "drone_accessories": (900, "Drone Accessories — a general range of accessories designed for drones."),
    "drone_and_action_camera": (18000, "Drone & Action Camera — a general range of aerial and action camera products."),
    "drone_arms": (1500, "Drone Arms — structural components that support a drone's motors and propellers."),
    "drone_battery": (5500, "Drone Battery — a rechargeable battery designed to power camera drones."),
    "drone_camera": (12000, "Drone Camera — a camera module designed for capturing aerial footage."),
    "drone_cameras_gimbals": (12000, "Drone Cameras & Gimbals — a general range of drone camera and stabilization products."),
    "drone_charger": (1800, "Drone Charger — a device used to recharge drone batteries."),
    "drone_controllers": (5500, "Drone Controllers — remote devices used to operate and pilot drones."),
    "drone_frame": (3500, "Drone Frame — the structural chassis that houses a drone's components."),
    "drone_maintenance_tools": (900, "Drone Maintenance Tools — a set of tools used for drone upkeep and repair."),
    "drone_parts": (900, "Drone Parts — a general range of replacement components for drones."),
    "drone_simulator": (2500, "Drone Simulator — software used to practice drone flying in a virtual environment."),
    "drone_skin": (900, "Drone Skin — a decorative protective wrap designed for drone bodies."),
    "drones": (35000, "Drones — a general range of unmanned aerial vehicles."),
    "drones_action_cameras": (5000, "Drones & Action Cameras — a general range of aerial and action camera products."),
    "drones_action_cameras1": (5000, "Drones & Action Cameras — a general range of aerial and action camera products."),
    "dual_battery_charger": (2500, "Dual Battery Charger — a charger capable of charging two drone batteries at once."),
    "esc_electronic_speed_controller": (1800, "ESC (Electronic Speed Controller) — a component that regulates a drone motor's speed."),
    "extension_pole": (900, "Extension Pole — a pole used to extend the reach of an action camera."),
    "external_microphone": (2500, "External Microphone — an add-on microphone used to improve action camera audio."),
    "fill_light": (2500, "Fill Light — a lighting accessory used to add supplementary illumination for video."),
    "flexible_tripod": (1500, "Flexible Tripod — a bendable tripod designed for versatile camera positioning."),
    "flight_controller": (5500, "Flight Controller — the central component that manages a drone's flight stability."),
    "flight_controller_board": (5500, "Flight Controller Board — the circuit board that manages a drone's flight operations."),
    "floating_handle_grip": (900, "Floating Handle Grip — a buoyant grip used to prevent an action camera from sinking in water."),
    "foldable_drone": (25000, "Foldable Drone — a drone designed to fold compactly for easy transport."),
    "fpv_antenna": (900, "FPV Antenna — an antenna used to transmit first-person-view video from a drone."),
    "fpv_camera": (2500, "FPV Camera — a lightweight camera used to provide first-person-view drone footage."),
    "fpv_drone": (35000, "FPV Drone — a drone designed for first-person-view immersive flying."),
    "fpv_equipment": (5500, "FPV Equipment — a general range of first-person-view flying gear."),
    "fpv_esc": (1800, "FPV ESC — an electronic speed controller designed for FPV racing drones."),
    "fpv_frame": (2500, "FPV Frame — a lightweight structural frame designed for FPV racing drones."),
    "fpv_goggles": (12000, "FPV Goggles — a headset used to view live first-person drone footage."),
    "fpv_monitor": (5500, "FPV Monitor — a display screen used to view live first-person drone footage."),
    "fpv_motors": (1800, "FPV Motors — high-speed motors designed for FPV racing drones."),
    "fpv_remote_controller": (5500, "FPV Remote Controller — a controller designed for flying FPV drones."),
    "gimbal_camera": (8500, "Gimbal Camera — a camera integrated with a stabilizing gimbal mount."),
    "gimbal_protector": (700, "Gimbal Protector — a protective cover designed to shield a drone's gimbal."),
    "gps_module": (2500, "GPS Module — a navigation component used to enable a drone's positioning system."),
    "gps_tracker": (2800, "GPS Tracker — a device used to monitor the real-time location of a drone."),
    "hard_carrying_case": (3500, "Hard Carrying Case — a rigid protective case designed for transporting drones."),
    "hard_case": (2500, "Hard Case — a rigid protective case designed for cameras and accessories."),
    "head_strap_mount": (700, "Head Strap Mount — a wearable strap used to mount an action camera on the head."),
    "helmet_camera": (5500, "Helmet Camera — a camera designed to mount on a helmet for hands-free recording."),
    "helmet_mount": (700, "Helmet Mount — a mount used to attach an action camera to a helmet."),
    "industrial_drone": (650000, "Industrial Drone — a heavy-duty drone designed for industrial inspection and use."),
    "inspection_drone": (450000, "Inspection Drone — a drone designed for infrastructure and equipment inspection."),
    "intelligent_flight_battery": (8500, "Intelligent Flight Battery — a smart battery designed with monitoring features for drones."),
    "landing_gear": (1500, "Landing Gear — structural legs used to support a drone during takeoff and landing."),
    "landing_pad": (900, "Landing Pad — a portable mat used to provide a clean surface for drone landings."),
    "led_video_light": (3500, "LED Video Light — a lighting panel used to illuminate video shoots."),
    "lens_cleaning_cloth": (150, "Lens Cleaning Cloth — a soft cloth used to clean camera lenses."),
    "lens_cleaning_kit": (900, "Lens Cleaning Kit — a set of tools used to clean lenses and camera bodies."),
    "lens_protector": (450, "Lens Protector — a protective cover designed to shield a camera lens."),
    "magnetic_mount": (700, "Magnetic Mount — a mount that uses magnets to securely attach a camera."),
    "mapping_drone": (550000, "Mapping Drone — a drone designed for aerial surveying and mapping."),
    "memory_card_wallet": (450, "Memory Card Wallet — a compact case used to organize and protect memory cards."),
    "microsd_card": (900, "MicroSD Card — a compact memory card used in drones and action cameras."),
    "mini_drone": (5500, "Mini Drone — a compact, lightweight drone designed for casual flying."),
    "mini_tripod": (900, "Mini Tripod — a compact tripod designed for portable camera support."),
    "motor_guards": (900, "Motor Guards — protective covers used to shield a drone's motors."),
    "motorcycle_camera": (5500, "Motorcycle Camera — a camera designed for mounting on a motorcycle."),
    "multispectral_camera": (185000, "Multispectral Camera — a specialized camera used for agricultural and scientific imaging."),
    "nd_filter_set": (2500, "ND Filter Set — a set of neutral density filters used to control exposure."),
    "organizer_bag": (1200, "Organizer Bag — a bag used to organize drone and camera accessories."),
    "photography_drone": (35000, "Photography Drone — a drone optimized for capturing aerial photographs."),
    "power_bank": (2500, "Power Bank — a portable battery pack used to charge drones and cameras."),
    "professional_drone": (250000, "Professional Drone — a high-performance drone designed for professional use."),
    "propeller_guards": (900, "Propeller Guards — protective rings used to shield a drone's propellers."),
    "propeller_removal_tool": (250, "Propeller Removal Tool — a tool used to safely remove drone propellers."),
    "propeller_set": (900, "Propeller Set — a replacement set of propellers designed for drones."),
    "propellers": (450, "Propellers — rotating blades that generate lift and thrust for a drone."),
    "protective_case": (1800, "Protective Case — a case designed to shield a drone or camera from damage."),
    "protective_frame": (900, "Protective Frame — a frame used to add impact resistance to a drone."),
    "quick_release_mount": (700, "Quick Release Mount — a mount that allows fast attachment and removal of a camera."),
    "racing_drone": (25000, "Racing Drone — a high-speed drone designed for competitive FPV racing."),
    "rechargeable_battery": (900, "Rechargeable Battery — a reusable battery designed for drones and cameras."),
    "recovery_float_kit": (900, "Recovery Float Kit — a floatation accessory used to recover a drone from water."),
    "remote_controller": (5500, "Remote Controller — a handheld device used to pilot a drone."),
    "repair_tool_kit": (900, "Repair Tool Kit — a set of tools used for drone maintenance and repair."),
    "screen_protector": (350, "Screen Protector — a protective film applied to a device's display."),
    "screwdriver_set": (450, "Screwdriver Set — a set of tools used for drone assembly and repair."),
    "sd_card": (900, "SD Card — a memory card used to store photos and videos in cameras and drones."),
    "selfie_stick": (700, "Selfie Stick — an extendable rod used to take photos and video from a wider angle."),
    "shoulder_bag": (1800, "Shoulder Bag — a bag designed to carry drones and camera equipment."),
    "signal_booster": (2500, "Signal Booster — a device used to strengthen a drone's remote control signal."),
    "silicone_cover": (450, "Silicone Cover — a protective silicone case designed for drones or cameras."),
    "smart_controller": (18000, "Smart Controller — an advanced remote controller with an integrated display."),
    "software_accessories": (900, "Software & Accessories — a general range of software tools for drone operation."),
    "soldering_kit": (1800, "Soldering Kit — a set of tools used for electronic soldering work."),
    "spare_screws": (150, "Spare Screws — replacement screws used for drone maintenance and repair."),
    "sports_camera": (18000, "Sports Camera — a rugged camera designed for capturing action and sports footage."),
    "suction_cup_mount": (700, "Suction Cup Mount — a mount that uses suction to attach a camera to smooth surfaces."),
    "sun_hood": (450, "Sun Hood — an attachment used to shield a screen or lens from sun glare."),
    "survey_drone": (450000, "Survey Drone — a drone designed for land and construction site surveying."),
    "thermal_camera": (85000, "Thermal Camera — a camera used to capture heat signatures for inspection or research."),
    "travel_case": (2500, "Travel Case — a protective case designed for transporting drones and camera gear."),
    "travel_storage": (900, "Travel Storage — a general range of storage solutions for drone and camera travel."),
    "tripod_mount": (700, "Tripod Mount — an adapter used to attach a camera to a tripod."),
    "tweezers": (150, "Tweezers — a precision tool used for handling small drone components."),
    "underwater_drone": (150000, "Underwater Drone — a submersible drone designed for underwater exploration."),
    "usb_charger": (450, "USB Charger — a charging adapter used to power drone and camera batteries."),
    "usb_charging_cable": (350, "USB Charging Cable — a cable used to charge drone and camera batteries."),
    "uv_filter": (900, "UV Filter — a protective lens filter used to reduce UV haze and shield the lens."),
    "video_receiver_vrx": (3500, "Video Receiver (VRx) — a device used to receive live video feed from an FPV drone."),
    "video_transmitter_vtx": (3500, "Video Transmitter (VTx) — a device used to transmit live video feed from an FPV drone."),
    "videography_drone": (55000, "Videography Drone — a drone optimized for capturing high-quality aerial video."),
    "waterproof_action_camera": (18000, "Waterproof Action Camera — a rugged camera designed for underwater recording."),
    "waterproof_backpack": (3500, "Waterproof Backpack — a water-resistant backpack designed to protect drone gear."),
    "waterproof_housing": (2500, "Waterproof Housing — a protective case designed to make a camera water-resistant."),
    "wearable_camera": (5500, "Wearable Camera — a compact camera designed to be worn for hands-free recording."),
    "windshield_deadcat": (700, "Windshield (Deadcat) — a wind protection cover used on microphones for outdoor recording."),
    "wireless_microphone": (5500, "Wireless Microphone — a microphone system that transmits audio without cables."),
    "wrist_strap_mount": (450, "Wrist Strap Mount — a strap used to mount an action camera on the wrist."),
}

path = "data/products-placeholder.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
skipped = []
for sku, prod in data.items():
    if prod.get("categoryId") == "drones_action_cameras":
        img = prod["images"]["main"].split("/")[-1].replace(".png", "")
        if img in price_desc:
            price, desc = price_desc[img]
            title = " ".join(w.capitalize() for w in img.split("_"))
            prod["title"] = title
            prod["price"] = price
            prod["description"] = desc
            prod["status"] = "active"
            updated += 1
        else:
            skipped.append((sku, img))

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
