import json

price_desc = {
    "acne_treatment_gel": (350, "Acne Treatment Gel — a targeted gel formulated to reduce breakouts and blemishes."),
    "aftershave_lotion": (350, "Aftershave Lotion — a soothing lotion applied after shaving to calm the skin."),
    "aloe_vera_gel": (250, "Aloe Vera Gel — a soothing gel used to hydrate and calm skin."),
    "anti_dandruff_shampoo": (350, "Anti-Dandruff Shampoo — a medicated shampoo formulated to reduce dandruff and scalp flaking."),
    "antiperspirant": (350, "Antiperspirant — a personal care product that reduces sweating and controls odor."),
    "argan_oil": (600, "Argan Oil — a nourishing oil used for hair and skin conditioning."),
    "aroma_diffuser_oil": (450, "Aroma Diffuser Oil — a scented oil used with diffusers to fragrance a room."),
    "baby_lotion": (300, "Baby Lotion — a gentle moisturizing lotion formulated for baby skin."),
    "baby_oil": (250, "Baby Oil — a gentle moisturizing oil formulated for infant skin."),
    "baby_powder": (200, "Baby Powder — a talc or cornstarch-based powder used to keep baby skin dry."),
    "baby_shampoo": (300, "Baby Shampoo — a tear-free shampoo formulated for infant hair and scalp."),
    "baby_soap": (200, "Baby Soap — a mild soap formulated for gentle infant skin cleansing."),
    "baby_wipes": (250, "Baby Wipes — gentle, pre-moistened wipes for cleaning an infant's skin."),
    "base_coat": (250, "Base Coat — a protective nail polish layer applied before color polish."),
    "bath_bomb": (300, "Bath Bomb — a fizzing bath product that releases fragrance and moisturizing oils."),
    "bath_gift_set": (1800, "Bath Gift Set — a curated set of bath products, ideal for gifting."),
    "bath_salt": (350, "Bath Salt — a mineral salt blend used to relax muscles in a warm bath."),
    "bath_soap": (150, "Bath Soap — a cleansing bar soap used for everyday bathing."),
    "bb_cream": (450, "BB Cream — a lightweight cream that combines skincare and light coverage."),
    "beard_balm": (450, "Beard Balm — a conditioning balm used to soften and style facial hair."),
    "beard_comb": (250, "Beard Comb — a comb designed for grooming and styling facial hair."),
    "beard_oil": (450, "Beard Oil — a nourishing oil used to condition and soften facial hair."),
    "beard_shampoo": (400, "Beard Shampoo — a cleansing shampoo formulated for facial hair care."),
    "beard_trimmer": (1800, "Beard Trimmer — an electric grooming tool used to trim and shape facial hair."),
    "beauty_personal_care": (300, "Beauty & Personal Care — a general range of beauty and personal care products."),
    "blackhead_remover": (250, "Blackhead Remover — a tool used to gently extract blackheads from the skin."),
    "blush": (450, "Blush — a cosmetic product used to add color to the cheeks."),
    "body_butter": (500, "Body Butter — a rich moisturizing cream used to nourish dry skin."),
    "body_lotion": (350, "Body Lotion — a moisturizing lotion used for everyday skin hydration."),
    "body_mist": (400, "Body Mist — a lightly scented spray used to refresh and fragrance the skin."),
    "body_oil": (450, "Body Oil — a nourishing oil used to moisturize and soften the skin."),
    "body_scrub": (450, "Body Scrub — an exfoliating product used to remove dead skin cells."),
    "body_spray": (350, "Body Spray — a fragranced spray used for everyday freshness."),
    "body_wash": (350, "Body Wash — a liquid cleanser used for daily body cleansing."),
    "bronzer": (500, "Bronzer — a cosmetic powder used to add warmth and a sun-kissed look to the skin."),
    "cc_cream": (450, "CC Cream — a color-correcting cream that blends skincare with light coverage."),
    "clay_mask": (400, "Clay Mask — a purifying face mask formulated to draw out impurities."),
    "cleansing_balm": (600, "Cleansing Balm — a balm-to-oil cleanser used to remove makeup and impurities."),
    "cleansing_oil": (500, "Cleansing Oil — an oil-based cleanser used to dissolve makeup and dirt."),
    "coconut_oil": (350, "Coconut Oil — a natural oil used for hair and skin nourishment."),
    "cologne": (900, "Cologne — a lightly scented fragrance for everyday wear."),
    "compact_powder": (450, "Compact Powder — a pressed powder used to set makeup and reduce shine."),
    "concealer": (450, "Concealer — a cosmetic product used to cover blemishes and dark circles."),
    "conditioner": (350, "Conditioner — a hair care product used to soften and detangle hair after shampooing."),
    "contour_stick": (500, "Contour Stick — a cosmetic stick used to sculpt and define facial features."),
    "cosmetic_bag": (450, "Cosmetic Bag — a bag designed to organize and carry makeup and beauty items."),
    "cotton_buds": (100, "Cotton Buds — soft cotton swabs used for gentle personal care."),
    "cotton_pads": (150, "Cotton Pads — soft pads used for applying or removing skincare products."),
    "cuticle_oil": (300, "Cuticle Oil — a nourishing oil used to soften and condition nail cuticles."),
    "cuticle_pusher": (200, "Cuticle Pusher — a manicure tool used to push back cuticles."),
    "day_cream": (500, "Day Cream — a lightweight moisturizer designed for daytime skincare."),
    "dental_floss": (150, "Dental Floss — a thin thread used to clean between teeth."),
    "deodorant": (350, "Deodorant — a personal care product used to control body odor."),
    "diaper_rash_cream": (300, "Diaper Rash Cream — a protective cream used to treat and prevent diaper rash."),
    "dry_shampoo": (500, "Dry Shampoo — a powder or spray used to refresh hair without water."),
    "eau_de_parfum": (1800, "Eau De Parfum — a long-lasting concentrated fragrance."),
    "eau_de_toilette": (1200, "Eau De Toilette — a lighter concentration fragrance suited for daily wear."),
    "electric_shaver": (2500, "Electric Shaver — an electric grooming device used for facial and body hair removal."),
    "electric_toothbrush": (1800, "Electric Toothbrush — a powered toothbrush used for effective daily dental cleaning."),
    "essential_oils": (600, "Essential Oils — concentrated plant oils used in aromatherapy and skincare."),
    "exfoliator": (400, "Exfoliator — a skincare product used to remove dead skin cells and reveal smoother skin."),
    "eye_cream": (600, "Eye Cream — a targeted cream used to hydrate and reduce puffiness around the eyes."),
    "eye_mask": (350, "Eye Mask — a hydrating patch used to soothe and refresh the under-eye area."),
    "eyebrow_gel": (350, "Eyebrow Gel — a cosmetic gel used to shape and set eyebrows."),
    "eyebrow_pencil": (350, "Eyebrow Pencil — a cosmetic pencil used to fill and define eyebrows."),
    "eyelash_curler": (350, "Eyelash Curler — a tool used to curl eyelashes before applying mascara."),
    "eyelash_glue": (250, "Eyelash Glue — an adhesive used to apply false eyelashes."),
    "eyeliner": (400, "Eyeliner — a cosmetic product used to define and accentuate the eyes."),
    "eyeshadow_palette": (900, "Eyeshadow Palette — a set of coordinated eyeshadow colors for eye makeup."),
    "face_cream": (500, "Face Cream — a moisturizing cream formulated for daily facial skincare."),
    "face_mask": (350, "Face Mask — a skincare treatment applied to the face to hydrate or purify skin."),
    "face_primer": (500, "Face Primer — a base makeup product used to smooth skin before foundation."),
    "face_scrub": (400, "Face Scrub — an exfoliating product used to remove dead skin cells from the face."),
    "face_serum": (700, "Face Serum — a concentrated skincare treatment targeting specific skin concerns."),
    "face_wash": (300, "Face Wash — a cleanser used for daily facial cleansing."),
    "facial_cleanser": (350, "Facial Cleanser — a gentle cleansing product used to remove dirt and makeup."),
    "facial_cleansing_brush": (1500, "Facial Cleansing Brush — an electric brush used to deep-clean facial skin."),
    "facial_mist": (400, "Facial Mist — a hydrating spray used to refresh and set makeup."),
    "facial_roller": (700, "Facial Roller — a massage tool used to promote circulation and skin relaxation."),
    "facial_steamer": (2200, "Facial Steamer — a device that uses steam to open pores and cleanse skin."),
    "false_eyelashes": (300, "False Eyelashes — synthetic lashes applied to enhance natural lashes."),
    "foot_cream": (400, "Foot Cream — a moisturizing cream formulated for dry, cracked feet."),
    "foot_scrub": (400, "Foot Scrub — an exfoliating product used to soften and smooth feet."),
    "foundation": (700, "Foundation — a cosmetic base product used to even out skin tone."),
    "gel_nail_polish": (450, "Gel Nail Polish — a long-lasting nail polish cured under UV or LED light."),
    "gua_sha_tool": (500, "Gua Sha Tool — a smooth-edged tool used for facial massage and skin toning."),
    "hair_bleach": (600, "Hair Bleach — a chemical treatment used to lighten hair color."),
    "hair_care_gift_set": (1800, "Hair Care Gift Set — a curated set of hair care essentials, ideal for gifting."),
    "hair_clipper": (2200, "Hair Clipper — an electric tool used for cutting and trimming hair."),
    "hair_color": (450, "Hair Color — a dye product used to change or refresh hair color."),
    "hair_cream": (350, "Hair Cream — a styling cream used to condition and manage hair."),
    "hair_curler": (1800, "Hair Curler — an electric styling tool used to curl hair."),
    "hair_dryer": (2200, "Hair Dryer — an electric appliance used to dry and style hair."),
    "hair_dye": (450, "Hair Dye — a coloring product used to change hair color."),
    "hair_gel": (300, "Hair Gel — a styling product used to hold and shape hair."),
    "hair_growth_serum": (900, "Hair Growth Serum — a treatment formulated to promote healthier hair growth."),
    "hair_mask": (500, "Hair Mask — a deep conditioning treatment used to nourish hair."),
    "hair_mousse": (400, "Hair Mousse — a lightweight styling foam used to add volume and hold."),
    "hair_oil": (350, "Hair Oil — a nourishing oil used to condition and strengthen hair."),
    "hair_serum": (600, "Hair Serum — a lightweight treatment used to smooth and add shine to hair."),
    "hair_spray": (400, "Hair Spray — a styling product used to hold hairstyles in place."),
    "hair_straightener": (2200, "Hair Straightener — an electric styling tool used to straighten hair."),
    "hair_wax": (350, "Hair Wax — a styling product used to define and texture hair."),
    "hand_cream": (350, "Hand Cream — a moisturizing cream formulated for dry hands."),
    "hand_sanitizer": (200, "Hand Sanitizer — an alcohol-based gel used to disinfect hands."),
    "hand_wash": (250, "Hand Wash — a liquid soap used for everyday hand cleansing."),
    "herbal_hair_oil": (400, "Herbal Hair Oil — a natural oil blend used to nourish and strengthen hair."),
    "highlighter": (600, "Highlighter — a cosmetic product used to add a luminous glow to the skin."),
    "hot_air_brush": (2500, "Hot Air Brush — a styling tool that combines a brush and blow-dryer for smooth curls."),
    "hyaluronic_acid_serum": (900, "Hyaluronic Acid Serum — a hydrating serum formulated to plump and moisturize skin."),
    "leave_in_conditioner": (450, "Leave-In Conditioner — a lightweight conditioner left in hair for ongoing hydration."),
    "led_makeup_mirror": (1800, "LED Makeup Mirror — a lighted mirror designed for precise makeup application."),
    "lip_balm": (150, "Lip Balm — a moisturizing product used to soothe and protect lips."),
    "lip_gloss": (350, "Lip Gloss — a cosmetic product used to add shine and color to the lips."),
    "lip_liner": (300, "Lip Liner — a cosmetic pencil used to outline and define the lips."),
    "lip_mask": (400, "Lip Mask — a hydrating treatment used to nourish and repair dry lips."),
    "lip_scrub": (300, "Lip Scrub — an exfoliating product used to smooth and soften lips."),
    "lipstick": (450, "Lipstick — a cosmetic product used to add color to the lips."),
    "liquid_lipstick": (500, "Liquid Lipstick — a long-wearing liquid formula that provides bold lip color."),
    "loose_powder": (450, "Loose Powder — a finely milled powder used to set makeup and control shine."),
    "lotion_bottle_makeup_brush_perfume": (600, "Beauty Accessory Set — a bundled set including a lotion bottle, makeup brush, and perfume."),
    "makeup_brush_set": (900, "Makeup Brush Set — a coordinated set of brushes for makeup application."),
    "makeup_cosmetics": (500, "Makeup Cosmetics — a general assortment of cosmetic makeup products."),
    "makeup_gift_set": (1800, "Makeup Gift Set — a curated set of cosmetics, ideal for gifting."),
    "makeup_mirror": (700, "Makeup Mirror — a mirror designed for applying makeup with clarity."),
    "makeup_remover": (300, "Makeup Remover — a cleansing product used to dissolve and remove makeup."),
    "makeup_sponge": (200, "Makeup Sponge — a blending sponge used for applying foundation and other makeup."),
    "mascara": (450, "Mascara — a cosmetic product used to darken and volumize eyelashes."),
    "moisturizer": (500, "Moisturizer — a hydrating skincare product used for daily skin care."),
    "mouthwash": (250, "Mouthwash — a liquid product used to freshen breath and clean the mouth."),
    "nail_art_kit": (700, "Nail Art Kit — a set of tools and accessories for decorative nail designs."),
    "nail_buffer": (200, "Nail Buffer — a manicure tool used to smooth and shine nails."),
    "nail_clipper": (150, "Nail Clipper — a grooming tool used to trim nails."),
    "nail_file": (100, "Nail File — a tool used to shape and smooth nail edges."),
    "nail_polish": (250, "Nail Polish — a cosmetic lacquer used to color and decorate nails."),
    "nail_polish_remover": (200, "Nail Polish Remover — a solution used to remove nail polish."),
    "nail_stickers": (200, "Nail Stickers — decorative stickers used for nail art designs."),
    "nail_tips": (350, "Nail Tips — artificial nail extensions used for nail enhancement."),
    "night_cream": (600, "Night Cream — a nourishing cream formulated for overnight skin repair."),
    "nose_hair_trimmer": (900, "Nose Hair Trimmer — a small grooming device used to trim nasal hair."),
    "organic_face_wash": (450, "Organic Face Wash — a natural cleanser formulated with organic ingredients."),
    "organic_shampoo": (500, "Organic Shampoo — a natural shampoo formulated with organic ingredients."),
    "organic_soap": (300, "Organic Soap — a natural soap bar formulated with organic ingredients."),
    "peel_off_mask": (350, "Peel-Off Mask — a face mask that hardens and peels away to remove impurities."),
    "perfume": (1800, "Perfume — a fragranced product used for personal scent enhancement."),
    "perfume_gift_set": (2500, "Perfume Gift Set — a curated set of fragrances, ideal for gifting."),
    "retinol_serum": (900, "Retinol Serum — an anti-aging treatment formulated to improve skin texture."),
    "roll_on_perfume": (450, "Roll-On Perfume — a portable fragrance applied directly with a roller ball."),
    "rose_water": (250, "Rose Water — a floral toner used to refresh and hydrate the skin."),
    "scalp_scrub": (450, "Scalp Scrub — an exfoliating treatment used to cleanse and refresh the scalp."),
    "setting_powder": (450, "Setting Powder — a translucent powder used to lock makeup in place."),
    "setting_spray": (500, "Setting Spray — a finishing spray used to extend the wear of makeup."),
    "shampoo": (350, "Shampoo — a hair cleansing product used for everyday washing."),
    "shaving_cream": (300, "Shaving Cream — a lathering cream used to soften hair before shaving."),
    "shaving_gel": (300, "Shaving Gel — a gel formula used to provide a smooth shaving surface."),
    "shea_butter": (450, "Shea Butter — a rich moisturizer used to nourish dry skin and hair."),
    "sheet_mask": (150, "Sheet Mask — a fabric mask soaked in serum used for quick skin hydration."),
    "shower_gel": (350, "Shower Gel — a liquid cleanser used for daily bathing."),
    "skincare_gift_set": (1800, "Skincare Gift Set — a curated set of skincare essentials, ideal for gifting."),
    "spa_gift_set": (2200, "Spa Gift Set — a curated set of relaxation and self-care products."),
    "sunblock": (500, "Sunblock — a protective product used to shield skin from UV rays."),
    "sunscreen": (500, "Sunscreen — a protective lotion used to prevent sun damage to the skin."),
    "talcum_powder": (200, "Talcum Powder — a fine powder used to keep skin dry and fresh."),
    "tea_tree_oil": (350, "Tea Tree Oil — a natural oil known for its purifying skincare properties."),
    "tissue_paper": (150, "Tissue Paper — soft paper used for everyday facial and personal hygiene."),
    "toner": (450, "Toner — a liquid skincare product used to balance and refresh skin after cleansing."),
    "tongue_cleaner": (150, "Tongue Cleaner — a hygiene tool used to clean the surface of the tongue."),
    "toothbrush": (100, "Toothbrush — a dental tool used for everyday teeth cleaning."),
    "toothpaste": (150, "Toothpaste — a dental care product used for cleaning teeth."),
    "top_coat": (250, "Top Coat — a protective nail polish layer applied over color polish for shine."),
    "tweezers": (200, "Tweezers — a precision tool used for plucking hair or handling small items."),
    "uv_nail_lamp": (1500, "UV Nail Lamp — a curing lamp used to set gel nail polish."),
    "vitamin_c_serum": (900, "Vitamin C Serum — a brightening serum formulated to even skin tone."),
    "wax_heater": (1500, "Wax Heater — a device used to melt wax for hair removal treatments."),
    "wet_wipes": (200, "Wet Wipes — pre-moistened wipes used for quick personal hygiene."),
}

path = "data/products-placeholder.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
skipped = []
for sku, prod in data.items():
    if prod.get("categoryId") == "beauty_personal_care":
        img = prod["images"]["main"].split("/")[-1].replace(".png", "")
        if img in price_desc:
            price, desc = price_desc[img]
            title = " ".join(w.capitalize() for w in img.split("_"))
            prod["title"] = title
            prod["price"] = price
            prod["description"] = desc
            prod["status"] = "active"
            updated += 1
        else:
            skipped.append((sku, img))

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
