import json

price_desc = {
    "abs_sensor": (900, "ABS Sensor — detects wheel speed to support the anti-lock braking system."),
    "air_brake_chamber": (3500, "Air Brake Chamber — a component that converts air pressure into braking force for heavy vehicles."),
    "air_compressor": (2500, "Air Compressor — a device used to pressurize air for tires and pneumatic tools."),
    "alloy_wheel": (8500, "Alloy Wheel — a lightweight wheel offering improved styling and performance."),
    "alternator": (4500, "Alternator — charges the battery and powers the electrical system while the engine runs."),
    "android_car_display": (6500, "Android Car Display — a touchscreen infotainment unit running Android for navigation and media."),
    "armrest": (900, "Armrest — a padded support installed in the vehicle cabin for driver and passenger comfort."),
    "automotive_vehicle_parts_accessories": (500, "Automotive, Vehicle Parts & Accessories — a general range of automotive parts and accessories."),
    "axle": (5500, "Axle — a central shaft that supports the wheels and transmits rotational force."),
    "ball_joint": (700, "Ball Joint — a pivoting joint connecting the control arms to the steering knuckles."),
    "battery_charger": (1800, "Battery Charger — a device used to recharge vehicle batteries."),
    "bluetooth_adapter": (600, "Bluetooth Adapter — a plug-in device enabling wireless audio streaming in vehicles."),
    "brake_booster": (3500, "Brake Booster — amplifies pedal force to make braking easier and more effective."),
    "brake_caliper": (2200, "Brake Caliper — houses the brake pads and applies pressure to the brake disc."),
    "brake_disc": (1500, "Brake Disc — a rotating disc that works with brake pads to slow the vehicle."),
    "brake_drum": (1400, "Brake Drum — a cylindrical component used in drum brake systems."),
    "brake_fluid": (350, "Brake Fluid — a hydraulic fluid used to transfer force in the braking system."),
    "brake_hose": (450, "Brake Hose — a flexible line that carries brake fluid to the brake calipers."),
    "brake_master_cylinder": (2800, "Brake Master Cylinder — converts pedal force into hydraulic pressure for braking."),
    "brake_pad": (900, "Brake Pad — a friction component that presses against the brake disc to stop the vehicle."),
    "brake_shoe": (700, "Brake Shoe — a curved friction component used in drum brake systems."),
    "bumper": (4500, "Bumper — a protective panel fitted to the front or rear of a vehicle."),
    "camshaft": (4200, "Camshaft — an engine component that controls the opening and closing of valves."),
    "car_alarm": (1800, "Car Alarm — a security system that alerts the owner of unauthorized vehicle access."),
    "car_battery": (6500, "Car Battery — provides the electrical power needed to start and run a vehicle."),
    "car_cover": (1500, "Car Cover — a protective cover that shields a vehicle from dust and weather."),
    "car_jack": (1200, "Car Jack — a tool used to lift a vehicle for tire changes and repairs."),
    "car_organizer": (500, "Car Organizer — a storage accessory used to keep the vehicle interior tidy."),
    "car_polish": (450, "Car Polish — a compound used to restore shine and protect the vehicle's paint."),
    "car_stereo": (3500, "Car Stereo — an audio system installed in the vehicle dashboard for music playback."),
    "car_tire": (4500, "Car Tire — a rubber tire designed for passenger vehicles."),
    "car_tire_wrench_automotive_accessories": (450, "Car Tire Wrench — a hand tool used to loosen and tighten wheel lug nuts."),
    "car_vacuum_cleaner": (1500, "Car Vacuum Cleaner — a portable vacuum designed for cleaning vehicle interiors."),
    "car_wash_shampoo": (350, "Car Wash Shampoo — a cleaning solution formulated for washing vehicle exteriors."),
    "ceramic_coating_kit": (3500, "Ceramic Coating Kit — a complete set for applying a protective ceramic layer to paint."),
    "cleaning_brush": (200, "Cleaning Brush — a brush used for cleaning vehicle surfaces and interiors."),
    "clutch_kit": (4500, "Clutch Kit — a complete set of components used to replace a vehicle's clutch system."),
    "coil_spring": (2200, "Coil Spring — a suspension component that absorbs road shocks."),
    "control_arm": (2500, "Control Arm — a suspension component that connects the wheel hub to the chassis."),
    "coolant": (450, "Coolant — a fluid used to regulate engine temperature and prevent overheating."),
    "cooling_fan": (1800, "Cooling Fan — a fan that helps regulate engine and radiator temperature."),
    "crankshaft": (7500, "Crankshaft — converts piston movement into rotational force to drive the engine."),
    "cv_joint": (1800, "CV Joint — a joint that allows power transfer at variable angles in the drivetrain."),
    "cylinder_head": (8500, "Cylinder Head — an engine component that houses the combustion chambers and valves."),
    "dash_camera": (3500, "Dash Camera — a camera mounted on the dashboard to record driving footage."),
    "dashboard_cover": (900, "Dashboard Cover — a protective cover that shields the dashboard from sun damage."),
    "daytime_running_light": (1200, "Daytime Running Light — a light that improves vehicle visibility during daytime."),
    "detailing_kit": (2200, "Detailing Kit — a complete set of tools and products for vehicle detailing."),
    "differential": (9500, "Differential — a drivetrain component that allows wheels to rotate at different speeds."),
    "drive_shaft": (5500, "Drive Shaft — transmits torque from the transmission to the wheels."),
    "engine": (85000, "Engine — the primary power unit that drives the vehicle."),
    "engine_block": (18000, "Engine Block — the structural core of the engine housing the cylinders."),
    "engine_cleaner": (450, "Engine Cleaner — a solution used to clean grease and grime from the engine bay."),
    "engine_mount": (1500, "Engine Mount — a component that secures the engine and absorbs vibration."),
    "engine_oil": (900, "Engine Oil — a lubricant that reduces friction and wear inside the engine."),
    "floor_mat": (700, "Floor Mat — a protective mat used to cover the vehicle's floor area."),
    "flywheel": (3800, "Flywheel — a rotating disc that stores rotational energy from the engine."),
    "fog_light": (1200, "Fog Light — a light designed to improve visibility in foggy or low-visibility conditions."),
    "front_grille": (2200, "Front Grille — a decorative and protective panel at the front of the vehicle."),
    "fuel_additive": (350, "Fuel Additive — a chemical mixed with fuel to improve engine performance."),
    "fuel_injector": (1800, "Fuel Injector — sprays fuel into the engine cylinders for combustion."),
    "fuel_pump": (2500, "Fuel Pump — moves fuel from the tank to the engine."),
    "fuse": (50, "Fuse — a safety component that protects the vehicle's electrical circuits."),
    "gasket_set": (1200, "Gasket Set — a set of seals used to prevent leaks between engine components."),
    "gearbox": (25000, "Gearbox — transmits engine power to the wheels through varying gear ratios."),
    "glass_cleaner": (250, "Glass Cleaner — a solution used to clean vehicle windows and mirrors."),
    "gps_navigation_system": (4500, "GPS Navigation System — a device that provides real-time route guidance."),
    "gps_tracker": (2800, "GPS Tracker — a device used to monitor a vehicle's real-time location."),
    "grease": (250, "Grease — a lubricant used for moving vehicle parts to reduce friction."),
    "headlight": (2800, "Headlight — a lighting unit that illuminates the road ahead of the vehicle."),
    "headlight_bulb": (450, "Headlight Bulb — a replacement bulb used inside the headlight assembly."),
    "hydraulic_jack": (2500, "Hydraulic Jack — a tool that uses hydraulic pressure to lift a vehicle."),
    "ignition_coil": (900, "Ignition Coil — converts battery voltage into the high voltage needed to fire spark plugs."),
    "intercooler": (5500, "Intercooler — cools compressed air from the turbocharger before it enters the engine."),
    "interior_led_light": (500, "Interior LED Light — an LED lighting accessory for the vehicle cabin."),
    "jumper_cable": (700, "Jumper Cable — a cable used to start a vehicle using another vehicle's battery."),
    "leaf_spring": (3500, "Leaf Spring — a suspension component made of layered metal strips."),
    "led_headlight": (3200, "LED Headlight — a headlight assembly using energy-efficient LED bulbs."),
    "led_light_bar": (2500, "LED Light Bar — a strip of LED lights used for extra vehicle illumination."),
    "microfiber_cloth": (150, "Microfiber Cloth — a soft cloth used for cleaning and polishing vehicle surfaces."),
    "motorcycle_battery": (2200, "Motorcycle Battery — provides electrical power to start and run a motorcycle."),
    "motorcycle_brake_pad": (450, "Motorcycle Brake Pad — a friction component used in motorcycle braking systems."),
    "motorcycle_chain": (900, "Motorcycle Chain — transmits power from the engine to the rear wheel."),
    "motorcycle_exhaust": (3500, "Motorcycle Exhaust — a component that channels exhaust gases away from the engine."),
    "motorcycle_helmet": (2500, "Motorcycle Helmet — protective headgear worn while riding a motorcycle."),
    "motorcycle_mirror": (400, "Motorcycle Mirror — a rearview mirror fitted on a motorcycle."),
    "motorcycle_seat": (1500, "Motorcycle Seat — a padded seat designed for motorcycle riders."),
    "motorcycle_sprocket": (600, "Motorcycle Sprocket — a toothed wheel that drives the motorcycle chain."),
    "motorcycle_tire": (2200, "Motorcycle Tire — a rubber tire designed for motorcycles."),
    "motorcycle_windshield": (1800, "Motorcycle Windshield — a protective shield that reduces wind impact on the rider."),
    "mud_flaps": (500, "Mud Flaps — protective flaps that reduce mud and debris splashing onto the vehicle."),
    "neck_pillow": (350, "Neck Pillow — a cushioned pillow used for neck support while driving or riding."),
    "obd2_scanner": (2200, "OBD2 Scanner — a diagnostic tool used to read vehicle engine fault codes."),
    "oil_filter_wrench": (350, "Oil Filter Wrench — a tool used to remove and install oil filters."),
    "oil_pump": (2500, "Oil Pump — circulates engine oil to lubricate moving engine parts."),
    "parking_sensor": (1800, "Parking Sensor — a sensor system that helps detect obstacles while parking."),
    "phone_holder": (350, "Phone Holder — a mount used to secure a phone inside the vehicle."),
    "piston": (1200, "Piston — a cylindrical engine component that moves within the cylinder to generate power."),
    "piston_ring": (500, "Piston Ring — a ring fitted on the piston to seal the combustion chamber."),
    "power_steering_pump": (3200, "Power Steering Pump — supplies hydraulic pressure to assist steering."),
    "propeller_shaft": (4500, "Propeller Shaft — transmits torque from the transmission to the differential."),
    "radiator": (3500, "Radiator — cools the engine by dissipating heat from the coolant."),
    "rear_view_mirror": (700, "Rear View Mirror — a mirror that provides the driver with a view behind the vehicle."),
    "relay": (150, "Relay — an electrical switch used to control various vehicle circuits."),
    "reverse_camera": (2200, "Reverse Camera — a camera that assists the driver while reversing the vehicle."),
    "roof_box": (6500, "Roof Box — a storage container mounted on the vehicle roof for extra cargo space."),
    "roof_rack": (4500, "Roof Rack — a frame mounted on the vehicle roof for carrying cargo."),
    "seat_cover": (1200, "Seat Cover — a protective cover fitted over vehicle seats."),
    "seat_cushion": (700, "Seat Cushion — a padded cushion used for added seating comfort."),
    "shock_absorber": (2800, "Shock Absorber — a suspension component that dampens road shocks."),
    "side_mirror": (1200, "Side Mirror — a mirror mounted on the side of the vehicle for rear visibility."),
    "socket_wrench_set": (1800, "Socket Wrench Set — a set of tools used for tightening and loosening bolts."),
    "spark_plug": (250, "Spark Plug — ignites the air-fuel mixture inside the engine cylinders."),
    "spoiler": (3200, "Spoiler — an aerodynamic accessory fitted to improve vehicle stability and styling."),
    "sponge": (100, "Sponge — a cleaning tool used for washing vehicle surfaces."),
    "stabilizer_link": (600, "Stabilizer Link — connects the sway bar to the suspension for improved handling."),
    "starter_motor": (3500, "Starter Motor — an electric motor that starts the vehicle's engine."),
    "steel_wheel": (3200, "Steel Wheel — a durable wheel made of steel construction."),
    "steering_rack": (5500, "Steering Rack — converts steering wheel rotation into wheel movement."),
    "steering_wheel_cover": (450, "Steering Wheel Cover — a protective and comfort accessory for the steering wheel."),
    "strut": (3200, "Strut — a suspension component that combines a shock absorber and structural support."),
    "sunshade": (400, "Sunshade — a shade used to block sunlight from entering the vehicle."),
    "tail_light": (2200, "Tail Light — a lighting unit fitted at the rear of the vehicle."),
    "thermostat": (700, "Thermostat — regulates engine coolant flow to maintain optimal temperature."),
    "tie_rod_end": (800, "Tie Rod End — connects the steering rack to the wheel hub for steering control."),
    "timing_belt": (1500, "Timing Belt — synchronizes the rotation of the crankshaft and camshaft."),
    "timing_chain": (2200, "Timing Chain — a metal chain that synchronizes engine valve timing."),
    "tire_inflator": (2200, "Tire Inflator — a portable device used to inflate vehicle tires."),
    "tire_pressure_gauge": (350, "Tire Pressure Gauge — a tool used to measure tire air pressure."),
    "tire_repair_kit": (900, "Tire Repair Kit — a set of tools and materials used to fix tire punctures."),
    "tire_shine": (350, "Tire Shine — a product used to give tires a glossy finish."),
    "tire_valve": (100, "Tire Valve — a component used to inflate and seal air inside the tire."),
    "torque_converter": (7500, "Torque Converter — transmits engine power to an automatic transmission."),
    "torque_wrench": (2200, "Torque Wrench — a tool used to tighten fasteners to a precise torque value."),
    "trailer_axle": (6500, "Trailer Axle — supports the wheels and load of a trailer."),
    "trailer_hitch": (3500, "Trailer Hitch — a device used to attach a trailer to a vehicle."),
    "transmission": (35000, "Transmission — transfers engine power to the wheels through different gear ratios."),
    "transmission_oil": (700, "Transmission Oil — a lubricant used to protect transmission components."),
    "truck_light": (1800, "Truck Light — a lighting unit designed for trucks and heavy vehicles."),
    "truck_mirror": (1500, "Truck Mirror — a rearview mirror designed for trucks."),
    "truck_seat": (5500, "Truck Seat — a seat designed for truck driver comfort and durability."),
    "truck_tire": (8500, "Truck Tire — a heavy-duty tire designed for trucks."),
    "turbocharger": (12000, "Turbocharger — forces extra air into the engine to boost power output."),
    "turn_signal_light": (500, "Turn Signal Light — a light used to indicate the vehicle's turning direction."),
    "usb_car_charger": (350, "USB Car Charger — a charging accessory that powers devices inside the vehicle."),
    "water_pump": (2200, "Water Pump — circulates coolant through the engine to regulate temperature."),
    "wax": (450, "Wax — a protective product applied to vehicle paint for shine and protection."),
    "wheel_cleaner": (350, "Wheel Cleaner — a cleaning solution formulated for vehicle wheels."),
    "wheel_cover": (900, "Wheel Cover — a decorative cover fitted over the vehicle's wheels."),
    "wheel_spacer": (900, "Wheel Spacer — a component that adjusts wheel positioning on the hub."),
    "window_visor": (900, "Window Visor — a rain guard fitted above vehicle windows."),
    "windshield_washer_fluid": (250, "Windshield Washer Fluid — a cleaning fluid used for the windshield wiper system."),
    "wiring_harness": (2500, "Wiring Harness — a bundled set of wires that connects the vehicle's electrical system."),
}

path = "data/products-placeholder.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
skipped = []
for sku, prod in data.items():
    if prod.get("categoryId") == "automotive_vehicle_parts_accessories":
        img = prod["images"]["main"].split("/")[-1].replace(".png", "")
        if img in price_desc:
            price, desc = price_desc[img]
            title = " ".join(w.capitalize() for w in img.split("_"))
            prod["title"] = title
            prod["price"] = price
            prod["description"] = desc
            prod["status"] = "active"
            updated += 1
        else:
            skipped.append((sku, img))

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
