import json

price_desc = {
    "mobile_phones_accessories": (500, "Mobile Phones & Accessories — a general range of phones and related accessories."),
    "smartphone_charger_cable": (350, "Smartphone Charger Cable — a standard cable used for charging smartphones."),
    "mobile_phones": (15000, "Mobile Phones — a general range of mobile phones for everyday use."),
    "smartphone": (18000, "Smartphone — a modern touchscreen phone with internet and app capabilities."),
    "android_smartphone": (16000, "Android Smartphone — a smartphone running the Android operating system."),
    "feature_phone": (2500, "Feature Phone — a basic mobile phone with limited smart features."),
    "foldable_smartphone": (65000, "Foldable Smartphone — a smartphone with a flexible folding display."),
    "flip_phone": (3500, "Flip Phone — a compact mobile phone with a folding clamshell design."),
    "rugged_smartphone": (22000, "Rugged Smartphone — a durable smartphone built to withstand harsh conditions."),
    "gaming_smartphone": (45000, "Gaming Smartphone — a high-performance smartphone optimized for mobile gaming."),
    "satellite_phone": (55000, "Satellite Phone — a phone that connects via satellite for remote area coverage."),
    "refurbished_phone": (9000, "Refurbished Phone — a pre-owned smartphone restored to good working condition."),
    "tablets": (18000, "Tablets — a general range of touchscreen tablet devices."),
    "android_tablet": (16000, "Android Tablet — a tablet running the Android operating system."),
    "windows_tablet": (25000, "Windows Tablet — a tablet running the Windows operating system."),
    "kids_tablet": (7500, "Kids' Tablet — a durable, simplified tablet designed for children."),
    "drawing_tablet": (12000, "Drawing Tablet — a tablet designed for digital drawing and illustration."),
    "e_reader": (9500, "E-Reader — a lightweight device designed for reading digital books."),
    "smartwatches_wearables": (5500, "Smartwatches & Wearables — a general range of wearable smart devices."),
    "smartwatch": (7500, "Smartwatch — a wearable device offering notifications, fitness tracking, and apps."),
    "fitness_band": (2500, "Fitness Band — a wearable device designed for tracking activity and health metrics."),
    "smart_ring": (8500, "Smart Ring — a compact wearable ring designed for health and activity tracking."),
    "gps_watch": (6500, "GPS Watch — a wearable device with built-in GPS tracking for outdoor activities."),
    "kids_smartwatch": (3500, "Kids' Smartwatch — a wearable device designed for children with safety features."),
    "phone_cases_covers": (400, "Phone Cases & Covers — a general range of protective cases for smartphones."),
    "silicone_case": (350, "Silicone Case — a soft, flexible protective case for smartphones."),
    "tpu_case": (350, "TPU Case — a flexible, shock-absorbent protective case for smartphones."),
    "hard_case": (400, "Hard Case — a rigid protective case designed for smartphones."),
    "rugged_case": (600, "Rugged Case — a heavy-duty case offering extra shock protection for smartphones."),
    "clear_case": (300, "Clear Case — a transparent protective case for smartphones."),
    "leather_flip_case": (700, "Leather Flip Case — a leather case with a flip cover for smartphones."),
    "wallet_case": (700, "Wallet Case — a phone case with built-in card storage."),
    "magnetic_case": (500, "Magnetic Case — a phone case with magnetic attachment support."),
    "shockproof_case": (600, "Shockproof Case — a case designed to absorb impact and protect against drops."),
    "waterproof_case": (900, "Waterproof Case — a sealed case designed to protect phones from water damage."),
    "bumper_case": (400, "Bumper Case — a minimalist case that protects the edges of a smartphone."),
    "screen_protection": (250, "Screen Protection — a general range of products used to protect phone screens."),
    "tempered_glass": (250, "Tempered Glass — a durable glass screen protector for smartphones."),
    "privacy_screen_protector": (400, "Privacy Screen Protector — a screen protector that limits side-angle visibility."),
    "matte_screen_protector": (350, "Matte Screen Protector — an anti-glare screen protector for smartphones."),
    "camera_lens_protector": (200, "Camera Lens Protector — a protective film or glass for phone camera lenses."),
    "hydrogel_film": (300, "Hydrogel Film — a flexible, self-healing screen protector for smartphones."),
    "screen_cleaning_kit": (300, "Screen Cleaning Kit — a set of tools designed for cleaning device screens."),
    "chargers": (500, "Chargers — a general range of charging devices for phones and gadgets."),
    "fast_charger": (700, "Fast Charger — a charger designed for rapid device charging."),
    "usb_charger": (400, "USB Charger — a standard charger with a USB output port."),
    "usb_c_charger": (500, "USB-C Charger — a charger designed with a USB-C output port."),
    "wireless_charger": (900, "Wireless Charger — a charging pad that powers devices without cables."),
    "magnetic_charger": (900, "Magnetic Charger — a wireless charger with magnetic alignment for phones."),
    "multi_port_charger": (900, "Multi-Port Charger — a charger with multiple ports for charging several devices."),
    "car_charger": (500, "Car Charger — a charger designed to plug into a vehicle's power outlet."),
    "travel_charger": (600, "Travel Charger — a compact charger designed for travel convenience."),
    "charging_dock": (900, "Charging Dock — a stand-based charger designed for convenient device charging."),
    "charging_cables": (300, "Charging Cables — a general range of cables used for device charging."),
    "usb_c_cable": (350, "USB-C Cable — a charging and data cable with a USB-C connector."),
    "lightning_cable": (450, "Lightning Cable — a charging and data cable designed for Apple devices."),
    "micro_usb_cable": (250, "Micro USB Cable — a charging and data cable with a Micro USB connector."),
    "magnetic_charging_cable": (500, "Magnetic Charging Cable — a cable with a magnetic connector for easy charging."),
    "braided_charging_cable": (400, "Braided Charging Cable — a durable, tangle-resistant charging cable."),
    "multi_charging_cable": (500, "Multi Charging Cable — a cable with multiple connector tips for various devices."),
    "otg_cable": (250, "OTG Cable — a cable that enables direct connection between phones and USB devices."),
    "power_banks": (1500, "Power Banks — a general range of portable charging devices."),
    "power_bank": (1800, "Power Bank — a portable battery pack used for charging devices on the go."),
    "wireless_power_bank": (2200, "Wireless Power Bank — a portable battery pack with wireless charging support."),
    "solar_power_bank": (2500, "Solar Power Bank — a portable battery pack that charges using solar energy."),
    "magnetic_power_bank": (2200, "Magnetic Power Bank — a portable battery pack with magnetic phone attachment."),
    "laptop_power_bank": (5500, "Laptop Power Bank — a high-capacity portable battery designed to charge laptops."),
    "audio_accessories": (900, "Audio Accessories — a general range of audio devices for mobile use."),
    "true_wireless_earbuds": (2500, "True Wireless Earbuds — fully wireless earbuds offering a cable-free listening experience."),
    "wired_earphones": (500, "Wired Earphones — earphones connected via a standard audio cable."),
    "wireless_earphones": (1500, "Wireless Earphones — earphones that connect to devices via Bluetooth."),
    "bluetooth_headphones": (2500, "Bluetooth Headphones — over-ear headphones with wireless Bluetooth connectivity."),
    "neckband_earphones": (1200, "Neckband Earphones — wireless earphones connected by a flexible neckband."),
    "bluetooth_speaker": (2500, "Bluetooth Speaker — a portable speaker with wireless Bluetooth connectivity."),
    "mobile_photography": (1200, "Mobile Photography — a general range of accessories for smartphone photography."),
    "selfie_stick": (600, "Selfie Stick — an extendable stick used for taking wide-angle photos and videos."),
    "phone_tripod": (900, "Phone Tripod — a compact tripod designed for stabilizing smartphones."),
    "gimbal_stabilizer": (5500, "Gimbal Stabilizer — a motorized device used to stabilize smartphone video footage."),
    "clip_on_lens_kit": (900, "Clip-On Lens Kit — a set of attachable lenses for smartphone photography."),
    "ring_light": (1200, "Ring Light — a circular light used for even illumination in photos and videos."),
    "mini_led_light": (700, "Mini LED Light — a compact light used for enhancing smartphone photography."),
    "phone_camera_grip": (900, "Phone Camera Grip — a handheld grip designed for stable smartphone photography."),
    "bluetooth_remote_shutter": (400, "Bluetooth Remote Shutter — a wireless remote used to trigger phone camera shutters."),
    "car_accessories": (700, "Car Accessories — a general range of mobile accessories designed for vehicle use."),
    "car_phone_mount": (700, "Car Phone Mount — a mount designed to secure a phone inside a vehicle."),
    "magnetic_car_mount": (700, "Magnetic Car Mount — a phone mount using magnets for vehicle installation."),
    "wireless_car_charger": (1500, "Wireless Car Charger — a charging mount that wirelessly powers a phone in a vehicle."),
    "bluetooth_fm_transmitter": (900, "Bluetooth FM Transmitter — a device that streams phone audio through a car's FM radio."),
    "storage": (500, "Storage — a general range of storage accessories for mobile devices."),
    "micro_sd_card": (900, "Micro SD Card — a small memory card used for expanding device storage."),
    "sd_card_adapter": (200, "SD Card Adapter — an adapter that allows a micro SD card to fit standard SD slots."),
    "usb_flash_drive": (700, "USB Flash Drive — a portable storage device with a standard USB connector."),
    "otg_flash_drive": (900, "OTG Flash Drive — a flash drive designed for direct connection to mobile devices."),
    "card_reader": (400, "Card Reader — a device used to read data from memory cards."),
    "mobile_gaming_accessories": (900, "Mobile Gaming Accessories — a general range of accessories for mobile gaming."),
    "mobile_game_controller": (1500, "Mobile Game Controller — a controller designed for gaming on mobile devices."),
    "gaming_triggers": (500, "Gaming Triggers — attachable triggers designed for enhanced mobile gaming control."),
    "cooling_fan": (900, "Cooling Fan — a compact fan designed to cool phones during extended gaming."),
    "finger_sleeves": (300, "Finger Sleeves — thin sleeves designed to improve touchscreen responsiveness while gaming."),
    "vr_headset": (2500, "VR Headset — a headset designed for virtual reality experiences using a smartphone."),
    "phone_gaming_grip": (700, "Phone Gaming Grip — an ergonomic grip designed for comfortable mobile gaming."),
    "smart_home_integration": (900, "Smart Home Integration — a general range of accessories linking phones with smart home devices."),
    "smart_tag": (2500, "Smart Tag — a small tracking device used to locate belongings via a phone app."),
    "bluetooth_tracker": (2200, "Bluetooth Tracker — a compact device used to track items via Bluetooth connectivity."),
    "nfc_tag": (300, "NFC Tag — a programmable tag used to trigger phone actions via NFC."),
    "smart_remote": (1500, "Smart Remote — a device that allows phones to control other smart devices."),
    "connectivity": (500, "Connectivity — a general range of accessories for expanding device connectivity."),
    "usb_hub": (700, "USB Hub — a device that expands a single USB port into multiple ports."),
    "usb_c_hub": (900, "USB-C Hub — a hub that expands USB-C connectivity into multiple ports."),
    "otg_adapter": (250, "OTG Adapter — an adapter enabling direct connection between phones and USB devices."),
    "lightning_adapter": (350, "Lightning Adapter — an adapter designed for connecting accessories to Apple devices."),
    "usb_to_ethernet_adapter": (700, "USB to Ethernet Adapter — an adapter that enables wired internet connectivity via USB."),
    "sim_card_adapter": (150, "SIM Card Adapter — an adapter that fits smaller SIM cards into larger slots."),
    "sim_card_cutter": (200, "SIM Card Cutter — a tool used to cut SIM cards into smaller sizes."),
    "repair_parts": (900, "Repair Parts — a general range of replacement components for mobile devices."),
    "phone_battery": (1200, "Phone Battery — a replacement battery for smartphones."),
    "replacement_display": (3500, "Replacement Display — a replacement screen assembly for smartphones."),
    "touch_screen_digitizer": (2500, "Touch Screen Digitizer — a replacement touch-sensitive layer for smartphone screens."),
    "charging_port": (500, "Charging Port — a replacement charging port component for smartphones."),
    "rear_camera_module": (1800, "Rear Camera Module — a replacement rear camera component for smartphones."),
    "front_camera_module": (1200, "Front Camera Module — a replacement front camera component for smartphones."),
    "speaker_module": (700, "Speaker Module — a replacement speaker component for smartphones."),
    "earpiece_speaker": (400, "Earpiece Speaker — a replacement earpiece speaker component for smartphones."),
    "microphone_module": (500, "Microphone Module — a replacement microphone component for smartphones."),
    "back_cover": (600, "Back Cover — a replacement rear panel for smartphones."),
    "side_buttons": (300, "Side Buttons — replacement volume and power button components for smartphones."),
    "sim_tray": (250, "SIM Tray — a replacement SIM card tray for smartphones."),
    "repair_tools": (700, "Repair Tools — a general range of tools used for mobile device repair."),
    "precision_screwdriver_set": (700, "Precision Screwdriver Set — a set of small screwdrivers used for device repair."),
    "opening_tool_kit": (500, "Opening Tool Kit — a set of tools designed for safely opening device casings."),
    "suction_cup": (200, "Suction Cup — a tool used to lift and separate device screens during repair."),
    "tweezers": (150, "Tweezers — a precision tool used for handling small device components."),
    "screen_separator_tool": (400, "Screen Separator Tool — a tool used to safely separate glass from device screens."),
    "heat_pad": (500, "Heat Pad — a heating tool used to loosen adhesive during screen repair."),
    "repair_mat": (400, "Repair Mat — a static-safe mat used as a work surface for device repair."),
    "wearable_accessories": (500, "Wearable Accessories — a general range of accessories for smartwatches and wearables."),
    "watch_band": (700, "Watch Band — a replacement strap for smartwatches."),
    "watch_charger": (700, "Watch Charger — a charging cable or dock designed for smartwatches."),
    "watch_screen_protector": (250, "Watch Screen Protector — a protective film or glass for smartwatch screens."),
    "smartwatch_case": (400, "Smartwatch Case — a protective case designed for smartwatches."),
    "phone_holders_stands": (500, "Phone Holders & Stands — a general range of accessories for holding phones upright."),
    "desktop_phone_stand": (500, "Desktop Phone Stand — a stand designed to hold a phone upright on a desk."),
    "foldable_phone_stand": (500, "Foldable Phone Stand — a compact, collapsible stand for holding phones."),
    "flexible_phone_holder": (700, "Flexible Phone Holder — an adjustable holder designed for hands-free phone use."),
    "gooseneck_phone_holder": (900, "Gooseneck Phone Holder — a flexible-arm holder designed for mounting phones."),
    "tablet_stand": (700, "Tablet Stand — a stand designed to hold a tablet upright."),
    "mobile_networking": (500, "Mobile Networking — a general range of accessories for mobile connectivity."),
    "sim_card": (200, "SIM Card — a card used to connect a mobile device to a cellular network."),
    "esim_activation_kit": (300, "eSIM Activation Kit — a kit designed to activate an embedded SIM on a device."),
    "mobile_wifi_hotspot": (3500, "Mobile WiFi Hotspot — a portable device that provides wireless internet access."),
    "wifi_dongle": (1500, "WiFi Dongle — a compact device that provides wireless internet connectivity."),
    "signal_booster": (5500, "Signal Booster — a device designed to strengthen mobile network signal."),
    "cleaning_protection": (300, "Cleaning & Protection — a general range of accessories for device care."),
    "cleaning_cloth": (150, "Cleaning Cloth — a soft cloth used for cleaning device screens."),
    "device_cleaning_kit": (400, "Device Cleaning Kit — a complete set of tools for cleaning electronic devices."),
    "dust_plug": (150, "Dust Plug — a small plug used to protect device ports from dust."),
    "waterproof_pouch": (500, "Waterproof Pouch — a sealed pouch designed to protect phones from water."),
    "anti_theft_phone_strap": (400, "Anti-Theft Phone Strap — a strap designed to secure a phone and deter theft."),
    "travel_accessories": (500, "Travel Accessories — a general range of accessories designed for mobile use while traveling."),
    "universal_travel_adapter": (900, "Universal Travel Adapter — an adapter designed to fit international power outlets."),
    "cable_organizer": (400, "Cable Organizer — a case or pouch designed to organize charging cables and accessories."),
    "gadget_organizer_bag": (900, "Gadget Organizer Bag — a bag designed to organize small electronic accessories."),
    "waterproof_travel_case": (900, "Waterproof Travel Case — a sealed case designed to protect gadgets while traveling."),
    "neck_phone_holder": (400, "Neck Phone Holder — a lanyard-style holder designed for hands-free phone use."),
}

files_map = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch3.json",
]

updated = 0
skipped = []

for path in files_map:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    changed = False
    for sku, prod in data.items():
        if prod.get("categoryId") == "mobile_phones_accessories":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
                changed = True
            else:
                skipped.append((path, sku, img))
    if changed:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
