import json

price_desc = {
    "4k_tv": (45000, "4K TV — an ultra-high-definition television designed for sharp, detailed viewing."),
    "8k_tv": (150000, "8K TV — a television offering extremely high-resolution picture quality."),
    "aa_battery": (150, "AA Battery — a standard battery used to power everyday electronic devices."),
    "aaa_battery": (150, "AAA Battery — a compact battery used to power small electronic devices."),
    "ambient_tv_lighting": (2500, "Ambient TV Lighting — LED lighting synced to a TV screen for immersive ambiance."),
    "amplifier": (8500, "Amplifier — a device used to boost audio signal power for speakers."),
    "android_tv": (25000, "Android TV — a smart television running the Android TV operating system."),
    "ar_glasses": (35000, "AR Glasses — wearable eyewear that overlays digital content onto the real world."),
    "arcade_stick": (5500, "Arcade Stick — a joystick controller designed for arcade-style gaming."),
    "audio_devices": (2500, "Audio Devices — a general range of audio playback and recording equipment."),
    "audio_interface": (6500, "Audio Interface — a device used to connect microphones and instruments to a computer."),
    "audio_splitter": (250, "Audio Splitter — a device used to connect multiple headphones to one source."),
    "aux_cable": (250, "Aux Cable — a cable used to connect audio devices via a 3.5mm jack."),
    "av_receiver": (18000, "AV Receiver — a central hub used to manage audio and video for home theater systems."),
    "batteries_chargers": (900, "Batteries & Chargers — a general range of battery and charging products."),
    "battery_charger": (1800, "Battery Charger — a device used to recharge electronic device batteries."),
    "bluetooth_speaker": (2200, "Bluetooth Speaker — a wireless speaker used for portable audio playback."),
    "bone_conduction_headphones": (5500, "Bone Conduction Headphones — headphones that transmit sound through vibrations, leaving ears open."),
    "bookshelf_speaker": (6500, "Bookshelf Speaker — a compact speaker designed for home audio setups."),
    "button_cell_battery": (100, "Button Cell Battery — a small round battery used in compact electronic devices."),
    "cable_organizer": (350, "Cable Organizer — a tool used to bundle and organize loose cables."),
    "cables_adapters": (450, "Cables & Adapters — a general range of connectivity cables and adapters."),
    "capture_card": (5500, "Capture Card — a device used to record and stream video from another source."),
    "card_reader": (700, "Card Reader — a device used to transfer files from memory cards to a computer."),
    "carrying_case": (1800, "Carrying Case — a protective case designed for transporting electronic devices."),
    "ceiling_mount": (2500, "Ceiling Mount — a bracket used to mount a projector or speaker on the ceiling."),
    "ceiling_speaker": (3500, "Ceiling Speaker — a speaker built into the ceiling for distributed audio."),
    "charging_dock": (1800, "Charging Dock — a stand used to charge a device conveniently."),
    "condenser_microphone": (5500, "Condenser Microphone — a sensitive microphone used for studio-quality recording."),
    "console_cooling_fan": (900, "Console Cooling Fan — a fan accessory used to keep a gaming console cool."),
    "controller_grip": (700, "Controller Grip — an ergonomic accessory used to improve controller handling."),
    "device_cleaning_kit": (450, "Device Cleaning Kit — a set of tools used to clean electronic devices and screens."),
    "digital_photo_frame": (3500, "Digital Photo Frame — an electronic frame that displays digital photos."),
    "displayport_cable": (450, "DisplayPort Cable — a cable used to connect monitors for high-resolution display."),
    "dj_controller": (25000, "DJ Controller — a device used to mix and control music tracks for DJing."),
    "dj_equipment": (18000, "DJ Equipment — a general range of gear used for DJ performances."),
    "dj_mixer": (18000, "DJ Mixer — a device used to blend audio tracks during DJ performances."),
    "dynamic_microphone": (3500, "Dynamic Microphone — a durable microphone commonly used for live performances."),
    "electronic_accessories": (700, "Electronic Accessories — a general range of accessories for electronic devices."),
    "electronics_tv_audio_gaming": (2500, "Electronics (TV, Audio, Gaming, etc.) — a general range of entertainment electronics."),
    "extension_cord": (700, "Extension Cord — a cord used to extend the reach of an electrical outlet."),
    "external_hard_drive": (4500, "External Hard Drive — a portable storage device used for saving digital files."),
    "external_ssd": (8500, "External SSD — a fast, portable solid-state drive for data storage."),
    "flight_stick": (8500, "Flight Stick — a joystick controller designed for flight simulation games."),
    "floor_standing_speaker": (18000, "Floor Standing Speaker — a large speaker designed for powerful home audio."),
    "fm_radio": (1500, "FM Radio — a device used to receive and play FM radio broadcasts."),
    "game_controller": (3500, "Game Controller — a handheld device used to control video games."),
    "gaming_accessories": (1500, "Gaming Accessories — a general range of accessories designed for gaming setups."),
    "gaming_chair": (12000, "Gaming Chair — an ergonomic chair designed for long gaming sessions."),
    "gaming_consoles": (35000, "Gaming Consoles — dedicated devices used to play video games."),
    "gaming_desk": (15000, "Gaming Desk — a desk designed with features suited for gaming setups."),
    "gaming_headset": (3500, "Gaming Headset — a headset designed for immersive gaming audio and communication."),
    "gaming_keyboard": (3500, "Gaming Keyboard — a keyboard designed for responsive gaming performance."),
    "gaming_monitor": (25000, "Gaming Monitor — a high-refresh-rate display designed for gaming."),
    "gaming_mouse": (2500, "Gaming Mouse — a precision mouse designed for gaming performance."),
    "gaming_mouse_pad": (700, "Gaming Mouse Pad — a surface designed for smooth and precise mouse movement."),
    "google_tv": (25000, "Google TV — a smart television running the Google TV operating system."),
    "green_screen": (3500, "Green Screen — a background used for chroma key video compositing."),
    "handheld_gaming_console": (18000, "Handheld Gaming Console — a portable device used to play video games on the go."),
    "hdmi_adapter": (450, "HDMI Adapter — a device used to connect HDMI cables to different port types."),
    "hdmi_cable": (350, "HDMI Cable — a cable used to transmit high-definition audio and video."),
    "hdmi_splitter": (900, "HDMI Splitter — a device used to send one HDMI signal to multiple displays."),
    "hdmi_switch": (900, "HDMI Switch — a device used to connect multiple HDMI sources to one display."),
    "headphone_stand": (900, "Headphone Stand — a stand used to store and display headphones."),
    "headphones_earphones": (900, "Headphones & Earphones — a general range of personal audio listening devices."),
    "home_gaming_console": (35000, "Home Gaming Console — a stationary device used to play video games at home."),
    "home_theater_projector": (35000, "Home Theater Projector — a projector designed for immersive home cinema viewing."),
    "home_theater_system": (25000, "Home Theater System — a multi-speaker setup designed for immersive home audio."),
    "internet_radio": (3500, "Internet Radio — a device used to stream radio stations over the internet."),
    "ir_remote_controller": (900, "IR Remote Controller — a remote used to control devices via infrared signal."),
    "karaoke_equipment": (8500, "Karaoke Equipment — a general range of gear used for karaoke performances."),
    "karaoke_machine": (12000, "Karaoke Machine — an all-in-one device used for singing along to music tracks."),
    "karaoke_microphone": (1800, "Karaoke Microphone — a microphone designed for karaoke singing."),
    "karaoke_mixer": (5500, "Karaoke Mixer — a device used to blend vocals and music for karaoke."),
    "karaoke_speaker": (5500, "Karaoke Speaker — a speaker designed for karaoke audio playback."),
    "laser_pointer": (450, "Laser Pointer — a handheld device used to project a laser dot for presentations."),
    "lavalier_microphone": (2500, "Lavalier Microphone — a small clip-on microphone used for hands-free audio recording."),
    "led_tv": (35000, "LED TV — a television using LED backlighting for everyday viewing."),
    "media_server": (25000, "Media Server — a device used to store and stream media content across a network."),
    "media_storage": (5500, "Media Storage — a general range of storage solutions for digital media."),
    "micro_hi_fi_system": (12000, "Micro Hi-Fi System — a compact audio system designed for home music playback."),
    "microphone_stand": (900, "Microphone Stand — a stand used to hold a microphone in place during recording."),
    "microphones": (2500, "Microphones — a general range of audio recording devices."),
    "microsd_card": (900, "MicroSD Card — a compact memory card used in electronic devices."),
    "midi_controller": (8500, "MIDI Controller — a device used to control music production software."),
    "mini_led_tv": (55000, "Mini LED TV — a television using mini-LED backlighting for enhanced contrast."),
    "mini_projector": (8500, "Mini Projector — a compact projector designed for portable display needs."),
    "noise_cancelling_headphones": (8500, "Noise Cancelling Headphones — headphones designed to block ambient sound for immersive listening."),
    "oled_tv": (85000, "OLED TV — a television offering deep contrast and vibrant colors through OLED technology."),
    "on_ear_headphones": (2500, "On-Ear Headphones — headphones that rest on the ears for lightweight listening."),
    "open_ear_headphones": (4500, "Open-Ear Headphones — headphones designed to allow ambient sound while listening."),
    "optical_audio_cable": (450, "Optical Audio Cable — a cable used to transmit digital audio signals."),
    "outdoor_speaker": (5500, "Outdoor Speaker — a weather-resistant speaker designed for outdoor use."),
    "over_ear_headphones": (5500, "Over-Ear Headphones — headphones that fully enclose the ears for immersive audio."),
    "pa_speaker": (12000, "PA Speaker — a powerful speaker designed for public address and events."),
    "pop_filter": (450, "Pop Filter — a screen used to reduce plosive sounds during microphone recording."),
    "portable_gaming_console": (18000, "Portable Gaming Console — a handheld device used to play video games on the go."),
    "portable_projector": (12000, "Portable Projector — a lightweight projector designed for on-the-go display needs."),
    "portable_speaker": (2500, "Portable Speaker — a compact speaker used for audio playback on the go."),
    "portable_tv": (8500, "Portable TV — a compact television designed for mobility."),
    "power_protection": (1500, "Power Protection — a general range of devices used to protect electronics from power issues."),
    "power_strip": (700, "Power Strip — a device with multiple outlets used to power several devices."),
    "projector_lamp": (5500, "Projector Lamp — a replacement bulb used in projectors."),
    "projector_screen": (5500, "Projector Screen — a surface used to display projected images and video."),
    "projectors": (25000, "Projectors — devices used to display images or video onto a large screen."),
    "qled_tv": (65000, "QLED TV — a television using quantum dot technology for enhanced color and brightness."),
    "racing_wheel": (12000, "Racing Wheel — a gaming peripheral designed for racing game simulation."),
    "rca_cable": (350, "RCA Cable — a cable used to connect analog audio and video devices."),
    "rechargeable_battery": (900, "Rechargeable Battery — a reusable battery designed for repeated charging cycles."),
    "remote_holder": (450, "Remote Holder — a caddy used to store TV and device remote controls."),
    "retro_gaming_console": (12000, "Retro Gaming Console — a device designed to play classic video games."),
    "ring_light": (2500, "Ring Light — a circular light source used for even, shadow-free illumination."),
    "screen_cleaning_kit": (450, "Screen Cleaning Kit — a set of tools used to clean device and TV screens."),
    "sd_card": (900, "SD Card — a memory card used to store data in cameras and electronic devices."),
    "shotgun_microphone": (3500, "Shotgun Microphone — a directional microphone used for focused audio capture."),
    "smart_display": (12000, "Smart Display — a connected screen device offering voice assistant integration."),
    "smart_entertainment_devices": (5500, "Smart Entertainment Devices — a general range of connected devices for home entertainment."),
    "smart_home_entertainment": (5500, "Smart Home Entertainment — a general range of connected entertainment products."),
    "smart_light_strip": (1800, "Smart Light Strip — a connected LED strip controllable via app or voice assistant."),
    "smart_plug": (900, "Smart Plug — a connected outlet that allows remote control of plugged-in devices."),
    "smart_power_strip": (1800, "Smart Power Strip — a connected power strip with app-controlled outlets."),
    "smart_projector": (35000, "Smart Projector — a projector with built-in smart streaming capabilities."),
    "smart_remote": (1800, "Smart Remote — a connected remote used to control multiple smart devices."),
    "smart_speaker": (5500, "Smart Speaker — a voice-controlled speaker with virtual assistant integration."),
    "smart_tv": (45000, "Smart TV — a television with built-in internet connectivity and streaming apps."),
    "soundbar": (5500, "Soundbar — a compact speaker system used to enhance TV audio."),
    "speaker_cable": (350, "Speaker Cable — a cable used to connect audio speakers to an amplifier."),
    "speaker_stand": (2500, "Speaker Stand — a stand used to position speakers for optimal audio."),
    "speaker_wall_mount": (900, "Speaker Wall Mount — a bracket used to mount a speaker on a wall."),
    "stereo_system": (12000, "Stereo System — an audio setup designed for high-quality home music playback."),
    "stream_deck": (12000, "Stream Deck — a customizable control panel used for live streaming."),
    "streaming_box": (5500, "Streaming Box — a device used to stream video content to a television."),
    "streaming_equipment": (8500, "Streaming Equipment — a general range of gear used for live content streaming."),
    "streaming_media_player": (6500, "Streaming Media Player — a device used to stream video content to a TV."),
    "streaming_stick": (3500, "Streaming Stick — a compact device used to add streaming apps to a TV."),
    "studio_headphones": (8500, "Studio Headphones — professional-grade headphones used for accurate audio monitoring."),
    "studio_monitor_speaker": (12000, "Studio Monitor Speaker — a speaker designed for accurate audio production monitoring."),
    "subwoofer": (8500, "Subwoofer — a speaker designed to reproduce low-frequency bass sound."),
    "surge_protector": (1500, "Surge Protector — a device used to protect electronics from power surges."),
    "television_speakers_game_controller": (2500, "Television, Speakers & Game Controller Set — a bundled set of entertainment electronics."),
    "televisions": (45000, "Televisions — a general range of TVs for home entertainment."),
    "thumb_grips": (450, "Thumb Grips — small accessories added to controllers for improved grip."),
    "travel_adapter": (900, "Travel Adapter — a device used to adapt plugs for international power outlets."),
    "turntable": (6500, "Turntable — a device used to play vinyl records."),
    "tv_accessories": (900, "TV Accessories — a general range of accessories designed for televisions."),
    "tv_antenna": (900, "TV Antenna — a device used to receive over-the-air television signals."),
    "tv_box": (3500, "TV Box — a streaming device used to add smart features to a television."),
    "tv_cover": (900, "TV Cover — a protective cover designed to shield a television when not in use."),
    "tv_remote_control": (700, "TV Remote Control — a remote used to operate a television."),
    "tv_screen_protector": (900, "TV Screen Protector — a protective panel applied to a television's screen."),
    "tv_stand": (8500, "TV Stand — a furniture piece designed to hold and display a television."),
    "tv_wall_mount": (2500, "TV Wall Mount — a bracket used to mount a television on a wall."),
    "universal_adapter": (700, "Universal Adapter — a versatile plug adapter compatible with multiple socket types."),
    "universal_remote": (900, "Universal Remote — a remote designed to control multiple electronic devices."),
    "universal_smart_remote": (1800, "Universal Smart Remote — a connected remote used to control multiple smart devices."),
    "ups": (8500, "UPS — an uninterruptible power supply used to provide backup power for electronics."),
    "usb_c_cable": (350, "USB-C Cable — a reversible cable used for data transfer and charging."),
    "usb_cable": (250, "USB Cable — a standard cable used for data transfer and charging."),
    "usb_flash_drive": (700, "USB Flash Drive — a portable storage device used for transferring digital files."),
    "usb_hub": (900, "USB Hub — a device used to expand the number of available USB ports."),
    "usb_microphone": (2500, "USB Microphone — a plug-and-play microphone used for computer audio recording."),
    "voice_assistant_device": (5500, "Voice Assistant Device — a smart speaker offering voice-controlled assistant features."),
    "vr_accessories": (2500, "VR Accessories — a general range of accessories for virtual reality equipment."),
    "vr_ar": (35000, "VR & AR — a general range of virtual and augmented reality products."),
    "vr_base_station": (8500, "VR Base Station — a tracking device used to enable VR headset room-scale movement."),
    "vr_controllers": (12000, "VR Controllers — handheld devices used to interact within virtual reality environments."),
    "vr_headset": (35000, "VR Headset — a wearable device used for immersive virtual reality experiences."),
    "webcam": (2500, "Webcam — a camera designed for video calls and live streaming."),
    "wired_earphones": (450, "Wired Earphones — in-ear headphones connected via cable for audio listening."),
    "wired_microphone": (1800, "Wired Microphone — a microphone connected via cable for reliable audio recording."),
    "wireless_controller": (3500, "Wireless Controller — a handheld device used to control video games without cables."),
    "wireless_earbuds": (3500, "Wireless Earbuds — compact in-ear headphones offering wireless audio listening."),
    "wireless_microphone": (5500, "Wireless Microphone — a microphone system that transmits audio without cables."),
}

path = "data/products-placeholder.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
skipped = []
for sku, prod in data.items():
    if prod.get("categoryId") == "electronics_tv_audio_gaming":
        img = prod["images"]["main"].split("/")[-1].replace(".png", "")
        if img in price_desc:
            price, desc = price_desc[img]
            title = " ".join(w.capitalize() for w in img.split("_"))
            prod["title"] = title
            prod["price"] = price
            prod["description"] = desc
            prod["status"] = "active"
            updated += 1
        else:
            skipped.append((sku, img))

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
