import json

price_desc = {
    "furniture_sofas_beds_etc": (700, "Furniture (Sofas, Beds, etc.) — a general range of furniture products."),
    "accent_chair": (8500, "Accent Chair — a stylish chair used to add visual interest to a room."),
    "adjustable_bed": (35000, "Adjustable Bed — a bed frame that allows position changes for comfort."),
    "armchair": (8500, "Armchair — a single-seat upholstered chair designed for comfort."),
    "baby_crib": (9500, "Baby Crib — a bed with high sides designed for infant sleep safety."),
    "bar_cabinet": (12000, "Bar Cabinet — a furniture piece designed to store and display drinks."),
    "bar_stool": (3500, "Bar Stool — a tall seat designed for use at a bar or counter."),
    "bar_table": (8500, "Bar Table — a tall table designed for use with bar stools."),
    "bassinet": (5500, "Bassinet — a small portable bed designed for newborn sleep."),
    "bathroom_furniture": (6500, "Bathroom Furniture — a general range of furniture pieces for bathrooms."),
    "bathroom_shelf": (1500, "Bathroom Shelf — a shelving unit designed for bathroom storage."),
    "bathroom_vanity": (15000, "Bathroom Vanity — a furniture piece combining a sink counter and storage."),
    "bean_bag_chair": (3500, "Bean Bag Chair — a soft, filled seat designed for casual lounging."),
    "bed_frame": (12000, "Bed Frame — a structural frame used to support a mattress."),
    "bedroom_bench": (5500, "Bedroom Bench — a padded bench designed for use at the foot of a bed."),
    "bedroom_furniture": (8500, "Bedroom Furniture — a general range of furniture pieces for bedrooms."),
    "bedside_table": (4500, "Bedside Table — a small table placed beside a bed for convenience."),
    "bistro_set": (12000, "Bistro Set — a compact table and chair set designed for small spaces."),
    "bookcase": (8500, "Bookcase — a furniture piece with shelves designed for storing books."),
    "bookshelf": (7500, "Bookshelf — a shelving unit designed for storing and displaying books."),
    "buffet_cabinet": (15000, "Buffet Cabinet — a storage furniture piece used for dining room organization."),
    "bunk_bed": (18000, "Bunk Bed — a stacked bed frame designed to save floor space."),
    "cabinet_handles": (150, "Cabinet Handles — hardware used for opening cabinets and drawers."),
    "cafe_table": (6500, "Cafe Table — a small table designed for casual dining settings."),
    "camping_chair": (1800, "Camping Chair — a portable folding chair designed for outdoor use."),
    "canopy_bed": (25000, "Canopy Bed — a bed frame featuring decorative overhead posts."),
    "cat_tree": (5500, "Cat Tree — a multi-level structure designed for cats to climb and rest."),
    "chair_cushions": (700, "Chair Cushions — padded cushions used to add comfort to seating."),
    "chaise_lounge": (18000, "Chaise Lounge — a long reclining chair designed for lounging."),
    "changing_table": (6500, "Changing Table — a dedicated surface designed for changing an infant's diaper."),
    "chest_of_drawers": (12000, "Chest of Drawers — a furniture piece with multiple drawers for storage."),
    "china_cabinet": (18000, "China Cabinet — a display cabinet designed to store fine dishware."),
    "closet": (18000, "Closet — a freestanding storage unit designed for clothing organization."),
    "closet_organizer": (900, "Closet Organizer — a storage system used to organize clothing and items."),
    "coat_rack": (1800, "Coat Rack — a stand used to hang coats and outerwear."),
    "coffee_table": (8500, "Coffee Table — a low table typically placed in front of a sofa."),
    "commercial_furniture": (15000, "Commercial Furniture — a general range of furniture designed for business use."),
    "computer_desk": (7500, "Computer Desk — a desk designed for computer and office work."),
    "conference_table": (25000, "Conference Table — a large table designed for business meetings."),
    "console_table": (6500, "Console Table — a narrow table typically placed against a wall."),
    "corner_shelf": (1500, "Corner Shelf — a shelving unit designed to fit into room corners."),
    "curio_cabinet": (15000, "Curio Cabinet — a glass-fronted cabinet used to display collectibles."),
    "daybed": (15000, "Daybed — a versatile furniture piece used as both a bed and sofa."),
    "dining_bench": (6500, "Dining Bench — a bench seat designed for use at a dining table."),
    "dining_chair": (3500, "Dining Chair — a chair designed for use at a dining table."),
    "dining_room_furniture": (15000, "Dining Room Furniture — a general range of furniture pieces for dining rooms."),
    "dining_table": (18000, "Dining Table — a table designed for meals and gatherings."),
    "dish_rack_cabinet": (5500, "Dish Rack Cabinet — a storage cabinet designed for drying and storing dishes."),
    "display_cabinet": (15000, "Display Cabinet — a furniture piece used to showcase decorative items."),
    "display_shelf": (2500, "Display Shelf — a shelving unit designed for displaying decorative items."),
    "double_bed": (15000, "Double Bed — a bed frame sized for two people."),
    "drawer_slides": (250, "Drawer Slides — hardware used for smooth drawer movement."),
    "dresser": (15000, "Dresser — a furniture piece with drawers used for clothing storage."),
    "dressing_table": (12000, "Dressing Table — a table with a mirror designed for grooming and makeup."),
    "end_table": (4500, "End Table — a small table placed beside seating for convenience."),
    "entertainment_unit": (15000, "Entertainment Unit — a furniture piece designed to hold TV and media equipment."),
    "entryway_bench": (5500, "Entryway Bench — a bench designed for seating and storage near an entrance."),
    "entryway_furniture": (5500, "Entryway Furniture — a general range of furniture pieces for entryways."),
    "ergonomic_chair": (12000, "Ergonomic Chair — a chair designed for supportive, comfortable seating."),
    "executive_desk": (18000, "Executive Desk — a large desk designed for professional office use."),
    "extendable_dining_table": (22000, "Extendable Dining Table — a dining table with an extension feature for more seating."),
    "felt_pads": (150, "Felt Pads — protective pads used under furniture legs to prevent floor scratches."),
    "filing_cabinet": (8500, "Filing Cabinet — a storage furniture piece designed for organizing documents."),
    "floating_shelf": (1500, "Floating Shelf — a wall-mounted shelf with a concealed support system."),
    "foldable_bed": (12000, "Foldable Bed — a bed frame designed to fold for easy storage."),
    "folding_chair": (900, "Folding Chair — a portable chair designed to fold flat for storage."),
    "folding_portable_furniture": (2500, "Folding & Portable Furniture — a general range of foldable furniture products."),
    "folding_table": (3500, "Folding Table — a portable table designed to fold flat for storage."),
    "furniture_casters": (350, "Furniture Casters — wheels used to make furniture easily movable."),
    "furniture_covers": (900, "Furniture Covers — protective covers designed to shield furniture."),
    "furniture_legs": (450, "Furniture Legs — replacement legs used to support furniture pieces."),
    "furniture_parts_accessories": (450, "Furniture Parts & Accessories — a general range of furniture hardware and parts."),
    "gaming_chair": (12000, "Gaming Chair — an ergonomic chair designed for long gaming sessions."),
    "garden_chair": (3500, "Garden Chair — an outdoor chair designed for garden and patio use."),
    "garden_table": (6500, "Garden Table — an outdoor table designed for garden and patio use."),
    "glass_table_top": (3500, "Glass Table Top — a protective glass cover designed for table surfaces."),
    "hall_tree": (8500, "Hall Tree — a furniture piece combining a coat rack and storage bench."),
    "hammock": (3500, "Hammock — a suspended fabric bed used for relaxing outdoors."),
    "headboard": (8500, "Headboard — a decorative panel attached to the head of a bed frame."),
    "hinges": (100, "Hinges — hardware used to allow doors and cabinets to pivot open and closed."),
    "hotel_furniture": (18000, "Hotel Furniture — a general range of furniture designed for hospitality use."),
    "key_cabinet": (2500, "Key Cabinet — a small locking cabinet designed to store keys."),
    "kids_bed": (12000, "Kids Bed — a bed frame sized and designed for children."),
    "kids_chair": (1200, "Kids Chair — a small chair sized for young children."),
    "kids_nursery_furniture": (8500, "Kids & Nursery Furniture — a general range of furniture designed for children's rooms."),
    "king_bed": (18000, "King Bed — a large bed frame sized for maximum sleeping space."),
    "kitchen_cabinet": (15000, "Kitchen Cabinet — a storage unit designed for kitchen organization."),
    "kitchen_cart": (6500, "Kitchen Cart — a mobile storage and prep unit designed for kitchens."),
    "kitchen_furniture": (12000, "Kitchen Furniture — a general range of furniture designed for kitchens."),
    "kitchen_island": (25000, "Kitchen Island — a freestanding counter unit designed for kitchen prep and storage."),
    "laundry_cabinet": (6500, "Laundry Cabinet — a storage cabinet designed for laundry room organization."),
    "living_room_furniture": (15000, "Living Room Furniture — a general range of furniture pieces for living rooms."),
    "loft_bed": (18000, "Loft Bed — an elevated bed frame designed to create space underneath."),
    "loveseat": (18000, "Loveseat — a small sofa designed for two people."),
    "massage_chair": (55000, "Massage Chair — a reclining chair equipped with massage functions."),
    "mattress": (12000, "Mattress — a cushioned pad used as a sleeping surface on a bed."),
    "medicine_cabinet": (3500, "Medicine Cabinet — a small cabinet designed to store medicines and toiletries."),
    "microwave_stand": (5500, "Microwave Stand — a furniture piece designed to hold a microwave oven."),
    "mobile_pedestal": (5500, "Mobile Pedestal — a small rolling storage unit designed for office use."),
    "nesting_tables": (6500, "Nesting Tables — a set of tables designed to stack together for space-saving."),
    "nightstand": (4500, "Nightstand — a small table placed beside a bed for convenience."),
    "nursery_wardrobe": (12000, "Nursery Wardrobe — a wardrobe designed for storing baby clothing and items."),
    "office_chair": (8500, "Office Chair — a chair designed for comfortable seating during office work."),
    "office_desk": (12000, "Office Desk — a desk designed for professional office use."),
    "office_furniture": (12000, "Office Furniture — a general range of furniture pieces for office use."),
    "office_partition": (8500, "Office Partition — a divider panel used to separate office workspaces."),
    "office_shelf": (2500, "Office Shelf — a shelving unit designed for office storage."),
    "ottoman": (5500, "Ottoman — a padded footstool used for seating or resting feet."),
    "outdoor_bench": (5500, "Outdoor Bench — a durable bench designed for outdoor use."),
    "outdoor_furniture": (12000, "Outdoor Furniture — a general range of furniture designed for outdoor spaces."),
    "outdoor_sofa": (25000, "Outdoor Sofa — a durable sofa designed for outdoor patio use."),
    "over_the_toilet_storage": (3500, "Over-the-Toilet Storage — a shelving unit designed to fit above a toilet."),
    "pantry_cabinet": (8500, "Pantry Cabinet — a storage cabinet designed for kitchen pantry organization."),
    "patio_set": (25000, "Patio Set — a coordinated furniture set designed for outdoor patio use."),
    "patio_umbrella": (5500, "Patio Umbrella — a large umbrella designed to provide outdoor shade."),
    "pet_bed": (1800, "Pet Bed — a cushioned bed designed for pets to sleep on."),
    "pet_furniture": (5500, "Pet Furniture — a general range of furniture designed for pets."),
    "picnic_table": (8500, "Picnic Table — an outdoor table designed for picnics and gatherings."),
    "plastic_drawer": (1500, "Plastic Drawer — a lightweight storage drawer unit."),
    "platform_bed": (18000, "Platform Bed — a low-profile bed frame that doesn't require a box spring."),
    "portable_desk": (3500, "Portable Desk — a lightweight desk designed for easy movement and storage."),
    "pouf": (2500, "Pouf — a soft, cushioned ottoman used for extra seating or footrest."),
    "queen_bed": (16000, "Queen Bed — a bed frame sized for two people with generous space."),
    "reception_desk": (25000, "Reception Desk — a front-facing desk designed for business reception areas."),
    "recliner_chair": (15000, "Recliner Chair — an adjustable chair designed for reclining comfort."),
    "restaurant_chair": (3500, "Restaurant Chair — a durable chair designed for commercial dining use."),
    "rocking_chair": (6500, "Rocking Chair — a gently rocking chair often used for relaxation."),
    "salon_chair": (8500, "Salon Chair — a chair designed for use in hair and beauty salons."),
    "seat_cushions": (700, "Seat Cushions — padded cushions used to add comfort to seating."),
    "sectional_sofa": (45000, "Sectional Sofa — a modular sofa designed for flexible seating arrangements."),
    "shelf_brackets": (250, "Shelf Brackets — hardware used to support wall-mounted shelves."),
    "shelving_unit": (5500, "Shelving Unit — a freestanding structure used for storage and display."),
    "shoe_cabinet": (5500, "Shoe Cabinet — an enclosed storage unit designed for organizing shoes."),
    "shoe_rack": (2500, "Shoe Rack — a rack designed to organize and store shoes."),
    "side_table": (4500, "Side Table — a small table placed beside seating for convenience."),
    "sideboard": (15000, "Sideboard — a storage furniture piece used in dining rooms."),
    "single_bed": (9500, "Single Bed — a bed frame sized for one person."),
    "sofa": (25000, "Sofa — an upholstered seating furniture piece designed for multiple people."),
    "sofa_and_bed": (35000, "Sofa & Bed Set — a bundled set of sofa and bed furniture."),
    "sofa_bed": (25000, "Sofa Bed — a versatile furniture piece that converts from sofa to bed."),
    "specialty_furniture": (15000, "Specialty Furniture — a general range of unique or custom furniture pieces."),
    "spice_rack": (900, "Spice Rack — a rack used to organize and store cooking spices."),
    "standing_desk": (15000, "Standing Desk — a height-adjustable desk designed for sit-stand work."),
    "storage_bed": (18000, "Storage Bed — a bed frame with built-in storage compartments."),
    "storage_bench": (5500, "Storage Bench — a bench with a hidden compartment for storage."),
    "storage_cabinet": (8500, "Storage Cabinet — a furniture piece designed for general household storage."),
    "storage_chest": (5500, "Storage Chest — a box-like furniture piece used for storage."),
    "storage_furniture": (8500, "Storage Furniture — a general range of furniture pieces designed for storage."),
    "study_desk": (6500, "Study Desk — a desk designed for reading and studying."),
    "study_table": (6500, "Study Table — a table designed for reading and studying."),
    "sun_lounger": (8500, "Sun Lounger — a reclining outdoor chair designed for sunbathing."),
    "swing_chair": (12000, "Swing Chair — a suspended chair designed for relaxed outdoor seating."),
    "table_protector": (900, "Table Protector — a protective covering used to shield table surfaces."),
    "toddler_bed": (8500, "Toddler Bed — a small bed frame designed for young children."),
    "towel_rack": (1500, "Towel Rack — a rack used to hang and organize towels."),
    "toy_storage_unit": (5500, "Toy Storage Unit — a furniture piece designed for organizing children's toys."),
    "trundle_bed": (18000, "Trundle Bed — a bed frame with a secondary pull-out bed underneath."),
    "tv_stand": (8500, "TV Stand — a furniture piece designed to hold and display a television."),
    "umbrella_stand": (1500, "Umbrella Stand — a stand used to hold and store umbrellas."),
    "vanity_cabinet": (12000, "Vanity Cabinet — a furniture piece combining a sink counter and storage."),
    "vanity_stool": (2500, "Vanity Stool — a small stool designed for use at a vanity or dressing table."),
    "visitor_chair": (3500, "Visitor Chair — a chair designed for guest seating in offices."),
    "waiting_room_chair": (3500, "Waiting Room Chair — a chair designed for commercial waiting areas."),
    "wall_shelf": (1500, "Wall Shelf — a shelving unit designed for wall mounting."),
    "wardrobe": (18000, "Wardrobe — a furniture piece designed for clothing storage."),
    "wine_rack": (2500, "Wine Rack — a storage rack designed for organizing wine bottles."),
    "writing_desk": (7500, "Writing Desk — a compact desk designed for writing and light office work."),
}

files_map = {
    "data/products-placeholder.json": {},
    "data/products-placeholder-batch2.json": {},
}

updated = 0
skipped = []

for path in files_map:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    changed = False
    for sku, prod in data.items():
        if prod.get("categoryId") == "furniture_sofas_beds_etc":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
                changed = True
            else:
                skipped.append((sku, img))
    if changed:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
