import json

price_desc = {
    "pet_supplies": (400, "Pet Supplies — a general range of products for pet care and comfort."),
    "pet_bowl_toy_paw_icon": (300, "Pet Bowl & Toy Set — a bundled set of basic pet care essentials."),
    "dog_supplies": (500, "Dog Supplies — a general range of products designed for dog care."),
    "dog_food": (900, "Dog Food — a nutritionally balanced food formulated for dogs."),
    "puppy_food": (900, "Puppy Food — a specially formulated food designed for growing puppies."),
    "wet_dog_food": (250, "Wet Dog Food — a moist, canned food formulated for dogs."),
    "dry_dog_food": (1200, "Dry Dog Food — a kibble-based food formulated for dogs."),
    "dog_treats": (350, "Dog Treats — snacks designed as rewards for dogs."),
    "dog_chews": (350, "Dog Chews — durable chew items designed for dogs' dental health."),
    "dog_bowl": (350, "Dog Bowl — a bowl designed for feeding food or water to dogs."),
    "automatic_pet_feeder": (3500, "Automatic Pet Feeder — a device that dispenses food on a schedule."),
    "water_fountain": (1800, "Water Fountain — a flowing water dispenser designed for pets."),
    "dog_bed": (1500, "Dog Bed — a cushioned bed designed for dogs to rest comfortably."),
    "dog_house": (3500, "Dog House — an outdoor shelter designed for dogs."),
    "dog_crate": (2500, "Dog Crate — a portable enclosure used for containing and transporting dogs."),
    "dog_carrier": (1800, "Dog Carrier — a bag or case designed for transporting small dogs."),
    "dog_leash": (400, "Dog Leash — a strap used for walking and controlling a dog."),
    "retractable_leash": (700, "Retractable Leash — a leash with an adjustable, extendable cord."),
    "dog_collar": (350, "Dog Collar — a band worn around a dog's neck for identification and control."),
    "harness": (600, "Harness — a body strap designed to control a pet without neck pressure."),
    "dog_muzzle": (400, "Dog Muzzle — a device used to prevent biting or unwanted chewing."),
    "dog_toys": (350, "Dog Toys — a general range of toys designed for dogs."),
    "chew_toys": (300, "Chew Toys — durable toys designed for dogs to chew safely."),
    "rope_toys": (300, "Rope Toys — braided toys designed for tugging and chewing play."),
    "fetch_ball": (250, "Fetch Ball — a ball designed for playing fetch with a dog."),
    "dog_training_pads": (500, "Dog Training Pads — absorbent pads used for housetraining puppies."),
    "poop_bags": (250, "Poop Bags — disposable bags used for cleaning up after pets."),
    "dog_diapers": (500, "Dog Diapers — absorbent garments designed for dogs."),
    "cat_supplies": (500, "Cat Supplies — a general range of products designed for cat care."),
    "cat_food": (900, "Cat Food — a nutritionally balanced food formulated for cats."),
    "kitten_food": (900, "Kitten Food — a specially formulated food designed for growing kittens."),
    "wet_cat_food": (250, "Wet Cat Food — a moist, canned food formulated for cats."),
    "dry_cat_food": (1200, "Dry Cat Food — a kibble-based food formulated for cats."),
    "cat_treats": (350, "Cat Treats — snacks designed as rewards for cats."),
    "cat_bowl": (350, "Cat Bowl — a bowl designed for feeding food or water to cats."),
    "cat_water_fountain": (1800, "Cat Water Fountain — a flowing water dispenser designed for cats."),
    "cat_bed": (1500, "Cat Bed — a cushioned bed designed for cats to rest comfortably."),
    "cat_tree": (4500, "Cat Tree — a multi-level structure designed for cats to climb and rest."),
    "cat_scratching_post": (2000, "Cat Scratching Post — a post designed for cats to scratch and stretch."),
    "cat_tunnel": (900, "Cat Tunnel — a collapsible tunnel designed for cat play."),
    "cat_carrier": (1800, "Cat Carrier — a bag or case designed for transporting cats."),
    "cat_litter_box": (1200, "Cat Litter Box — a container designed for cat waste disposal."),
    "self_cleaning_litter_box": (12000, "Self-Cleaning Litter Box — an automated litter box that removes waste automatically."),
    "cat_litter": (700, "Cat Litter — absorbent material used to fill a litter box."),
    "litter_scoop": (200, "Litter Scoop — a scoop used for cleaning a litter box."),
    "cat_toys": (300, "Cat Toys — a general range of toys designed for cats."),
    "feather_wand": (350, "Feather Wand — an interactive toy used to engage cats in play."),
    "laser_toy": (450, "Laser Toy — a light-based toy used to stimulate cat play."),
    "catnip_toys": (300, "Catnip Toys — toys infused with catnip to attract and entertain cats."),
    "fish_aquarium": (2500, "Fish Aquarium — a general range of products for aquarium fish keeping."),
    "aquarium_tank": (3500, "Aquarium Tank — a glass or acrylic tank designed for keeping fish."),
    "fish_bowl": (500, "Fish Bowl — a small container designed for keeping a single fish."),
    "aquarium_stand": (2500, "Aquarium Stand — a stand designed to support an aquarium tank."),
    "aquarium_filter": (1500, "Aquarium Filter — a device used for filtering aquarium water."),
    "air_pump": (700, "Air Pump — a device used to oxygenate aquarium water."),
    "aquarium_heater": (900, "Aquarium Heater — a device used to regulate aquarium water temperature."),
    "aquarium_thermometer": (250, "Aquarium Thermometer — a tool used to monitor aquarium water temperature."),
    "led_aquarium_light": (1500, "LED Aquarium Light — a lighting fixture designed for aquarium tanks."),
    "aquarium_gravel": (400, "Aquarium Gravel — decorative substrate used at the bottom of aquariums."),
    "aquarium_sand": (400, "Aquarium Sand — fine substrate used at the bottom of aquariums."),
    "aquarium_plants": (350, "Aquarium Plants — decorative or live plants used in aquarium setups."),
    "aquarium_decorations": (500, "Aquarium Decorations — decorative items used to enhance an aquarium setup."),
    "fish_net": (200, "Fish Net — a small net used for catching and moving aquarium fish."),
    "fish_food": (250, "Fish Food — nutritionally formulated food for aquarium fish."),
    "water_conditioner": (350, "Water Conditioner — a solution used to treat and condition aquarium water."),
    "bird_supplies": (500, "Bird Supplies — a general range of products designed for bird care."),
    "bird_cage": (3500, "Bird Cage — an enclosure designed for housing pet birds."),
    "bird_stand": (1500, "Bird Stand — a stand designed for birds to perch on."),
    "bird_feeder": (500, "Bird Feeder — a container designed to hold and dispense bird food."),
    "bird_water_dispenser": (400, "Bird Water Dispenser — a container designed to provide drinking water for birds."),
    "bird_nest": (350, "Bird Nest — a small enclosure designed for birds to nest and rest."),
    "bird_perch": (350, "Bird Perch — a bar or branch designed for birds to sit on."),
    "bird_toys": (300, "Bird Toys — a general range of toys designed for pet birds."),
    "bird_food": (400, "Bird Food — nutritionally formulated food for pet birds."),
    "cuttlefish_bone": (150, "Cuttlefish Bone — a calcium-rich supplement used for bird beak health."),
    "small_animal_supplies": (500, "Small Animal Supplies — a general range of products for small pet care."),
    "rabbit_cage": (2500, "Rabbit Cage — an enclosure designed for housing pet rabbits."),
    "guinea_pig_cage": (2500, "Guinea Pig Cage — an enclosure designed for housing guinea pigs."),
    "hamster_cage": (1800, "Hamster Cage — an enclosure designed for housing hamsters."),
    "ferret_cage": (3500, "Ferret Cage — an enclosure designed for housing pet ferrets."),
    "rabbit_food": (500, "Rabbit Food — nutritionally formulated food for pet rabbits."),
    "hamster_food": (350, "Hamster Food — nutritionally formulated food for hamsters."),
    "hay_feeder": (500, "Hay Feeder — a container designed to hold hay for small animals."),
    "water_bottle": (300, "Water Bottle — a drip-feed bottle designed for small pets."),
    "exercise_wheel": (700, "Exercise Wheel — a spinning wheel designed for small pets to exercise."),
    "small_animal_bedding": (400, "Small Animal Bedding — absorbent material used for small pet enclosures."),
    "reptile_supplies": (500, "Reptile Supplies — a general range of products designed for reptile care."),
    "reptile_terrarium": (3500, "Reptile Terrarium — an enclosure designed for housing pet reptiles."),
    "heat_lamp": (900, "Heat Lamp — a lamp designed to provide warmth for reptile enclosures."),
    "uvb_lamp": (900, "UVB Lamp — a lamp designed to provide UVB light for reptile health."),
    "reptile_heating_pad": (700, "Reptile Heating Pad — a pad designed to provide warmth for reptile enclosures."),
    "thermometer": (250, "Thermometer — a tool used to monitor enclosure temperature."),
    "hygrometer": (300, "Hygrometer — a tool used to monitor enclosure humidity."),
    "reptile_hide": (500, "Reptile Hide — a shelter designed for reptiles to hide and rest."),
    "reptile_food": (400, "Reptile Food — nutritionally formulated food for pet reptiles."),
    "water_bowl": (300, "Water Bowl — a bowl designed for providing drinking water to pets."),
    "pet_grooming": (400, "Pet Grooming — a general range of products for pet grooming and hygiene."),
    "pet_shampoo": (450, "Pet Shampoo — a cleansing shampoo formulated for pets."),
    "pet_conditioner": (450, "Pet Conditioner — a conditioning product formulated for pet fur."),
    "grooming_brush": (350, "Grooming Brush — a brush designed for removing loose fur and detangling coats."),
    "deshedding_tool": (700, "Deshedding Tool — a tool designed to reduce shedding by removing loose undercoat."),
    "nail_clipper": (350, "Nail Clipper — a tool designed for trimming pet nails."),
    "nail_grinder": (900, "Nail Grinder — an electric tool designed for smoothing pet nails."),
    "pet_hair_trimmer": (2200, "Pet Hair Trimmer — a clipper designed for trimming pet fur."),
    "grooming_gloves": (350, "Grooming Gloves — gloves designed for removing loose fur while petting."),
    "ear_cleaner": (300, "Ear Cleaner — a solution used for cleaning pet ears."),
    "toothbrush": (200, "Toothbrush — a brush designed for cleaning pet teeth."),
    "pet_toothpaste": (350, "Pet Toothpaste — a toothpaste formulated safely for pets."),
    "grooming_wipes": (300, "Grooming Wipes — pre-moistened wipes used for quick pet cleaning."),
    "pet_health_wellness": (400, "Pet Health & Wellness — a general range of products supporting pet health."),
    "flea_comb": (200, "Flea Comb — a fine-toothed comb designed for removing fleas from fur."),
    "tick_remover": (250, "Tick Remover — a tool designed for safely removing ticks from pets."),
    "pet_vitamins": (700, "Pet Vitamins — dietary supplements formulated to support pet health."),
    "joint_supplements": (900, "Joint Supplements — supplements formulated to support pet joint health."),
    "calming_treats": (600, "Calming Treats — treats formulated to help reduce pet anxiety."),
    "dental_chews": (500, "Dental Chews — chew treats formulated to support pet dental health."),
    "recovery_collar": (450, "Recovery Collar — a protective collar used to prevent pets from licking wounds."),
    "pet_first_aid_kit": (1500, "Pet First Aid Kit — a kit containing essential supplies for pet emergencies."),
    "pet_travel": (500, "Pet Travel — a general range of products for traveling with pets."),
    "pet_carrier_bag": (1800, "Pet Carrier Bag — a comfortable bag designed for transporting small pets."),
    "pet_backpack": (2000, "Pet Backpack — a backpack-style carrier designed for pets."),
    "car_seat_cover": (900, "Car Seat Cover — a protective cover designed to shield car seats from pet fur and dirt."),
    "pet_car_seat": (2200, "Pet Car Seat — a secure seat designed for pets during car travel."),
    "travel_water_bottle": (400, "Travel Water Bottle — a portable water bottle designed for pets on the go."),
    "foldable_food_bowl": (300, "Foldable Food Bowl — a collapsible bowl designed for travel convenience."),
    "travel_crate": (2500, "Travel Crate — a secure crate designed for pet travel."),
    "pet_clothing": (500, "Pet Clothing — a general range of clothing designed for pets."),
    "dog_jacket": (700, "Dog Jacket — a warm outer garment designed for dogs in cold weather."),
    "dog_sweater": (600, "Dog Sweater — a knit garment designed to keep dogs warm."),
    "raincoat": (700, "Raincoat — a waterproof garment designed to keep pets dry in the rain."),
    "pet_boots": (600, "Pet Boots — protective footwear designed for pets."),
    "pet_bandana": (200, "Pet Bandana — a decorative fabric accessory worn around a pet's neck."),
    "pet_costume": (900, "Pet Costume — a decorative outfit designed for pets."),
    "pet_training": (400, "Pet Training — a general range of products used for pet training."),
    "clicker": (150, "Clicker — a small device used for clicker-based pet training."),
    "training_whistle": (250, "Training Whistle — a whistle used for signal-based pet training."),
    "agility_tunnel": (1500, "Agility Tunnel — a collapsible tunnel used for pet agility training."),
    "training_pads": (500, "Training Pads — absorbent pads used for housetraining pets."),
    "treat_pouch": (400, "Treat Pouch — a pouch designed for carrying training treats."),
    "training_leash": (400, "Training Leash — a leash designed for obedience training."),
    "pet_cleaning": (300, "Pet Cleaning — a general range of products for pet-related cleaning."),
    "litter_mat": (450, "Litter Mat — a mat placed under a litter box to catch stray litter."),
    "litter_box_liners": (300, "Litter Box Liners — disposable liners used to simplify litter box cleaning."),
    "odor_remover": (400, "Odor Remover — a solution formulated to eliminate pet odors."),
    "stain_remover": (400, "Stain Remover — a solution formulated to remove pet stains."),
    "pet_hair_roller": (250, "Pet Hair Roller — a roller tool used for removing pet hair from surfaces."),
    "vacuum_attachment_for_pet_hair": (700, "Vacuum Attachment for Pet Hair — a specialized attachment for removing pet hair."),
    "pet_furniture": (900, "Pet Furniture — a general range of furniture designed for pets."),
    "pet_sofa": (3500, "Pet Sofa — a small couch designed for pet comfort."),
    "pet_stairs": (1800, "Pet Stairs — steps designed to help pets access furniture."),
    "pet_ramp": (1800, "Pet Ramp — a ramp designed to help pets access furniture or vehicles."),
    "window_perch": (900, "Window Perch — a mounted seat designed for cats to sit by a window."),
    "pet_playpen": (2500, "Pet Playpen — a portable enclosure designed for pet play and containment."),
    "outdoor_kennel": (5500, "Outdoor Kennel — an outdoor enclosure designed for housing dogs."),
    "farm_poultry_supplies": (500, "Farm & Poultry Supplies — a general range of products for poultry care."),
    "chicken_feeder": (700, "Chicken Feeder — a container designed to dispense feed for poultry."),
    "chicken_waterer": (700, "Chicken Waterer — a container designed to provide drinking water for poultry."),
    "poultry_cage": (2500, "Poultry Cage — an enclosure designed for housing poultry."),
    "bird_incubator": (5500, "Bird Incubator — a device designed for incubating bird eggs."),
    "nesting_box": (900, "Nesting Box — a box designed for poultry to lay eggs."),
    "poultry_feed": (900, "Poultry Feed — nutritionally formulated feed for poultry."),
    "pet_accessories": (400, "Pet Accessories — a general range of accessory items for pets."),
    "id_tag": (200, "ID Tag — a small tag used for pet identification."),
    "gps_pet_tracker": (3500, "GPS Pet Tracker — a wearable device used to track a pet's location."),
    "led_collar": (500, "LED Collar — a light-up collar designed for pet visibility at night."),
    "bell_collar": (250, "Bell Collar — a collar fitted with a bell for locating a pet by sound."),
    "personalized_pet_tag": (350, "Personalized Pet Tag — a custom-engraved tag for pet identification."),
    "pet_bowl_mat": (350, "Pet Bowl Mat — a mat placed under food and water bowls to catch spills."),
    "food_storage_container": (700, "Food Storage Container — a sealed container used to store pet food."),
    "treat_jar": (400, "Treat Jar — a container designed for storing pet treats."),
    "pet_toys": (350, "Pet Toys — a general range of toys designed for pets."),
    "interactive_toys": (700, "Interactive Toys — toys designed to mentally stimulate pets."),
    "puzzle_toys": (700, "Puzzle Toys — toys designed to challenge pets and reward problem-solving."),
    "plush_toys": (300, "Plush Toys — soft stuffed toys designed for pet play."),
    "squeaky_toys": (300, "Squeaky Toys — toys that produce sound to engage pets in play."),
    "tug_toys": (300, "Tug Toys — durable toys designed for interactive tug-of-war play."),
    "ball_launcher": (900, "Ball Launcher — a tool designed to throw balls for fetch play."),
    "aquarium_accessories": (500, "Aquarium Accessories — a general range of accessories for aquarium setups."),
    "co2_system": (3500, "CO2 System — a system used to supply carbon dioxide for planted aquariums."),
    "protein_skimmer": (5500, "Protein Skimmer — a device used to remove organic waste from aquarium water."),
    "aquarium_test_kit": (700, "Aquarium Test Kit — a kit used for testing aquarium water quality."),
    "automatic_fish_feeder": (2200, "Automatic Fish Feeder — a device that dispenses fish food on a schedule."),
    "aquarium_background": (500, "Aquarium Background — a decorative backing used behind an aquarium tank."),
    "cleaning_magnet": (700, "Cleaning Magnet — a magnetic tool used for cleaning aquarium glass."),
    "bird_accessories": (400, "Bird Accessories — a general range of accessories for pet birds."),
    "cage_cover": (500, "Cage Cover — a fabric cover designed for bird cages."),
    "swing_perch": (500, "Swing Perch — a swinging perch designed for birds."),
    "bird_bath": (500, "Bird Bath — a small basin designed for birds to bathe."),
    "bird_ladder": (350, "Bird Ladder — a ladder accessory designed for birds to climb."),
    "foraging_toy": (500, "Foraging Toy — a toy designed to encourage natural foraging behavior in birds."),
    "seasonal_pet_supplies": (500, "Seasonal Pet Supplies — a general range of products for seasonal pet care."),
    "cooling_mat": (900, "Cooling Mat — a mat designed to help pets stay cool in warm weather."),
    "heated_pet_bed": (2500, "Heated Pet Bed — a bed designed to provide warmth for pets in cold weather."),
    "cooling_vest": (900, "Cooling Vest — a vest designed to help keep pets cool in hot weather."),
    "reflective_safety_vest": (600, "Reflective Safety Vest — a vest designed to improve pet visibility at night."),
    "life_jacket_for_dogs": (1500, "Life Jacket for Dogs — a flotation vest designed for water safety."),
}

files_map = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch3.json",
]

updated = 0
skipped = []

for path in files_map:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    changed = False
    for sku, prod in data.items():
        if prod.get("categoryId") == "pet_supplies":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
                changed = True
            else:
                skipped.append((path, sku, img))
    if changed:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
