import json

price_desc = {
    "aac_blocks": (65, "AAC Blocks — lightweight autoclaved aerated concrete blocks used in construction."),
    "acoustic_panels": (900, "Acoustic Panels — sound-absorbing panels used to reduce noise in interior spaces."),
    "adhesives_sealants": (350, "Adhesives & Sealants — bonding and sealing materials used in construction."),
    "air_duct": (900, "Air Duct — a channel used to distribute air through HVAC systems."),
    "aluminum_door": (12000, "Aluminum Door — a durable door made from aluminum framing."),
    "aluminum_ladder": (4500, "Aluminum Ladder — a lightweight, durable ladder used for construction and maintenance."),
    "aluminum_profile": (450, "Aluminum Profile — extruded aluminum bars used in construction and fabrication."),
    "aluminum_sheet": (900, "Aluminum Sheet — flat aluminum panels used in construction and manufacturing."),
    "aluminum_window": (8500, "Aluminum Window — a durable window frame made from aluminum."),
    "anchors": (50, "Anchors — fasteners used to secure materials into concrete or masonry."),
    "artificial_grass": (350, "Artificial Grass — synthetic turf used for landscaping and outdoor surfaces."),
    "asphalt_shingles": (450, "Asphalt Shingles — roofing material used for residential roof covering."),
    "ball_valve": (450, "Ball Valve — a plumbing valve used to control fluid flow."),
    "bitumen_sheet": (900, "Bitumen Sheet — a waterproofing membrane used for roofing applications."),
    "bolts": (20, "Bolts — threaded fasteners used to join construction materials."),
    "bricks_cement_bags_construction_materials": (500, "Bricks, Cement & Construction Materials Set — a bundled set of core building materials."),
    "bricks_masonry": (12, "Bricks & Masonry — clay or concrete bricks used for building walls and structures."),
    "cable_trunking": (450, "Cable Trunking — a protective channel used to route and organize electrical cables."),
    "carpet_tiles": (450, "Carpet Tiles — modular flooring tiles designed for easy installation and replacement."),
    "ceiling_tiles": (150, "Ceiling Tiles — panels used for suspended ceiling installations."),
    "cement": (550, "Cement — a binding material used as the foundation for concrete and mortar."),
    "cement_concrete": (600, "Cement Concrete — a mixed building material used for structural construction."),
    "cement_mixer": (35000, "Cement Mixer — a machine used to mix cement, sand, and water for construction."),
    "ceramic_tiles": (60, "Ceramic Tiles — glazed tiles used for flooring and wall applications."),
    "chain_link_fence": (350, "Chain Link Fence — a woven wire fence used for boundary and security fencing."),
    "circuit_breaker_mcb": (450, "Circuit Breaker (MCB) — an electrical safety device used to protect circuits from overload."),
    "clay_bricks": (12, "Clay Bricks — traditional fired bricks used in masonry construction."),
    "concrete_blocks": (60, "Concrete Blocks — precast blocks used for building walls and foundations."),
    "concrete_bricks": (25, "Concrete Bricks — solid bricks made from cast concrete for construction."),
    "concrete_pavers": (85, "Concrete Pavers — precast concrete units used for paving walkways and driveways."),
    "concrete_pipes": (1500, "Concrete Pipes — precast pipes used for drainage and sewerage systems."),
    "concrete_vibrator": (8500, "Concrete Vibrator — a tool used to remove air bubbles from poured concrete."),
    "construction_adhesive": (350, "Construction Adhesive — a strong bonding agent used for construction materials."),
    "construction_building_materials": (500, "Construction & Building Materials — a general range of construction supplies."),
    "construction_tools": (900, "Construction Tools — a general range of hand and power tools used in construction."),
    "copper_pipe": (900, "Copper Pipe — durable piping used for plumbing and water supply systems."),
    "cpvc_pipe": (250, "CPVC Pipe — a plastic pipe used for hot and cold water plumbing."),
    "crack_filler": (350, "Crack Filler — a compound used to repair cracks in walls and surfaces."),
    "crushed_stone": (900, "Crushed Stone — aggregate material used as a base for construction projects."),
    "decorative_stones": (450, "Decorative Stones — ornamental stones used for landscaping and design."),
    "decorative_wall_cladding": (900, "Decorative Wall Cladding — panels used to enhance interior and exterior wall aesthetics."),
    "distribution_board": (3500, "Distribution Board — an electrical panel used to distribute power to circuits."),
    "door_handles": (450, "Door Handles — hardware used for opening and closing doors."),
    "doors_windows": (8500, "Doors & Windows — a general range of door and window products."),
    "drawer_slides": (250, "Drawer Slides — hardware used for smooth drawer movement in cabinetry."),
    "drywall_panels": (700, "Drywall Panels — gypsum-based panels used for interior wall construction."),
    "duct_insulation": (450, "Duct Insulation — material used to insulate HVAC ductwork."),
    "dust_mask": (100, "Dust Mask — protective gear used to filter airborne dust particles."),
    "ear_protection": (350, "Ear Protection — safety gear used to protect hearing at construction sites."),
    "electrical_cable": (900, "Electrical Cable — wiring used for electrical power distribution."),
    "electrical_materials": (900, "Electrical Materials — a general range of electrical construction supplies."),
    "electrical_socket": (150, "Electrical Socket — a wall outlet used to connect electrical devices."),
    "electrical_switch": (150, "Electrical Switch — a device used to control electrical circuits."),
    "electrical_wire": (450, "Electrical Wire — conductive wiring used in electrical installations."),
    "epoxy_adhesive": (450, "Epoxy Adhesive — a strong two-part adhesive used for bonding materials."),
    "epoxy_coating": (900, "Epoxy Coating — a protective coating used for floors and surfaces."),
    "exhaust_fan": (2500, "Exhaust Fan — a ventilation fan used to remove air and moisture from a space."),
    "expanded_metal": (900, "Expanded Metal — a mesh material used for fencing and architectural applications."),
    "extension_ladder": (6500, "Extension Ladder — an adjustable ladder used for reaching greater heights."),
    "exterior_paint": (900, "Exterior Paint — weather-resistant paint designed for outdoor surfaces."),
    "fasteners_hardware": (350, "Fasteners & Hardware — a general range of construction fastening components."),
    "faucets": (900, "Faucets — plumbing fixtures used to control water flow at sinks and basins."),
    "fence_posts": (450, "Fence Posts — support posts used for installing fencing."),
    "fencing_gates": (3500, "Fencing & Gates — a general range of fencing and gate products."),
    "fiberglass_insulation": (450, "Fiberglass Insulation — insulating material used for thermal control in buildings."),
    "fiberglass_ladder": (5500, "Fiberglass Ladder — a durable, non-conductive ladder suited for electrical work."),
    "floor_adhesive": (450, "Floor Adhesive — a bonding agent used to install flooring materials."),
    "flooring_materials": (450, "Flooring Materials — a general range of products used for floor installation."),
    "fly_ash_bricks": (10, "Fly Ash Bricks — eco-friendly bricks made from industrial fly ash byproduct."),
    "foam_insulation": (450, "Foam Insulation — a lightweight insulating material used for thermal control."),
    "frosted_glass": (900, "Frosted Glass — translucent glass used for privacy in windows and doors."),
    "galvanized_steel": (900, "Galvanized Steel — steel coated with zinc for corrosion resistance."),
    "garden_edging": (450, "Garden Edging — border material used to define garden and landscaping areas."),
    "garden_pavers": (85, "Garden Pavers — precast units used for garden pathways and patios."),
    "gate_valve": (700, "Gate Valve — a plumbing valve used to control the flow of water."),
    "glass_blocks": (350, "Glass Blocks — decorative blocks used for walls with light transmission."),
    "glass_door": (12000, "Glass Door — a door constructed with tempered glass panels."),
    "glass_products": (900, "Glass Products — a general range of glass materials for construction."),
    "granite_chips": (900, "Granite Chips — crushed granite used for decorative and construction purposes."),
    "granite_tiles": (250, "Granite Tiles — natural stone tiles used for flooring and countertops."),
    "gravel": (900, "Gravel — loose aggregate material used as a construction base."),
    "grout": (250, "Grout — a filler material used to fill gaps between tiles."),
    "gypsum_board": (700, "Gypsum Board — panels used for interior wall and ceiling construction."),
    "hardwood_timber": (1500, "Hardwood Timber — durable wood used for structural and finishing applications."),
    "hdpe_pipe": (450, "HDPE Pipe — durable plastic piping used for water supply and drainage."),
    "hinges": (100, "Hinges — hardware used to allow doors and cabinets to pivot open and closed."),
    "hollow_blocks": (35, "Hollow Blocks — lightweight concrete blocks with hollow cores used in construction."),
    "hvac_filters": (450, "HVAC Filters — filters used to maintain air quality in HVAC systems."),
    "hvac_materials": (900, "HVAC Materials — a general range of heating and cooling system components."),
    "insulation_materials": (450, "Insulation Materials — a general range of products used for thermal insulation."),
    "interior_paint": (900, "Interior Paint — paint formulated for indoor wall and ceiling surfaces."),
    "junction_box": (150, "Junction Box — an enclosure used to safely house electrical wire connections."),
    "ladders_scaffolding": (6500, "Ladders & Scaffolding — a general range of access equipment for construction."),
    "laminate_flooring": (450, "Laminate Flooring — synthetic flooring designed to mimic natural wood or stone."),
    "laminated_board": (900, "Laminated Board — engineered board with a decorative laminate surface."),
    "laminated_glass": (1500, "Laminated Glass — safety glass constructed with an interlayer for strength."),
    "landscaping_materials": (450, "Landscaping Materials — a general range of products used for outdoor landscaping."),
    "limestone": (900, "Limestone — natural stone material used in construction and decoration."),
    "locks": (450, "Locks — security hardware used to secure doors and gates."),
    "manufactured_sand_m_sand": (900, "Manufactured Sand (M-Sand) — crushed stone sand used as an alternative to natural sand."),
    "marble_tiles": (450, "Marble Tiles — natural stone tiles used for flooring and wall finishes."),
    "mason_hammer": (450, "Mason Hammer — a hand tool used for masonry work."),
    "masonry_sand": (900, "Masonry Sand — fine sand used for mortar and masonry applications."),
    "mdf_board": (700, "MDF Board — engineered wood panel used for furniture and construction."),
    "measuring_tape": (250, "Measuring Tape — a tool used to measure length in construction projects."),
    "metal_angle": (350, "Metal Angle — L-shaped metal bars used for structural framing."),
    "metal_gate": (8500, "Metal Gate — a durable gate constructed from steel or iron."),
    "metal_paint": (900, "Metal Paint — paint formulated for protecting and finishing metal surfaces."),
    "metal_roofing_sheets": (900, "Metal Roofing Sheets — durable sheets used for roof covering."),
    "mirror_glass": (900, "Mirror Glass — reflective glass used for mirrors and decorative purposes."),
    "modular_building_panels": (2500, "Modular Building Panels — prefabricated panels used for quick building construction."),
    "mortar_mix": (450, "Mortar Mix — a blended material used for bonding bricks and blocks."),
    "nails": (100, "Nails — metal fasteners used to join construction materials."),
    "nuts": (20, "Nuts — threaded fasteners used with bolts to secure materials."),
    "osb_board": (700, "OSB Board — an engineered wood panel used for structural sheathing."),
    "paint_coatings": (900, "Paint & Coatings — a general range of paint and protective coating products."),
    "paint_thinner": (350, "Paint Thinner — a solvent used to thin paint and clean equipment."),
    "particle_board": (600, "Particle Board — an engineered wood panel used for furniture and construction."),
    "pebbles": (450, "Pebbles — small decorative stones used for landscaping."),
    "pipe_fittings": (150, "Pipe Fittings — components used to connect and adapt sections of piping."),
    "plaster": (350, "Plaster — a material used to coat and finish interior walls and ceilings."),
    "plumbing_materials": (450, "Plumbing Materials — a general range of products used in plumbing systems."),
    "plywood": (900, "Plywood — engineered wood panels used for construction and furniture."),
    "polycarbonate_roofing_sheet": (900, "Polycarbonate Roofing Sheet — a durable, translucent sheet used for roofing."),
    "porcelain_tiles": (250, "Porcelain Tiles — dense, durable tiles used for flooring and walls."),
    "portable_cabin": (150000, "Portable Cabin — a prefabricated structure used for temporary housing or offices."),
    "ppr_pipe": (250, "PPR Pipe — a plastic pipe used for hot and cold water plumbing systems."),
    "prefabricated_building_materials": (2500, "Prefabricated Building Materials — pre-manufactured components used for rapid construction."),
    "primer": (450, "Primer — a preparatory coating applied before paint for better adhesion."),
    "pu_foam": (450, "PU Foam — an expanding foam sealant used for gap filling and insulation."),
    "pvc_ceiling_panels": (450, "PVC Ceiling Panels — lightweight panels used for ceiling installation."),
    "pvc_conduit": (150, "PVC Conduit — plastic tubing used to protect electrical wiring."),
    "pvc_pipe": (250, "PVC Pipe — plastic piping used for plumbing and drainage systems."),
    "ready_mix_concrete": (5500, "Ready Mix Concrete — pre-mixed concrete delivered ready for use in construction."),
    "reflective_insulation": (450, "Reflective Insulation — insulation material that reflects radiant heat."),
    "retaining_wall_blocks": (85, "Retaining Wall Blocks — precast blocks used to build supportive retaining walls."),
    "river_sand": (900, "River Sand — natural sand used in concrete and construction applications."),
    "rock_wool": (450, "Rock Wool — mineral fiber insulation used for thermal and sound insulation."),
    "roof_coating": (900, "Roof Coating — a protective layer applied to roofs for waterproofing."),
    "roof_insulation": (450, "Roof Insulation — material used to regulate temperature through the roof."),
    "roof_tiles": (60, "Roof Tiles — durable tiles used for roof covering."),
    "roofing_materials": (900, "Roofing Materials — a general range of products used for roof construction."),
    "roofing_nails": (150, "Roofing Nails — specialized nails used for securing roofing materials."),
    "safety_boots": (1500, "Safety Boots — protective footwear designed for construction work."),
    "safety_equipment": (900, "Safety Equipment — a general range of personal protective gear for construction."),
    "safety_gloves": (250, "Safety Gloves — protective gloves used to guard hands during construction work."),
    "safety_goggles": (250, "Safety Goggles — protective eyewear used to guard eyes from construction hazards."),
    "safety_helmet": (450, "Safety Helmet — protective headgear used at construction sites."),
    "safety_vest": (450, "Safety Vest — a high-visibility vest worn for safety at construction sites."),
    "sand_stone_aggregates": (900, "Sand & Stone Aggregates — a general range of aggregate materials for construction."),
    "sandwich_panels": (900, "Sandwich Panels — insulated panels used for wall and roof construction."),
    "scaffold_planks": (900, "Scaffold Planks — wooden or metal boards used as scaffolding platforms."),
    "scaffolding_frame": (3500, "Scaffolding Frame — a modular frame system used for construction access."),
    "screws": (50, "Screws — threaded fasteners used to join construction materials."),
    "shovel": (450, "Shovel — a hand tool used for digging and moving materials."),
    "shower_set": (2500, "Shower Set — a complete plumbing fixture set for showers."),
    "silicone_sealant": (350, "Silicone Sealant — a flexible sealant used to seal gaps and joints."),
    "sliding_door": (12000, "Sliding Door — a space-saving door that opens by sliding along a track."),
    "softwood_timber": (900, "Softwood Timber — lightweight wood used for general construction purposes."),
    "solid_blocks": (45, "Solid Blocks — dense concrete blocks used for load-bearing walls."),
    "spirit_level": (450, "Spirit Level — a tool used to check surfaces for level and plumb."),
    "spray_paint": (450, "Spray Paint — aerosol paint used for quick and even surface coating."),
    "stainless_steel_sheet": (2500, "Stainless Steel Sheet — corrosion-resistant metal sheet used in construction."),
    "steel_door": (12000, "Steel Door — a durable, security-focused door made from steel."),
    "steel_metal_materials": (900, "Steel & Metal Materials — a general range of steel and metal construction products."),
    "steel_pipe": (900, "Steel Pipe — durable metal piping used in structural and plumbing applications."),
    "steel_rod_rebar": (900, "Steel Rod (Rebar) — reinforcing steel bars used in concrete construction."),
    "steel_sheet": (900, "Steel Sheet — flat steel panels used in construction and fabrication."),
    "steel_structure_components": (2500, "Steel Structure Components — parts used to assemble steel-framed structures."),
    "stone_blocks": (85, "Stone Blocks — natural stone units used for construction and landscaping."),
    "tempered_glass": (1500, "Tempered Glass — heat-treated glass known for its strength and safety properties."),
    "tile_adhesive": (450, "Tile Adhesive — a bonding compound used to install tiles."),
    "tile_cutter": (2500, "Tile Cutter — a tool used to accurately cut ceramic and porcelain tiles."),
    "tile_spacers": (100, "Tile Spacers — small tools used to maintain even gaps between tiles."),
    "trowel": (350, "Trowel — a hand tool used for applying and smoothing mortar or plaster."),
    "upvc_door": (12000, "UPVC Door — a durable, weather-resistant door made from UPVC material."),
    "upvc_window": (8500, "UPVC Window — a durable, weather-resistant window made from UPVC material."),
    "veneer": (450, "Veneer — a thin decorative wood layer applied to furniture and panels."),
    "ventilation_grilles": (350, "Ventilation Grilles — covers used to allow airflow through walls or ducts."),
    "vinyl_flooring": (450, "Vinyl Flooring — durable, water-resistant flooring material."),
    "wall_ceiling_materials": (900, "Wall & Ceiling Materials — a general range of products for wall and ceiling construction."),
    "wall_panels": (900, "Wall Panels — decorative or functional panels used for wall construction."),
    "wall_putty": (450, "Wall Putty — a smoothing compound applied to walls before painting."),
    "wallpaper": (450, "Wallpaper — decorative paper used to cover and finish interior walls."),
    "washers": (20, "Washers — flat fasteners used to distribute load under bolts and screws."),
    "water_pump": (12000, "Water Pump — machinery used to move water for construction or building use."),
    "water_tank": (8500, "Water Tank — a container used to store water for building use."),
    "waterproof_coating": (900, "Waterproof Coating — a protective coating used to prevent water infiltration."),
    "waterproof_membrane": (900, "Waterproof Membrane — a barrier material used to prevent water penetration."),
    "waterproof_sealant": (450, "Waterproof Sealant — a sealant used to prevent water leakage at joints."),
    "waterproofing_materials": (900, "Waterproofing Materials — a general range of products used to prevent water damage."),
    "welded_wire_fence": (450, "Welded Wire Fence — a durable fence made from welded wire mesh."),
    "wheelbarrow": (3500, "Wheelbarrow — a hand-pushed cart used for transporting construction materials."),
    "white_cement": (700, "White Cement — a decorative cement used for finishing and architectural work."),
    "window_glass": (900, "Window Glass — glass panels used for window installation."),
    "wire_mesh": (450, "Wire Mesh — a mesh material used for reinforcement and fencing."),
    "wood_glue": (250, "Wood Glue — an adhesive used to bond wood materials."),
    "wood_paint": (900, "Wood Paint — paint formulated for finishing and protecting wood surfaces."),
    "wood_timber": (900, "Wood Timber — general timber material used in construction."),
    "wooden_beams": (1500, "Wooden Beams — structural timber used for framing and support."),
    "wooden_door": (8500, "Wooden Door — a durable door made from natural wood."),
    "wooden_fence": (2500, "Wooden Fence — a fence constructed from wood for boundary and privacy."),
    "wooden_flooring": (900, "Wooden Flooring — natural wood flooring material."),
    "wooden_planks": (450, "Wooden Planks — flat wood boards used in construction and carpentry."),
    "wooden_window": (6500, "Wooden Window — a window frame constructed from natural wood."),
}

path = "data/products-placeholder.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
skipped = []
for sku, prod in data.items():
    if prod.get("categoryId") == "construction_building_materials":
        img = prod["images"]["main"].split("/")[-1].replace(".png", "")
        if img in price_desc:
            price, desc = price_desc[img]
            title = " ".join(w.capitalize() for w in img.split("_"))
            prod["title"] = title
            prod["price"] = price
            prod["description"] = desc
            prod["status"] = "active"
            updated += 1
        else:
            skipped.append((sku, img))

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
