import json

price_desc = {
    "aa_batteries": (150, "AA Batteries — standard batteries used to power everyday electronic devices."),
    "aaa_batteries": (150, "AAA Batteries — compact batteries used to power small electronic devices."),
    "action_camera": (12000, "Action Camera — a compact, durable camera designed for capturing adventure footage."),
    "air_fryer": (6500, "Air Fryer — a kitchen appliance that cooks food using hot air circulation."),
    "air_purifier": (8500, "Air Purifier — a device used to filter and clean indoor air."),
    "android_car_display": (6500, "Android Car Display — a touchscreen infotainment unit running Android."),
    "android_tv": (25000, "Android TV — a smart television running the Android TV operating system."),
    "ar_glasses": (35000, "AR Glasses — wearable eyewear that overlays digital content onto the real world."),
    "arduino_board": (900, "Arduino Board — a microcontroller board used for electronics prototyping."),
    "aroma_diffuser": (1800, "Aroma Diffuser — a device that disperses fragrance into a room."),
    "audio_devices": (2500, "Audio Devices — a general range of audio playback and recording equipment."),
    "audio_splitter": (250, "Audio Splitter — a device used to connect multiple headphones to one source."),
    "aux_cable": (250, "Aux Cable — a cable used to connect audio devices via a 3.5mm jack."),
    "barcode_scanner": (3500, "Barcode Scanner — a device used to read and process barcodes for retail."),
    "batteries_accessories": (350, "Batteries & Accessories — a general range of battery products and accessories."),
    "battery_charger": (1800, "Battery Charger — a device used to recharge rechargeable batteries."),
    "beard_trimmer": (1800, "Beard Trimmer — an electric grooming tool used to trim facial hair."),
    "blender": (3500, "Blender — a kitchen appliance used to mix and puree food and drinks."),
    "bluetooth_speaker": (2200, "Bluetooth Speaker — a wireless speaker used for portable audio playback."),
    "breadboard": (350, "Breadboard — a prototyping board used for building electronic circuits."),
    "button_cell_batteries": (100, "Button Cell Batteries — small round batteries used in compact devices."),
    "cable_organizer": (350, "Cable Organizer — a tool used to bundle and organize loose cables."),
    "cables_adapters": (450, "Cables & Adapters — a general range of connectivity cables and adapters."),
    "calculator": (450, "Calculator — a device used to perform mathematical calculations."),
    "camcorder": (25000, "Camcorder — a video camera designed for recording moving footage."),
    "cameras_video": (25000, "Cameras & Video — a general range of camera and video recording equipment."),
    "car_bluetooth_adapter": (900, "Car Bluetooth Adapter — a device used to add wireless audio streaming to a car."),
    "car_charger": (450, "Car Charger — a device used to charge electronics via a vehicle's power outlet."),
    "car_electronics": (2500, "Car Electronics — a general range of electronic accessories for vehicles."),
    "car_stereo": (3500, "Car Stereo — an audio system installed in the vehicle dashboard."),
    "car_vacuum_cleaner": (1500, "Car Vacuum Cleaner — a portable vacuum designed for cleaning vehicle interiors."),
    "card_reader": (700, "Card Reader — a device used to transfer files from memory cards to a computer."),
    "chargers_power": (900, "Chargers & Power — a general range of charging and power accessories."),
    "charging_cable": (350, "Charging Cable — a cable used to charge electronic devices."),
    "cleaning_kit": (450, "Cleaning Kit — a set of tools used to clean electronic devices and screens."),
    "coffee_maker": (5500, "Coffee Maker — a kitchen appliance used to brew coffee."),
    "computer_peripherals": (1500, "Computer Peripherals — a general range of computer accessories and devices."),
    "consumer_electronics": (1500, "Consumer Electronics — a general range of everyday electronic products."),
    "dash_cam": (3500, "Dash Cam — a camera mounted on the dashboard to record driving footage."),
    "dash_camera": (3500, "Dash Camera — a camera mounted on the dashboard to record driving footage."),
    "dehumidifier": (8500, "Dehumidifier — a device used to reduce moisture levels in the air."),
    "device_stand": (700, "Device Stand — a stand used to hold and position electronic devices."),
    "digital_photo_frame": (3500, "Digital Photo Frame — an electronic frame that displays digital photos."),
    "displayport_cable": (450, "DisplayPort Cable — a cable used to connect monitors for high-resolution display."),
    "docking_station": (5500, "Docking Station — a hub that expands a laptop or phone's connectivity options."),
    "document_scanner": (8500, "Document Scanner — a device used to digitize physical documents."),
    "electric_kettle": (2200, "Electric Kettle — an appliance used to quickly boil water."),
    "electric_massager": (3500, "Electric Massager — a device used to relieve muscle tension through vibration."),
    "electric_shaver": (2500, "Electric Shaver — an electric grooming device used for facial and body hair removal."),
    "electric_toothbrush": (1800, "Electric Toothbrush — a powered toothbrush used for effective dental cleaning."),
    "electronic_accessories": (700, "Electronic Accessories — a general range of accessories for electronic devices."),
    "electronic_components_diy": (450, "Electronic Components (DIY) — parts used for building and prototyping electronic projects."),
    "ethernet_cable": (450, "Ethernet Cable — a network cable used for wired internet connections."),
    "external_dvd_drive": (2500, "External DVD Drive — a portable drive used to read and write optical discs."),
    "external_hard_drive": (4500, "External Hard Drive — a portable storage device used for saving digital files."),
    "external_ssd": (8500, "External SSD — a fast, portable solid-state drive for data storage."),
    "facial_cleansing_brush": (1500, "Facial Cleansing Brush — an electric brush used to deep-clean facial skin."),
    "fan_heater": (2500, "Fan Heater — an electric heater that uses a fan to circulate warm air."),
    "fast_charger": (900, "Fast Charger — a charging adapter designed to quickly recharge devices."),
    "feature_phones": (2500, "Feature Phones — basic mobile phones designed for calling and texting."),
    "fitness_tracker": (3500, "Fitness Tracker — a wearable device used to monitor activity and health metrics."),
    "fm_radio": (1500, "FM Radio — a device used to receive and play FM radio broadcasts."),
    "foldable_phones": (85000, "Foldable Phones — smartphones featuring a folding display design."),
    "food_processor": (5500, "Food Processor — a kitchen appliance used to chop, blend, and mix food."),
    "gaming_console": (35000, "Gaming Console — a dedicated device used to play video games."),
    "gaming_controller": (3500, "Gaming Controller — a handheld device used to control video games."),
    "gaming_electronics": (5500, "Gaming Electronics — a general range of gaming devices and accessories."),
    "gaming_headset": (3500, "Gaming Headset — a headset designed for immersive gaming audio and communication."),
    "gaming_microphone": (3500, "Gaming Microphone — a microphone designed for streaming and gaming communication."),
    "gaming_mouse": (2500, "Gaming Mouse — a precision mouse designed for gaming performance."),
    "garment_steamer": (3500, "Garment Steamer — an appliance used to remove wrinkles from clothing using steam."),
    "gps_navigation_device": (4500, "GPS Navigation Device — a device that provides real-time route guidance."),
    "gps_watch": (8500, "GPS Watch — a wearable device with built-in GPS tracking for fitness and navigation."),
    "hair_clipper": (2200, "Hair Clipper — an electric tool used for cutting and trimming hair."),
    "hair_curler": (1800, "Hair Curler — an electric styling tool used to curl hair."),
    "hair_dryer": (2200, "Hair Dryer — an electric appliance used to dry and style hair."),
    "hair_straightener": (2200, "Hair Straightener — an electric styling tool used to straighten hair."),
    "hand_mixer": (2500, "Hand Mixer — a handheld kitchen appliance used to mix ingredients."),
    "handheld_gaming_console": (18000, "Handheld Gaming Console — a portable device used to play video games on the go."),
    "hdmi_adapter": (450, "HDMI Adapter — a device used to connect HDMI cables to different port types."),
    "hdmi_cable": (350, "HDMI Cable — a cable used to transmit high-definition audio and video."),
    "home_appliances_small": (2500, "Home Appliances (Small) — a general range of compact household appliances."),
    "home_theater_system": (25000, "Home Theater System — a multi-speaker setup designed for immersive home audio."),
    "humidifier": (3500, "Humidifier — a device that adds moisture to the air in a room."),
    "internet_radio": (3500, "Internet Radio — a device used to stream radio stations over the internet."),
    "juicer": (4500, "Juicer — a kitchen appliance used to extract juice from fruits and vegetables."),
    "jumper_wires": (250, "Jumper Wires — wires used to make electronic circuit connections."),
    "keyboard": (900, "Keyboard — an input device used for typing on computers."),
    "label_printer": (8500, "Label Printer — a device used to print adhesive labels."),
    "laminator": (3500, "Laminator — a device used to apply a protective plastic layer to documents."),
    "laptop_sleeve": (700, "Laptop Sleeve — a padded case used to protect a laptop during transport."),
    "led_tv": (35000, "LED TV — a television using LED backlighting for everyday viewing."),
    "lightning_cable": (450, "Lightning Cable — a charging and data cable designed for Apple devices."),
    "mechanical_keyboard": (3500, "Mechanical Keyboard — a keyboard using individual mechanical switches for tactile typing."),
    "memory_card": (900, "Memory Card — a portable storage card used in various devices."),
    "mesh_wi_fi_system": (12000, "Mesh Wi-Fi System — a networking system used to extend Wi-Fi coverage seamlessly."),
    "micro_usb_cable": (250, "Micro USB Cable — a cable used for charging and data transfer on older devices."),
    "microsd_card": (900, "MicroSD Card — a compact memory card used in mobile and computing devices."),
    "mini_led_tv": (55000, "Mini LED TV — a television using mini-LED backlighting for enhanced contrast."),
    "mini_projector": (8500, "Mini Projector — a compact projector designed for portable display needs."),
    "mixer_grinder": (4500, "Mixer Grinder — a kitchen appliance used to mix and grind ingredients."),
    "mobile_charger": (700, "Mobile Charger — a charging adapter designed for smartphones."),
    "modem": (3500, "Modem — a networking device used to connect to an internet service provider."),
    "mouse": (900, "Mouse — an input device used to control a cursor on a computer."),
    "mp3_player": (2500, "MP3 Player — a portable device used for playing digital audio files."),
    "multi_port_charger": (1500, "Multi Port Charger — a charging hub designed to charge multiple devices at once."),
    "multimeter": (2200, "Multimeter — an electrical testing tool used to measure voltage, current, and resistance."),
    "network_switch": (5500, "Network Switch — a networking device used to connect multiple devices on a LAN."),
    "networking_devices": (5500, "Networking Devices — a general range of equipment used to build computer networks."),
    "noise_cancelling_headphones": (8500, "Noise Cancelling Headphones — headphones designed to block ambient sound for immersive listening."),
    "office_electronics": (5500, "Office Electronics — a general range of electronic devices used for office productivity."),
    "oled_tv": (85000, "OLED TV — a television offering deep contrast and vibrant colors through OLED technology."),
    "on_ear_headphones": (2500, "On-Ear Headphones — headphones that rest on the ears for lightweight listening."),
    "otg_adapter": (250, "OTG Adapter — a device used to connect USB peripherals to mobile devices."),
    "over_ear_headphones": (5500, "Over-Ear Headphones — headphones that fully enclose the ears for immersive audio."),
    "paper_cutter": (1500, "Paper Cutter — a tool used to cut paper cleanly and precisely."),
    "personal_care_electronics": (2500, "Personal Care Electronics — a general range of electronic grooming and self-care devices."),
    "phone_case": (700, "Phone Case — a protective case designed for smartphones."),
    "portable_speaker": (2500, "Portable Speaker — a compact speaker used for audio playback on the go."),
    "power_bank": (2500, "Power Bank — a portable battery pack used to charge electronic devices."),
    "power_strip": (700, "Power Strip — a device with multiple outlets used to power several devices."),
    "projector": (25000, "Projector — a device used to display images or video onto a large screen."),
    "projector_screen": (5500, "Projector Screen — a surface used to display projected images and video."),
    "qled_tv": (65000, "QLED TV — a television using quantum dot technology for enhanced color and brightness."),
    "racing_wheel": (12000, "Racing Wheel — a gaming peripheral designed for racing game simulation."),
    "raspberry_pi": (5500, "Raspberry Pi — a small, affordable computer used for programming and DIY electronics."),
    "rechargeable_batteries": (450, "Rechargeable Batteries — reusable batteries designed for repeated charging cycles."),
    "reverse_camera": (2200, "Reverse Camera — a camera that assists the driver while reversing a vehicle."),
    "rice_cooker": (3500, "Rice Cooker — a kitchen appliance used to cook rice automatically."),
    "robot_vacuum": (25000, "Robot Vacuum — an automated vacuum cleaner that navigates and cleans floors independently."),
    "rugged_phones": (25000, "Rugged Phones — durable smartphones designed to withstand harsh conditions."),
    "sandwich_maker": (2500, "Sandwich Maker — a kitchen appliance used to toast and grill sandwiches."),
    "satellite_phones": (55000, "Satellite Phones — phones that connect via satellite for remote-area communication."),
    "screen_protector": (350, "Screen Protector — a protective film applied to a device's display."),
    "sd_card": (900, "SD Card — a memory card used to store data in cameras and computers."),
    "sensors": (700, "Sensors — electronic components used to detect and measure physical conditions."),
    "shredder": (5500, "Shredder — a device used to destroy sensitive documents."),
    "smart_alarm": (2500, "Smart Alarm — a connected alarm clock offering smart features and integrations."),
    "smart_band": (2500, "Smart Band — a wearable fitness band that tracks activity and health metrics."),
    "smart_bulb": (900, "Smart Bulb — a connected light bulb controllable via app or voice assistant."),
    "smart_door_lock": (8500, "Smart Door Lock — a connected lock offering keyless entry and remote control."),
    "smart_doorbell": (5500, "Smart Doorbell — a connected doorbell with camera and remote notification features."),
    "smart_home_devices": (3500, "Smart Home Devices — a general range of connected devices for home automation."),
    "smart_hub": (3500, "Smart Hub — a central device used to connect and control smart home devices."),
    "smart_plug": (900, "Smart Plug — a connected outlet that allows remote control of plugged-in devices."),
    "smart_ring": (12000, "Smart Ring — a wearable ring that tracks health and fitness metrics."),
    "smart_security_camera": (5500, "Smart Security Camera — a connected camera used for home monitoring and security."),
    "smart_sensor": (900, "Smart Sensor — a connected sensor used to detect motion, temperature, or other conditions."),
    "smart_speaker": (5500, "Smart Speaker — a voice-controlled speaker with virtual assistant integration."),
    "smart_switch": (900, "Smart Switch — a connected light switch controllable via app or voice assistant."),
    "smart_thermostat": (8500, "Smart Thermostat — a connected device used to control home temperature remotely."),
    "smart_tv": (45000, "Smart TV — a television with built-in internet connectivity and streaming apps."),
    "smartphone_smartwatch_earbuds": (2500, "Smartphone, Smartwatch & Earbuds Set — a bundled set of personal electronics."),
    "smartphones": (25000, "Smartphones — mobile devices offering internet, apps, and communication features."),
    "smartphones_mobile_devices": (25000, "Smartphones & Mobile Devices — a general range of mobile communication devices."),
    "smartwatch": (8500, "Smartwatch — a wearable device offering notifications and health tracking features."),
    "smartwatches_wearables": (8500, "Smartwatches & Wearables — a general range of wearable smart devices."),
    "soldering_kit": (1800, "Soldering Kit — a set of tools used for electronic soldering work."),
    "soundbar": (5500, "Soundbar — a compact speaker system used to enhance TV audio."),
    "steam_iron": (2500, "Steam Iron — an appliance used to press and remove wrinkles from clothing."),
    "stereo_system": (12000, "Stereo System — an audio setup designed for high-quality home music playback."),
    "storage_devices": (5500, "Storage Devices — a general range of internal and external data storage devices."),
    "streaming_media_player": (6500, "Streaming Media Player — a device used to stream video content to a TV."),
    "surge_protector": (1500, "Surge Protector — a device used to protect electronics from power surges."),
    "tablet_case": (900, "Tablet Case — a protective case designed for tablets."),
    "televisions_home_entertainment": (45000, "Televisions & Home Entertainment — a general range of TV and home entertainment products."),
    "tire_pressure_monitor": (2500, "Tire Pressure Monitor — a device used to track and alert on vehicle tire pressure."),
    "toaster": (2200, "Toaster — a kitchen appliance used to toast bread."),
    "travel_adapter": (900, "Travel Adapter — a device used to adapt plugs for international power outlets."),
    "tv_antenna": (900, "TV Antenna — a device used to receive over-the-air television signals."),
    "tv_box": (3500, "TV Box — a streaming device used to add smart features to a television."),
    "tv_wall_mount": (2500, "TV Wall Mount — a bracket used to mount a television on a wall."),
    "universal_adapter": (700, "Universal Adapter — a versatile plug adapter compatible with multiple socket types."),
    "universal_remote_control": (900, "Universal Remote Control — a remote designed to control multiple electronic devices."),
    "ups": (8500, "UPS — an uninterruptible power supply used to provide backup power for electronics."),
    "usb_adapter": (450, "USB Adapter — a device used to convert USB connection types."),
    "usb_c_cable": (350, "USB-C Cable — a reversible cable used for data transfer and charging."),
    "usb_flash_drive": (700, "USB Flash Drive — a portable storage device used for transferring digital files."),
    "usb_hub": (900, "USB Hub — a device used to expand the number of available USB ports."),
    "vacuum_cleaner": (8500, "Vacuum Cleaner — an appliance used to clean floors and surfaces."),
    "vga_cable": (350, "VGA Cable — a legacy cable used to connect displays with VGA ports."),
    "voice_recorder": (1800, "Voice Recorder — a device used to capture and store audio recordings."),
    "vr_gaming_headset": (35000, "VR Gaming Headset — a wearable device used for immersive virtual reality gaming."),
    "vr_headset": (35000, "VR Headset — a wearable device used for immersive virtual reality experiences."),
    "webcam": (2500, "Webcam — a camera designed for video calls and live streaming."),
    "wi_fi_range_extender": (1800, "Wi-Fi Range Extender — a device used to boost wireless network coverage."),
    "wi_fi_router": (3500, "Wi-Fi Router — a networking device used to provide wireless internet access."),
    "wired_earphones": (450, "Wired Earphones — in-ear headphones connected via cable for audio listening."),
    "wireless_charger": (1500, "Wireless Charger — a pad used to charge compatible devices without cables."),
    "wireless_earbuds": (3500, "Wireless Earbuds — compact in-ear headphones offering wireless audio listening."),
}

path = "data/products-placeholder.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
skipped = []
for sku, prod in data.items():
    if prod.get("categoryId") == "consumer_electronics":
        img = prod["images"]["main"].split("/")[-1].replace(".png", "")
        if img in price_desc:
            price, desc = price_desc[img]
            title = " ".join(w.capitalize() for w in img.split("_"))
            prod["title"] = title
            prod["price"] = price
            prod["description"] = desc
            prod["status"] = "active"
            updated += 1
        else:
            skipped.append((sku, img))

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
