import json

price_desc = {
    "makeup_skincare_fragrance": (500, "Makeup, Skincare & Fragrance — a general range of beauty products."),
    "perfume_bottle_lipstick_skincare_cream": (700, "Perfume, Lipstick & Skincare Cream Set — a bundled set of beauty essentials."),
    "face_makeup": (500, "Face Makeup — a general range of cosmetic products for the face."),
    "primer": (500, "Primer — a base makeup product used to smooth skin before foundation."),
    "foundation": (700, "Foundation — a cosmetic base product used to even out skin tone."),
    "bb_cream": (450, "BB Cream — a lightweight cream that combines skincare and light coverage."),
    "cc_cream": (450, "CC Cream — a color-correcting cream that blends skincare with light coverage."),
    "cushion_foundation": (900, "Cushion Foundation — a compact foundation applied with a sponge for a natural finish."),
    "concealer": (450, "Concealer — a cosmetic product used to cover blemishes and dark circles."),
    "color_corrector": (450, "Color Corrector — a cosmetic product used to neutralize skin discoloration."),
    "face_powder": (450, "Face Powder — a cosmetic powder used to set makeup and reduce shine."),
    "compact_powder": (450, "Compact Powder — a pressed powder used to set makeup and reduce shine."),
    "loose_powder": (450, "Loose Powder — a finely milled powder used to set makeup and control shine."),
    "setting_powder": (450, "Setting Powder — a translucent powder used to lock makeup in place."),
    "setting_spray": (500, "Setting Spray — a finishing spray used to extend the wear of makeup."),
    "makeup_fixing_spray": (500, "Makeup Fixing Spray — a spray used to set and prolong makeup wear."),
    "blush": (450, "Blush — a cosmetic product used to add color to the cheeks."),
    "bronzer": (500, "Bronzer — a cosmetic powder used to add warmth and a sun-kissed look to the skin."),
    "contour_stick": (500, "Contour Stick — a cosmetic stick used to sculpt and define facial features."),
    "contour_palette": (700, "Contour Palette — a set of shades used to sculpt and highlight the face."),
    "highlighter": (600, "Highlighter — a cosmetic product used to add a luminous glow to the skin."),
    "illuminator": (600, "Illuminator — a cosmetic product used to add radiant shine to the skin."),
    "eye_makeup": (500, "Eye Makeup — a general range of cosmetic products for the eyes."),
    "mascara": (450, "Mascara — a cosmetic product used to darken and volumize eyelashes."),
    "eyeliner": (400, "Eyeliner — a cosmetic product used to define and accentuate the eyes."),
    "kajal": (300, "Kajal — a soft eyeliner pencil traditionally used for eye definition."),
    "kohl_pencil": (300, "Kohl Pencil — a soft pencil used for eye definition."),
    "eyebrow_pencil": (350, "Eyebrow Pencil — a cosmetic pencil used to fill and define eyebrows."),
    "eyebrow_gel": (350, "Eyebrow Gel — a cosmetic gel used to shape and set eyebrows."),
    "eyebrow_powder": (450, "Eyebrow Powder — a powder used to fill and define eyebrows."),
    "eyeshadow_palette": (900, "Eyeshadow Palette — a set of coordinated eyeshadow colors for eye makeup."),
    "single_eyeshadow": (350, "Single Eyeshadow — an individual eyeshadow shade for eye makeup."),
    "eye_primer": (450, "Eye Primer — a base product used to prep eyelids before eyeshadow application."),
    "false_eyelashes": (300, "False Eyelashes — synthetic lashes applied to enhance natural lashes."),
    "eyelash_glue": (250, "Eyelash Glue — an adhesive used to apply false eyelashes."),
    "eyelash_curler": (350, "Eyelash Curler — a tool used to curl eyelashes before applying mascara."),
    "glitter_eyeshadow": (450, "Glitter Eyeshadow — a shimmering eyeshadow shade for eye makeup."),
    "lip_makeup": (450, "Lip Makeup — a general range of cosmetic products for the lips."),
    "lipstick": (450, "Lipstick — a cosmetic product used to add color to the lips."),
    "matte_lipstick": (450, "Matte Lipstick — a lipstick with a non-shiny, flat finish."),
    "liquid_lipstick": (500, "Liquid Lipstick — a long-wearing liquid formula that provides bold lip color."),
    "lip_gloss": (350, "Lip Gloss — a cosmetic product used to add shine and color to the lips."),
    "lip_tint": (350, "Lip Tint — a lightweight lip color offering a natural, sheer finish."),
    "lip_liner": (300, "Lip Liner — a cosmetic pencil used to outline and define the lips."),
    "lip_balm": (150, "Lip Balm — a moisturizing product used to soothe and protect lips."),
    "lip_mask": (400, "Lip Mask — a hydrating treatment used to nourish and repair dry lips."),
    "lip_scrub": (300, "Lip Scrub — an exfoliating product used to smooth and soften lips."),
    "lip_oil": (400, "Lip Oil — a nourishing oil product used to hydrate and add shine to lips."),
    "makeup_tools_accessories": (450, "Makeup Tools & Accessories — a general range of tools used for makeup application."),
    "makeup_brush_set": (900, "Makeup Brush Set — a coordinated set of brushes for makeup application."),
    "foundation_brush": (350, "Foundation Brush — a brush designed for applying liquid or cream foundation."),
    "powder_brush": (350, "Powder Brush — a brush designed for applying loose or pressed powder."),
    "blush_brush": (300, "Blush Brush — a brush designed for applying blush to the cheeks."),
    "eyeshadow_brush": (250, "Eyeshadow Brush — a brush designed for applying and blending eyeshadow."),
    "eyeliner_brush": (200, "Eyeliner Brush — a precision brush designed for applying eyeliner."),
    "makeup_sponge": (200, "Makeup Sponge — a blending sponge used for applying foundation and other makeup."),
    "beauty_blender": (350, "Beauty Blender — an egg-shaped sponge used for seamless makeup blending."),
    "powder_puff": (150, "Powder Puff — a soft pad used to apply loose or pressed powder."),
    "makeup_mirror": (700, "Makeup Mirror — a mirror designed for applying makeup with clarity."),
    "led_makeup_mirror": (1800, "LED Makeup Mirror — a lighted mirror designed for precise makeup application."),
    "makeup_organizer": (900, "Makeup Organizer — a storage unit used to organize cosmetics and beauty tools."),
    "cosmetic_bag": (450, "Cosmetic Bag — a bag designed to organize and carry makeup and beauty items."),
    "brush_cleaner": (350, "Brush Cleaner — a solution used to clean makeup brushes."),
    "brush_holder": (300, "Brush Holder — an organizer designed for storing makeup brushes."),
    "makeup_removers": (300, "Makeup Removers — a general range of products used to remove makeup."),
    "micellar_water": (350, "Micellar Water — a gentle cleansing water used to remove makeup and impurities."),
    "cleansing_balm": (600, "Cleansing Balm — a balm-to-oil cleanser used to remove makeup and impurities."),
    "cleansing_oil": (500, "Cleansing Oil — an oil-based cleanser used to dissolve makeup and dirt."),
    "makeup_remover_wipes": (250, "Makeup Remover Wipes — pre-moistened wipes used to remove makeup."),
    "eye_makeup_remover": (300, "Eye Makeup Remover — a gentle solution used to remove eye makeup."),
    "skincare_cleansers": (350, "Skincare Cleansers — a general range of facial cleansing products."),
    "face_wash": (300, "Face Wash — a cleanser used for daily facial cleansing."),
    "facial_cleanser": (350, "Facial Cleanser — a gentle cleansing product used to remove dirt and makeup."),
    "cleansing_foam": (350, "Cleansing Foam — a foaming facial cleanser used for daily skincare."),
    "cleansing_gel": (350, "Cleansing Gel — a gel-based facial cleanser used for daily skincare."),
    "cleansing_milk": (350, "Cleansing Milk — a gentle milky cleanser used for sensitive skin."),
    "facial_soap": (250, "Facial Soap — a mild soap bar formulated for facial cleansing."),
    "exfoliating_cleanser": (400, "Exfoliating Cleanser — a cleanser formulated to remove dead skin cells."),
    "skincare_toners_mists": (400, "Skincare Toners & Mists — a general range of hydrating facial toner products."),
    "facial_toner": (450, "Facial Toner — a liquid skincare product used to balance and refresh skin."),
    "hydrating_toner": (450, "Hydrating Toner — a moisturizing toner formulated for skin hydration."),
    "rose_water": (250, "Rose Water — a floral toner used to refresh and hydrate the skin."),
    "face_mist": (400, "Face Mist — a hydrating spray used to refresh and set makeup."),
    "setting_mist": (450, "Setting Mist — a finishing spray used to lock in makeup."),
    "skincare_serums_treatments": (700, "Skincare Serums & Treatments — a general range of targeted skincare treatments."),
    "vitamin_c_serum": (900, "Vitamin C Serum — a brightening serum formulated to even skin tone."),
    "hyaluronic_acid_serum": (900, "Hyaluronic Acid Serum — a hydrating serum formulated to plump and moisturize skin."),
    "niacinamide_serum": (700, "Niacinamide Serum — a serum formulated to refine pores and even skin tone."),
    "retinol_serum": (900, "Retinol Serum — an anti-aging treatment formulated to improve skin texture."),
    "peptide_serum": (900, "Peptide Serum — a serum formulated to support skin firmness and elasticity."),
    "brightening_serum": (700, "Brightening Serum — a serum formulated to even and brighten skin tone."),
    "acne_treatment_gel": (350, "Acne Treatment Gel — a targeted gel formulated to reduce breakouts and blemishes."),
    "dark_spot_corrector": (700, "Dark Spot Corrector — a targeted treatment formulated to reduce dark spots."),
    "moisturizers": (500, "Moisturizers — a general range of hydrating skincare products."),
    "face_cream": (500, "Face Cream — a moisturizing cream formulated for daily facial skincare."),
    "day_cream": (500, "Day Cream — a lightweight moisturizer designed for daytime skincare."),
    "night_cream": (600, "Night Cream — a nourishing cream formulated for overnight skin repair."),
    "moisturizer": (500, "Moisturizer — a hydrating skincare product used for daily skin care."),
    "gel_moisturizer": (500, "Gel Moisturizer — a lightweight, water-based hydrating skincare product."),
    "face_lotion": (450, "Face Lotion — a lightweight lotion used for daily facial hydration."),
    "facial_oil": (600, "Facial Oil — a nourishing oil used to moisturize and enhance skin radiance."),
    "sun_protection": (500, "Sun Protection — a general range of products used to protect skin from UV rays."),
    "sunscreen_lotion": (500, "Sunscreen Lotion — a protective lotion used to prevent sun damage to the skin."),
    "sunscreen_cream": (500, "Sunscreen Cream — a protective cream used to prevent sun damage to the skin."),
    "sunscreen_gel": (500, "Sunscreen Gel — a lightweight gel formulated to protect skin from UV rays."),
    "sunscreen_stick": (450, "Sunscreen Stick — a portable stick formulated to protect skin from UV rays."),
    "tinted_sunscreen": (600, "Tinted Sunscreen — a sunscreen formulated with light coverage and UV protection."),
    "after_sun_gel": (450, "After Sun Gel — a soothing gel used to calm skin after sun exposure."),
    "face_masks": (400, "Face Masks — a general range of skincare treatments applied to the face."),
    "sheet_mask": (150, "Sheet Mask — a fabric mask soaked in serum used for quick skin hydration."),
    "clay_mask": (400, "Clay Mask — a purifying face mask formulated to draw out impurities."),
    "peel_off_mask": (350, "Peel-Off Mask — a face mask that hardens and peels away to remove impurities."),
    "sleeping_mask": (600, "Sleeping Mask — an overnight treatment mask used for deep hydration."),
    "gel_mask": (400, "Gel Mask — a cooling, hydrating mask formulated for soothing skincare."),
    "charcoal_mask": (400, "Charcoal Mask — a detoxifying mask formulated to draw out impurities."),
    "body_care": (400, "Body Care — a general range of skincare products for the body."),
    "body_lotion": (350, "Body Lotion — a moisturizing lotion used for everyday skin hydration."),
    "body_butter": (500, "Body Butter — a rich moisturizing cream used to nourish dry skin."),
    "body_cream": (450, "Body Cream — a nourishing cream used for daily body skincare."),
    "body_oil": (450, "Body Oil — a nourishing oil used to moisturize and soften the skin."),
    "body_scrub": (450, "Body Scrub — an exfoliating product used to remove dead skin cells."),
    "shower_gel": (350, "Shower Gel — a liquid cleanser used for daily bathing."),
    "body_wash": (350, "Body Wash — a liquid cleanser used for daily body cleansing."),
    "bath_salts": (350, "Bath Salts — a mineral salt blend used to relax muscles in a warm bath."),
    "bath_bomb": (300, "Bath Bomb — a fizzing bath product that releases fragrance and moisturizing oils."),
    "hand_cream": (350, "Hand Cream — a moisturizing cream formulated for dry hands."),
    "foot_cream": (400, "Foot Cream — a moisturizing cream formulated for dry, cracked feet."),
    "fragrance": (900, "Fragrance — a general range of scented personal care products."),
    "perfume": (1800, "Perfume — a fragranced product used for personal scent enhancement."),
    "eau_de_parfum": (1800, "Eau De Parfum — a long-lasting concentrated fragrance."),
    "eau_de_toilette": (1200, "Eau De Toilette — a lighter concentration fragrance suited for daily wear."),
    "eau_de_cologne": (900, "Eau De Cologne — a light, refreshing fragrance for everyday wear."),
    "perfume_oil": (700, "Perfume Oil — a concentrated fragrance oil applied directly to the skin."),
    "body_mist": (400, "Body Mist — a lightly scented spray used to refresh and fragrance the skin."),
    "body_spray": (350, "Body Spray — a fragranced spray used for everyday freshness."),
    "deodorant_spray": (350, "Deodorant Spray — a spray-on personal care product used to control body odor."),
    "roll_on_deodorant": (300, "Roll-On Deodorant — a roll-applied personal care product used to control body odor."),
    "solid_perfume": (700, "Solid Perfume — a portable wax-based fragrance applied directly to the skin."),
    "mens_grooming": (500, "Men's Grooming — a general range of personal care products for men."),
    "beard_oil": (450, "Beard Oil — a nourishing oil used to condition and soften facial hair."),
    "beard_balm": (450, "Beard Balm — a conditioning balm used to soften and style facial hair."),
    "beard_wash": (400, "Beard Wash — a cleansing wash formulated for facial hair care."),
    "beard_comb": (250, "Beard Comb — a comb designed for grooming and styling facial hair."),
    "shaving_cream": (300, "Shaving Cream — a lathering cream used to soften hair before shaving."),
    "shaving_gel": (300, "Shaving Gel — a gel formula used to provide a smooth shaving surface."),
    "aftershave_lotion": (350, "Aftershave Lotion — a soothing lotion applied after shaving to calm the skin."),
    "face_moisturizer_for_men": (500, "Face Moisturizer for Men — a hydrating skincare product formulated for men."),
    "hair_care": (400, "Hair Care — a general range of hair care products."),
    "shampoo": (350, "Shampoo — a hair cleansing product used for everyday washing."),
    "conditioner": (350, "Conditioner — a hair care product used to soften and detangle hair after shampooing."),
    "hair_mask": (500, "Hair Mask — a deep conditioning treatment used to nourish hair."),
    "hair_serum": (600, "Hair Serum — a lightweight treatment used to smooth and add shine to hair."),
    "hair_oil": (350, "Hair Oil — a nourishing oil used to condition and strengthen hair."),
    "hair_spray": (400, "Hair Spray — a styling product used to hold hairstyles in place."),
    "hair_wax": (350, "Hair Wax — a styling product used to define and texture hair."),
    "hair_gel": (300, "Hair Gel — a styling product used to hold and shape hair."),
    "dry_shampoo": (500, "Dry Shampoo — a powder or spray used to refresh hair without water."),
    "hair_mousse": (400, "Hair Mousse — a lightweight styling foam used to add volume and hold."),
    "heat_protectant_spray": (450, "Heat Protectant Spray — a spray used to shield hair from heat styling damage."),
    "nail_care": (400, "Nail Care — a general range of nail care products."),
    "nail_polish": (250, "Nail Polish — a cosmetic lacquer used to color and decorate nails."),
    "gel_nail_polish": (450, "Gel Nail Polish — a long-lasting nail polish cured under UV or LED light."),
    "nail_polish_remover": (200, "Nail Polish Remover — a solution used to remove nail polish."),
    "nail_file": (100, "Nail File — a tool used to shape and smooth nail edges."),
    "nail_buffer": (200, "Nail Buffer — a manicure tool used to smooth and shine nails."),
    "cuticle_oil": (300, "Cuticle Oil — a nourishing oil used to soften and condition nail cuticles."),
    "manicure_kit": (900, "Manicure Kit — a complete set of tools for at-home nail care."),
    "pedicure_kit": (900, "Pedicure Kit — a complete set of tools for at-home foot and nail care."),
    "nail_art_kit": (700, "Nail Art Kit — a set of tools and accessories for decorative nail designs."),
    "beauty_devices": (2500, "Beauty Devices — a general range of electronic beauty and skincare tools."),
    "facial_cleansing_brush": (1500, "Facial Cleansing Brush — an electric brush used to deep-clean facial skin."),
    "facial_steamer": (2200, "Facial Steamer — a device that uses steam to open pores and cleanse skin."),
    "blackhead_remover": (250, "Blackhead Remover — a tool used to gently extract blackheads from the skin."),
    "led_face_mask": (5500, "LED Face Mask — a device using LED light therapy for skincare treatment."),
    "jade_roller": (700, "Jade Roller — a massage tool used to promote circulation and skin relaxation."),
    "gua_sha_tool": (500, "Gua Sha Tool — a smooth-edged tool used for facial massage and skin toning."),
    "electric_makeup_brush_cleaner": (2500, "Electric Makeup Brush Cleaner — a device used to automatically clean makeup brushes."),
    "beauty_gift_sets": (1800, "Beauty Gift Sets — a curated set of beauty products, ideal for gifting."),
    "makeup_gift_set": (1800, "Makeup Gift Set — a curated set of cosmetics, ideal for gifting."),
    "skincare_gift_set": (1800, "Skincare Gift Set — a curated set of skincare essentials, ideal for gifting."),
    "perfume_gift_set": (2500, "Perfume Gift Set — a curated set of fragrances, ideal for gifting."),
    "bath_body_gift_set": (1800, "Bath & Body Gift Set — a curated set of bath and body products, ideal for gifting."),
    "mens_grooming_gift_set": (1800, "Men's Grooming Gift Set — a curated set of grooming essentials, ideal for gifting."),
    "travel_size_products": (350, "Travel Size Products — compact beauty products designed for travel convenience."),
    "travel_makeup_kit": (900, "Travel Makeup Kit — a compact set of makeup essentials for travel."),
    "travel_skincare_set": (900, "Travel Skincare Set — a compact set of skincare essentials for travel."),
    "travel_perfume": (700, "Travel Perfume — a compact fragrance bottle designed for travel."),
    "travel_cosmetic_bottles": (250, "Travel Cosmetic Bottles — refillable containers designed for travel-sized toiletries."),
    "toiletry_kit": (900, "Toiletry Kit — a compact bag of personal care essentials for travel."),
}

files_map = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch3.json",
]

updated = 0
skipped = []

for path in files_map:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    changed = False
    for sku, prod in data.items():
        if prod.get("categoryId") == "makeup_skincare_fragrance":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
                changed = True
            else:
                skipped.append((sku, img))
    if changed:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
