import json

price_desc = {
    "clothing_fashion_apparel_men_women_kids": (500, "Clothing, Fashion & Apparel — a wide range of clothing and accessories for men, women, and kids."),
    "clothes_rack_shirts_fashion_apparel": (500, "Clothing Collection — an assorted range of fashion apparel items."),
    "mens_clothing": (600, "Men's Clothing — a general range of clothing designed for men."),
    "t_shirts": (350, "T-Shirts — comfortable, everyday casual t-shirts."),
    "polo_shirts": (500, "Polo Shirts — smart-casual collared shirts for everyday wear."),
    "casual_shirts": (600, "Casual Shirts — relaxed-fit shirts suitable for everyday wear."),
    "formal_shirts": (700, "Formal Shirts — crisp, tailored shirts suitable for office and formal occasions."),
    "denim_shirts": (750, "Denim Shirts — durable denim shirts with a classic casual look."),
    "hoodies": (800, "Hoodies — warm, comfortable hooded sweatshirts."),
    "sweatshirts": (700, "Sweatshirts — cozy, casual sweatshirts for everyday wear."),
    "jackets": (1200, "Jackets — versatile jackets suitable for various occasions and weather."),
    "blazers": (2000, "Blazers — tailored blazers for formal and smart-casual looks."),
    "suits": (4500, "Suits — formal suit sets for professional and special occasions."),
    "waistcoats": (900, "Waistcoats — stylish sleeveless vests worn over shirts."),
    "sweaters": (900, "Sweaters — warm knitted sweaters for cooler weather."),
    "cardigans": (900, "Cardigans — lightweight, button-up knitwear layering pieces."),
    "tank_tops": (300, "Tank Tops — sleeveless casual tops for everyday and workout wear."),
    "vests": (400, "Vests — lightweight sleeveless tops for layering."),
    "jeans": (1200, "Jeans — durable denim trousers in various fits and washes."),
    "chinos": (900, "Chinos — smart-casual cotton trousers."),
    "trousers": (900, "Trousers — versatile formal and casual pants."),
    "cargo_pants": (900, "Cargo Pants — utility-style pants with multiple pockets."),
    "joggers": (700, "Joggers — comfortable, tapered pants suitable for casual and athletic wear."),
    "shorts": (450, "Shorts — casual shorts for warm-weather comfort."),
    "track_pants": (600, "Track Pants — comfortable pants suitable for sports and casual wear."),
    "pajamas": (500, "Pajamas — comfortable loungewear for sleeping and relaxing."),
    "nightwear": (500, "Nightwear — comfortable clothing designed for sleep and rest."),
    "lungi": (350, "Lungi — traditional wraparound garment popular in Bangladesh."),
    "panjabi_kurta": (900, "Panjabi Kurta — traditional attire for festive and religious occasions."),
    "sherwani": (5000, "Sherwani — formal traditional attire for weddings and special events."),
    "thobe": (1500, "Thobe — traditional ankle-length garment worn by men."),
    "ihram_clothing": (800, "Ihram Clothing — simple garments worn during Hajj and Umrah."),
    "swimwear": (700, "Swimwear — comfortable clothing designed for swimming and beach wear."),
    "womens_clothing": (600, "Women's Clothing — a general range of clothing designed for women."),
    "tops": (450, "Tops — versatile everyday tops for women."),
    "blouses": (500, "Blouses — elegant tops suitable for casual and formal occasions."),
    "tunics": (550, "Tunics — loose-fitting tops suitable for layering and everyday wear."),
    "shirts": (500, "Shirts — versatile shirts suitable for various occasions."),
    "dresses": (900, "Dresses — versatile dresses for everyday and special occasions."),
    "maxi_dresses": (1100, "Maxi Dresses — floor-length dresses offering elegant, flowing style."),
    "midi_dresses": (900, "Midi Dresses — knee-to-ankle length dresses for versatile styling."),
    "mini_dresses": (700, "Mini Dresses — short, stylish dresses for casual and evening wear."),
    "gowns": (2500, "Gowns — elegant formal dresses for special occasions."),
    "skirts": (600, "Skirts — versatile skirts in various lengths and styles."),
    "leggings": (400, "Leggings — stretchy, comfortable bottoms for everyday and athletic wear."),
    "jeggings": (500, "Jeggings — denim-style leggings combining comfort and style."),
    "pants": (700, "Pants — versatile everyday pants for women."),
    "palazzo_pants": (650, "Palazzo Pants — wide-legged, flowy pants offering comfort and style."),
    "jumpsuits": (1100, "Jumpsuits — stylish one-piece outfits for casual and formal wear."),
    "rompers": (700, "Rompers — playful one-piece shorts outfits for casual wear."),
    "sarees": (1800, "Sarees — traditional draped garments for festive and formal occasions."),
    "salwar_kameez": (1200, "Salwar Kameez — traditional South Asian attire, a comfortable everyday outfit."),
    "kurtis": (600, "Kurtis — versatile tunic-style tops popular for everyday wear."),
    "abayas": (1500, "Abayas — modest, flowing outer garments for women."),
    "hijabs": (350, "Hijabs — versatile headscarves in various fabrics and styles."),
    "kaftans": (900, "Kaftans — loose-fitting, flowing garments for comfort and style."),
    "lingerie": (400, "Lingerie — comfortable, quality women's undergarments."),
    "bras": (350, "Bras — everyday supportive undergarments."),
    "panties": (150, "Panties — comfortable, everyday women's undergarments."),
    "shapewear": (600, "Shapewear — supportive garments designed for a smooth silhouette."),
    "maternity_wear": (800, "Maternity Wear — comfortable clothing designed for expecting mothers."),
    "nursing_wear": (700, "Nursing Wear — practical clothing designed for breastfeeding mothers."),
    "kids_clothing": (400, "Kids' Clothing — a general range of clothing designed for children."),
    "baby_0_2_years": (350, "Baby Clothing (0-2 Years) — soft, comfortable clothing for infants and toddlers."),
    "baby_bodysuits": (300, "Baby Bodysuits — soft, easy-to-wear bodysuits for infants."),
    "sleepsuits": (350, "Sleepsuits — comfortable one-piece sleepwear for babies."),
    "baby_t_shirts": (250, "Baby T-Shirts — soft, comfortable t-shirts for babies."),
    "baby_pants": (250, "Baby Pants — comfortable, soft pants for babies."),
    "baby_shorts": (250, "Baby Shorts — comfortable, soft shorts for babies."),
    "baby_dresses": (400, "Baby Dresses — cute, comfortable dresses for baby girls."),
    "baby_jackets": (450, "Baby Jackets — warm, cozy jackets for babies."),
    "baby_sweaters": (400, "Baby Sweaters — warm knitted sweaters for babies."),
    "baby_socks": (150, "Baby Socks — soft, comfortable socks for babies."),
    "baby_hats": (200, "Baby Hats — soft hats to keep babies warm and protected."),
    "bibs": (150, "Bibs — practical feeding bibs for babies."),
    "boys": (400, "Boys' Clothing — a general range of clothing designed for boys."),
    "school_uniforms": (700, "School Uniforms — durable, standard uniforms for school children."),
    "ethnic_wear": (900, "Ethnic Wear — traditional clothing for festive and cultural occasions."),
    "girls": (400, "Girls' Clothing — a general range of clothing designed for girls."),
    "frocks": (500, "Frocks — cute, comfortable dresses for girls."),
    "party_dresses": (900, "Party Dresses — festive dresses for celebrations and special occasions."),
    "footwear": (700, "Footwear — a general range of shoes for everyday and formal use."),
    "sneakers": (1500, "Sneakers — comfortable, versatile shoes for everyday wear."),
    "running_shoes": (1800, "Running Shoes — supportive shoes designed for running and athletic activity."),
    "casual_shoes": (1000, "Casual Shoes — comfortable, everyday shoes for casual wear."),
    "formal_shoes": (1800, "Formal Shoes — polished shoes suitable for office and formal occasions."),
    "loafers": (1500, "Loafers — slip-on shoes combining comfort and smart style."),
    "boots": (2000, "Boots — durable, versatile footwear for various occasions and weather."),
    "sandals": (600, "Sandals — comfortable, open footwear for everyday wear."),
    "slippers": (300, "Slippers — comfortable indoor and casual footwear."),
    "flip_flops": (250, "Flip Flops — lightweight, casual footwear ideal for everyday use."),
    "high_heels": (1500, "High Heels — elegant shoes for formal and evening occasions."),
    "wedges": (1300, "Wedges — comfortable elevated shoes combining height and stability."),
    "flats": (900, "Flats — comfortable, versatile flat shoes for everyday wear."),
    "ballet_flats": (900, "Ballet Flats — soft, comfortable flat shoes with a classic silhouette."),
    "baby_shoes": (350, "Baby Shoes — soft, comfortable first shoes for babies."),
    "school_shoes": (900, "School Shoes — durable, comfortable shoes designed for daily school wear."),
    "fashion_accessories": (400, "Fashion Accessories — a general range of accessories to complement any outfit."),
    "watches": (1500, "Watches — stylish timepieces for everyday and formal wear."),
    "sunglasses": (700, "Sunglasses — stylish eyewear offering sun protection."),
    "belts": (500, "Belts — versatile accessories for both function and style."),
    "wallets": (700, "Wallets — practical accessories for carrying cash and cards."),
    "handbags": (1200, "Handbags — stylish bags for everyday and formal occasions."),
    "shoulder_bags": (1100, "Shoulder Bags — practical, stylish bags for everyday carrying."),
    "tote_bags": (900, "Tote Bags — spacious, versatile bags for daily use."),
    "backpacks": (1200, "Backpacks — durable, practical bags for daily and travel use."),
    "crossbody_bags": (1000, "Crossbody Bags — compact, hands-free bags for everyday convenience."),
    "travel_bags": (2000, "Travel Bags — spacious, durable bags designed for travel."),
    "caps": (400, "Caps — casual headwear suitable for everyday and outdoor use."),
    "hats": (500, "Hats — versatile headwear for style and sun protection."),
    "beanies": (350, "Beanies — warm, snug knit hats for cold weather."),
    "scarves": (450, "Scarves — versatile accessories for warmth and style."),
    "mufflers": (400, "Mufflers — warm scarves designed for cold-weather protection."),
    "gloves": (350, "Gloves — practical hand coverings for warmth and protection."),
    "ties": (500, "Ties — classic formal accessories for shirts and suits."),
    "bow_ties": (400, "Bow Ties — elegant formal accessories for special occasions."),
    "cufflinks": (600, "Cufflinks — decorative fasteners for formal dress shirt cuffs."),
    "suspenders": (500, "Suspenders — practical and stylish accessories for holding up trousers."),
    "socks": (150, "Socks — everyday comfort essentials for footwear."),
    "handkerchiefs": (150, "Handkerchiefs — practical fabric accessories for everyday use."),
    "jewelry_accessories": (500, "Jewelry & Accessories — a general range of decorative fashion jewelry."),
    "rings": (500, "Rings — decorative jewelry pieces for everyday and special occasions."),
    "necklaces": (700, "Necklaces — elegant jewelry pieces to complement any outfit."),
    "chains": (600, "Chains — versatile jewelry accessories for everyday wear."),
    "earrings": (400, "Earrings — decorative jewelry pieces for ears."),
    "bracelets": (500, "Bracelets — stylish wrist jewelry for everyday and formal wear."),
    "bangles": (400, "Bangles — traditional decorative wrist jewelry."),
    "anklets": (350, "Anklets — decorative jewelry worn around the ankle."),
    "pendants": (450, "Pendants — decorative jewelry pieces typically worn on a chain."),
    "brooches": (400, "Brooches — decorative pins used to accessorize clothing."),
    "hair_clips": (150, "Hair Clips — practical accessories for styling and securing hair."),
    "hair_bands": (150, "Hair Bands — everyday accessories for managing and styling hair."),
    "hair_accessories": (200, "Hair Accessories — a general range of accessories for hair styling."),
    "sports_activewear": (700, "Sports & Activewear — a general range of clothing designed for athletic activity."),
    "gym_t_shirts": (450, "Gym T-Shirts — breathable t-shirts designed for workouts."),
    "compression_wear": (700, "Compression Wear — fitted athletic wear designed to support muscles during activity."),
    "sports_bras": (500, "Sports Bras — supportive bras designed for athletic activity."),
    "yoga_pants": (600, "Yoga Pants — stretchy, comfortable pants designed for yoga and athletic wear."),
    "tracksuits": (1500, "Tracksuits — matching athletic sets for sports and casual wear."),
    "running_shorts": (450, "Running Shorts — lightweight shorts designed for running and athletic activity."),
    "cycling_jerseys": (900, "Cycling Jerseys — breathable jerseys designed for cycling performance."),
    "sports_jackets": (1300, "Sports Jackets — lightweight jackets designed for athletic activity."),
    "training_shoes": (1600, "Training Shoes — versatile shoes designed for gym and athletic training."),
    "seasonal_wear": (900, "Seasonal Wear — a general range of clothing designed for specific weather conditions."),
    "raincoats": (700, "Raincoats — waterproof outerwear designed for rainy weather."),
    "winter_jackets": (1800, "Winter Jackets — warm, insulated jackets for cold weather."),
    "puffer_jackets": (1800, "Puffer Jackets — insulated, lightweight jackets for cold-weather warmth."),
    "thermal_wear": (700, "Thermal Wear — insulating base-layer clothing for cold weather."),
    "fleece_jackets": (1100, "Fleece Jackets — soft, warm jackets ideal for cool weather."),
    "wool_sweaters": (1100, "Wool Sweaters — warm, natural-fiber sweaters for cold weather."),
    "wool_caps": (350, "Wool Caps — warm knitted caps for cold weather."),
    "workwear_uniforms": (900, "Workwear & Uniforms — a general range of clothing designed for professional and work settings."),
    "office_shirts": (700, "Office Shirts — professional shirts suitable for the workplace."),
    "office_pants": (900, "Office Pants — professional trousers suitable for the workplace."),
    "chef_uniforms": (1200, "Chef Uniforms — durable, practical uniforms designed for kitchen professionals."),
    "medical_scrubs": (900, "Medical Scrubs — comfortable, practical uniforms for healthcare professionals."),
    "security_uniforms": (1000, "Security Uniforms — durable uniforms designed for security personnel."),
    "construction_safety_vests": (500, "Construction Safety Vests — high-visibility vests for workplace safety."),
    "industrial_uniforms": (1100, "Industrial Uniforms — durable workwear designed for industrial settings."),
    "traditional_religious_clothing": (900, "Traditional & Religious Clothing — a general range of attire for cultural and religious occasions."),
    "niqab": (500, "Niqab — modest face-covering veil worn by women."),
    "prayer_cap_kufi": (250, "Prayer Cap (Kufi) — a traditional cap worn during prayer and religious occasions."),
    "prayer_dress": (900, "Prayer Dress — modest, comfortable attire designed for prayer."),
}

path = "data/products-placeholder.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
skipped = []
for sku, prod in data.items():
    if prod.get("categoryId") == "clothing_fashion_apparel_men_women_kids":
        img = prod["images"]["main"].split("/")[-1].replace(".png", "")
        if img in price_desc:
            price, desc = price_desc[img]
            prod["title"] = " ".join(w.capitalize() for w in img.split("_"))
            prod["price"] = price
            prod["description"] = desc
            prod["status"] = "active"
            updated += 1
        else:
            skipped.append((sku, img))

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
