import json

price_desc = {
    "gifts_crafts": (500, "Gifts & Crafts — a general range of gift and craft products."),
    "acrylic_paint": (400, "Acrylic Paint — a fast-drying water-based paint for various art projects."),
    "air_dry_clay": (350, "Air Dry Clay — a modeling clay that hardens without baking, ideal for crafts."),
    "anniversary_gifts": (2500, "Anniversary Gifts — curated gift items designed for celebrating anniversaries."),
    "art_craft_supplies": (700, "Art & Craft Supplies — a general range of materials used for art and craft projects."),
    "artificial_flowers": (400, "Artificial Flowers — decorative faux flowers for home and craft use."),
    "balloon_pump": (350, "Balloon Pump — a tool used to quickly inflate balloons."),
    "balloons": (250, "Balloons — decorative inflatable items used for parties and celebrations."),
    "beads": (250, "Beads — small decorative pieces used in jewelry making and crafts."),
    "birthday_gifts": (1800, "Birthday Gifts — curated gift items designed for birthday celebrations."),
    "bubble_wrap": (350, "Bubble Wrap — protective packaging material used for shipping items."),
    "cake_toppers": (450, "Cake Toppers — decorative accents used to top celebration cakes."),
    "candle_holder": (450, "Candle Holder — a decorative stand used to hold candles."),
    "canvas": (500, "Canvas — a blank stretched surface used for painting."),
    "cardstock": (300, "Cardstock — thick, sturdy paper suited for crafting and card making."),
    "charcoal_pencils": (300, "Charcoal Pencils — drawing pencils used for sketching and shading."),
    "charms": (200, "Charms — small decorative pieces used in jewelry and craft making."),
    "christmas_gift_sets": (2500, "Christmas Gift Sets — curated gift sets designed for holiday giving."),
    "christmas_ornaments": (450, "Christmas Ornaments — decorative items used to adorn a Christmas tree."),
    "christmas_stockings": (700, "Christmas Stockings — decorative stockings used for holiday gift display."),
    "clasps": (100, "Clasps — small fasteners used in jewelry making."),
    "clay": (350, "Clay — a moldable material used for sculpting and craft projects."),
    "coins": (1500, "Coins — collectible currency coins valued by collectors."),
    "collectible_figurines": (900, "Collectible Figurines — decorative statues valued for craftsmanship and rarity."),
    "collectibles_souvenirs": (900, "Collectibles & Souvenirs — a general range of memorabilia and souvenir items."),
    "colored_pencils": (500, "Colored Pencils — a set of pencils used for coloring and illustration."),
    "coloring_books": (200, "Coloring Books — books with illustrations designed for coloring activities."),
    "confetti": (150, "Confetti — small decorative paper pieces used for celebrations."),
    "craft_glue": (250, "Craft Glue — an adhesive used for various craft projects."),
    "craft_paper": (250, "Craft Paper — colored or textured paper used for craft making."),
    "craft_punch": (450, "Craft Punch — a tool used to cut decorative shapes from paper."),
    "craft_sticks": (150, "Craft Sticks — small wooden sticks used for craft projects."),
    "crayons": (250, "Crayons — a set of wax-based coloring sticks for drawing."),
    "crochet_hooks": (350, "Crochet Hooks — tools used for crochet needlework projects."),
    "crochet_items": (900, "Crochet Items — handmade items crafted using crochet techniques."),
    "custom_cushion": (900, "Custom Cushion — a personalized cushion designed with custom prints."),
    "custom_phone_case": (700, "Custom Phone Case — a personalized phone case designed with custom prints."),
    "custom_photo_frame": (700, "Custom Photo Frame — a personalized frame designed for displaying photos."),
    "decorative_bows": (150, "Decorative Bows — ornamental bows used for gift wrapping and decor."),
    "decorative_mirror": (2500, "Decorative Mirror — an ornamental mirror used to enhance home decor."),
    "decorative_moss": (250, "Decorative Moss — artificial moss used for craft and floral arrangements."),
    "decorative_paper": (250, "Decorative Paper — patterned paper used for craft and scrapbooking projects."),
    "decorative_plates": (900, "Decorative Plates — ornamental plates used for home display."),
    "decorative_stickers": (200, "Decorative Stickers — adhesive designs used for craft and decoration."),
    "decorative_tape": (150, "Decorative Tape — patterned adhesive tape used for craft projects."),
    "decorative_vase": (900, "Decorative Vase — an ornamental vase used for home decor."),
    "diy_bracelet_kit": (700, "DIY Bracelet Kit — a complete set of supplies for making bracelets."),
    "diy_craft_materials": (700, "DIY Craft Materials — a general range of materials used for do-it-yourself craft projects."),
    "drawing_paper": (300, "Drawing Paper — paper designed for sketching and drawing."),
    "dried_flowers": (450, "Dried Flowers — preserved flowers used for decorative arrangements."),
    "earring_hooks": (150, "Earring Hooks — small components used in handmade earring assembly."),
    "easel": (1500, "Easel — a stand designed for supporting canvases while painting."),
    "eid_decoration_set": (900, "Eid Decoration Set — a curated set of decorative items for Eid celebrations."),
    "eid_gift_box": (1500, "Eid Gift Box — a curated gift box designed for Eid celebrations."),
    "elastic_cord": (150, "Elastic Cord — stretchable cord used in jewelry and craft making."),
    "embroidery_kit": (900, "Embroidery Kit — a complete set of supplies for embroidery projects."),
    "embroidery_thread": (200, "Embroidery Thread — colored thread used for embroidery work."),
    "engraved_jewelry": (2500, "Engraved Jewelry — personalized jewelry pieces featuring custom engravings."),
    "engraved_pen": (900, "Engraved Pen — a personalized pen featuring custom engraving."),
    "epoxy_resin": (900, "Epoxy Resin — a clear resin used for casting and coating craft projects."),
    "fabric_glue": (250, "Fabric Glue — an adhesive used for bonding fabric materials."),
    "fabric_scissors": (450, "Fabric Scissors — cutting tools designed specifically for fabric projects."),
    "fathers_day_gifts": (2500, "Father's Day Gifts — curated gift items designed for Father's Day celebrations."),
    "felt_fabric": (250, "Felt Fabric — soft fabric sheets commonly used in craft making."),
    "figurines": (700, "Figurines — small decorative statues used for home display."),
    "finger_paint": (350, "Finger Paint — a washable paint designed for hands-on painting activities."),
    "floral_decorative_supplies": (700, "Floral & Decorative Supplies — a general range of decorative floral craft materials."),
    "floral_foam": (250, "Floral Foam — a foam block used to arrange and secure flowers."),
    "flower_wrapping_paper": (250, "Flower Wrapping Paper — decorative paper used to wrap floral bouquets."),
    "foam_sheets": (250, "Foam Sheets — colored foam material used for craft projects."),
    "gift_bag": (250, "Gift Bag — a decorative bag used for presenting gifts."),
    "gift_basket": (1800, "Gift Basket — a curated basket of items used for gifting."),
    "gift_box": (450, "Gift Box — a decorative box used for presenting gifts."),
    "gift_box_with_ribbon": (600, "Gift Box with Ribbon — a decorative gift box featuring a ribbon accent."),
    "gift_boxes": (450, "Gift Boxes — a general range of decorative boxes used for gifting."),
    "gift_card": (1000, "Gift Card — a prepaid card given as a gift for future purchases."),
    "gift_hamper": (2500, "Gift Hamper — a curated basket of assorted items used for gifting."),
    "gift_items": (900, "Gift Items — a general range of items curated for gifting."),
    "gift_ribbon": (150, "Gift Ribbon — decorative ribbon used for wrapping and gift presentation."),
    "gift_tags": (100, "Gift Tags — small labels used to personalize gift presentations."),
    "gift_wrap": (250, "Gift Wrap — decorative paper used to wrap gifts."),
    "glitter": (150, "Glitter — small sparkling particles used for craft decoration."),
    "glue_gun_sticks": (150, "Glue Gun Sticks — solid adhesive sticks used with a glue gun."),
    "glue_stick": (100, "Glue Stick — a solid adhesive stick used for paper crafts."),
    "googly_eyes": (100, "Googly Eyes — small movable eye craft pieces used for decoration."),
    "greeting_card": (150, "Greeting Card — a printed card used for special occasions."),
    "handmade_bags": (1500, "Handmade Bags — artisan-crafted bags made by hand."),
    "handmade_candles": (600, "Handmade Candles — artisan candles crafted by hand."),
    "handmade_cards": (250, "Handmade Cards — artisan-crafted greeting cards made by hand."),
    "handmade_crafts": (900, "Handmade Crafts — a general range of artisan-crafted craft items."),
    "handmade_dolls": (1800, "Handmade Dolls — artisan-crafted dolls made by hand."),
    "handmade_jewelry": (1200, "Handmade Jewelry — artisan-crafted jewelry pieces made by hand."),
    "handmade_pottery": (1800, "Handmade Pottery — artisan-crafted ceramic pieces made by hand."),
    "handmade_soap": (350, "Handmade Soap — artisan soap crafted using natural ingredients."),
    "hole_punch": (250, "Hole Punch — a tool used to create holes in paper for craft projects."),
    "home_decor_gifts": (1800, "Home Decor Gifts — curated decorative items designed for gifting."),
    "hot_glue_gun": (500, "Hot Glue Gun — a tool that melts glue sticks for craft bonding."),
    "indoor_plant": (700, "Indoor Plant — a potted plant used to decorate indoor spaces."),
    "ink_pads": (250, "Ink Pads — stamping pads used for craft and card making projects."),
    "islamic_wall_art": (1800, "Islamic Wall Art — decorative wall pieces featuring Islamic calligraphy and design."),
    "jewelry_beads": (250, "Jewelry Beads — small decorative pieces used in jewelry making."),
    "jewelry_making_supplies": (700, "Jewelry Making Supplies — a general range of materials used for crafting jewelry."),
    "jewelry_pliers": (450, "Jewelry Pliers — precision tools used for jewelry assembly."),
    "jewelry_wire": (250, "Jewelry Wire — flexible wire used in jewelry making projects."),
    "jump_rings": (100, "Jump Rings — small metal rings used to connect jewelry components."),
    "keychains": (200, "Keychains — decorative or collectible accessories for keys."),
    "kids_craft_kit": (900, "Kids Craft Kit — a complete set of supplies for children's craft activities."),
    "kids_craft_supplies": (700, "Kids Craft Supplies — a general range of craft materials designed for children."),
    "knitted_items": (900, "Knitted Items — handmade items crafted using knitting techniques."),
    "knitting_needles": (350, "Knitting Needles — tools used for knitting projects."),
    "kraft_paper_bags": (250, "Kraft Paper Bags — eco-friendly paper bags used for gifting and packaging."),
    "macrame_wall_hanging": (1500, "Macrame Wall Hanging — decorative wall art crafted using knotting techniques."),
    "markers": (400, "Markers — a set of coloring pens used for drawing and lettering."),
    "measuring_tape": (250, "Measuring Tape — a tool used to measure length in craft projects."),
    "miniature_models": (900, "Miniature Models — small-scale replicas used for display and collection."),
    "modeling_clay": (350, "Modeling Clay — pliable clay used for sculpting and craft projects."),
    "molds": (350, "Molds — shaping tools used in resin, candle, and craft projects."),
    "mothers_day_gifts": (2500, "Mother's Day Gifts — curated gift items designed for Mother's Day celebrations."),
    "name_plate": (900, "Name Plate — a personalized sign used for identification or display."),
    "office_school_crafts": (700, "Office & School Crafts — a general range of craft materials for office and school use."),
    "oil_paint": (600, "Oil Paint — a slow-drying paint used for fine art painting."),
    "origami_paper": (250, "Origami Paper — pre-cut paper designed for origami folding projects."),
    "packaging_supplies": (450, "Packaging Supplies — a general range of materials used for gift and product packaging."),
    "packaging_tape": (250, "Packaging Tape — adhesive tape used for sealing packages."),
    "paint_brushes": (400, "Paint Brushes — a set of brushes used for painting and craft projects."),
    "palette": (350, "Palette — a flat surface used for mixing paint colors."),
    "paper_cutter": (1500, "Paper Cutter — a tool used to cut paper cleanly and precisely."),
    "party_banners": (450, "Party Banners — decorative banners used for celebrations."),
    "party_celebration_supplies": (700, "Party & Celebration Supplies — a general range of party decoration products."),
    "party_hats": (250, "Party Hats — decorative hats worn during celebrations."),
    "pendant_blanks": (250, "Pendant Blanks — unfinished pendant pieces used for custom jewelry making."),
    "personalized_clock": (1800, "Personalized Clock — a custom clock designed with personalized details."),
    "personalized_gifts": (1800, "Personalized Gifts — a general range of gift items customized with personal details."),
    "personalized_keychain": (350, "Personalized Keychain — a custom keychain designed with personalized details."),
    "personalized_mug": (700, "Personalized Mug — a custom mug designed with personalized prints."),
    "personalized_t_shirt": (900, "Personalized T-Shirt — a custom t-shirt designed with personalized prints."),
    "photo_booth_props": (450, "Photo Booth Props — decorative props used for event photo booths."),
    "photo_corners": (150, "Photo Corners — small adhesive mounts used to attach photos in albums."),
    "pipe_cleaners": (150, "Pipe Cleaners — flexible fuzzy sticks used for craft projects."),
    "polymer_clay": (400, "Polymer Clay — a moldable clay that hardens when baked, used in crafts."),
    "prayer_mat_gift_set": (1800, "Prayer Mat Gift Set — a curated gift set featuring a prayer mat and accessories."),
    "quran_stand": (900, "Quran Stand — a decorative stand designed to hold the Quran while reading."),
    "ramadan_decoration": (900, "Ramadan Decoration — decorative items used for Ramadan celebrations."),
    "ramadan_lantern": (900, "Ramadan Lantern — a decorative lantern used for Ramadan celebrations."),
    "religious_gifts": (1500, "Religious Gifts — curated gift items designed for religious occasions."),
    "resin_art": (2800, "Resin Art — decorative artwork crafted using cast resin."),
    "resin_kit": (1200, "Resin Kit — a complete set of supplies for resin art projects."),
    "sand_art_kit": (700, "Sand Art Kit — a craft set used to create colorful sand designs."),
    "scented_candles": (600, "Scented Candles — fragranced candles used for ambiance and gifting."),
    "scissors": (250, "Scissors — cutting tool used for craft and sewing projects."),
    "scrapbook_album": (900, "Scrapbook Album — a book used to organize and display personal memorabilia."),
    "scrapbooking": (700, "Scrapbooking — a general range of materials used for scrapbook crafting."),
    "seasonal_gifts": (1800, "Seasonal Gifts — curated gift items designed for seasonal occasions."),
    "sequins": (150, "Sequins — small shiny decorative pieces used for craft projects."),
    "sewing_kit": (700, "Sewing Kit — a complete set of supplies for basic sewing tasks."),
    "sewing_knitting": (700, "Sewing & Knitting — a general range of sewing and knitting supplies."),
    "sewing_machine": (8500, "Sewing Machine — an appliance used for stitching fabric and garments."),
    "shipping_labels": (250, "Shipping Labels — adhesive labels used for packaging and shipping."),
    "sketchbook": (350, "Sketchbook — a bound book of blank paper used for drawing and sketching."),
    "snow_globe": (900, "Snow Globe — a decorative glass globe featuring a miniature winter scene."),
    "souvenir_magnets": (250, "Souvenir Magnets — decorative magnets collected as travel keepsakes."),
    "stamps": (1200, "Stamps — collectible postage stamps valued by collectors."),
    "stapler": (350, "Stapler — a tool used to fasten sheets of paper together."),
    "sticker_book": (450, "Sticker Book — a book filled with reusable decorative stickers."),
    "streamers": (250, "Streamers — decorative paper strips used for party decoration."),
    "surprise_box": (1800, "Surprise Box — a curated box of mystery items used for gifting."),
    "table_decor": (700, "Table Decor — decorative items used to accent tabletop surfaces."),
    "table_decorations": (700, "Table Decorations — a general range of decorative items for tables."),
    "tasbih": (450, "Tasbih — a prayer bead set used for religious counting."),
    "tissue_paper": (150, "Tissue Paper — soft paper used for gift wrapping and packaging."),
    "transparent_gift_bags": (250, "Transparent Gift Bags — clear bags used to present gift items."),
    "valentines_gifts": (2500, "Valentine's Gifts — curated gift items designed for Valentine's Day celebrations."),
    "wall_art": (2500, "Wall Art — decorative artwork designed for wall display."),
    "wall_clock": (900, "Wall Clock — a decorative clock designed for wall mounting."),
    "washi_tape": (150, "Washi Tape — decorative paper tape used for craft and scrapbooking projects."),
    "watercolor_paint": (450, "Watercolor Paint — a water-based paint used for fine art painting."),
    "wood_crafts": (1200, "Wood Crafts — handmade decorative items crafted from wood."),
    "wreath_base": (450, "Wreath Base — a foundation frame used to build decorative wreaths."),
    "yarn": (300, "Yarn — spun fiber used for knitting and crochet projects."),
}

files_map = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch2.json",
]

updated = 0
skipped = []

for path in files_map:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    changed = False
    for sku, prod in data.items():
        if prod.get("categoryId") == "gifts_crafts":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
                changed = True
            else:
                skipped.append((sku, img))
    if changed:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
