import json

price_desc = {
    "gardening_outdoor_living": (500, "Gardening & Outdoor Living — a general range of gardening and outdoor products."),
    "above_ground_pool": (55000, "Above Ground Pool — a freestanding pool designed for backyard installation."),
    "arbor": (12000, "Arbor — a garden structure used to support climbing plants and create shaded walkways."),
    "artificial_grass": (350, "Artificial Grass — synthetic turf used for landscaping and outdoor surfaces."),
    "bbq_smoker": (18000, "BBQ Smoker — an outdoor cooking appliance used to slow-cook and smoke food."),
    "bbq_tool_set": (1800, "BBQ Tool Set — a set of tools used for grilling and outdoor cooking."),
    "bee_house": (1500, "Bee House — a shelter designed to attract and house pollinating bees."),
    "bird_bath": (2500, "Bird Bath — a shallow basin used to attract birds for bathing and drinking."),
    "bird_feeder": (900, "Bird Feeder — a device used to provide food for wild birds."),
    "bird_house": (900, "Bird House — a small shelter designed for birds to nest in."),
    "bird_netting": (450, "Bird Netting — mesh netting used to protect gardens from birds."),
    "bird_wildlife_care": (900, "Bird & Wildlife Care — a general range of products for supporting garden wildlife."),
    "bonsai_trees": (3500, "Bonsai Trees — miniature ornamental trees cultivated for decorative display."),
    "brush_cutter": (8500, "Brush Cutter — a power tool used to clear thick vegetation and brush."),
    "cactus": (450, "Cactus — a low-maintenance succulent plant used for decor."),
    "camping_chair": (1800, "Camping Chair — a portable folding chair designed for outdoor use."),
    "camping_lantern": (1500, "Camping Lantern — a portable light source designed for outdoor camping."),
    "camping_outdoor_living": (900, "Camping & Outdoor Living — a general range of camping and outdoor products."),
    "camping_stove": (2500, "Camping Stove — a portable stove designed for cooking outdoors."),
    "camping_table": (3500, "Camping Table — a portable table designed for outdoor use."),
    "camping_tent": (6500, "Camping Tent — a portable shelter designed for outdoor camping."),
    "ceramic_pots": (700, "Ceramic Pots — decorative pots used for growing plants."),
    "chainsaw": (12000, "Chainsaw — a power tool used for cutting wood and trees."),
    "charcoal_grill": (8500, "Charcoal Grill — an outdoor grill that uses charcoal for cooking."),
    "charcoal_starter": (900, "Charcoal Starter — a tool used to quickly ignite charcoal for grilling."),
    "chemical_fertilizer": (450, "Chemical Fertilizer — a synthetic nutrient product used to promote plant growth."),
    "clay_pots": (500, "Clay Pots — handmade pottery vessels used for planting."),
    "coco_peat": (350, "Coco Peat — an organic growing medium made from coconut husks."),
    "compost": (450, "Compost — decomposed organic matter used to enrich garden soil."),
    "compost_bin": (3500, "Compost Bin — a container used to compost organic waste."),
    "cooler_box": (2500, "Cooler Box — an insulated container used to keep food and drinks cold outdoors."),
    "decorative_stones": (450, "Decorative Stones — ornamental stones used for landscaping."),
    "dibber": (250, "Dibber — a hand tool used to make holes for planting seeds and bulbs."),
    "drip_irrigation_kit": (2500, "Drip Irrigation Kit — a system used to deliver water directly to plant roots."),
    "expandable_hose": (1800, "Expandable Hose — a lightweight hose that expands with water pressure."),
    "fence_panels": (2500, "Fence Panels — prefabricated panels used to build garden fencing."),
    "fence_posts": (450, "Fence Posts — support posts used for installing fencing."),
    "fencing_landscaping": (2500, "Fencing & Landscaping — a general range of outdoor fencing and landscaping products."),
    "fire_pit": (8500, "Fire Pit — an outdoor structure used for containing an open fire."),
    "firewood_rack": (2500, "Firewood Rack — a stand used to store and organize firewood."),
    "flower_pot_watering_can_garden_tools": (900, "Flower Pot, Watering Can & Garden Tools Set — a bundled set of gardening essentials."),
    "flower_seeds": (150, "Flower Seeds — seeds used to grow decorative flowering plants."),
    "flowering_plants": (700, "Flowering Plants — potted plants that produce decorative blooms."),
    "frost_cover": (450, "Frost Cover — a protective cover used to shield plants from frost damage."),
    "fruit_seeds": (150, "Fruit Seeds — seeds used to grow fruit-bearing plants."),
    "fungicide": (450, "Fungicide — a chemical treatment used to control fungal plant diseases."),
    "garden_accessories": (700, "Garden Accessories — a general range of gardening accessory products."),
    "garden_chair": (3500, "Garden Chair — an outdoor chair designed for garden and patio use."),
    "garden_cover": (900, "Garden Cover — a protective cover used to shield garden beds."),
    "garden_edging": (450, "Garden Edging — border material used to define garden and landscaping areas."),
    "garden_fence": (3500, "Garden Fence — a fence used to enclose and protect garden areas."),
    "garden_flags": (450, "Garden Flags — decorative flags used to accent outdoor garden spaces."),
    "garden_fork": (700, "Garden Fork — a hand tool used to till and aerate soil."),
    "garden_gloves": (350, "Garden Gloves — protective gloves used for gardening tasks."),
    "garden_gnomes": (900, "Garden Gnomes — decorative figurines used for garden display."),
    "garden_hoe": (700, "Garden Hoe — a hand tool used to cultivate soil and remove weeds."),
    "garden_hose": (1500, "Garden Hose — a flexible hose used for watering plants and gardens."),
    "garden_knife": (450, "Garden Knife — a hand tool used for cutting and digging in garden tasks."),
    "garden_lamp_posts": (3500, "Garden Lamp Posts — decorative outdoor lighting fixtures for gardens."),
    "garden_netting": (450, "Garden Netting — mesh netting used to protect plants from pests."),
    "garden_scissors": (350, "Garden Scissors — small scissors used for precise garden trimming."),
    "garden_shed": (45000, "Garden Shed — an outdoor storage structure designed for tools and equipment."),
    "garden_shredder": (12000, "Garden Shredder — a machine used to chop garden waste into mulch."),
    "garden_soil": (450, "Garden Soil — enriched soil used for planting and gardening."),
    "garden_sprayer": (900, "Garden Sprayer — a tool used to apply water or chemicals to plants."),
    "garden_statue": (2500, "Garden Statue — a decorative sculpture used for garden display."),
    "garden_storage": (8500, "Garden Storage — a storage unit designed for garden tools and equipment."),
    "garden_table": (6500, "Garden Table — an outdoor table designed for garden and patio use."),
    "garden_tool_set": (1800, "Garden Tool Set — a coordinated set of hand tools for gardening."),
    "garden_tools": (700, "Garden Tools — a general range of hand tools used for gardening."),
    "garden_twine": (150, "Garden Twine — durable string used for tying and supporting plants."),
    "gas_grill": (18000, "Gas Grill — an outdoor grill powered by propane or natural gas."),
    "gazebo": (35000, "Gazebo — a freestanding structure used to provide shade in outdoor spaces."),
    "grass_seeds": (350, "Grass Seeds — seeds used to grow and maintain a lawn."),
    "grass_trimmer": (5500, "Grass Trimmer — a power tool used to trim grass and edges."),
    "greenhouse_cover": (2500, "Greenhouse Cover — a protective covering used for greenhouse structures."),
    "greenhouse_shelving": (2500, "Greenhouse Shelving — shelving units designed for greenhouse plant organization."),
    "greenhouse_supplies": (900, "Greenhouse Supplies — a general range of products used for greenhouse gardening."),
    "grill_brush": (450, "Grill Brush — a tool used to clean grill grates."),
    "grill_cover": (900, "Grill Cover — a protective cover designed to shield an outdoor grill."),
    "grow_bags": (350, "Grow Bags — fabric bags used as containers for growing plants."),
    "hammock": (3500, "Hammock — a suspended fabric bed used for relaxing outdoors."),
    "hand_cultivator": (450, "Hand Cultivator — a hand tool used to loosen and aerate soil."),
    "hand_trowel": (350, "Hand Trowel — a small hand tool used for digging and planting."),
    "hanging_planters": (700, "Hanging Planters — suspended containers used for growing plants."),
    "hedge_shears": (900, "Hedge Shears — a hand tool used to trim hedges and bushes."),
    "hedge_trimmer": (5500, "Hedge Trimmer — a power tool used to shape and trim hedges."),
    "herb_seeds": (150, "Herb Seeds — seeds used to grow culinary and medicinal herbs."),
    "herbicide": (450, "Herbicide — a chemical treatment used to control unwanted weeds."),
    "hiking_backpack": (3500, "Hiking Backpack — a durable backpack designed for outdoor hiking trips."),
    "hose_connector": (250, "Hose Connector — a fitting used to join sections of garden hose."),
    "hose_reel": (2500, "Hose Reel — a device used to store and wind a garden hose."),
    "hose_storage": (1500, "Hose Storage — a container used to organize and store garden hoses."),
    "ice_scraper": (250, "Ice Scraper — a tool used to remove ice from surfaces."),
    "indoor_plants": (700, "Indoor Plants — potted plants used to decorate indoor spaces."),
    "inflatable_pool": (3500, "Inflatable Pool — a portable pool that inflates for temporary use."),
    "insect_traps": (450, "Insect Traps — devices used to capture and control garden pests."),
    "insecticide": (450, "Insecticide — a chemical treatment used to control garden pests."),
    "kneeling_pad": (450, "Kneeling Pad — a cushioned pad used for comfort while gardening."),
    "landscaping_fabric": (900, "Landscaping Fabric — a weed-blocking fabric used in garden beds."),
    "lanterns": (900, "Lanterns — decorative light fixtures used for outdoor ambiance."),
    "lawn_mower": (18000, "Lawn Mower — a machine used to cut and maintain grass."),
    "leaf_blower": (6500, "Leaf Blower — a power tool used to clear leaves and debris."),
    "leaf_collection_bag": (450, "Leaf Collection Bag — a bag used to collect fallen leaves and yard waste."),
    "led_flood_lights": (1800, "LED Flood Lights — bright outdoor lights used for illuminating large areas."),
    "liquid_fertilizer": (450, "Liquid Fertilizer — a nutrient solution used to promote plant growth."),
    "lopper": (900, "Lopper — a long-handled tool used to cut thick branches."),
    "mini_greenhouse": (5500, "Mini Greenhouse — a small structure used to grow plants in a controlled environment."),
    "moisture_meter": (700, "Moisture Meter — a tool used to measure soil moisture levels."),
    "motion_sensor_lights": (1800, "Motion Sensor Lights — outdoor lights that activate based on detected movement."),
    "mulch": (450, "Mulch — organic material used to cover soil and retain moisture."),
    "organic_fertilizer": (450, "Organic Fertilizer — a natural nutrient product used to promote plant growth."),
    "organic_pesticide": (450, "Organic Pesticide — a natural treatment used to control garden pests."),
    "outdoor_bench": (5500, "Outdoor Bench — a durable bench designed for outdoor use."),
    "outdoor_clock": (1500, "Outdoor Clock — a weather-resistant clock designed for outdoor display."),
    "outdoor_cooking": (3500, "Outdoor Cooking — a general range of outdoor cooking equipment."),
    "outdoor_decor": (900, "Outdoor Decor — decorative items designed for outdoor spaces."),
    "outdoor_furniture": (12000, "Outdoor Furniture — a general range of furniture designed for outdoor spaces."),
    "outdoor_lighting": (1800, "Outdoor Lighting — a general range of lighting products for outdoor spaces."),
    "outdoor_plants": (700, "Outdoor Plants — potted or garden plants used for outdoor spaces."),
    "outdoor_sofa": (25000, "Outdoor Sofa — a durable sofa designed for outdoor patio use."),
    "pathway_lights": (900, "Pathway Lights — outdoor lights used to illuminate walkways."),
    "patio_furniture_set": (25000, "Patio Furniture Set — a coordinated furniture set designed for patios."),
    "patio_umbrella": (5500, "Patio Umbrella — a large umbrella designed to provide outdoor shade."),
    "pergola": (35000, "Pergola — an outdoor structure with a lattice roof used for shade and decor."),
    "perlite": (350, "Perlite — a lightweight volcanic material used to improve soil aeration."),
    "pest_weed_control": (450, "Pest & Weed Control — a general range of products used to manage garden pests and weeds."),
    "picnic_basket": (1800, "Picnic Basket — a basket used to carry food for outdoor picnics."),
    "picnic_table": (8500, "Picnic Table — an outdoor table designed for picnics and gatherings."),
    "pizza_oven": (25000, "Pizza Oven — an outdoor oven designed for cooking pizza."),
    "plant_covers": (700, "Plant Covers — protective covers used to shield plants from weather."),
    "plant_hangers": (450, "Plant Hangers — hardware used to suspend potted plants."),
    "plant_labels": (150, "Plant Labels — markers used to identify plants in a garden."),
    "plant_stands": (1500, "Plant Stands — stands used to elevate and display potted plants."),
    "plant_support_stakes": (250, "Plant Support Stakes — stakes used to support growing plants."),
    "plants_seeds": (450, "Plants & Seeds — a general range of plants and seed products."),
    "plastic_pots": (250, "Plastic Pots — lightweight pots used for growing plants."),
    "pole_saw": (8500, "Pole Saw — a long-handled saw used to trim high branches."),
    "pool_cleaning_kit": (3500, "Pool Cleaning Kit — a set of tools used to maintain and clean a pool."),
    "pool_cover": (3500, "Pool Cover — a protective cover designed to shield a pool."),
    "pool_filter": (5500, "Pool Filter — a device used to filter and clean pool water."),
    "pool_float": (900, "Pool Float — an inflatable accessory used for floating in a pool."),
    "pool_ladder": (3500, "Pool Ladder — a ladder used for safe pool entry and exit."),
    "pool_pump": (12000, "Pool Pump — a device used to circulate and filter pool water."),
    "pools_outdoor_fun": (3500, "Pools & Outdoor Fun — a general range of pool and outdoor recreation products."),
    "portable_bbq_grill": (3500, "Portable BBQ Grill — a compact grill designed for outdoor cooking on the go."),
    "portable_shower": (3500, "Portable Shower — a mobile shower unit designed for outdoor use."),
    "pots_planters": (700, "Pots & Planters — a general range of containers used for growing plants."),
    "potting_soil": (450, "Potting Soil — enriched soil used for container gardening."),
    "power_garden_tools": (8500, "Power Garden Tools — a general range of motorized gardening equipment."),
    "pressure_sprayer": (1500, "Pressure Sprayer — a hand-pumped sprayer used to apply water or chemicals."),
    "pressure_washer": (12000, "Pressure Washer — a machine that uses high-pressure water for outdoor cleaning."),
    "pruning_saw": (900, "Pruning Saw — a hand saw used to cut tree branches."),
    "pruning_shears": (700, "Pruning Shears — a hand tool used to trim plants and small branches."),
    "rain_barrel": (5500, "Rain Barrel — a container used to collect and store rainwater."),
    "raised_garden_beds": (5500, "Raised Garden Beds — elevated planting boxes used for gardening."),
    "rake": (700, "Rake — a hand tool used to gather leaves and debris."),
    "retaining_wall_blocks": (85, "Retaining Wall Blocks — precast blocks used to build supportive retaining walls."),
    "robotic_lawn_mower": (65000, "Robotic Lawn Mower — an automated mower that maintains a lawn independently."),
    "seed_trays": (350, "Seed Trays — trays used for starting seeds indoors."),
    "seedling_heat_mat": (1800, "Seedling Heat Mat — a mat used to provide warmth for seed germination."),
    "self_watering_pots": (900, "Self-Watering Pots — planters designed with a built-in water reservoir."),
    "shade_net": (900, "Shade Net — a mesh material used to provide shade for plants."),
    "shovel": (450, "Shovel — a hand tool used for digging and moving materials."),
    "sleeping_bag": (1800, "Sleeping Bag — a portable bedding used for outdoor camping."),
    "snow_shovel": (900, "Snow Shovel — a tool used to clear snow from surfaces."),
    "soaker_hose": (1500, "Soaker Hose — a porous hose used to slowly water garden beds."),
    "soil_fertilizers": (450, "Soil & Fertilizers — a general range of soil and fertilizer products."),
    "soil_ph_tester": (700, "Soil pH Tester — a tool used to measure soil acidity levels."),
    "solar_garden_lights": (900, "Solar Garden Lights — outdoor lights powered by solar energy."),
    "spade": (700, "Spade — a hand tool used for digging and edging in gardening."),
    "spotlights": (1800, "Spotlights — focused outdoor lights used to highlight garden features."),
    "spray_nozzle": (350, "Spray Nozzle — an attachment used to control water flow from a hose."),
    "sprinkler": (900, "Sprinkler — a device used to distribute water across a lawn or garden."),
    "squirrel_feeder": (900, "Squirrel Feeder — a feeder designed to provide food for squirrels."),
    "storage_box": (700, "Storage Box — a box designed for organizing outdoor items."),
    "string_lights": (700, "String Lights — decorative lights used for outdoor ambiance."),
    "succulents": (450, "Succulents — low-maintenance potted plants used for decor."),
    "sun_lounger": (8500, "Sun Lounger — a reclining outdoor chair designed for sunbathing."),
    "swing_chair": (12000, "Swing Chair — a suspended chair designed for relaxed outdoor seating."),
    "thermometer": (450, "Thermometer — a device used to measure outdoor or garden temperature."),
    "tool_belt": (900, "Tool Belt — a wearable belt used to carry gardening tools."),
    "tool_rack": (1800, "Tool Rack — a rack used to organize and store garden tools."),
    "tree_saplings": (900, "Tree Saplings — young trees used for planting and landscaping."),
    "trellis": (1800, "Trellis — a garden structure used to support climbing plants."),
    "vegetable_seeds": (150, "Vegetable Seeds — seeds used to grow vegetable plants."),
    "vermicompost": (450, "Vermicompost — nutrient-rich compost produced using earthworms."),
    "walk_in_greenhouse": (12000, "Walk-In Greenhouse — a large structure used to grow plants in a controlled environment."),
    "water_fountain": (8500, "Water Fountain — a decorative feature used to add ambiance to gardens."),
    "water_timer": (1500, "Water Timer — a device used to automate garden watering schedules."),
    "watering_can": (450, "Watering Can — a container used to manually water plants."),
    "watering_equipment": (900, "Watering Equipment — a general range of tools used for garden watering."),
    "weed_killer": (450, "Weed Killer — a chemical treatment used to eliminate unwanted weeds."),
    "weeder": (450, "Weeder — a hand tool used to remove weeds from soil."),
    "wheelbarrow": (3500, "Wheelbarrow — a hand-pushed cart used for transporting garden materials."),
    "wildlife_camera": (5500, "Wildlife Camera — a motion-activated camera used to observe outdoor wildlife."),
    "wind_chimes": (700, "Wind Chimes — decorative hanging chimes used for garden ambiance."),
    "window_planters": (700, "Window Planters — containers designed for growing plants on window ledges."),
    "winter_seasonal_care": (900, "Winter & Seasonal Care — a general range of products for seasonal garden maintenance."),
}

files_map = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch2.json",
]

updated = 0
skipped = []

for path in files_map:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    changed = False
    for sku, prod in data.items():
        if prod.get("categoryId") == "gardening_outdoor_living":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
                changed = True
            else:
                skipped.append((sku, img))
    if changed:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
