import json

price_desc = {
    "ac_adapter": (450, "AC Adapter — a device used to convert AC power for electronic devices."),
    "alligator_clip": (50, "Alligator Clip — a spring-loaded clip used for temporary electrical connections."),
    "arc_flash_face_shield": (900, "Arc Flash Face Shield — protective gear used to guard against electrical arc hazards."),
    "armored_cable": (450, "Armored Cable — a protected cable used for durable electrical wiring."),
    "auto_transformer": (5500, "Auto Transformer — a transformer used to adjust voltage levels efficiently."),
    "ballast": (700, "Ballast — a device used to regulate current for fluorescent lighting."),
    "banana_plug": (50, "Banana Plug — a connector used for quick electrical test connections."),
    "batteries_charging": (900, "Batteries & Charging — a general range of battery and charging products."),
    "battery_charger": (1800, "Battery Charger — a device used to recharge electrical batteries."),
    "battery_terminal": (150, "Battery Terminal — a connector used to attach cables to a battery."),
    "bulb_holder": (50, "Bulb Holder — a socket fixture used to hold a light bulb."),
    "busbar": (900, "Busbar — a metal strip used to conduct electricity within a panel."),
    "butt_connector": (30, "Butt Connector — a small sleeve used to join two electrical wires."),
    "cable_clips": (50, "Cable Clips — fasteners used to secure and organize cables."),
    "cable_cutter": (450, "Cable Cutter — a tool used to cut electrical cables and wires."),
    "cable_gland": (100, "Cable Gland — a fitting used to secure and seal a cable entering an enclosure."),
    "cable_markers": (50, "Cable Markers — labels used to identify wires and cables."),
    "cable_reel": (2500, "Cable Reel — a spool used to store and dispense electrical cable."),
    "cable_sleeves": (150, "Cable Sleeves — protective covers used to bundle and organize cables."),
    "cable_tester": (1500, "Cable Tester — a device used to check cable connectivity and faults."),
    "cable_ties": (100, "Cable Ties — fasteners used to bundle and secure cables."),
    "cable_tray": (900, "Cable Tray — a support system used to route and organize cables."),
    "cable_trunking": (450, "Cable Trunking — a protective channel used to route electrical cables."),
    "carbon_monoxide_detector": (1800, "Carbon Monoxide Detector — a safety device used to detect dangerous CO gas levels."),
    "ceiling_fan_regulator": (350, "Ceiling Fan Regulator — a control device used to adjust ceiling fan speed."),
    "ceiling_light": (1500, "Ceiling Light — a light fixture mounted on the ceiling."),
    "changeover_switch": (2500, "Changeover Switch — a switch used to alternate between two power sources."),
    "circuit_protection": (450, "Circuit Protection — a general range of devices used to protect electrical circuits."),
    "clamp_meter": (3500, "Clamp Meter — an electrical measurement tool used to test current."),
    "coaxial_cable": (350, "Coaxial Cable — a shielded cable used for signal transmission."),
    "conduit_box": (150, "Conduit Box — an enclosure used to house electrical wiring connections."),
    "conduits_cable_management": (450, "Conduits & Cable Management — a general range of products for organizing electrical wiring."),
    "connectors_terminals": (150, "Connectors & Terminals — a general range of electrical connection components."),
    "consumer_unit": (5500, "Consumer Unit — an electrical panel used to distribute power in a building."),
    "contactor": (1800, "Contactor — an electrically controlled switch used for power circuits."),
    "control_cable": (900, "Control Cable — a cable used to transmit control signals in electrical systems."),
    "cooling_fan": (900, "Cooling Fan — a fan used to dissipate heat in electrical enclosures."),
    "crimping_tool": (900, "Crimping Tool — a tool used to attach connectors to wires."),
    "dc_power_supply": (3500, "DC Power Supply — a device used to provide regulated direct current power."),
    "desoldering_pump": (350, "Desoldering Pump — a tool used to remove solder from electrical joints."),
    "digital_multimeter": (2200, "Digital Multimeter — an electrical testing tool used to measure voltage, current, and resistance."),
    "dimmer_switch": (900, "Dimmer Switch — a switch used to adjust the brightness of lighting."),
    "din_rail": (350, "DIN Rail — a metal rail used to mount electrical components in a panel."),
    "distribution_board": (3500, "Distribution Board — an electrical panel used to distribute power to circuits."),
    "distribution_control": (2500, "Distribution & Control — a general range of electrical distribution products."),
    "doorbell": (900, "Doorbell — a device used to signal a visitor's presence at a door."),
    "downlight": (900, "Downlight — a recessed light fixture installed into the ceiling."),
    "electric_bell": (450, "Electric Bell — an electrically powered bell used for signaling."),
    "electric_drill": (3500, "Electric Drill — a power tool used for drilling holes and driving screws."),
    "electric_motor": (12000, "Electric Motor — a machine that converts electrical energy into mechanical motion."),
    "electric_screwdriver": (2500, "Electric Screwdriver — a power tool used to drive screws efficiently."),
    "electrical_accessories": (450, "Electrical Accessories — a general range of electrical supply products."),
    "electrical_equipment_supplies": (500, "Electrical Equipment & Supplies — a general range of electrical products."),
    "electrical_panel": (8500, "Electrical Panel — a panel used to distribute and control electrical circuits."),
    "electrical_safety_helmet": (900, "Electrical Safety Helmet — protective headgear designed for electrical work."),
    "electrical_socket": (150, "Electrical Socket — a wall outlet used to connect electrical devices."),
    "electrical_tape": (100, "Electrical Tape — insulating tape used to cover and protect wire connections."),
    "electrical_tools": (900, "Electrical Tools — a general range of tools used for electrical work."),
    "electrical_wire": (450, "Electrical Wire — conductive wiring used in electrical installations."),
    "electrical_wires_cables": (450, "Electrical Wires & Cables — a general range of electrical wiring products."),
    "emergency_light": (1800, "Emergency Light — a battery-backed light used during power outages."),
    "energy_meter": (2500, "Energy Meter — a device used to measure electricity consumption."),
    "exhaust_fan": (2500, "Exhaust Fan — a ventilation fan used to remove air and moisture from a space."),
    "extension_cable": (700, "Extension Cable — a cable used to extend the reach of an electrical connection."),
    "extension_cord": (700, "Extension Cord — a cord used to extend the reach of an electrical outlet."),
    "extension_socket": (450, "Extension Socket — a multi-outlet device used to expand available electrical sockets."),
    "fans_ventilation": (2500, "Fans & Ventilation — a general range of ventilation products."),
    "flexible_cable": (450, "Flexible Cable — a bendable cable used for wiring in tight spaces."),
    "flexible_conduit": (350, "Flexible Conduit — a bendable tube used to protect electrical wiring."),
    "flood_light": (1800, "Flood Light — a powerful light fixture used to illuminate large outdoor areas."),
    "fuse": (50, "Fuse — a safety component that protects electrical circuits from overload."),
    "fuse_holder": (150, "Fuse Holder — a mount used to secure and connect a fuse."),
    "gear_motor": (12000, "Gear Motor — an electric motor combined with a gear reduction system."),
    "heat_gun": (2500, "Heat Gun — a power tool used to apply heat for stripping or shrinking materials."),
    "heat_shrink_sleeve": (100, "Heat Shrink Sleeve — a sleeve that shrinks when heated to insulate wire connections."),
    "heat_shrink_tube": (100, "Heat Shrink Tube — a tube that shrinks when heated to insulate wire connections."),
    "hmi_display": (12000, "HMI Display — a human-machine interface used to control industrial equipment."),
    "home_electrical_supplies": (450, "Home Electrical Supplies — a general range of residential electrical products."),
    "house_wiring_cable": (450, "House Wiring Cable — cable used for residential electrical wiring."),
    "indicator_light": (150, "Indicator Light — a small light used to signal equipment status."),
    "industrial_electrical_supplies": (900, "Industrial Electrical Supplies — a general range of electrical products for industrial use."),
    "insulated_gloves": (900, "Insulated Gloves — protective gloves designed for electrical work safety."),
    "insulated_screwdriver_set": (900, "Insulated Screwdriver Set — a set of screwdrivers designed for safe electrical work."),
    "insulating_tape": (100, "Insulating Tape — tape used to insulate and protect wire connections."),
    "insulation_tester": (5500, "Insulation Tester — a device used to test the integrity of electrical insulation."),
    "inverter": (12000, "Inverter — a device that converts DC power to AC power."),
    "isolator_switch": (900, "Isolator Switch — a switch used to disconnect a circuit for safety."),
    "junction_box": (150, "Junction Box — an enclosure used to safely house electrical wire connections."),
    "lamp_holder": (100, "Lamp Holder — a fixture used to hold and connect a light bulb."),
    "lead_acid_battery": (8500, "Lead Acid Battery — a rechargeable battery type used in backup power systems."),
    "led_bulb": (250, "LED Bulb — an energy-efficient light bulb using LED technology."),
    "led_driver": (700, "LED Driver — a device used to regulate power supplied to LED lighting."),
    "led_tube": (450, "LED Tube — an energy-efficient tube light using LED technology."),
    "light_bulb_socket_electrical_supplies": (100, "Light Bulb Socket — a fixture used to hold and connect a light bulb."),
    "lighting_components": (450, "Lighting Components — a general range of parts used in lighting fixtures."),
    "limit_switch": (450, "Limit Switch — a switch that detects the presence or position of an object."),
    "lithium_battery": (2500, "Lithium Battery — a rechargeable battery known for high energy density."),
    "lockout_tagout_kit": (2500, "Lockout Tagout Kit — a safety kit used to secure equipment during maintenance."),
    "mc4_connector": (150, "MC4 Connector — a connector used for solar panel wiring."),
    "measuring_testing_instruments": (2500, "Measuring & Testing Instruments — a general range of electrical testing tools."),
    "metal_conduit": (450, "Metal Conduit — a metal tube used to protect electrical wiring."),
    "miniature_circuit_breaker_mcb": (450, "Miniature Circuit Breaker (MCB) — an electrical safety device used to protect circuits from overload."),
    "molded_case_circuit_breaker_mccb": (5500, "Molded Case Circuit Breaker (MCCB) — a heavy-duty breaker used to protect higher-capacity circuits."),
    "motion_sensor": (900, "Motion Sensor — a device used to detect movement for lighting or security."),
    "motion_sensor_switch": (900, "Motion Sensor Switch — a switch that activates lighting based on detected movement."),
    "motor_starter": (2500, "Motor Starter — a device used to safely start and control an electric motor."),
    "motors_drives": (12000, "Motors & Drives — a general range of electric motors and drive systems."),
    "multi_plug_adapter": (450, "Multi Plug Adapter — a device used to connect multiple plugs to one outlet."),
    "oscilloscope": (25000, "Oscilloscope — an instrument used to visualize electrical signal waveforms."),
    "overload_relay": (900, "Overload Relay — a protective device used to prevent motor overload damage."),
    "phase_tester": (150, "Phase Tester — a tool used to detect the presence of electrical voltage."),
    "photoelectric_sensor": (900, "Photoelectric Sensor — a sensor used to detect objects using light."),
    "plc_controller": (35000, "PLC Controller — a programmable device used to automate industrial processes."),
    "plug_adapter": (250, "Plug Adapter — a device used to adapt plugs for different socket types."),
    "plug_top": (100, "Plug Top — the connector end of an electrical cord."),
    "power_cable": (450, "Power Cable — a cable used to supply electrical power."),
    "power_meter": (2500, "Power Meter — a device used to measure electrical power consumption."),
    "power_strip": (700, "Power Strip — a device with multiple outlets used to power several devices."),
    "power_supplies": (2500, "Power Supplies — a general range of devices that provide regulated electrical power."),
    "proximity_sensor": (900, "Proximity Sensor — a sensor used to detect nearby objects without contact."),
    "push_button": (150, "Push Button — a control component used to trigger electrical circuits."),
    "push_button_switch": (150, "Push Button Switch — a switch activated by pressing a button."),
    "pvc_conduit_pipe": (150, "PVC Conduit Pipe — plastic tubing used to protect electrical wiring."),
    "rcbo": (1500, "RCBO — a combined circuit breaker offering overload and earth fault protection."),
    "rechargeable_battery": (900, "Rechargeable Battery — a reusable battery designed for repeated charging cycles."),
    "relay": (150, "Relay — an electrical switch used to control various circuits."),
    "residual_current_circuit_breaker_rccb": (1800, "Residual Current Circuit Breaker (RCCB) — a safety device that protects against electrical shock."),
    "residual_current_device_rcd": (1800, "Residual Current Device (RCD) — a safety device that detects and interrupts electrical faults."),
    "ring_terminal": (30, "Ring Terminal — a connector used to attach a wire to a bolted electrical terminal."),
    "rubber_safety_mat": (2500, "Rubber Safety Mat — an insulating mat used for electrical safety."),
    "safety_equipment": (900, "Safety Equipment — a general range of personal protective gear for electrical work."),
    "selector_switch": (450, "Selector Switch — a switch used to select between multiple circuit options."),
    "servo_motor": (15000, "Servo Motor — a precision motor used for controlled motion in automation systems."),
    "smart_doorbell": (5500, "Smart Doorbell — a connected doorbell with camera and remote notification features."),
    "smart_electrical_devices": (2500, "Smart Electrical Devices — a general range of connected electrical products."),
    "smart_energy_meter": (3500, "Smart Energy Meter — a connected device used to track and report electricity usage."),
    "smart_led_bulb": (900, "Smart LED Bulb — a connected light bulb controllable via app or voice assistant."),
    "smart_plug": (900, "Smart Plug — a connected outlet that allows remote control of plugged-in devices."),
    "smart_power_strip": (1800, "Smart Power Strip — a connected power strip with app-controlled outlets."),
    "smart_relay": (1800, "Smart Relay — a programmable relay used for automation control."),
    "smart_switch": (900, "Smart Switch — a connected light switch controllable via app or voice assistant."),
    "smart_thermostat": (8500, "Smart Thermostat — a connected device used to control temperature remotely."),
    "smoke_detector": (900, "Smoke Detector — a safety device used to detect smoke and fire hazards."),
    "smps": (900, "SMPS — a switch-mode power supply used to convert and regulate electrical power."),
    "soft_starter": (5500, "Soft Starter — a device used to gradually start an electric motor to reduce strain."),
    "solar_battery": (18000, "Solar Battery — a rechargeable battery designed to store solar-generated power."),
    "solar_cable": (450, "Solar Cable — a durable cable designed for solar panel wiring."),
    "solar_charge_controller": (3500, "Solar Charge Controller — a device that regulates power flow from a solar panel to a battery."),
    "solar_electrical_supplies": (2500, "Solar Electrical Supplies — a general range of products used for solar power systems."),
    "solar_inverter": (18000, "Solar Inverter — a device that converts solar-generated DC power into usable AC power."),
    "solar_junction_box": (900, "Solar Junction Box — an enclosure used to house solar panel wiring connections."),
    "solar_mounting_kit": (3500, "Solar Mounting Kit — hardware used to secure solar panels in place."),
    "solar_panel": (12000, "Solar Panel — a device used to convert sunlight into electrical energy."),
    "solder_wire": (350, "Solder Wire — a metal alloy wire used to join electrical components."),
    "soldering_iron": (900, "Soldering Iron — a tool used to melt solder for joining electrical components."),
    "spade_terminal": (30, "Spade Terminal — a connector used to attach a wire to a flat electrical terminal."),
    "speaker_cable": (350, "Speaker Cable — a cable used to connect audio speakers to an amplifier."),
    "spiral_cable_wrap": (250, "Spiral Cable Wrap — a wrap used to bundle and organize multiple cables."),
    "spot_light": (900, "Spot Light — a focused light fixture used to highlight specific areas."),
    "starter": (450, "Starter — a device used to initiate current flow for fluorescent lighting."),
    "stepper_motor": (2500, "Stepper Motor — a motor used for precise, incremental rotational control."),
    "street_light": (5500, "Street Light — an outdoor light fixture designed for road and pathway illumination."),
    "surge_protection_device_spd": (2500, "Surge Protection Device (SPD) — a device used to protect circuits from voltage spikes."),
    "switches_sockets": (250, "Switches & Sockets — a general range of electrical switching and outlet products."),
    "switching_power_supply": (1800, "Switching Power Supply — a device used to convert and regulate electrical power efficiently."),
    "telephone_cable": (350, "Telephone Cable — a cable used for landline telephone connections."),
    "terminal_block": (250, "Terminal Block — a connector used to join multiple electrical wires."),
    "terminal_connector": (100, "Terminal Connector — a connector used to attach wires to electrical terminals."),
    "timer_relay": (900, "Timer Relay — a relay used to control circuits based on a preset time delay."),
    "touch_switch": (900, "Touch Switch — a switch activated by touch rather than a physical toggle."),
    "track_light": (1800, "Track Light — an adjustable light fixture mounted on a track system."),
    "transformer": (65000, "Transformer — an electrical device used to change voltage levels in a power system."),
    "travel_adapter": (900, "Travel Adapter — a device used to adapt plugs for international power outlets."),
    "tube_light": (450, "Tube Light — a linear light fixture commonly used for general illumination."),
    "universal_socket": (250, "Universal Socket — a versatile outlet compatible with multiple plug types."),
    "ups": (8500, "UPS — an uninterruptible power supply used to provide backup power for electronics."),
    "usb_wall_socket": (900, "USB Wall Socket — a wall outlet with integrated USB charging ports."),
    "variable_frequency_drive_vfd": (18000, "Variable Frequency Drive (VFD) — a device used to control motor speed by varying power frequency."),
    "ventilation_fan": (2500, "Ventilation Fan — a fan used to improve air circulation in enclosed spaces."),
    "voltage_stabilizer": (3500, "Voltage Stabilizer — a device used to regulate voltage for connected equipment."),
    "voltage_tester": (350, "Voltage Tester — a tool used to detect the presence of electrical voltage."),
    "wall_switch": (150, "Wall Switch — a switch used to control electrical devices and lighting."),
    "warning_sign": (250, "Warning Sign — a safety sign used to indicate electrical hazards."),
    "welding_cable": (900, "Welding Cable — a heavy-duty cable used for welding equipment connections."),
    "wi_fi_switch_module": (900, "Wi-Fi Switch Module — a connected module used to enable remote switch control."),
    "wire_connector": (50, "Wire Connector — a component used to join electrical wires securely."),
    "wire_duct": (450, "Wire Duct — a channel used to organize and protect electrical wiring."),
    "wire_ferrule": (30, "Wire Ferrule — a metal sleeve used to protect stripped wire ends."),
    "wire_labels": (100, "Wire Labels — tags used to identify electrical wires."),
    "wire_stripper": (450, "Wire Stripper — a tool used to remove insulation from electrical wires."),
}

path = "data/products-placeholder.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
skipped = []
for sku, prod in data.items():
    if prod.get("categoryId") == "electrical_equipment_supplies":
        img = prod["images"]["main"].split("/")[-1].replace(".png", "")
        if img in price_desc:
            price, desc = price_desc[img]
            title = " ".join(w.capitalize() for w in img.split("_"))
            prod["title"] = title
            prod["price"] = price
            prod["description"] = desc
            prod["status"] = "active"
            updated += 1
        else:
            skipped.append((sku, img))

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
