import json

price_desc = {
    "home_kitchen": (500, "Home & Kitchen Products — a general range of items designed for household and kitchen use."),
    "air_fryer": (5500, "Air Fryer — a kitchen appliance used to cook food with hot air for a healthier alternative to frying."),
    "air_purifier": (4500, "Air Purifier — a device that filters and cleans indoor air."),
    "airtight_container": (350, "Airtight Container — a sealed container designed to keep food fresh."),
    "aluminum_foil": (200, "Aluminum Foil — a thin metal foil used for food storage and cooking."),
    "artificial_flowers": (450, "Artificial Flowers — decorative flowers designed for long-lasting home decor."),
    "bakeware": (900, "Bakeware — a general range of pans and dishes designed for baking."),
    "baking_dish": (700, "Baking Dish — an oven-safe dish designed for baking meals."),
    "baking_tray": (450, "Baking Tray — a flat tray designed for baking in an oven."),
    "bath_mat": (500, "Bath Mat — a mat designed to provide a non-slip bathroom surface."),
    "bathroom_essentials": (500, "Bathroom Essentials — a general range of items designed for bathroom use."),
    "bathroom_shelf": (900, "Bathroom Shelf — a shelf designed for bathroom storage."),
    "bed_sheet": (900, "Bed Sheet — a fitted or flat sheet designed for a bed."),
    "bedroom_essentials": (700, "Bedroom Essentials — a general range of items designed for bedroom use."),
    "bedspread": (1500, "Bedspread — a decorative covering designed for a bed."),
    "beverage_dispenser": (900, "Beverage Dispenser — a container designed for serving drinks."),
    "blanket": (900, "Blanket — a soft covering designed to keep warm."),
    "blender": (2500, "Blender — a kitchen appliance used to blend fruits, vegetables, and beverages."),
    "bottle_opener": (150, "Bottle Opener — a small tool used to open bottle caps."),
    "bowl": (250, "Bowl — a round dish used for serving or preparing food."),
    "broom": (350, "Broom — a cleaning tool used to sweep floors."),
    "bucket": (350, "Bucket — a container used for carrying water or cleaning supplies."),
    "cake_mold": (450, "Cake Mold — a shaped pan designed for baking cakes."),
    "cake_pan": (450, "Cake Pan — a pan designed for baking cakes."),
    "cake_stand": (900, "Cake Stand — a raised stand designed for displaying cakes."),
    "can_opener": (250, "Can Opener — a tool used to open canned food."),
    "candle_holder": (450, "Candle Holder — a decorative stand designed to hold candles."),
    "casserole_dish": (900, "Casserole Dish — an oven-safe dish designed for baking and serving casseroles."),
    "chef_knife": (900, "Chef Knife — a versatile kitchen knife designed for food preparation."),
    "christmas_decorations": (700, "Christmas Decorations — festive decor items designed for the holiday season."),
    "cleaning_cloth": (150, "Cleaning Cloth — a reusable cloth designed for household cleaning."),
    "cleaning_sponge": (100, "Cleaning Sponge — a sponge designed for household cleaning tasks."),
    "cleaning_supplies": (350, "Cleaning Supplies — a general range of products designed for household cleaning."),
    "closet_organizer": (900, "Closet Organizer — a storage system used to organize clothing and items."),
    "clothes_drying_rack": (1200, "Clothes Drying Rack — a rack designed for air-drying laundry."),
    "coffee_cup_set": (700, "Coffee Cup Set — a set of cups designed for serving coffee."),
    "coffee_maker": (2500, "Coffee Maker — a kitchen appliance used to brew coffee."),
    "colander": (350, "Colander — a perforated bowl used to drain food."),
    "comforter": (2200, "Comforter — a thick quilted covering designed for a bed."),
    "cookie_sheet": (450, "Cookie Sheet — a flat tray designed for baking cookies."),
    "cookware": (2500, "Cookware — a general range of pots and pans designed for cooking."),
    "cookware_kitchen_utensils": (900, "Cookware & Kitchen Utensils — a general range of tools designed for cooking."),
    "cookware_set": (5500, "Cookware Set — a coordinated set of pots and pans designed for cooking."),
    "cooling_rack": (350, "Cooling Rack — a wire rack designed for cooling baked goods."),
    "cup": (150, "Cup — a drinking vessel used for beverages."),
    "cushion": (450, "Cushion — a padded cover designed for seating comfort."),
    "cushion_cover": (350, "Cushion Cover — a fabric cover designed for a cushion."),
    "cutting_board": (450, "Cutting Board — a flat board designed for food preparation."),
    "decorative_lights": (700, "Decorative Lights — string or accent lights designed for home decor."),
    "decorative_vase": (700, "Decorative Vase — a vase designed for displaying flowers or as home decor."),
    "dehumidifier": (5500, "Dehumidifier — a device that reduces excess moisture in indoor air."),
    "dining_serving": (900, "Dining & Serving Products — a general range of items designed for dining and serving food."),
    "dinner_plate": (250, "Dinner Plate — a plate designed for serving meals."),
    "dinner_set": (3500, "Dinner Set — a coordinated set of plates and dishes designed for dining."),
    "dinnerware": (1800, "Dinnerware — a general range of plates and dishes designed for dining."),
    "dish_brush": (150, "Dish Brush — a brush designed for washing dishes."),
    "dish_drying_rack": (900, "Dish Drying Rack — a rack designed for air-drying washed dishes."),
    "dish_rack": (900, "Dish Rack — a rack designed for storing and drying dishes."),
    "drawer_organizer": (500, "Drawer Organizer — a tray insert designed to organize drawer contents."),
    "dustpan": (250, "Dustpan — a cleaning tool used to collect swept debris."),
    "dutch_oven": (3500, "Dutch Oven — a heavy pot designed for slow cooking and braising."),
    "duvet": (2500, "Duvet — a soft quilted covering designed for a bed."),
    "eid_decorations": (700, "Eid Decorations — festive decor items designed for Eid celebrations."),
    "electric_kettle": (1500, "Electric Kettle — an appliance used to quickly boil water."),
    "electric_oven": (8500, "Electric Oven — a kitchen appliance used for baking and roasting."),
    "espresso_machine": (7500, "Espresso Machine — an appliance used to brew espresso coffee."),
    "fabric_storage_bag": (450, "Fabric Storage Bag — a soft bag designed for storing clothing or linens."),
    "fan_heater": (2500, "Fan Heater — a portable heater that uses a fan to circulate warm air."),
    "festive_table_decor": (700, "Festive Table Decor — decorative items designed for holiday table settings."),
    "floor_lamp": (2500, "Floor Lamp — a standing lamp designed for ambient room lighting."),
    "food_processor": (4500, "Food Processor — a kitchen appliance used to chop, blend, and process food."),
    "food_storage": (500, "Food Storage Products — a general range of containers designed for storing food."),
    "food_storage_container": (450, "Food Storage Container — a container designed for storing food."),
    "food_wrap": (150, "Food Wrap — a plastic film used to cover and preserve food."),
    "frying_pan": (900, "Frying Pan — a flat-bottomed pan designed for frying food."),
    "garbage_bags": (200, "Garbage Bags — disposable bags designed for waste disposal."),
    "garlic_press": (250, "Garlic Press — a tool used to crush garlic cloves."),
    "garment_steamer": (2500, "Garment Steamer — a device used to remove wrinkles from clothing using steam."),
    "glass_set": (900, "Glass Set — a coordinated set of drinking glasses."),
    "glass_storage_jar": (450, "Glass Storage Jar — a glass container designed for food storage."),
    "grater": (250, "Grater — a tool used to shred or grate food."),
    "grill_pan": (900, "Grill Pan — a ridged pan designed for stovetop grilling."),
    "hand_mixer": (1800, "Hand Mixer — a handheld appliance used for mixing and beating ingredients."),
    "hangers": (200, "Hangers — clothing hangers designed for closet storage."),
    "hanging_basket": (450, "Hanging Basket — a basket designed for hanging storage or plants."),
    "home_appliances": (2500, "Home Appliances — a general range of electric devices designed for household use."),
    "home_decor": (700, "Home Decor Products — a general range of decorative items designed for the home."),
    "home_storage": (700, "Home Storage Products — a general range of solutions designed for household organization."),
    "humidifier": (3500, "Humidifier — a device that adds moisture to indoor air."),
    "ice_maker": (7500, "Ice Maker — an appliance used to produce ice cubes."),
    "indoor_plant": (700, "Indoor Plant — a plant designed for decorative indoor use."),
    "induction_cooker": (3500, "Induction Cooker — a cooktop that uses electromagnetic heating for cooking."),
    "ironing_accessories": (350, "Ironing Accessories — a general range of items designed to assist with ironing."),
    "ironing_board": (1800, "Ironing Board — a foldable board designed for ironing clothes."),
    "juicer": (3500, "Juicer — a kitchen appliance used to extract juice from fruits and vegetables."),
    "kitchen_appliances": (3500, "Kitchen Appliances — a general range of electric devices designed for cooking."),
    "kitchen_cabinet_organizer": (700, "Kitchen Cabinet Organizer — a storage solution designed for kitchen cabinets."),
    "kitchen_scissors": (300, "Kitchen Scissors — scissors designed for food preparation tasks."),
    "kitchen_shelf": (1500, "Kitchen Shelf — a shelf designed for kitchen storage."),
    "kitchen_storage_organization": (700, "Kitchen Storage & Organization Products — a general range of solutions designed for kitchen storage."),
    "kitchen_utensils": (500, "Kitchen Utensils — a general range of tools designed for food preparation."),
    "knife_set": (1800, "Knife Set — a coordinated set of kitchen knives."),
    "ladle": (200, "Ladle — a long-handled spoon used for serving soups and stews."),
    "laundry_basket": (900, "Laundry Basket — a basket designed for carrying and storing laundry."),
    "laundry_cleaning": (500, "Laundry & Cleaning Products — a general range of items designed for laundry care."),
    "lint_roller": (150, "Lint Roller — a tool used to remove lint and pet hair from fabric."),
    "loaf_pan": (450, "Loaf Pan — a pan designed for baking bread and loaves."),
    "lunch_box": (500, "Lunch Box — a container designed for carrying meals."),
    "mattress_protector": (900, "Mattress Protector — a waterproof cover designed to protect a mattress."),
    "measuring_cups": (300, "Measuring Cups — a set of cups designed for accurate ingredient measurement."),
    "measuring_spoons": (200, "Measuring Spoons — a set of spoons designed for accurate ingredient measurement."),
    "meat_grinder": (3500, "Meat Grinder — an appliance used to grind meat."),
    "microwave_oven": (7500, "Microwave Oven — an appliance used to heat and cook food using microwaves."),
    "mirror": (900, "Mirror — a reflective glass panel designed for home decor."),
    "mixer_grinder": (3500, "Mixer Grinder — an appliance used to grind and mix ingredients."),
    "mixing_bowl": (450, "Mixing Bowl — a bowl designed for mixing ingredients."),
    "mop": (450, "Mop — a cleaning tool used to clean floors."),
    "mortar_pestle": (450, "Mortar & Pestle — a tool set used to grind spices and ingredients."),
    "muffin_tray": (450, "Muffin Tray — a pan designed for baking muffins."),
    "mug": (200, "Mug — a drinking vessel designed for hot beverages."),
    "multi_cooker": (5500, "Multi-Cooker — an appliance that combines multiple cooking functions."),
    "pantry_storage_bin": (450, "Pantry Storage Bin — a bin designed for organizing pantry items."),
    "peeler": (150, "Peeler — a tool used to peel the skin off fruits and vegetables."),
    "pet_bed": (1800, "Pet Bed — a bed designed for pet comfort."),
    "pet_feeding_mat": (450, "Pet Feeding Mat — a mat designed to catch spills around pet feeding bowls."),
    "pet_food_bowl": (350, "Pet Food Bowl — a bowl designed for feeding pets."),
    "pet_home_essentials": (900, "Pet Home Essentials — a general range of items designed for pet care at home."),
    "pet_storage_bin": (450, "Pet Storage Bin — a bin designed for storing pet food and supplies."),
    "pet_water_fountain": (2500, "Pet Water Fountain — a device that provides a continuous water source for pets."),
    "photo_frame": (450, "Photo Frame — a frame designed for displaying photographs."),
    "pillow": (700, "Pillow — a soft cushion designed for head and neck support."),
    "pillow_cover": (350, "Pillow Cover — a fabric cover designed for a pillow."),
    "pizza_cutter": (200, "Pizza Cutter — a wheeled tool used to slice pizza."),
    "pizza_pan": (450, "Pizza Pan — a flat pan designed for baking pizza."),
    "plastic_drawer": (1500, "Plastic Drawer — a stackable drawer unit designed for storage."),
    "plate_rack": (700, "Plate Rack — a rack designed for storing and drying plates."),
    "pot_rack": (1500, "Pot Rack — a rack designed for hanging and storing pots."),
    "pressure_cooker": (3500, "Pressure Cooker — a pot designed to cook food quickly using pressurized steam."),
    "ramadan_lantern": (700, "Ramadan Lantern — a decorative lantern designed for Ramadan celebrations."),
    "rice_cooker": (2500, "Rice Cooker — an appliance used to cook rice."),
    "roasting_pan": (1500, "Roasting Pan — a large pan designed for roasting meats and vegetables."),
    "robot_vacuum": (15000, "Robot Vacuum — an automated vacuum cleaner designed for hands-free cleaning."),
    "rolling_pin": (250, "Rolling Pin — a tool used to flatten dough."),
    "rubber_gloves": (150, "Rubber Gloves — protective gloves designed for cleaning tasks."),
    "salad_bowl": (450, "Salad Bowl — a bowl designed for serving salads."),
    "sandwich_maker": (2200, "Sandwich Maker — an appliance used to toast and press sandwiches."),
    "saucepan": (900, "Saucepan — a pan designed for cooking sauces and small dishes."),
    "scented_candle": (450, "Scented Candle — a candle designed to release fragrance while burning."),
    "scrub_pad": (100, "Scrub Pad — a pad designed for scrubbing dishes and surfaces."),
    "seasonal_holiday": (700, "Seasonal & Holiday Products — a general range of decor items designed for seasonal celebrations."),
    "serving_bowl": (700, "Serving Bowl — a bowl designed for serving food at the table."),
    "serving_platter": (900, "Serving Platter — a flat dish designed for serving food."),
    "serving_spoon": (200, "Serving Spoon — a large spoon designed for serving food."),
    "serving_tray": (700, "Serving Tray — a flat tray designed for carrying and serving food."),
    "shelving_unit": (2500, "Shelving Unit — a freestanding unit designed for storage."),
    "shoe_rack": (1500, "Shoe Rack — a rack designed for organizing footwear."),
    "shower_curtain": (700, "Shower Curtain — a curtain designed for bathroom shower enclosures."),
    "side_plate": (200, "Side Plate — a small plate designed for serving side dishes."),
    "sieve": (250, "Sieve — a mesh tool used to strain or sift ingredients."),
    "silicone_baking_mat": (450, "Silicone Baking Mat — a reusable mat designed for non-stick baking."),
    "sink_organizer": (450, "Sink Organizer — a caddy designed to organize sink-side cleaning supplies."),
    "slow_cooker": (3500, "Slow Cooker — an appliance used to cook food slowly at low temperatures."),
    "smart_bulb": (900, "Smart Bulb — a connected light bulb controllable via app or voice."),
    "smart_doorbell": (5500, "Smart Doorbell — a connected doorbell with camera and app notifications."),
    "smart_home": (2500, "Smart Home Products — a general range of connected devices designed for home automation."),
    "smart_plug": (700, "Smart Plug — a connected outlet adapter controllable via app or voice."),
    "smart_security_camera": (4500, "Smart Security Camera — a connected camera designed for home monitoring."),
    "smart_speaker": (3500, "Smart Speaker — a voice-controlled speaker with smart assistant integration."),
    "smart_switch": (900, "Smart Switch — a connected light switch controllable via app or voice."),
    "soap_dispenser": (350, "Soap Dispenser — a dispenser designed for convenient hand soap use."),
    "soup_bowl": (250, "Soup Bowl — a bowl designed for serving soup."),
    "spatula": (200, "Spatula — a flat tool used for flipping and serving food."),
    "spice_jar": (200, "Spice Jar — a small jar designed for storing spices."),
    "spice_rack": (900, "Spice Rack — a rack designed for organizing spice jars."),
    "spray_bottle": (150, "Spray Bottle — a bottle designed for dispensing liquid in a fine mist."),
    "springform_pan": (900, "Springform Pan — a baking pan with removable sides, ideal for cheesecakes."),
    "stand_mixer": (9500, "Stand Mixer — a countertop appliance used for mixing and kneading ingredients."),
    "steam_cleaner": (5500, "Steam Cleaner — a device that uses steam to clean and sanitize surfaces."),
    "steam_iron": (1800, "Steam Iron — an iron that uses steam to remove wrinkles from clothing."),
    "steamer_pot": (1500, "Steamer Pot — a pot designed for steaming food."),
    "stock_pot": (1800, "Stock Pot — a large pot designed for making stocks and soups."),
    "storage_basket": (700, "Storage Basket — a basket used to organize household items."),
    "storage_box": (700, "Storage Box — a box designed for general household storage."),
    "string_lights": (450, "String Lights — decorative lights designed for ambient home lighting."),
    "table_lamp": (1800, "Table Lamp — a lamp designed for tabletop ambient lighting."),
    "tea_cup_set": (700, "Tea Cup Set — a set of cups designed for serving tea."),
    "tea_maker": (2500, "Tea Maker — an appliance used to brew tea."),
    "thermos_flask": (700, "Thermos Flask — an insulated flask designed to keep beverages hot or cold."),
    "toaster": (1800, "Toaster — an appliance used to toast bread."),
    "toilet_brush": (250, "Toilet Brush — a brush designed for cleaning the toilet."),
    "tongs": (250, "Tongs — a tool used to grip and serve food."),
    "toothbrush_holder": (250, "Toothbrush Holder — a stand designed for storing toothbrushes."),
    "towel": (350, "Towel — an absorbent fabric designed for drying."),
    "towel_rack": (700, "Towel Rack — a rack designed for hanging towels."),
    "tower_fan": (3500, "Tower Fan — a slim standing fan designed for room cooling."),
    "trash_bin": (700, "Trash Bin — a container designed for household waste disposal."),
    "under_sink_organizer": (700, "Under-Sink Organizer — a storage solution designed for under-sink cabinets."),
    "vacuum_cleaner": (6500, "Vacuum Cleaner — an appliance used to clean floors and carpets."),
    "vacuum_flask": (700, "Vacuum Flask — an insulated flask designed to keep beverages hot or cold."),
    "vacuum_food_container": (700, "Vacuum Food Container — a container designed to vacuum-seal food for freshness."),
    "vacuum_storage_bag": (350, "Vacuum Storage Bag — a bag designed to compress and store clothing or linens."),
    "waffle_maker": (2500, "Waffle Maker — an appliance used to cook waffles."),
    "wall_art": (900, "Wall Art — decorative artwork designed for wall display."),
    "wall_clock": (900, "Wall Clock — a clock designed for wall display."),
    "washing_basket": (900, "Washing Basket — a basket designed for carrying laundry."),
    "water_dispenser": (5500, "Water Dispenser — a device designed to dispense drinking water."),
    "water_jug": (450, "Water Jug — a container designed for storing and pouring water."),
    "water_purifier": (5500, "Water Purifier — a device designed to purify drinking water."),
    "whisk": (200, "Whisk — a tool used to beat and mix ingredients."),
    "wine_glass": (350, "Wine Glass — a glass designed for serving wine."),
    "wok": (900, "Wok — a round-bottomed pan designed for stir-frying."),
    "wreath": (700, "Wreath — a decorative ring designed for door or wall display."),
    "zip_lock_bags": (200, "Zip Lock Bags — resealable bags designed for food storage."),
}

paths = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch2.json",
]

total_updated = 0
total_skipped = []
for path in paths:
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        continue

    updated = 0
    for sku, prod in data.items():
        if prod.get("categoryId") == "home_kitchen":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
            else:
                total_skipped.append((path, sku, img))

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"{path}: Updated {updated}")
    total_updated += updated

print(f"Total Updated: {total_updated}")
print(f"Skipped: {total_skipped}")
