import json

price_desc = {
    "industrial_machinery_equipment": (2500, "Industrial Machinery & Equipment — a general range of machines designed for industrial and manufacturing use."),
    "abrasive_wheels": (700, "Abrasive Wheels — cutting and grinding wheels designed for industrial power tools."),
    "ac_motor": (8500, "AC Motor — an electric motor powered by alternating current, used in industrial equipment."),
    "air_compressor": (12500, "Air Compressor — a machine that pressurizes air for powering pneumatic tools."),
    "air_dryer": (9500, "Air Dryer — an industrial device used to remove moisture from compressed air."),
    "air_filter_regulator": (1800, "Air Filter Regulator — a device used to filter and regulate compressed air pressure."),
    "air_hose": (900, "Air Hose — a flexible hose designed for transmitting compressed air."),
    "air_tank": (5500, "Air Tank — a storage tank designed for compressed air systems."),
    "arc_welding_machine": (12500, "Arc Welding Machine — a machine used to fuse metal using an electric arc."),
    "asphalt_cutter": (25000, "Asphalt Cutter — a machine used to cut through asphalt and concrete surfaces."),
    "automatic_transfer_switch": (15000, "Automatic Transfer Switch — a device that automatically switches power sources during an outage."),
    "ball_valve": (450, "Ball Valve — a valve used to control the flow of liquid or gas."),
    "band_saw": (9500, "Band Saw — a power tool used for cutting materials with a continuous blade."),
    "bench_grinder": (3500, "Bench Grinder — a stationary power tool used for grinding and sharpening."),
    "blow_molding_machine": (85000, "Blow Molding Machine — an industrial machine used to manufacture hollow plastic products."),
    "bone_saw_machine": (9500, "Bone Saw Machine — an industrial machine used to cut through bone in meat processing."),
    "booster_pump": (5500, "Booster Pump — a pump used to increase water or fluid pressure."),
    "bottle_filling_machine": (45000, "Bottle Filling Machine — an industrial machine used to fill bottles with liquid products."),
    "butterfly_valve": (900, "Butterfly Valve — a valve used to regulate flow in a pipeline."),
    "cable_ties": (100, "Cable Ties — plastic ties used to bundle and organize cables."),
    "capping_machine": (25000, "Capping Machine — an industrial machine used to seal bottle caps."),
    "carton_sealing_machine": (15000, "Carton Sealing Machine — an industrial machine used to seal packaging cartons."),
    "centrifugal_pump": (6500, "Centrifugal Pump — a pump that uses rotational energy to move fluid."),
    "centrifuge": (12500, "Centrifuge — a machine that uses rotation to separate substances of different densities."),
    "chain_conveyor": (25000, "Chain Conveyor — an industrial system designed to move materials using a chain mechanism."),
    "check_valve": (450, "Check Valve — a valve that allows fluid flow in only one direction."),
    "chemical_pump": (6500, "Chemical Pump — a pump designed for transferring corrosive or chemical fluids."),
    "clamp_meter": (2500, "Clamp Meter — an electrical testing tool used to measure current without disconnecting wires."),
    "cnc_lathe_machine": (150000, "CNC Lathe Machine — a computer-controlled machine used for precision turning operations."),
    "cnc_machine": (150000, "CNC Machine — a computer-controlled machine used for precision manufacturing."),
    "cnc_router": (85000, "CNC Router — a computer-controlled cutting machine used for various materials."),
    "coding_machine": (15000, "Coding Machine — an industrial machine used to print codes and dates on packaging."),
    "commercial_blender": (5500, "Commercial Blender — a heavy-duty blender designed for commercial kitchen use."),
    "concrete_mixer": (25000, "Concrete Mixer — a machine used to mix cement, sand, and water into concrete."),
    "concrete_vibrator": (9500, "Concrete Vibrator — a tool used to remove air bubbles from poured concrete."),
    "contactor": (900, "Contactor — an electrical switch used to control high-power circuits."),
    "conveyor_belt": (35000, "Conveyor Belt — a system designed to move materials continuously along a path."),
    "crane": (250000, "Crane — a heavy machine used to lift and move large loads."),
    "cultivator": (15000, "Cultivator — an agricultural machine used to till and prepare soil."),
    "cutting_oil": (900, "Cutting Oil — a lubricant used to cool and lubricate metal cutting operations."),
    "dc_motor": (6500, "DC Motor — an electric motor powered by direct current, used in industrial equipment."),
    "diaphragm_pump": (5500, "Diaphragm Pump — a pump that uses a flexible diaphragm to move fluid."),
    "die_casting_machine": (150000, "Die Casting Machine — an industrial machine used to manufacture metal parts by injecting molten metal into molds."),
    "diesel_generator": (65000, "Diesel Generator — a machine that generates electricity using a diesel engine."),
    "digital_multimeter": (1800, "Digital Multimeter — an electrical testing tool used to measure voltage, current, and resistance."),
    "dough_mixer": (12500, "Dough Mixer — an industrial mixer designed for bakery dough preparation."),
    "drill_press": (9500, "Drill Press — a stationary power tool used for precision drilling."),
    "drilling_machine": (12500, "Drilling Machine — an industrial machine used for drilling holes in various materials."),
    "drum_trolley": (3500, "Drum Trolley — a wheeled cart designed for transporting industrial drums."),
    "electric_forklift": (350000, "Electric Forklift — a battery-powered vehicle used for lifting and moving heavy loads."),
    "electric_pallet_jack": (85000, "Electric Pallet Jack — a battery-powered tool used to lift and move pallets."),
    "emergency_eye_wash_station": (9500, "Emergency Eye Wash Station — a safety device designed for immediate eye irrigation in emergencies."),
    "extrusion_machine": (150000, "Extrusion Machine — an industrial machine used to shape material by forcing it through a die."),
    "face_shield": (250, "Face Shield — a protective clear shield worn over the face."),
    "fire_extinguisher": (1500, "Fire Extinguisher — a portable device designed to put out small fires."),
    "floor_scrubber": (15000, "Floor Scrubber — a machine used to clean and scrub large floor areas."),
    "forklift": (450000, "Forklift — a vehicle used for lifting and moving heavy loads."),
    "fuel_transfer_pump": (5500, "Fuel Transfer Pump — a pump designed for moving fuel between containers."),
    "gas_generator": (55000, "Gas Generator — a machine that generates electricity using natural gas or propane."),
    "gate_valve": (450, "Gate Valve — a valve used to control the flow of liquid in a pipeline."),
    "gear_motor": (7500, "Gear Motor — an electric motor combined with a gear reducer for controlled output speed."),
    "generator_control_panel": (12500, "Generator Control Panel — a panel used to monitor and control a generator's operation."),
    "globe_valve": (700, "Globe Valve — a valve used to regulate flow in a pipeline."),
    "grain_mill": (9500, "Grain Mill — a machine used to grind grain into flour."),
    "grinding_machine": (25000, "Grinding Machine — an industrial machine used for precision surface grinding."),
    "hand_pallet_truck": (9500, "Hand Pallet Truck — a manual tool used to lift and move pallets."),
    "harvesting_machine": (250000, "Harvesting Machine — an agricultural machine used to harvest crops."),
    "high_visibility_vest": (350, "High Visibility Vest — a reflective vest designed for worker safety."),
    "hmi_touch_panel": (15000, "HMI Touch Panel — a human-machine interface used to control industrial systems."),
    "hoist": (15000, "Hoist — a device used to lift and lower heavy loads."),
    "hot_plate": (1500, "Hot Plate — a heating device used for laboratory or industrial applications."),
    "hydraulic_jack": (3500, "Hydraulic Jack — a tool used to lift heavy loads."),
    "hydraulic_oil": (900, "Hydraulic Oil — a fluid used to power hydraulic machinery."),
    "hydraulic_press": (65000, "Hydraulic Press — a machine that uses hydraulic pressure to shape or compress materials."),
    "hydraulic_pump": (12500, "Hydraulic Pump — a pump used to generate hydraulic fluid flow for machinery."),
    "incubator": (9500, "Incubator — a controlled-environment chamber used for laboratory or agricultural purposes."),
    "industrial_adhesives": (900, "Industrial Adhesives — heavy-duty adhesives designed for industrial bonding applications."),
    "industrial_generator": (75000, "Industrial Generator — a heavy-duty machine that generates electricity for industrial use."),
    "industrial_grease": (700, "Industrial Grease — a lubricant designed for heavy machinery maintenance."),
    "industrial_oven": (35000, "Industrial Oven — a heavy-duty oven designed for manufacturing or processing applications."),
    "industrial_power_supply": (9500, "Industrial Power Supply — a device designed to convert and regulate power for industrial equipment."),
    "industrial_relay": (450, "Industrial Relay — an electrical switch used to control industrial circuits."),
    "industrial_shelving": (5500, "Industrial Shelving — heavy-duty shelving designed for warehouse storage."),
    "industrial_tool_set": (5500, "Industrial Tool Set — a coordinated collection of heavy-duty tools."),
    "industrial_vacuum_cleaner": (15000, "Industrial Vacuum Cleaner — a heavy-duty vacuum designed for industrial cleaning."),
    "infrared_thermometer": (900, "Infrared Thermometer — a non-contact thermometer used to measure surface temperature."),
    "injection_molding_machine": (350000, "Injection Molding Machine — an industrial machine used to manufacture plastic parts by injecting molten material into molds."),
    "insulation_tester": (5500, "Insulation Tester — a device used to test electrical insulation resistance."),
    "irrigation_pump": (9500, "Irrigation Pump — a pump designed for agricultural water irrigation."),
    "labeling_machine": (25000, "Labeling Machine — an industrial machine used to apply labels to products."),
    "laboratory_balance": (5500, "Laboratory Balance — a precision scale used for laboratory measurements."),
    "laboratory_oven": (9500, "Laboratory Oven — an oven designed for controlled heating in laboratory settings."),
    "laser_cutting_machine": (250000, "Laser Cutting Machine — an industrial machine that uses a laser to cut materials."),
    "laser_distance_meter": (2500, "Laser Distance Meter — a device used to measure distance using a laser."),
    "limit_switch": (450, "Limit Switch — an electrical switch used to detect the position of machinery."),
    "lubricants": (700, "Lubricants — a general range of fluids designed to reduce friction in machinery."),
    "meat_grinder": (3500, "Meat Grinder — an appliance used to grind meat."),
    "meat_slicer": (9500, "Meat Slicer — a machine used to slice meat and deli products."),
    "microscope": (9500, "Microscope — an instrument used to view small objects and specimens."),
    "mig_welding_machine": (15000, "MIG Welding Machine — a machine used for metal inert gas welding."),
    "milling_machine": (150000, "Milling Machine — an industrial machine used for precision material removal."),
    "motor_starter": (1500, "Motor Starter — an electrical device used to safely start an electric motor."),
    "oil_press_machine": (25000, "Oil Press Machine — a machine used to extract oil from seeds and nuts."),
    "oscilloscope": (15000, "Oscilloscope — an electronic testing device used to visualize electrical signals."),
    "pallet_rack": (9500, "Pallet Rack — a storage rack system designed for warehouse pallets."),
    "ph_meter": (2500, "pH Meter — a device used to measure the acidity or alkalinity of a solution."),
    "photoelectric_sensor": (900, "Photoelectric Sensor — a sensor that uses light to detect objects in industrial automation."),
    "pipe_fittings": (250, "Pipe Fittings — connectors designed for joining pipes."),
    "pipe_flange": (700, "Pipe Flange — a fitting used to connect pipes, valves, and equipment."),
    "piston_compressor": (25000, "Piston Compressor — an air compressor that uses pistons to compress air."),
    "plasma_cutting_machine": (55000, "Plasma Cutting Machine — an industrial machine that uses plasma to cut conductive materials."),
    "plasma_welder": (25000, "Plasma Welder — a welding machine that uses a plasma arc for precision welding."),
    "plate_compactor": (25000, "Plate Compactor — a machine used to compact soil and asphalt surfaces."),
    "plc_controller": (25000, "PLC Controller — a programmable logic controller used to automate industrial processes."),
    "pneumatic_cylinder": (2500, "Pneumatic Cylinder — a device that uses compressed air to produce mechanical motion."),
    "pneumatic_drill": (5500, "Pneumatic Drill — an air-powered drill used for industrial applications."),
    "pneumatic_grinder": (3500, "Pneumatic Grinder — an air-powered grinder used for industrial applications."),
    "portable_generator": (25000, "Portable Generator — a compact machine that generates electricity for on-the-go use."),
    "power_tiller": (55000, "Power Tiller — an agricultural machine used to till soil."),
    "power_trowel": (35000, "Power Trowel — a machine used to smooth and finish concrete surfaces."),
    "press_machine": (85000, "Press Machine — an industrial machine used to shape or cut materials using pressure."),
    "pressure_gauge": (450, "Pressure Gauge — a device used to measure fluid or gas pressure."),
    "pressure_washer": (9500, "Pressure Washer — a machine that uses pressurized water for cleaning."),
    "proximity_sensor": (700, "Proximity Sensor — a sensor used to detect the presence of nearby objects."),
    "punch_press": (150000, "Punch Press — an industrial machine used to cut or shape metal using a punching mechanism."),
    "rebar_bender": (25000, "Rebar Bender — a machine used to bend steel reinforcement bars."),
    "rebar_cutter": (25000, "Rebar Cutter — a machine used to cut steel reinforcement bars."),
    "respirator": (700, "Respirator — a protective mask designed to filter harmful airborne particles."),
    "rice_transplanter": (150000, "Rice Transplanter — an agricultural machine used to plant rice seedlings."),
    "road_cutter": (25000, "Road Cutter — a machine used to cut through road surfaces."),
    "robotic_arm_industrial_machine": (250000, "Robotic Arm — an automated industrial machine used for manufacturing tasks."),
    "roller_conveyor": (25000, "Roller Conveyor — a conveyor system that uses rollers to move materials."),
    "rotary_screw_compressor": (65000, "Rotary Screw Compressor — an industrial air compressor using a rotary screw mechanism."),
    "safety_boots": (1800, "Safety Boots — protective footwear designed for work environments."),
    "safety_gloves": (350, "Safety Gloves — protective gloves designed for industrial work."),
    "safety_helmet": (700, "Safety Helmet — protective headgear designed for work environments."),
    "sanding_belts": (350, "Sanding Belts — abrasive belts designed for use with belt sanders."),
    "scissor_lift": (150000, "Scissor Lift — a platform machine used to lift workers and materials to height."),
    "seed_drill": (55000, "Seed Drill — an agricultural machine used to plant seeds at controlled depth and spacing."),
    "servo_drive": (9500, "Servo Drive — a device used to control servo motors in automation systems."),
    "servo_motor": (12500, "Servo Motor — a precision motor used in automation and robotics."),
    "shrink_wrapping_machine": (35000, "Shrink Wrapping Machine — an industrial machine used to wrap products in shrink film."),
    "soft_starter": (5500, "Soft Starter — an electrical device used to gradually start an electric motor."),
    "solenoid_valve": (700, "Solenoid Valve — an electrically controlled valve used to regulate fluid flow."),
    "spot_welding_machine": (25000, "Spot Welding Machine — a machine used to join metal sheets using localized heat."),
    "sprayer": (2500, "Sprayer — a machine used to spray liquids for agricultural or industrial use."),
    "stacker": (150000, "Stacker — a machine used to lift and stack palletized loads."),
    "steam_cleaner": (5500, "Steam Cleaner — a device that uses steam to clean and sanitize surfaces."),
    "stepper_motor": (2500, "Stepper Motor — a precision motor used in automation systems for controlled movement."),
    "storage_bin": (450, "Storage Bin — a container designed for general storage."),
    "storage_cabinet": (5500, "Storage Cabinet — a cabinet designed for industrial storage."),
    "strapping_machine": (25000, "Strapping Machine — an industrial machine used to secure packages with strapping."),
    "submersible_pump": (7500, "Submersible Pump — a pump designed to operate while fully submerged in fluid."),
    "sweeper_machine": (55000, "Sweeper Machine — a machine used to clean large floor and outdoor areas."),
    "thickness_gauge": (2500, "Thickness Gauge — a device used to measure material thickness."),
    "thresher": (85000, "Thresher — an agricultural machine used to separate grain from stalks."),
    "tig_welding_machine": (18000, "TIG Welding Machine — a machine used for tungsten inert gas welding."),
    "timer_relay": (450, "Timer Relay — an electrical device used to control timed operations in circuits."),
    "tool_cabinet": (5500, "Tool Cabinet — a cabinet designed for organizing and storing tools."),
    "torque_wrench": (1800, "Torque Wrench — a wrench designed to apply a precise amount of torque."),
    "tractor": (850000, "Tractor — a heavy agricultural vehicle used for farming operations."),
    "transformer": (25000, "Transformer — an electrical device used to change voltage levels in a power system."),
    "vacuum_packaging_machine": (25000, "Vacuum Packaging Machine — an industrial machine used to vacuum-seal products."),
    "vacuum_pump": (9500, "Vacuum Pump — a pump used to remove air or gas from a sealed space."),
    "variable_frequency_drive": (12500, "Variable Frequency Drive — a device used to control motor speed by varying frequency."),
    "vegetable_cutter": (5500, "Vegetable Cutter — a commercial machine used to cut and prepare vegetables."),
    "vibration_meter": (5500, "Vibration Meter — a device used to measure mechanical vibration levels."),
    "voltage_stabilizer": (3500, "Voltage Stabilizer — a device used to regulate voltage supply to equipment."),
    "warehouse_trolley": (3500, "Warehouse Trolley — a wheeled cart designed for transporting goods in a warehouse."),
    "water_bath": (5500, "Water Bath — a laboratory device used to maintain a consistent water temperature."),
    "water_jet_cutting_machine": (350000, "Water Jet Cutting Machine — an industrial machine that uses high-pressure water to cut materials."),
    "water_pump": (5500, "Water Pump — a pump used to move water through a system."),
    "welding_clamp": (700, "Welding Clamp — a clamp used to hold materials in place during welding."),
    "welding_gloves": (450, "Welding Gloves — protective gloves designed for welding work."),
    "welding_goggles": (450, "Welding Goggles — protective eyewear designed to shield the eyes during welding."),
    "welding_helmet": (2500, "Welding Helmet — protective headgear designed to shield the face during welding."),
    "welding_rods": (450, "Welding Rods — filler metal rods used in welding processes."),
    "welding_wire": (700, "Welding Wire — a continuous wire electrode used in welding processes."),
    "winch": (9500, "Winch — a mechanical device used to pull or lift heavy loads."),
    "workbench": (5500, "Workbench — a sturdy table designed for workshop tasks."),
}

paths = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch2.json",
]

total_updated = 0
total_skipped = []
for path in paths:
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        continue

    updated = 0
    for sku, prod in data.items():
        if prod.get("categoryId") == "industrial_machinery_equipment":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
            else:
                total_skipped.append((path, sku, img))

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"{path}: Updated {updated}")
    total_updated += updated

print(f"Total Updated: {total_updated}")
print(f"Skipped: {total_skipped}")
