import json

price_desc = {
    "safety_security": (500, "Safety & Security — a general range of products for protection and monitoring."),
    "shield_cctv_camera_padlock": (700, "Shield, CCTV Camera & Padlock Set — a bundled set of basic security essentials."),
    "cctv_surveillance": (2500, "CCTV Surveillance — a general range of camera-based monitoring equipment."),
    "cctv_camera": (2500, "CCTV Camera — a surveillance camera used for monitoring premises."),
    "ip_camera": (3500, "IP Camera — a network-connected camera used for remote surveillance."),
    "wifi_security_camera": (3000, "WiFi Security Camera — a wireless camera used for home and office surveillance."),
    "ptz_camera": (8500, "PTZ Camera — a pan-tilt-zoom camera used for wide-area surveillance."),
    "dome_camera": (2500, "Dome Camera — a dome-shaped surveillance camera for indoor or outdoor use."),
    "bullet_camera": (2500, "Bullet Camera — a cylindrical surveillance camera commonly used outdoors."),
    "indoor_security_camera": (2500, "Indoor Security Camera — a camera designed for monitoring indoor spaces."),
    "outdoor_security_camera": (3500, "Outdoor Security Camera — a weatherproof camera designed for outdoor monitoring."),
    "doorbell_camera": (4500, "Doorbell Camera — a smart doorbell equipped with video monitoring."),
    "baby_monitor_camera": (3500, "Baby Monitor Camera — a camera used for remotely monitoring a baby."),
    "hidden_camera": (2500, "Hidden Camera — a covert camera designed for discreet surveillance."),
    "nvr": (8500, "NVR — a network video recorder used for storing IP camera footage."),
    "dvr": (7500, "DVR — a digital video recorder used for storing analog camera footage."),
    "cctv_monitor": (5500, "CCTV Monitor — a display screen used for viewing surveillance footage."),
    "cctv_camera_kit": (12000, "CCTV Camera Kit — a complete surveillance system including cameras and recorder."),
    "surveillance_hard_drive": (4500, "Surveillance Hard Drive — a storage drive designed for continuous CCTV recording."),
    "smart_home_security": (2500, "Smart Home Security — a general range of connected devices for home protection."),
    "smart_door_lock": (7500, "Smart Door Lock — a Wi-Fi enabled lock offering keyless entry and remote control."),
    "fingerprint_door_lock": (8500, "Fingerprint Door Lock — a lock using fingerprint recognition for secure entry."),
    "smart_doorbell": (4500, "Smart Doorbell — a Wi-Fi enabled doorbell with video and app connectivity."),
    "video_doorbell": (4000, "Video Doorbell — a doorbell equipped with a built-in camera."),
    "smart_alarm_system": (8500, "Smart Alarm System — a connected system designed to detect intrusions."),
    "motion_sensor": (900, "Motion Sensor — a device used to detect movement within a monitored area."),
    "door_sensor": (700, "Door Sensor — a sensor used to detect when a door is opened."),
    "window_sensor": (700, "Window Sensor — a sensor used to detect when a window is opened."),
    "glass_break_sensor": (1200, "Glass Break Sensor — a sensor designed to detect the sound of breaking glass."),
    "smart_security_hub": (5500, "Smart Security Hub — a central device used to connect and manage smart security devices."),
    "smart_siren": (1800, "Smart Siren — a connected siren used to alert during a security breach."),
    "panic_button": (900, "Panic Button — a device used to trigger an emergency alert instantly."),
    "fire_safety": (900, "Fire Safety — a general range of products for fire prevention and protection."),
    "fire_extinguisher": (1800, "Fire Extinguisher — a portable device used for putting out small fires."),
    "fire_blanket": (900, "Fire Blanket — a fire-resistant blanket used to smother small fires."),
    "smoke_detector": (900, "Smoke Detector — a device used to detect smoke and alert of potential fire."),
    "heat_detector": (900, "Heat Detector — a device used to detect abnormal heat and alert of fire risk."),
    "carbon_monoxide_detector": (1500, "Carbon Monoxide Detector — a device used to detect dangerous carbon monoxide levels."),
    "fire_alarm_bell": (1200, "Fire Alarm Bell — a loud bell used to alert occupants during a fire emergency."),
    "fire_alarm_panel": (8500, "Fire Alarm Panel — a control panel used to manage a building's fire alarm system."),
    "emergency_exit_light": (1200, "Emergency Exit Light — a lighted sign used to guide occupants to safety exits."),
    "fire_hose_reel": (5500, "Fire Hose Reel — a mounted reel used for deploying a fire hose quickly."),
    "fire_sprinkler": (2500, "Fire Sprinkler — a fixed device used to automatically suppress fires."),
    "personal_safety": (500, "Personal Safety — a general range of protective gear for individual use."),
    "safety_helmet": (900, "Safety Helmet — a protective helmet used to prevent head injuries."),
    "hard_hat": (900, "Hard Hat — a rigid helmet used for protection on construction sites."),
    "safety_glasses": (350, "Safety Glasses — protective eyewear used to shield eyes from hazards."),
    "protective_goggles": (450, "Protective Goggles — sealed eyewear used for full eye protection."),
    "face_shield": (500, "Face Shield — a protective shield used to cover the face from hazards."),
    "ear_protection": (400, "Ear Protection — protective gear used to reduce noise exposure."),
    "respirator_mask": (700, "Respirator Mask — a mask designed to filter airborne particles and fumes."),
    "dust_mask": (150, "Dust Mask — a basic mask used to filter dust particles."),
    "work_gloves": (350, "Work Gloves — protective gloves used for general labor tasks."),
    "cut_resistant_gloves": (700, "Cut-Resistant Gloves — gloves designed to protect hands from sharp objects."),
    "safety_boots": (2500, "Safety Boots — protective footwear designed for workplace hazards."),
    "high_visibility_vest": (500, "High-Visibility Vest — a reflective vest used to increase worker visibility."),
    "knee_pads": (500, "Knee Pads — protective padding used to cushion the knees during work."),
    "elbow_pads": (500, "Elbow Pads — protective padding used to cushion the elbows during work."),
    "workplace_safety": (500, "Workplace Safety — a general range of products for hazard prevention at work."),
    "safety_cone": (400, "Safety Cone — a cone used to mark hazards or restrict access."),
    "barrier_tape": (200, "Barrier Tape — tape used to cordon off hazardous or restricted areas."),
    "warning_sign": (350, "Warning Sign — a sign used to alert individuals of potential hazards."),
    "safety_barrier": (2500, "Safety Barrier — a physical barrier used to control access and protect areas."),
    "floor_safety_sign": (350, "Floor Safety Sign — a sign placed on the floor to alert of hazards like wet surfaces."),
    "traffic_mirror": (2500, "Traffic Mirror — a convex mirror used to improve visibility at blind corners."),
    "speed_bump": (3500, "Speed Bump — a raised strip used to slow vehicle traffic."),
    "wheel_stopper": (700, "Wheel Stopper — a device used to prevent vehicles from rolling past a parking spot."),
    "chain_barrier": (1500, "Chain Barrier — a chain-based barrier used to restrict vehicle or foot access."),
    "access_control": (2500, "Access Control — a general range of systems for regulating entry to secured areas."),
    "rfid_card_reader": (3500, "RFID Card Reader — a device used to read RFID cards for access control."),
    "biometric_fingerprint_scanner": (5500, "Biometric Fingerprint Scanner — a device used for fingerprint-based access control."),
    "face_recognition_terminal": (8500, "Face Recognition Terminal — a device used for facial recognition-based access control."),
    "access_control_panel": (5500, "Access Control Panel — a central unit used to manage building access systems."),
    "rfid_cards": (100, "RFID Cards — cards used for access control via RFID technology."),
    "key_fobs": (250, "Key Fobs — small devices used for access control via proximity technology."),
    "exit_button": (350, "Exit Button — a button used to release a locked door from inside."),
    "electric_door_strike": (1800, "Electric Door Strike — an electronic locking mechanism used in access control systems."),
    "magnetic_door_lock": (2500, "Magnetic Door Lock — an electromagnetic lock used in access control systems."),
    "emergency_equipment": (700, "Emergency Equipment — a general range of tools for use during emergencies."),
    "emergency_light": (900, "Emergency Light — a backup light used during power outages or emergencies."),
    "rechargeable_emergency_light": (1200, "Rechargeable Emergency Light — a battery-powered light used during power outages."),
    "emergency_flashlight": (500, "Emergency Flashlight — a portable flashlight used during emergencies."),
    "led_torch": (400, "LED Torch — a handheld flashlight using LED bulbs for illumination."),
    "headlamp": (500, "Headlamp — a hands-free light worn on the head for illumination."),
    "first_aid_kit": (900, "First Aid Kit — a kit containing essential supplies for treating minor injuries."),
    "emergency_radio": (2200, "Emergency Radio — a radio used for receiving emergency broadcasts."),
    "emergency_blanket": (250, "Emergency Blanket — a lightweight thermal blanket used in emergency situations."),
    "safety_whistle": (150, "Safety Whistle — a whistle used to signal for help in an emergency."),
    "escape_ladder": (3500, "Escape Ladder — a portable ladder used for emergency evacuation from upper floors."),
    "home_security": (900, "Home Security — a general range of products designed for home protection."),
    "door_lock": (900, "Door Lock — a standard lock used for securing doors."),
    "deadbolt_lock": (1200, "Deadbolt Lock — a strong lock designed for enhanced door security."),
    "padlock": (350, "Padlock — a portable lock used for securing gates and containers."),
    "smart_padlock": (2500, "Smart Padlock — a padlock with app-based or keyless unlocking features."),
    "window_lock": (400, "Window Lock — a lock designed to secure windows from unauthorized opening."),
    "door_chain": (400, "Door Chain — a chain lock used to partially secure a door while allowing viewing."),
    "door_stop_alarm": (700, "Door Stop Alarm — an alarm-equipped door wedge that alerts of forced entry."),
    "peephole_viewer": (500, "Peephole Viewer — a small lens installed in a door for viewing visitors."),
    "security_safe": (5500, "Security Safe — a locked container designed for protecting valuables."),
    "key_safe_box": (1500, "Key Safe Box — a small locked box designed for securely storing keys."),
    "industrial_safety": (900, "Industrial Safety — a general range of products for occupational hazard protection."),
    "lockout_tagout_kit": (2500, "Lockout/Tagout Kit — a kit used to safely isolate hazardous energy sources."),
    "safety_harness": (2500, "Safety Harness — a harness used to protect workers from falls at height."),
    "fall_protection_lanyard": (1500, "Fall Protection Lanyard — a safety line used with a harness to arrest falls."),
    "lifeline_rope": (2500, "Lifeline Rope — a rope system used for fall protection at height."),
    "gas_detector": (3500, "Gas Detector — a device used to detect hazardous gases in the air."),
    "voltage_detector": (700, "Voltage Detector — a tool used to detect the presence of electrical voltage."),
    "arc_flash_suit": (8500, "Arc Flash Suit — a protective suit designed for electrical hazard protection."),
    "welding_helmet": (2500, "Welding Helmet — a protective helmet designed for welding tasks."),
    "vehicle_safety": (900, "Vehicle Safety — a general range of products for road and vehicle protection."),
    "dash_camera": (2500, "Dash Camera — a camera mounted in a vehicle to record driving footage."),
    "tire_pressure_gauge": (350, "Tire Pressure Gauge — a tool used to measure vehicle tire pressure."),
    "emergency_car_kit": (2500, "Emergency Car Kit — a kit containing essential tools for roadside emergencies."),
    "reflective_triangle": (500, "Reflective Triangle — a warning device placed near a stopped vehicle."),
    "jump_starter": (3500, "Jump Starter — a portable device used to start a vehicle with a dead battery."),
    "fire_extinguisher_for_car": (1200, "Fire Extinguisher for Car — a compact extinguisher designed for vehicle use."),
    "seat_belt_cutter": (300, "Seat Belt Cutter — a tool used to quickly cut a seat belt in an emergency."),
    "window_breaker_tool": (350, "Window Breaker Tool — a tool used to break a car window during an emergency."),
    "communication_alerts": (700, "Communication & Alerts — a general range of devices for emergency communication."),
    "walkie_talkie": (2500, "Walkie Talkie — a handheld two-way radio used for direct communication."),
    "two_way_radio": (2500, "Two-Way Radio — a radio device used for direct voice communication."),
    "megaphone": (2200, "Megaphone — a handheld device used to amplify voice for public address."),
    "public_address_speaker": (3500, "Public Address Speaker — a speaker system used for announcements over a wide area."),
    "emergency_siren": (2500, "Emergency Siren — a loud alarm device used to signal an emergency."),
    "alarm_bell": (900, "Alarm Bell — a bell used to signal alerts or emergencies."),
    "security_storage": (900, "Security Storage — a general range of products for securely storing valuables."),
    "digital_safe": (5500, "Digital Safe — a safe secured with a digital keypad lock."),
    "fireproof_safe": (7500, "Fireproof Safe — a safe designed to protect contents from fire damage."),
    "cash_box": (1500, "Cash Box — a lockable box designed for storing cash securely."),
    "key_cabinet": (2200, "Key Cabinet — a lockable cabinet designed for organizing and securing keys."),
    "lock_box": (1200, "Lock Box — a small secure box used for storing valuables or keys."),
    "document_safe": (3500, "Document Safe — a safe designed to protect important documents."),
    "lighting_visibility": (900, "Lighting & Visibility — a general range of products for improving visibility and security."),
    "security_flood_light": (1800, "Security Flood Light — a bright light designed to illuminate large outdoor areas."),
    "motion_sensor_light": (900, "Motion Sensor Light — a light that activates automatically upon detecting movement."),
    "solar_security_light": (1200, "Solar Security Light — a solar-powered light designed for outdoor security."),
    "searchlight": (2500, "Searchlight — a powerful handheld light used for long-range illumination."),
    "work_light": (900, "Work Light — a portable light designed for illuminating work areas."),
    "cyber_digital_security": (900, "Cyber & Digital Security — a general range of products for digital data protection."),
    "usb_security_key": (2500, "USB Security Key — a hardware device used for secure two-factor authentication."),
    "hardware_encryption_drive": (5500, "Hardware Encryption Drive — a storage drive with built-in data encryption."),
    "rfid_blocking_wallet": (700, "RFID-Blocking Wallet — a wallet designed to prevent unauthorized RFID scanning."),
    "webcam_cover": (150, "Webcam Cover — a sliding cover used to block a webcam lens for privacy."),
    "privacy_screen_filter": (900, "Privacy Screen Filter — a filter used to limit side-angle screen visibility."),
    "inspection_detection": (900, "Inspection & Detection — a general range of tools for detecting hidden hazards."),
    "metal_detector": (3500, "Metal Detector — a device used to detect metal objects."),
    "stud_finder": (900, "Stud Finder — a tool used to locate studs behind walls."),
    "inspection_camera": (2500, "Inspection Camera — a camera used for viewing hard-to-reach or hidden spaces."),
    "thermal_camera": (8500, "Thermal Camera — a camera used to detect heat signatures and temperature variance."),
    "leak_detector": (1500, "Leak Detector — a device used to detect gas or liquid leaks."),
    "water_leak_sensor": (900, "Water Leak Sensor — a sensor used to detect the presence of water leaks."),
    "security_accessories": (500, "Security Accessories — a general range of components for security system installation."),
    "cctv_cable": (350, "CCTV Cable — a cable used for connecting surveillance cameras."),
    "bnc_connector": (50, "BNC Connector — a connector used for CCTV cable installations."),
    "power_supply_adapter": (350, "Power Supply Adapter — an adapter used to power security devices."),
    "camera_mount_bracket": (350, "Camera Mount Bracket — a bracket used to mount surveillance cameras."),
    "cable_clips": (100, "Cable Clips — clips used to organize and secure cables during installation."),
    "network_switch_poe": (3500, "Network Switch PoE — a network switch that provides power over ethernet to devices."),
    "ups_for_cctv": (3500, "UPS for CCTV — a backup power supply designed for surveillance systems."),
    "safety_clothing": (700, "Safety Clothing — a general range of protective clothing for hazardous work."),
    "reflective_jacket": (700, "Reflective Jacket — a jacket with reflective strips for visibility."),
    "safety_raincoat": (700, "Safety Raincoat — a waterproof coat designed with high-visibility features."),
    "disposable_coverall": (350, "Disposable Coverall — a single-use protective suit for hazardous environments."),
    "chemical_resistant_suit": (2500, "Chemical Resistant Suit — a suit designed to protect against hazardous chemicals."),
    "protective_apron": (500, "Protective Apron — an apron designed to shield the body from hazards."),
    "child_elderly_safety": (700, "Child & Elderly Safety — a general range of products for vulnerable individuals' safety."),
    "baby_safety_gate": (2200, "Baby Safety Gate — a gate used to restrict a child's access to hazardous areas."),
    "cabinet_safety_lock": (300, "Cabinet Safety Lock — a lock used to prevent children from opening cabinets."),
    "corner_protectors": (200, "Corner Protectors — cushioned guards used to soften sharp furniture corners."),
    "bed_rail": (1800, "Bed Rail — a guard rail used to prevent falls from a bed."),
    "gps_tracker": (2500, "GPS Tracker — a wearable or portable device used for location tracking."),
    "personal_emergency_alarm": (900, "Personal Emergency Alarm — a portable alarm used to signal for help in an emergency."),
    "marine_outdoor_safety": (900, "Marine & Outdoor Safety — a general range of products for water and outdoor safety."),
    "life_jacket": (1800, "Life Jacket — a flotation vest designed for water safety."),
    "lifebuoy": (1500, "Lifebuoy — a floating ring designed to assist rescue in water emergencies."),
    "waterproof_emergency_light": (900, "Waterproof Emergency Light — a sealed light designed for use in wet conditions."),
    "survival_kit": (2500, "Survival Kit — a kit containing essential tools for outdoor emergencies."),
    "compass": (350, "Compass — a navigational tool used to determine direction."),
    "waterproof_dry_bag": (900, "Waterproof Dry Bag — a sealed bag designed to keep contents dry."),
    "safety_signs": (350, "Safety Signs — a general range of signage used to communicate hazards and directions."),
    "exit_sign": (700, "Exit Sign — a lighted or reflective sign indicating an exit route."),
    "fire_exit_sign": (700, "Fire Exit Sign — a sign indicating the route to a fire exit."),
    "no_smoking_sign": (200, "No Smoking Sign — a sign indicating a smoke-free area."),
    "hazard_sign": (250, "Hazard Sign — a sign used to warn of potential dangers."),
    "direction_sign": (250, "Direction Sign — a sign used to guide movement within a facility."),
    "glow_in_the_dark_safety_sticker": (150, "Glow-in-the-Dark Safety Sticker — a luminescent sticker used for low-light visibility."),
}

files_map = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch3.json",
]

updated = 0
skipped = []

for path in files_map:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    changed = False
    for sku, prod in data.items():
        if prod.get("categoryId") == "safety_security":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
                changed = True
            else:
                skipped.append((path, sku, img))
    if changed:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
