import json

price_desc = {
    "lighting_lamps": (500, "Lighting & Lamps — a general range of lighting and lamp products."),
    "table_lamp_pendant_light": (900, "Table Lamp & Pendant Light Set — a bundled set of lighting fixtures."),
    "indoor_lighting": (900, "Indoor Lighting — a general range of lighting products for indoor spaces."),
    "ceiling_light": (1500, "Ceiling Light — a light fixture mounted on the ceiling."),
    "led_ceiling_light": (1800, "LED Ceiling Light — an energy-efficient ceiling fixture using LED technology."),
    "flush_mount_light": (1800, "Flush Mount Light — a ceiling light installed close to the ceiling surface."),
    "semi_flush_mount_light": (1800, "Semi Flush Mount Light — a ceiling light installed with a small gap from the ceiling."),
    "pendant_light": (3500, "Pendant Light — a decorative hanging light fixture."),
    "chandelier": (12000, "Chandelier — a decorative hanging light fixture with multiple arms."),
    "recessed_light": (900, "Recessed Light — a light fixture installed flush into the ceiling."),
    "downlight": (900, "Downlight — a recessed light fixture installed into the ceiling."),
    "spot_light": (900, "Spot Light — a focused light fixture used to highlight specific areas."),
    "track_light": (1800, "Track Light — an adjustable light fixture mounted on a track system."),
    "wall_light": (1800, "Wall Light — a light fixture designed for wall mounting."),
    "wall_sconce": (1800, "Wall Sconce — a decorative light fixture mounted on a wall."),
    "picture_light": (1500, "Picture Light — a light fixture designed to illuminate artwork."),
    "cove_light": (900, "Cove Light — indirect lighting installed within architectural recesses."),
    "lamps": (1800, "Lamps — a general range of standalone lighting fixtures."),
    "table_lamp": (1800, "Table Lamp — a lamp designed for placement on tables and desks."),
    "desk_lamp": (1500, "Desk Lamp — a lamp designed for focused lighting at a desk."),
    "floor_lamp": (3500, "Floor Lamp — a tall standing lamp used for room lighting."),
    "reading_lamp": (900, "Reading Lamp — adjustable lamps designed for comfortable reading light."),
    "bedside_lamp": (1200, "Bedside Lamp — a lamp designed for placement on a nightstand."),
    "touch_lamp": (1800, "Touch Lamp — a lamp activated by touch rather than a switch."),
    "smart_lamp": (2500, "Smart Lamp — a connected lamp controllable via app or voice assistant."),
    "led_lamp": (900, "LED Lamp — an energy-efficient lamp using LED technology."),
    "clip_on_lamp": (900, "Clip-On Lamp — a lamp with a clamp designed to attach to surfaces."),
    "rechargeable_lamp": (1500, "Rechargeable Lamp — a battery-powered lamp designed for portable use."),
    "decorative_lamp": (1500, "Decorative Lamp — an ornamental lamp designed for ambient home decor."),
    "salt_lamp": (900, "Salt Lamp — a decorative lamp made from natural salt crystal."),
    "lava_lamp": (1200, "Lava Lamp — a decorative lamp featuring flowing colored wax."),
    "led_lighting": (900, "LED Lighting — a general range of energy-efficient LED light products."),
    "led_bulb": (250, "LED Bulb — an energy-efficient light bulb using LED technology."),
    "smart_led_bulb": (900, "Smart LED Bulb — a connected light bulb controllable via app or voice assistant."),
    "led_tube_light": (450, "LED Tube Light — an energy-efficient tube light using LED technology."),
    "led_strip_light": (900, "LED Strip Light — a flexible LED lighting strip used for accent lighting."),
    "rgb_led_strip": (1200, "RGB LED Strip — a color-changing LED lighting strip for accent lighting."),
    "led_panel_light": (1500, "LED Panel Light — a flat LED fixture used for even ceiling illumination."),
    "led_flood_light": (1800, "LED Flood Light — a bright outdoor light used for illuminating large areas."),
    "led_high_bay_light": (5500, "LED High Bay Light — an industrial LED fixture designed for high-ceiling spaces."),
    "led_corn_bulb": (900, "LED Corn Bulb — a high-output LED bulb designed for industrial fixtures."),
    "led_module": (450, "LED Module — a compact LED unit used within larger lighting fixtures."),
    "outdoor_lighting": (1800, "Outdoor Lighting — a general range of lighting products for outdoor spaces."),
    "garden_light": (900, "Garden Light — an outdoor light fixture designed for garden illumination."),
    "pathway_light": (900, "Pathway Light — an outdoor light used to illuminate walkways."),
    "landscape_light": (1200, "Landscape Light — an outdoor light used to accent garden landscaping."),
    "wall_lantern": (1500, "Wall Lantern — a decorative outdoor light fixture mounted on a wall."),
    "street_light": (5500, "Street Light — an outdoor light fixture designed for road and pathway illumination."),
    "flood_light": (1800, "Flood Light — a powerful light fixture used to illuminate large outdoor areas."),
    "solar_garden_light": (900, "Solar Garden Light — an outdoor light powered by solar energy."),
    "solar_wall_light": (900, "Solar Wall Light — a wall-mounted outdoor light powered by solar energy."),
    "motion_sensor_light": (1800, "Motion Sensor Light — an outdoor light that activates based on detected movement."),
    "security_light": (1800, "Security Light — an outdoor light designed to improve visibility for safety."),
    "post_light": (2500, "Post Light — a light fixture mounted on a standing post for outdoor use."),
    "deck_light": (900, "Deck Light — a small light fixture designed for outdoor deck installation."),
    "solar_lighting": (900, "Solar Lighting — a general range of solar-powered lighting products."),
    "solar_street_light": (12000, "Solar Street Light — a solar-powered light fixture designed for road illumination."),
    "solar_flood_light": (1800, "Solar Flood Light — a solar-powered light used to illuminate large outdoor areas."),
    "solar_lantern": (900, "Solar Lantern — a portable outdoor lantern powered by solar energy."),
    "solar_path_light": (700, "Solar Path Light — a solar-powered light used to illuminate walkways."),
    "solar_string_light": (700, "Solar String Light — solar-powered decorative string lights."),
    "solar_spot_light": (900, "Solar Spot Light — a solar-powered focused light used to highlight outdoor features."),
    "solar_camping_light": (900, "Solar Camping Light — a portable solar-powered light designed for camping."),
    "smart_lighting": (2500, "Smart Lighting — a general range of connected lighting products."),
    "smart_bulb": (900, "Smart Bulb — a connected light bulb controllable via app or voice assistant."),
    "smart_light_strip": (1800, "Smart Light Strip — a connected LED strip controllable via app or voice assistant."),
    "smart_ceiling_light": (2500, "Smart Ceiling Light — a connected ceiling fixture controllable via app or voice assistant."),
    "smart_switch": (900, "Smart Switch — a connected light switch controllable via app or voice assistant."),
    "smart_dimmer": (1500, "Smart Dimmer — a connected dimmer switch controllable via app or voice assistant."),
    "wifi_light_controller": (900, "Wi-Fi Light Controller — a device used to control lighting via Wi-Fi connectivity."),
    "zigbee_light_controller": (900, "Zigbee Light Controller — a device used to control lighting via Zigbee protocol."),
    "decorative_lighting": (900, "Decorative Lighting — a general range of ambient and decorative light products."),
    "fairy_lights": (450, "Fairy Lights — small decorative string lights used for ambient decor."),
    "string_lights": (700, "String Lights — decorative lights used for ambient home decor."),
    "curtain_lights": (900, "Curtain Lights — decorative hanging lights used to create a curtain-like display."),
    "neon_sign": (2500, "Neon Sign — a decorative illuminated sign used for display."),
    "led_neon_light": (1800, "LED Neon Light — a flexible LED strip designed to mimic neon lighting."),
    "decorative_lantern": (900, "Decorative Lantern — an ornamental lantern used for ambient lighting."),
    "candle_lamp": (900, "Candle Lamp — a decorative lamp designed to resemble a candle flame."),
    "festive_lights": (900, "Festive Lights — decorative string lights used for holiday and celebration decor."),
    "ramadan_lantern": (900, "Ramadan Lantern — a decorative lantern used for Ramadan celebrations."),
    "eid_decorative_lights": (900, "Eid Decorative Lights — decorative lighting used for Eid celebrations."),
    "christmas_lights": (900, "Christmas Lights — decorative string lights used for holiday decor."),
    "office_commercial_lighting": (1800, "Office & Commercial Lighting — a general range of lighting products for business use."),
    "office_panel_light": (1800, "Office Panel Light — a flat LED fixture designed for office ceiling installation."),
    "task_light": (1500, "Task Light — a focused light fixture designed for work areas."),
    "desk_light": (1500, "Desk Light — a lamp designed for focused lighting at a desk."),
    "high_bay_light": (5500, "High Bay Light — an industrial fixture designed for high-ceiling spaces."),
    "low_bay_light": (3500, "Low Bay Light — an industrial fixture designed for lower-ceiling spaces."),
    "warehouse_light": (5500, "Warehouse Light — an industrial fixture designed for large storage facilities."),
    "shop_display_light": (1800, "Shop Display Light — a light fixture designed for retail product display."),
    "emergency_exit_light": (1800, "Emergency Exit Light — a battery-backed sign used to indicate exit routes."),
    "industrial_lighting": (3500, "Industrial Lighting — a general range of heavy-duty lighting products."),
    "explosion_proof_light": (8500, "Explosion Proof Light — a rugged fixture designed for hazardous industrial environments."),
    "work_light": (1800, "Work Light — a portable light designed for job site illumination."),
    "portable_work_light": (1800, "Portable Work Light — a movable light designed for job site illumination."),
    "machine_light": (900, "Machine Light — a light fixture designed for mounting on industrial machinery."),
    "construction_light": (2500, "Construction Light — a rugged light fixture designed for construction sites."),
    "inspection_lamp": (900, "Inspection Lamp — a handheld light used for detailed inspection work."),
    "emergency_lighting": (1800, "Emergency Lighting — a general range of battery-backed safety lighting products."),
    "emergency_light": (1800, "Emergency Light — a battery-backed light used during power outages."),
    "rechargeable_emergency_light": (1800, "Rechargeable Emergency Light — a battery-powered light designed for outages."),
    "exit_sign_light": (1800, "Exit Sign Light — a battery-backed sign used to indicate exit routes."),
    "emergency_torch": (900, "Emergency Torch — a portable light used during power outages."),
    "led_emergency_bulb": (900, "LED Emergency Bulb — a battery-backed bulb that continues to work during outages."),
    "flashlights_portable_lighting": (900, "Flashlights & Portable Lighting — a general range of handheld light products."),
    "flashlight": (700, "Flashlight — a portable handheld light source."),
    "tactical_flashlight": (1500, "Tactical Flashlight — a durable, high-powered flashlight designed for demanding use."),
    "rechargeable_flashlight": (1200, "Rechargeable Flashlight — a battery-powered flashlight designed for repeated use."),
    "camping_lantern": (1500, "Camping Lantern — a portable light source designed for outdoor camping."),
    "headlamp": (900, "Headlamp — a wearable light source designed for hands-free illumination."),
    "keychain_flashlight": (250, "Keychain Flashlight — a compact light designed to attach to a keychain."),
    "work_torch": (900, "Work Torch — a portable handheld light designed for job site use."),
    "bulbs": (250, "Bulbs — a general range of light bulb products."),
    "incandescent_bulb": (150, "Incandescent Bulb — a traditional light bulb using a heated filament."),
    "halogen_bulb": (250, "Halogen Bulb — a bright, energy-efficient bulb using halogen gas technology."),
    "cfl_bulb": (250, "CFL Bulb — a compact fluorescent bulb known for energy efficiency."),
    "filament_bulb": (350, "Filament Bulb — a decorative bulb featuring a visible glowing filament."),
    "vintage_edison_bulb": (450, "Vintage Edison Bulb — a decorative bulb designed with a classic retro appearance."),
    "tube_light": (450, "Tube Light — a linear light fixture commonly used for general illumination."),
    "lighting_accessories": (450, "Lighting Accessories — a general range of parts and accessories for lighting fixtures."),
    "lamp_shade": (900, "Lamp Shade — a decorative cover used to diffuse light from a lamp."),
    "lamp_base": (900, "Lamp Base — the structural support component of a lamp."),
    "lamp_holder": (100, "Lamp Holder — a fixture used to hold and connect a light bulb."),
    "bulb_holder": (50, "Bulb Holder — a socket fixture used to hold a light bulb."),
    "ceiling_rose": (350, "Ceiling Rose — a decorative fixture used to cover ceiling wiring at a light fitting."),
    "light_socket": (100, "Light Socket — a fixture used to connect and power a light bulb."),
    "extension_cord": (700, "Extension Cord — a cord used to extend the reach of an electrical outlet."),
    "dimmer_switch": (900, "Dimmer Switch — a switch used to adjust the brightness of lighting."),
    "motion_sensor": (900, "Motion Sensor — a device used to detect movement for lighting or security."),
    "remote_control": (700, "Remote Control — a handheld device used to operate lighting fixtures."),
    "smart_lighting_hub": (3500, "Smart Lighting Hub — a central device used to connect and control smart lighting."),
    "electrical_lighting_components": (450, "Electrical Lighting Components — a general range of parts used in lighting systems."),
    "led_driver": (700, "LED Driver — a device used to regulate power supplied to LED lighting."),
    "ballast": (700, "Ballast — a device used to regulate current for fluorescent lighting."),
    "starter": (450, "Starter — a device used to initiate current flow for fluorescent lighting."),
    "transformer": (65000, "Transformer — an electrical device used to change voltage levels in a lighting system."),
    "junction_box": (150, "Junction Box — an enclosure used to safely house electrical wire connections."),
    "wire_connector": (50, "Wire Connector — a component used to join electrical wires securely."),
    "cable_clips": (50, "Cable Clips — fasteners used to secure and organize lighting cables."),
    "electrical_wire": (450, "Electrical Wire — conductive wiring used in lighting installations."),
    "stage_studio_lighting": (5500, "Stage & Studio Lighting — a general range of professional lighting equipment."),
    "ring_light": (2500, "Ring Light — a circular light source used for even, shadow-free illumination."),
    "softbox_light": (3500, "Softbox Light — a lighting accessory used to diffuse and soften studio light."),
    "led_video_light": (3500, "LED Video Light — a lighting panel used to illuminate video shoots."),
    "studio_flash": (8500, "Studio Flash — a powerful flash unit used for professional photography lighting."),
    "par_light": (3500, "PAR Light — a fixture used for stage and event lighting effects."),
    "moving_head_light": (25000, "Moving Head Light — a motorized stage light capable of directional movement."),
    "dmx_controller": (5500, "DMX Controller — a device used to control stage lighting via the DMX protocol."),
    "light_stand": (1800, "Light Stand — an adjustable stand used to position photography and video lights."),
    "aquarium_specialty_lighting": (1800, "Aquarium & Specialty Lighting — a general range of specialized lighting products."),
    "aquarium_led_light": (2500, "Aquarium LED Light — an LED fixture designed for illuminating fish tanks."),
    "plant_grow_light": (2500, "Plant Grow Light — a specialized light used to support indoor plant growth."),
    "uv_lamp": (900, "UV Lamp — a light fixture emitting ultraviolet light for various applications."),
    "infrared_lamp": (900, "Infrared Lamp — a light fixture used to provide radiant heat."),
    "heat_lamp": (900, "Heat Lamp — a light fixture used to provide warmth in a targeted area."),
    "germicidal_uv_light": (2500, "Germicidal UV Light — a UV fixture used for disinfection purposes."),
    "ceiling_fans_with_lights": (5500, "Ceiling Fans with Lights — a general range of ceiling fans featuring integrated lighting."),
    "ceiling_fan_with_led_light": (5500, "Ceiling Fan with LED Light — a ceiling fan featuring an integrated LED light fixture."),
    "smart_ceiling_fan": (8500, "Smart Ceiling Fan — a connected ceiling fan controllable via app or voice assistant."),
    "decorative_ceiling_fan": (6500, "Decorative Ceiling Fan — a stylish ceiling fan designed for aesthetic appeal."),
    "lighting_maintenance": (450, "Lighting Maintenance — a general range of products used for lighting upkeep."),
    "light_cleaning_kit": (450, "Light Cleaning Kit — a set of tools used to clean lighting fixtures."),
    "replacement_led_module": (450, "Replacement LED Module — a spare LED unit used for fixture repair."),
    "replacement_lamp_shade": (900, "Replacement Lamp Shade — a spare shade used to replace a worn lamp cover."),
    "spare_bulbs": (250, "Spare Bulbs — replacement light bulbs kept on hand for maintenance."),
    "mounting_hardware": (350, "Mounting Hardware — fasteners and brackets used to install lighting fixtures."),
}

files_map = [
    "data/products-placeholder.json",
    "data/products-placeholder-batch3.json",
]

updated = 0
skipped = []

for path in files_map:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    changed = False
    for sku, prod in data.items():
        if prod.get("categoryId") == "lighting_lamps":
            img = prod["images"]["main"].split("/")[-1].replace(".png", "")
            if img in price_desc:
                price, desc = price_desc[img]
                title = " ".join(w.capitalize() for w in img.split("_"))
                prod["title"] = title
                prod["price"] = price
                prod["description"] = desc
                prod["status"] = "active"
                updated += 1
                changed = True
            else:
                skipped.append((sku, img))
    if changed:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
