import json

price_desc = {
    "activity_gym": (2200, "Activity Gym — a padded play mat with hanging toys to stimulate a baby's development."),
    "air_purifier_nursery": (4500, "Air Purifier for Nursery — a device that filters and cleans air in the baby's room."),
    "anti_lost_wrist_link": (450, "Anti-Lost Wrist Link — a safety strap that keeps young children close to a parent in public."),
    "baby_bathtub": (1200, "Baby Bathtub — a small tub designed for safely bathing infants."),
    "baby_bed_sheet": (500, "Baby Bed Sheet — a soft fitted sheet designed for a baby's crib or cot."),
    "baby_bib": (150, "Baby Bib — a fabric covering worn during feeding to protect clothing."),
    "baby_bib_apron": (200, "Baby Bib Apron — a full-coverage bib designed to protect clothing during messy feeding."),
    "baby_blanket": (700, "Baby Blanket — a soft blanket designed to keep an infant warm and comfortable."),
    "baby_body_wash": (350, "Baby Body Wash — a gentle cleanser formulated for delicate baby skin."),
    "baby_bodysuit": (350, "Baby Bodysuit — a one-piece garment designed for everyday infant wear."),
    "baby_books": (300, "Baby Books — early learning books designed to engage infants and toddlers."),
    "baby_bottle_nipples": (150, "Baby Bottle Nipples — replacement nipples designed for feeding bottles."),
    "baby_bottles": (350, "Baby Bottles — feeding bottles designed for infants."),
    "baby_bouncer": (3500, "Baby Bouncer — a gentle rocking seat that soothes and entertains infants."),
    "baby_brush": (150, "Baby Brush — a soft-bristled brush designed for an infant's delicate hair."),
    "baby_cap": (150, "Baby Cap — a soft cap designed to keep an infant's head warm."),
    "baby_car_seat": (5500, "Baby Car Seat — a safety seat designed to protect infants while traveling by car."),
    "baby_care_gift_box": (2200, "Baby Care Gift Box — a curated set of baby care essentials, ideal for gifting."),
    "baby_carrier": (2500, "Baby Carrier — a wearable sling used to carry an infant hands-free."),
    "baby_cereal": (350, "Baby Cereal — a fortified cereal formulated as an early solid food for infants."),
    "baby_clothing_set": (700, "Baby Clothing Set — a coordinated outfit set designed for infants."),
    "baby_cologne": (450, "Baby Cologne — a mild, alcohol-free fragrance formulated for babies."),
    "baby_comb": (100, "Baby Comb — a gentle comb designed for an infant's fine hair."),
    "baby_cot": (7500, "Baby Cot — a small bed designed for infants to sleep safely."),
    "baby_cream": (300, "Baby Cream — a moisturizing cream formulated for sensitive baby skin."),
    "baby_crib": (9500, "Baby Crib — a bed with high sides designed for infant sleep safety."),
    "baby_diapers": (850, "Baby Diapers — absorbent disposable diapers designed for infants."),
    "baby_dress": (450, "Baby Dress — a soft dress designed for infant girls."),
    "baby_feeding": (500, "Baby Feeding Set — a set of feeding essentials designed for infants."),
    "baby_first_aid_kit": (1200, "Baby First Aid Kit — a compact kit of essential care items for infant emergencies."),
    "baby_food": (250, "Baby Food — a jar or pouch of pureed food formulated for infants."),
    "baby_formula": (1200, "Baby Formula — a nutritional powder formulated as an infant milk substitute."),
    "baby_grooming_kit": (900, "Baby Grooming Kit — a complete set of grooming tools designed for infants."),
    "baby_hat": (200, "Baby Hat — a soft hat designed to protect an infant's head."),
    "baby_jacket": (700, "Baby Jacket — a warm outer garment designed for infants."),
    "baby_lotion": (300, "Baby Lotion — a gentle moisturizing lotion formulated for baby skin."),
    "baby_mattress": (3500, "Baby Mattress — a firm mattress designed for safe infant sleep."),
    "baby_mittens": (150, "Baby Mittens — soft hand coverings that prevent infants from scratching themselves."),
    "baby_monitor": (3500, "Baby Monitor — a device that lets parents remotely hear or see their sleeping baby."),
    "baby_nail_clipper": (150, "Baby Nail Clipper — a small, safe clipper designed for trimming an infant's nails."),
    "baby_oil": (250, "Baby Oil — a gentle moisturizing oil formulated for infant skin."),
    "baby_pants": (350, "Baby Pants — soft, comfortable pants designed for infants."),
    "baby_pillow": (400, "Baby Pillow — a small, supportive pillow designed for infant head shaping."),
    "baby_powder": (200, "Baby Powder — a talc or cornstarch-based powder used to keep baby skin dry."),
    "baby_pram": (6500, "Baby Pram — a wheeled carriage designed for transporting infants."),
    "baby_products_baby_essentials": (500, "Baby Products, Baby Essentials — a general range of baby care and essential items."),
    "baby_quilt": (700, "Baby Quilt — a padded quilt designed to keep an infant warm."),
    "baby_rattle": (250, "Baby Rattle — a small toy that makes noise to entertain infants."),
    "baby_romper": (400, "Baby Romper — a one-piece outfit designed for everyday infant wear."),
    "baby_safety_gate": (2500, "Baby Safety Gate — a barrier gate used to restrict a child's access to certain areas."),
    "baby_shampoo": (300, "Baby Shampoo — a tear-free shampoo formulated for infant hair and scalp."),
    "baby_shoes": (500, "Baby Shoes — soft-soled shoes designed for infants."),
    "baby_sling": (1500, "Baby Sling — a fabric wrap used to carry an infant close to the body."),
    "baby_snacks": (200, "Baby Snacks — soft, easy-to-eat snacks formulated for young children."),
    "baby_soap": (200, "Baby Soap — a mild soap formulated for gentle infant skin cleansing."),
    "baby_socks": (150, "Baby Socks — soft socks designed for infants."),
    "baby_stroller": (7500, "Baby Stroller — a wheeled carriage used to transport an infant or toddler."),
    "baby_stroller_baby_bottle_pacifier": (600, "Baby Stroller Accessory Set — a bundled set including a bottle and pacifier holder for strollers."),
    "baby_sunscreen": (400, "Baby Sunscreen — a gentle sunscreen formulated to protect sensitive baby skin."),
    "baby_sweater": (600, "Baby Sweater — a warm knitted garment designed for infants."),
    "baby_swing": (5500, "Baby Swing — a motorized or manual swing that soothes and entertains infants."),
    "baby_t_shirt": (300, "Baby T-Shirt — a soft, breathable t-shirt designed for infants."),
    "baby_towel": (450, "Baby Towel — a soft, absorbent towel designed for infants."),
    "baby_walker": (3500, "Baby Walker — a wheeled frame that supports a baby learning to walk."),
    "baby_wipes": (250, "Baby Wipes — gentle, pre-moistened wipes for cleaning an infant's skin."),
    "bassinet": (5500, "Bassinet — a small portable bed designed for newborn sleep."),
    "bath_gift_set": (1800, "Bath Gift Set — a curated set of baby bath products, ideal for gifting."),
    "bath_seat": (1500, "Bath Seat — a supportive seat that helps stabilize an infant during bath time."),
    "bath_sponge": (150, "Bath Sponge — a soft sponge designed for gently bathing infants."),
    "bath_thermometer": (450, "Bath Thermometer — a device used to check bathwater temperature for infant safety."),
    "bath_toys": (350, "Bath Toys — floating toys designed to entertain babies during bath time."),
    "bed_rail": (2200, "Bed Rail — a safety barrier that prevents a child from falling out of bed."),
    "booster_seat": (1800, "Booster Seat — a raised seat that helps a young child sit at the dining table."),
    "bottle_drying_rack": (700, "Bottle Drying Rack — a rack used to air-dry baby bottles and feeding accessories."),
    "bottle_sterilizer": (3500, "Bottle Sterilizer — a device that sterilizes baby bottles using steam or UV."),
    "bottle_warmer": (2200, "Bottle Warmer — a device used to warm baby bottles to a safe feeding temperature."),
    "breast_pump": (4500, "Breast Pump — a device used to express and collect breast milk."),
    "building_blocks": (700, "Building Blocks — stackable toy blocks that support early childhood development."),
    "cabinet_locks": (350, "Cabinet Locks — childproof locks that restrict access to cabinets and drawers."),
    "changing_table": (6500, "Changing Table — a dedicated surface designed for changing an infant's diaper."),
    "closet_organizer": (900, "Closet Organizer — a storage system used to organize baby clothing and items."),
    "cloth_diapers": (600, "Cloth Diapers — reusable fabric diapers designed for infants."),
    "corner_guards": (250, "Corner Guards — soft padding used to childproof sharp furniture corners."),
    "cotton_buds": (100, "Cotton Buds — soft cotton swabs used for gentle infant hygiene care."),
    "cradle": (6500, "Cradle — a small rocking bed designed for soothing infants to sleep."),
    "crib_mattress_protector": (500, "Crib Mattress Protector — a waterproof cover used to protect a crib mattress."),
    "crib_mobile": (1500, "Crib Mobile — a hanging toy set that spins above a crib to entertain infants."),
    "crib_organizer": (700, "Crib Organizer — a storage accessory that attaches to a crib for holding essentials."),
    "diaper_bag": (1800, "Diaper Bag — a bag designed to carry diapers and baby essentials while traveling."),
    "diaper_pants": (850, "Diaper Pants — pull-up style diapers designed for infants and toddlers."),
    "diaper_rash_cream": (300, "Diaper Rash Cream — a protective cream used to treat and prevent diaper rash."),
    "digital_baby_thermometer": (700, "Digital Baby Thermometer — an electronic thermometer designed for accurate infant temperature readings."),
    "door_stopper": (200, "Door Stopper — a childproofing device that prevents doors from slamming shut."),
    "ear_thermometer": (1500, "Ear Thermometer — a thermometer that measures body temperature via the ear canal."),
    "educational_toys": (900, "Educational Toys — toys designed to support learning and cognitive development."),
    "feeding_bowl": (300, "Feeding Bowl — a bowl designed for feeding infants and toddlers."),
    "feeding_gift_set": (1800, "Feeding Gift Set — a curated set of feeding essentials, ideal for gifting."),
    "feeding_spoon": (150, "Feeding Spoon — a soft-tipped spoon designed for feeding infants."),
    "high_chair": (5500, "High Chair — a raised chair used for feeding infants and toddlers at the table."),
    "humidifier": (3500, "Humidifier — a device that adds moisture to the air in a baby's room."),
    "keepsake_box": (900, "Keepsake Box — a decorative box used to store cherished baby mementos."),
    "kids_chair": (1200, "Kids Chair — a small chair sized for young children."),
    "kids_table": (2500, "Kids Table — a small table sized for young children's activities."),
    "laundry_bag": (400, "Laundry Bag — a bag used to separate and carry baby laundry."),
    "medicine_dispenser": (250, "Medicine Dispenser — a tool used to accurately measure and give liquid medicine to infants."),
    "milk_storage_bags": (400, "Milk Storage Bags — bags designed for safely storing expressed breast milk."),
    "mosquito_net": (700, "Mosquito Net — a protective net used to shield a baby's crib from insects."),
    "musical_toys": (900, "Musical Toys — toys that play sounds or melodies to entertain infants."),
    "nasal_aspirator": (450, "Nasal Aspirator — a device used to gently clear an infant's nasal congestion."),
    "newborn_gift_set": (2500, "Newborn Gift Set — a curated set of essentials designed for newborn babies."),
    "nursing_pillow": (1500, "Nursing Pillow — a supportive pillow designed to assist with breastfeeding."),
    "pacifier": (150, "Pacifier — a soothing device designed for infants to suck on."),
    "pacifier_case": (200, "Pacifier Case — a small case used to store and protect a pacifier."),
    "pacifier_clip": (150, "Pacifier Clip — a clip that attaches a pacifier to clothing to prevent loss."),
    "play_mat": (1800, "Play Mat — a padded mat designed as a safe surface for infant play."),
    "playpen": (5500, "Playpen — an enclosed play area designed to safely contain a young child."),
    "plush_toys": (500, "Plush Toys — soft stuffed toys designed for infants and toddlers."),
    "rinse_cup": (200, "Rinse Cup — a cup designed to help rinse an infant's hair during bath time."),
    "rocking_chair": (6500, "Rocking Chair — a gently rocking chair often used for soothing a baby."),
    "safety_harness": (700, "Safety Harness — a strap system used to secure a child in a seat or stroller."),
    "shape_sorter": (700, "Shape Sorter — an educational toy that helps toddlers learn shapes."),
    "sippy_cup": (350, "Sippy Cup — a spill-resistant training cup designed for toddlers."),
    "sleeping_bag": (1200, "Sleeping Bag — a wearable blanket designed to keep an infant warm while sleeping."),
    "socket_covers": (150, "Socket Covers — childproofing covers that block access to electrical outlets."),
    "soft_toys": (500, "Soft Toys — plush, cuddly toys designed for infants and toddlers."),
    "stacking_toys": (600, "Stacking Toys — toys designed for toddlers to stack and build."),
    "storage_basket": (700, "Storage Basket — a basket used to organize baby clothes and items."),
    "straw_cup": (350, "Straw Cup — a training cup fitted with a straw for toddlers."),
    "stroller_organizer": (700, "Stroller Organizer — a storage accessory that attaches to a stroller for essentials."),
    "stroller_rain_cover": (700, "Stroller Rain Cover — a protective cover that shields a stroller from rain."),
    "swaddle_blanket": (700, "Swaddle Blanket — a wrap blanket used to snugly swaddle newborns."),
    "teether": (250, "Teether — a chewable toy designed to soothe a teething infant's gums."),
    "teething_gel": (300, "Teething Gel — a topical gel used to relieve discomfort during teething."),
    "toy_gift_set": (1800, "Toy Gift Set — a curated set of toys, ideal for gifting."),
    "toy_organizer": (900, "Toy Organizer — a storage unit used to keep children's toys organized."),
    "toy_storage_box": (900, "Toy Storage Box — a box designed for storing children's toys."),
    "travel_stroller": (7500, "Travel Stroller — a compact, foldable stroller designed for travel convenience."),
    "vaporizer": (2500, "Vaporizer — a device that releases medicated vapor to relieve a baby's congestion."),
    "video_baby_monitor": (5500, "Video Baby Monitor — a monitor with camera and screen for remotely watching a sleeping baby."),
    "washcloth": (200, "Washcloth — a soft cloth designed for gently cleaning an infant."),
    "wet_bag": (400, "Wet Bag — a waterproof bag used to store soiled baby items while traveling."),
}

path = "data/products-placeholder.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
skipped = []
for sku, prod in data.items():
    if prod.get("categoryId") == "baby_products_baby_essentials":
        img = prod["images"]["main"].split("/")[-1].replace(".png", "")
        if img in price_desc:
            price, desc = price_desc[img]
            title = " ".join(w.capitalize() for w in img.split("_"))
            prod["title"] = title
            prod["price"] = price
            prod["description"] = desc
            prod["status"] = "active"
            updated += 1
        else:
            skipped.append((sku, img))

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
