import json

price_desc = {
    "air_compressor": (25000, "Air Compressor — an industrial machine used to pressurize air for pneumatic tools."),
    "angle_grinder": (4500, "Angle Grinder — a power tool used for cutting, grinding, and polishing metal."),
    "asphalt_paver": (8500000, "Asphalt Paver — heavy machinery used to lay asphalt for road construction."),
    "autoclave": (35000, "Autoclave — a sterilization device used to disinfect equipment using high-pressure steam."),
    "backhoe_loader": (4500000, "Backhoe Loader — heavy construction machinery used for digging and loading."),
    "bakery_oven": (85000, "Bakery Oven — a commercial oven designed for baking bread and pastries."),
    "barcode_scanner": (3500, "Barcode Scanner — a device used to read and process barcodes for inventory and retail."),
    "bearings": (450, "Bearings — mechanical components used to reduce friction between moving parts."),
    "belt": (700, "Belt — an industrial belt used to transmit power between machine components."),
    "bench_grinder": (6500, "Bench Grinder — a stationary power tool used for grinding and sharpening tools."),
    "bending_machine": (185000, "Bending Machine — industrial equipment used to bend metal sheets and bars."),
    "binding_machine": (12000, "Binding Machine — office equipment used to bind documents together."),
    "blow_molding_machine": (850000, "Blow Molding Machine — industrial equipment used to manufacture hollow plastic parts."),
    "boom_lift": (2500000, "Boom Lift — a hydraulic platform used for working at height."),
    "boring_machine": (185000, "Boring Machine — industrial equipment used to enlarge and finish drilled holes."),
    "bottle_filling_machine": (250000, "Bottle Filling Machine — industrial equipment used to fill bottles in production lines."),
    "bulldozer": (5500000, "Bulldozer — heavy machinery used for pushing large quantities of earth or debris."),
    "business_industrial_machinery": (5000, "Business & Industrial, Machinery — a general range of business and industrial equipment."),
    "capping_machine": (65000, "Capping Machine — industrial equipment used to seal bottle and container caps."),
    "carton_sealing_machine": (55000, "Carton Sealing Machine — industrial equipment used to seal cardboard boxes automatically."),
    "cash_register": (18000, "Cash Register — a retail device used to process sales transactions."),
    "chaff_cutter": (35000, "Chaff Cutter — agricultural machinery used to cut fodder for livestock."),
    "chain": (900, "Chain — a mechanical linkage used to transmit power in industrial machinery."),
    "chain_saw": (12000, "Chain Saw — a power tool used for cutting wood and heavy materials."),
    "circular_saw": (5500, "Circular Saw — a power tool used for making straight cuts in wood and materials."),
    "clamp_meter": (3500, "Clamp Meter — an electrical measurement tool used to test current without disconnecting wires."),
    "cleaning_chemicals": (900, "Cleaning Chemicals — industrial-grade chemicals used for facility and equipment cleaning."),
    "cnc_lathe_machine": (850000, "CNC Lathe Machine — computer-controlled machinery used for precision metal turning."),
    "cnc_machine": (1200000, "CNC Machine — computer-controlled machinery used for precision manufacturing."),
    "coding_machine": (65000, "Coding Machine — industrial equipment used to print codes and batch numbers on products."),
    "combine_harvester": (6500000, "Combine Harvester — agricultural machinery used to harvest grain crops."),
    "concrete_mixer": (45000, "Concrete Mixer — machinery used to mix cement, sand, and water for construction."),
    "concrete_pump": (2500000, "Concrete Pump — heavy machinery used to pump liquid concrete to construction sites."),
    "conveyor_system": (350000, "Conveyor System — industrial equipment used to transport materials along a production line."),
    "couplings": (900, "Couplings — mechanical components used to connect two shafts for power transmission."),
    "currency_counter": (12000, "Currency Counter — a device used to quickly count and verify cash notes."),
    "cutting_machine": (85000, "Cutting Machine — industrial equipment used to cut various materials precisely."),
    "die_casting_machine": (950000, "Die Casting Machine — industrial equipment used to manufacture metal parts by injecting molten metal."),
    "diesel_generator": (185000, "Diesel Generator — a machine that generates electricity using diesel fuel."),
    "digital_caliper": (900, "Digital Caliper — a precision measuring tool used for dimensional accuracy."),
    "dough_mixer": (45000, "Dough Mixer — commercial equipment used to mix bread and pastry dough."),
    "drilling_machine": (55000, "Drilling Machine — industrial equipment used to create precise holes in materials."),
    "ear_protection": (350, "Ear Protection — safety gear used to protect hearing in loud industrial environments."),
    "electric_drill": (3500, "Electric Drill — a power tool used for drilling holes and driving screws."),
    "electric_motor": (12000, "Electric Motor — a machine that converts electrical energy into mechanical motion."),
    "excavator": (6500000, "Excavator — heavy machinery used for digging and earthmoving."),
    "extrusion_machine": (650000, "Extrusion Machine — industrial equipment used to shape materials by forcing them through a die."),
    "face_shield": (350, "Face Shield — protective gear used to guard the face during industrial work."),
    "factory_industrial_machinery": (5000, "Factory Industrial Machinery — a general range of factory production equipment."),
    "feed_mixer": (85000, "Feed Mixer — agricultural machinery used to mix livestock feed."),
    "filling_machine": (185000, "Filling Machine — industrial equipment used to fill containers with liquid or powder products."),
    "fire_extinguisher": (2500, "Fire Extinguisher — a safety device used to put out small fires."),
    "first_aid_kit": (900, "First Aid Kit — a compact kit of essential care items for workplace emergencies."),
    "floor_scrubber": (65000, "Floor Scrubber — an industrial cleaning machine used to scrub and dry floors."),
    "flour_mill": (350000, "Flour Mill — industrial equipment used to grind grain into flour."),
    "food_dryer": (85000, "Food Dryer — commercial equipment used to dehydrate food products."),
    "forklift": (1500000, "Forklift — an industrial vehicle used for lifting and moving heavy loads."),
    "fruit_juicer_machine": (45000, "Fruit Juicer Machine — commercial equipment used to extract juice from fruits."),
    "fume_hood": (85000, "Fume Hood — laboratory equipment used to safely vent hazardous fumes."),
    "gas_generator": (185000, "Gas Generator — a machine that generates electricity using gas fuel."),
    "gaskets": (350, "Gaskets — sealing components used to prevent leaks between machine parts."),
    "gear": (700, "Gear — a toothed mechanical component used to transmit rotational power."),
    "gear_motor": (12000, "Gear Motor — an electric motor combined with a gear reduction system."),
    "gearbox": (25000, "Gearbox — industrial equipment used to transmit power at varying speeds and torque."),
    "generator_set": (350000, "Generator Set — a complete power generation unit used for backup electricity."),
    "grinding_machine": (185000, "Grinding Machine — industrial equipment used for precision surface finishing."),
    "harvester": (5500000, "Harvester — heavy agricultural machinery used for harvesting crops."),
    "heat_gun": (2500, "Heat Gun — a power tool used to apply heat for stripping, welding, or drying materials."),
    "heat_treatment_furnace": (650000, "Heat Treatment Furnace — industrial equipment used to alter material properties through heat."),
    "hydraulic_cylinder": (18000, "Hydraulic Cylinder — a mechanical actuator used to generate linear force in machinery."),
    "hydraulic_press": (350000, "Hydraulic Press — industrial equipment used to apply force for shaping materials."),
    "impact_wrench": (6500, "Impact Wrench — a power tool used to tighten or loosen fasteners with high torque."),
    "incubator": (45000, "Incubator — laboratory or agricultural equipment used to maintain controlled environmental conditions."),
    "industrial_blower": (25000, "Industrial Blower — machinery used to move large volumes of air for ventilation or drying."),
    "industrial_fan": (18000, "Industrial Fan — a heavy-duty fan used for ventilation in industrial settings."),
    "industrial_hose": (900, "Industrial Hose — durable hoses used to transport fluids in industrial applications."),
    "industrial_machinery": (5000, "Industrial Machinery — a general range of heavy-duty production equipment."),
    "industrial_mop": (900, "Industrial Mop — a heavy-duty mop used for large-scale facility cleaning."),
    "industrial_oven": (150000, "Industrial Oven — heavy-duty ovens used for manufacturing and processing applications."),
    "industrial_robot": (2500000, "Industrial Robot — an automated machine used for manufacturing and assembly tasks."),
    "industrial_vacuum_cleaner": (35000, "Industrial Vacuum Cleaner — a heavy-duty vacuum used for large-scale cleaning tasks."),
    "industrial_valve": (2500, "Industrial Valve — a mechanical component used to regulate fluid or gas flow."),
    "infrared_thermometer": (2500, "Infrared Thermometer — a device used to measure surface temperature without contact."),
    "injection_molding_machine": (1500000, "Injection Molding Machine — industrial equipment used to manufacture plastic parts."),
    "irrigation_pump": (35000, "Irrigation Pump — agricultural machinery used to pump water for crop irrigation."),
    "label_printer": (8500, "Label Printer — a device used to print adhesive labels for products and packaging."),
    "labeling_machine": (85000, "Labeling Machine — industrial equipment used to apply labels to products automatically."),
    "laboratory_balance": (12000, "Laboratory Balance — a precision scale used for accurate laboratory measurements."),
    "laboratory_centrifuge": (85000, "Laboratory Centrifuge — a device used to separate substances by spinning at high speed."),
    "laboratory_microscope": (25000, "Laboratory Microscope — an optical instrument used for detailed scientific examination."),
    "laboratory_oven": (35000, "Laboratory Oven — a controlled heating device used for laboratory applications."),
    "laminating_machine": (18000, "Laminating Machine — equipment used to apply a protective plastic layer to documents."),
    "laser_cutting_machine": (1200000, "Laser Cutting Machine — industrial equipment used to precisely cut materials with a laser."),
    "laser_distance_meter": (3500, "Laser Distance Meter — a device used to measure distances accurately using a laser."),
    "lathe_machine": (450000, "Lathe Machine — industrial equipment used to shape materials by rotating them against a cutting tool."),
    "meat_grinder": (18000, "Meat Grinder — commercial equipment used to grind meat for food preparation."),
    "meat_slicer": (25000, "Meat Slicer — commercial equipment used to slice meat and deli products."),
    "metal_stamping_machine": (650000, "Metal Stamping Machine — industrial equipment used to shape metal sheets using stamping dies."),
    "micrometer": (1500, "Micrometer — a precision measuring tool used for small dimensional measurements."),
    "milling_machine": (450000, "Milling Machine — industrial equipment used to shape materials with rotary cutters."),
    "mobile_crane": (8500000, "Mobile Crane — heavy machinery used for lifting and moving heavy loads on construction sites."),
    "motor_grader": (5500000, "Motor Grader — heavy machinery used to level and grade surfaces in construction."),
    "multimeter": (2200, "Multimeter — an electrical testing tool used to measure voltage, current, and resistance."),
    "oil_press_machine": (85000, "Oil Press Machine — industrial equipment used to extract oil from seeds and nuts."),
    "paper_shredder": (8500, "Paper Shredder — office equipment used to destroy sensitive documents."),
    "ph_meter": (3500, "pH Meter — a device used to measure the acidity or alkalinity of a solution."),
    "pipe_fittings": (250, "Pipe Fittings — components used to connect and adapt sections of piping."),
    "plasma_cutting_machine": (450000, "Plasma Cutting Machine — industrial equipment used to cut metal using a plasma torch."),
    "plate_compactor": (65000, "Plate Compactor — construction equipment used to compact soil and asphalt."),
    "pneumatic_cylinder": (3500, "Pneumatic Cylinder — a mechanical actuator that uses compressed air to generate motion."),
    "pos_machine": (25000, "POS Machine — a point-of-sale device used to process retail transactions."),
    "powder_coating_machine": (185000, "Powder Coating Machine — industrial equipment used to apply protective powder coatings."),
    "power_tiller": (85000, "Power Tiller — agricultural machinery used to till and prepare soil for planting."),
    "press_machine": (350000, "Press Machine — industrial equipment used to apply pressure for shaping materials."),
    "pressure_gauge": (900, "Pressure Gauge — a device used to measure fluid or gas pressure in systems."),
    "pressure_washer": (12000, "Pressure Washer — a machine that uses high-pressure water for industrial cleaning."),
    "pulley": (450, "Pulley — a mechanical wheel component used to change the direction of force."),
    "punching_machine": (250000, "Punching Machine — industrial equipment used to punch holes or shapes into materials."),
    "receipt_printer": (5500, "Receipt Printer — a device used to print sales receipts at point-of-sale terminals."),
    "reflective_vest": (450, "Reflective Vest — a high-visibility safety vest worn in industrial environments."),
    "respirator_mask": (700, "Respirator Mask — protective gear used to filter airborne particles and fumes."),
    "rice_mill": (450000, "Rice Mill — agricultural machinery used to process harvested rice."),
    "rice_transplanter": (850000, "Rice Transplanter — agricultural machinery used to plant rice seedlings."),
    "rivet_gun": (3500, "Rivet Gun — a tool used to install rivets for fastening materials together."),
    "road_roller": (3500000, "Road Roller — heavy machinery used to compact surfaces during road construction."),
    "road_sweeper": (2500000, "Road Sweeper — a vehicle used to clean debris from roads and streets."),
    "rolling_machine": (350000, "Rolling Machine — industrial equipment used to shape metal by passing it through rollers."),
    "rotary_hammer": (8500, "Rotary Hammer — a power tool used for heavy-duty drilling and chiseling."),
    "safety_gloves": (250, "Safety Gloves — protective gloves used to guard hands in industrial work."),
    "safety_goggles": (250, "Safety Goggles — protective eyewear used to guard eyes from industrial hazards."),
    "safety_helmet": (450, "Safety Helmet — protective headgear used at industrial and construction sites."),
    "safety_shoes": (1500, "Safety Shoes — protective footwear designed for industrial work environments."),
    "sandblasting_machine": (85000, "Sandblasting Machine — industrial equipment used to clean and finish surfaces using abrasive media."),
    "scissor_lift": (850000, "Scissor Lift — a hydraulic platform used for working at elevated heights."),
    "sealing_machine": (35000, "Sealing Machine — industrial equipment used to seal packaging materials."),
    "seals": (250, "Seals — components used to prevent leaks between machine parts."),
    "seed_drill": (185000, "Seed Drill — agricultural machinery used to plant seeds at controlled depths."),
    "servo_motor": (15000, "Servo Motor — a precision motor used for controlled motion in automation systems."),
    "shaping_machine": (350000, "Shaping Machine — industrial equipment used to shape flat or contoured surfaces."),
    "shrink_wrapping_machine": (85000, "Shrink Wrapping Machine — industrial equipment used to wrap products in shrink film."),
    "skid_steer_loader": (3500000, "Skid Steer Loader — compact heavy machinery used for loading and earthmoving."),
    "spectrophotometer": (185000, "Spectrophotometer — laboratory equipment used to measure light absorption in samples."),
    "sprayer_machine": (35000, "Sprayer Machine — agricultural equipment used to spray fertilizers or pesticides."),
    "sprocket": (700, "Sprocket — a toothed wheel used to engage a chain for power transmission."),
    "steam_cleaner": (18000, "Steam Cleaner — industrial equipment used for deep cleaning using high-temperature steam."),
    "strapping_machine": (85000, "Strapping Machine — industrial equipment used to secure packages with plastic or steel straps."),
    "telehandler": (5500000, "Telehandler — heavy machinery used for lifting and placing loads at height."),
    "temperature_controller": (3500, "Temperature Controller — an electronic device used to regulate industrial process temperature."),
    "thickness_gauge": (3500, "Thickness Gauge — a precision tool used to measure material thickness."),
    "time_attendance_machine": (8500, "Time Attendance Machine — a device used to record employee work hours."),
    "torque_wrench": (2200, "Torque Wrench — a precision tool used to tighten fasteners to a specific torque."),
    "tower_crane": (12000000, "Tower Crane — heavy construction machinery used for lifting materials at height."),
    "tractor": (1800000, "Tractor — agricultural machinery used for farming and heavy field work."),
    "transformer": (65000, "Transformer — an electrical device used to change voltage levels in a power system."),
    "vacuum_packaging_machine": (65000, "Vacuum Packaging Machine — industrial equipment used to vacuum-seal products for preservation."),
    "vegetable_cutter": (18000, "Vegetable Cutter — commercial equipment used to cut vegetables for food preparation."),
    "vibration_meter": (12000, "Vibration Meter — a device used to measure mechanical vibration in equipment."),
    "vibratory_roller": (3500000, "Vibratory Roller — heavy machinery used to compact soil and asphalt with vibration."),
    "waste_bin": (900, "Waste Bin — an industrial container used for waste collection and disposal."),
    "water_bath": (18000, "Water Bath — laboratory equipment used to maintain consistent liquid temperatures."),
    "water_jet_cutting_machine": (1500000, "Water Jet Cutting Machine — industrial equipment used to cut materials using high-pressure water."),
    "water_pump": (12000, "Water Pump — machinery used to move water for industrial or agricultural applications."),
    "welding_machine": (35000, "Welding Machine — industrial equipment used to join metal parts through welding."),
    "wheel_loader": (5500000, "Wheel Loader — heavy machinery used for loading and moving bulk materials."),
}

path = "data/products-placeholder.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

updated = 0
skipped = []
for sku, prod in data.items():
    if prod.get("categoryId") == "business_industrial_machinery":
        img = prod["images"]["main"].split("/")[-1].replace(".png", "")
        if img in price_desc:
            price, desc = price_desc[img]
            title = " ".join(w.capitalize() for w in img.split("_"))
            prod["title"] = title
            prod["price"] = price
            prod["description"] = desc
            prod["status"] = "active"
            updated += 1
        else:
            skipped.append((sku, img))

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Updated: {updated}")
print(f"Skipped: {skipped}")
